/**
 * 语文 · C4B 病句修改题包 (Phase 2 P2-2, v0.35.95).
 *
 * 期中考第 5 题型: "找 1 处语序颠倒句子, 用修改符号在信中修改". G4B 高频考点.
 *
 * 病句类型 (5 大类, 期中考全覆盖):
 *  - 语序颠倒 (subj_order_wrong): "在公园里我看到了" → "我在公园里看到了"
 *  - 成分残缺 (component_missing): 缺主语 / 谓语 / 宾语
 *  - 搭配不当 (mismatch): "改善生活条件" vs "改善生活水平"
 *  - 重复啰嗦 (redundant): "大约 50 多人" → "大约 50 人" 或 "50 多人"
 *  - 前后矛盾 (contradiction): "全班都来了, 只有小明没来"
 *
 * 题型设计 (4 选 1):
 *  - "下面哪句话没有病句?" (1 对 + 3 病)
 *  - "下列哪句话有语序颠倒?" 指定病类
 *  - "下面这句话哪种修改对? '...'" 给病句, 选正确修改
 *  - "找出短文中的 N 处病句"
 *
 * 50+ 题分布:
 *  - U1 第一单元 (古诗 + 乡村田园): 13 题
 *  - U2 第二单元 (自然科技): 12 题
 *  - U3 第三单元 (现代诗): 12 题
 *  - U4 第四单元 (动物): 13 题
 */

import type { Question } from "../../core/types";
import { pickChoice } from "./questionHelpers";

const U1 = "C4B_U1_NATURE";
const U2 = "C4B_U2_SCIENCE";
const U3 = "C4B_U3_POETRY";
const U4 = "C4B_U4_ANIMALS";

const BADSENT_U1 = "C4B_U1_BADSENT";
const BADSENT_U2 = "C4B_U2_BADSENT";
const BADSENT_U3 = "C4B_U3_BADSENT";
const BADSENT_U4 = "C4B_U4_BADSENT";

export const SEED_QUESTIONS_CHINESE_BADSENT: Question[] = [
  // ============================================================
  // 第一单元 · 病句修改 (13 题)
  // ============================================================
  pickChoice({
    id: "cn-u1-bad-001",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence", "expression"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下面哪句话没有病句?",
    options: [
      { id: "a", text: "我去乡下看望了奶奶。" },
      { id: "b", text: "在乡下我看望了奶奶。", errorTag: "subj_order_wrong" },
      { id: "c", text: "我看望了乡下在奶奶。", errorTag: "subj_order_wrong" },
      { id: "d", text: "去乡下奶奶我看望了。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ["主语 (我) + 状语 (去乡下) + 谓语 (看望) + 宾语 (奶奶) 是正确语序."],
  }),
  pickChoice({
    id: "cn-u1-bad-002",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下面这句话有病, 怎么改最好?\n\"经过老师认真地讲解, 使我明白了《清平乐·村居》的意思。\"",
    options: [
      { id: "a", text: "经过老师认真地讲解, 我明白了《清平乐·村居》的意思。" },
      { id: "b", text: "经过老师认真讲解, 使明白了《清平乐·村居》的意思。", errorTag: "component_missing" },
      { id: "c", text: "老师认真地讲解, 使我明白了。", errorTag: "component_missing" },
      { id: "d", text: "我明白了, 经过老师认真讲解。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['原句缺主语 — "经过... 使..." 让 "我" 失去主语地位. 应删 "使" 字.'],
  }),
  pickChoice({
    id: "cn-u1-bad-003",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下列哪句话有重复啰嗦的毛病?",
    options: [
      { id: "a", text: "乡下人家的菜园里种着许多 各种各样 的蔬菜。", errorTag: "redundant" },
      { id: "b", text: "乡下人家的菜园里种着各种蔬菜。" },
      { id: "c", text: "菜园里大约有 50 棵蔬菜。" },
      { id: "d", text: "春天的乡下生机勃勃。" },
    ],
    correct: "a",
    solution: ['"许多 + 各种各样" 重复 (各种各样已含很多的意思). 应该去掉 "许多".'],
  }),
  pickChoice({
    id: "cn-u1-bad-004",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence"],
    difficulty: 4,
    stem: "找出下面句子的病 — \"院子里大约有 30 多只蜻蜓飞来飞去。\"",
    options: [
      { id: "a", text: "重复: '大约' 和 '多' 重复" },
      { id: "b", text: "语序颠倒", errorTag: "wrong_diagnosis" },
      { id: "c", text: "成分残缺", errorTag: "wrong_diagnosis" },
      { id: "d", text: "没有病", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"大约" 表示估计, "30 多" 也表示估计, 二者只留一个. 改 "大约 30 只" 或 "30 多只".'],
  }),
  pickChoice({
    id: "cn-u1-bad-005",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下面哪句话搭配不当?",
    options: [
      { id: "a", text: "春风轻轻地吹拂着我的脸庞。" },
      { id: "b", text: "春风强烈地吹动着我的脸庞。", errorTag: "mismatch" },
      { id: "c", text: "桃花在春风中摇曳。" },
      { id: "d", text: "我喜欢春天的乡下。" },
    ],
    correct: "b",
    solution: ['"春风" 通常 "轻轻地 / 温柔地" 搭配, "强烈" 是大风. 应改 "微微地" 或 "轻柔地".'],
  }),
  pickChoice({
    id: "cn-u1-bad-006",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence"],
    difficulty: 4,
    stem: "下面哪一句没有病句?",
    options: [
      { id: "a", text: "我们要努力改正并发现自己的缺点。", errorTag: "logic_order" },
      { id: "b", text: "我们要努力发现并改正自己的缺点。" },
      { id: "c", text: "我们要改正发现自己的缺点努力。", errorTag: "subj_order_wrong" },
      { id: "d", text: "改正发现缺点努力我们。", errorTag: "subj_order_wrong" },
    ],
    correct: "b",
    solution: ['逻辑顺序: 先 "发现" 才能 "改正". "改正并发现" 顺序倒了.'],
  }),
  pickChoice({
    id: "cn-u1-bad-007",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '下面这句话的修改最准确的是?\n"《宿新市徐公店》这首诗写的内容非常生动有趣的事情。"',
    options: [
      { id: "a", text: "《宿新市徐公店》这首诗写的内容非常生动有趣。" },
      { id: "b", text: "《宿新市徐公店》这首诗写的事情。", errorTag: "over_delete" },
      { id: "c", text: "这首诗非常生动有趣的事情。", errorTag: "component_missing" },
      { id: "d", text: "无需修改", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"非常生动有趣的事情" 跟前半 "写的内容" 重复. 删 "的事情" 即可.'],
  }),
  pickChoice({
    id: "cn-u1-bad-008",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence"],
    difficulty: 3,
    stem: '下面这句有什么问题? "全班同学都来了田野郊游, 只有小明没来。"',
    options: [
      { id: "a", text: "前后矛盾: 全班都来 vs 小明没来" },
      { id: "b", text: "重复", errorTag: "wrong_diagnosis" },
      { id: "c", text: "搭配不当", errorTag: "wrong_diagnosis" },
      { id: "d", text: "没病句", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"全班都来" 跟 "小明没来" 自相矛盾. 应改 "全班同学几乎都来了, 只有小明没来" 或类似.'],
  }),
  pickChoice({
    id: "cn-u1-bad-009",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "改正下面的病句最合适的是: \"乡下人家的天空, 飘着洁白的白云。\"",
    options: [
      { id: "a", text: "乡下人家的天空, 飘着洁白的云朵。" },
      { id: "b", text: "乡下人家的天空, 飘着白白的白云。", errorTag: "redundant" },
      { id: "c", text: "乡下人家的天空, 飘着洁白白云。", errorTag: "redundant" },
      { id: "d", text: "乡下人家天空飘着洁白的白云。", errorTag: "component_missing" },
    ],
    correct: "a",
    solution: ['"洁白" + "白云" 重复 ("白" 在两处). 改 "云朵" 或 "白色 + 云朵".'],
  }),
  pickChoice({
    id: "cn-u1-bad-010",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence"],
    difficulty: 3,
    stem: "下面哪一句没有病句?",
    options: [
      { id: "a", text: "我和小明在田野里捉迷藏, 玩得很开心。" },
      { id: "b", text: "在田野里我和小明捉迷藏玩得很开心。", errorTag: "subj_order_wrong" },
      { id: "c", text: "捉迷藏在田野里我和小明玩得很开心。", errorTag: "subj_order_wrong" },
      { id: "d", text: "玩得很开心我和小明在田野里捉迷藏。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['主语 + 状语 + 谓语 + 补语 顺序自然清晰.'],
  }),
  pickChoice({
    id: "cn-u1-bad-011",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '下面句子的修改最准确的是? "通过阅读乡下人家, 我更加更喜欢乡村生活。"',
    options: [
      { id: "a", text: "通过阅读《乡下人家》, 我更加喜欢乡村生活。" },
      { id: "b", text: "通过《乡下人家》, 我更加更喜欢乡村生活。", errorTag: "redundant" },
      { id: "c", text: "我更加更喜欢乡村生活, 通过阅读乡下人家。", errorTag: "subj_order_wrong" },
      { id: "d", text: "阅读《乡下人家》, 喜欢乡村生活。", errorTag: "component_missing" },
    ],
    correct: "a",
    solution: ['"更加" + "更" 重复, 删一个; 加书名号《》.'],
  }),
  pickChoice({
    id: "cn-u1-bad-012",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence"],
    difficulty: 3,
    stem: '哪句话有 "成分残缺" 的毛病?',
    options: [
      { id: "a", text: "经过努力, 我们顺利完成了任务。" },
      { id: "b", text: "经过努力, 顺利完成了任务。", errorTag: "component_missing" },
      { id: "c", text: "我们经过努力顺利完成了任务。" },
      { id: "d", text: "完成了任务, 经过努力。", errorTag: "subj_order_wrong" },
    ],
    correct: "b",
    solution: ['B 句缺主语 — 谁完成? 应加 "我们" 或类似主语.'],
  }),
  pickChoice({
    id: "cn-u1-bad-013",
    unit_id: U1,
    skill_id: BADSENT_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "找下面这段话的病句 — \"乡下人家的小院里, 有许多各种各样的花. 妈妈每天浇水让花更加更漂亮.\"",
    options: [
      { id: "a", text: "2 处病: '许多 + 各种各样' 重复 + '更加 + 更' 重复" },
      { id: "b", text: "只有 '许多 + 各种各样' 重复", errorTag: "miss_typo" },
      { id: "c", text: "只有 '更加 + 更' 重复", errorTag: "miss_typo" },
      { id: "d", text: "没有病句", errorTag: "miss_typo" },
    ],
    correct: "a",
    solution: ['2 处典型重复啰嗦. 改 "各种各样的花" + "更加漂亮" 或 "更漂亮".'],
  }),

  // ============================================================
  // 第二单元 · 病句修改 (12 题)
  // ============================================================
  pickChoice({
    id: "cn-u2-bad-001",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence", "expression"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下面哪句话没有病句?",
    options: [
      { id: "a", text: "科学家们通过研究, 发现了恐龙的秘密。" },
      { id: "b", text: "通过科学家们研究, 发现了恐龙的秘密。", errorTag: "component_missing" },
      { id: "c", text: "通过科学家们的研究, 使发现了恐龙的秘密。", errorTag: "component_missing" },
      { id: "d", text: "发现了恐龙的秘密, 科学家们通过研究。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['"通过 + 使" 让主语缺失. 删 "通过" 或删 "使".'],
  }),
  pickChoice({
    id: "cn-u2-bad-002",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence"],
    difficulty: 4,
    stem: "下面这句话哪种修改正确? \"纳米技术可以使我们的生活变得更加好。\"",
    options: [
      { id: "a", text: "纳米技术可以使我们的生活变得更加美好。" },
      { id: "b", text: "纳米技术可以使我们的生活更加更好。", errorTag: "redundant" },
      { id: "c", text: "纳米技术使生活变得好。", errorTag: "component_missing" },
      { id: "d", text: "无需修改", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"更加好" 不通, 应该是 "更加美好" 或 "更好".'],
  }),
  pickChoice({
    id: "cn-u2-bad-003",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence"],
    difficulty: 3,
    stem: '下列哪句有 "搭配不当"?',
    options: [
      { id: "a", text: "科学家提出了新的方法。" },
      { id: "b", text: "科学家提出了新的成绩。", errorTag: "mismatch" },
      { id: "c", text: "科学家取得了新的成绩。" },
      { id: "d", text: "科学家发明了新的工具。" },
    ],
    correct: "b",
    solution: ['"提出" 配 "方法 / 意见 / 问题", 不配 "成绩". 成绩搭 "取得 / 获得".'],
  }),
  pickChoice({
    id: "cn-u2-bad-004",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下面这句话怎么改最好? \"实验室里有大约 20 多个仪器在运作。\"",
    options: [
      { id: "a", text: "实验室里有 20 多个仪器在运作。" },
      { id: "b", text: "实验室里大约有 20 多个仪器在运作。", errorTag: "redundant" },
      { id: "c", text: "实验室里有大约 20 多个仪器。", errorTag: "redundant" },
      { id: "d", text: "实验室里有许多大约 20 多个仪器在运作。", errorTag: "redundant" },
    ],
    correct: "a",
    solution: ['"大约" 跟 "20 多" 都表估计, 留一个. 答案 A 去掉 "大约". 也可改 "大约 20 个" (去 "多").'],
  }),
  pickChoice({
    id: "cn-u2-bad-005",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下面哪句话没有病句?",
    options: [
      { id: "a", text: "我们一定要珍惜并保护自己的眼睛。" },
      { id: "b", text: "我们一定要保护并珍惜自己的眼睛。", errorTag: "logic_order" },
      { id: "c", text: "我们一定要珍惜保护并自己的眼睛。", errorTag: "subj_order_wrong" },
      { id: "d", text: "保护并珍惜眼睛我们一定要自己的。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['逻辑顺序: 先 "珍惜" (认识到价值) 再 "保护" (行动). 不能颠倒.'],
  }),
  pickChoice({
    id: "cn-u2-bad-006",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence"],
    difficulty: 3,
    stem: "下面哪句有 '前后矛盾' 的毛病?",
    options: [
      { id: "a", text: "全班同学都喜欢这本书, 只有小明不喜欢。", errorTag: "contradiction" },
      { id: "b", text: "全班同学几乎都喜欢这本书, 小明不喜欢。" },
      { id: "c", text: "大部分同学喜欢这本书。" },
      { id: "d", text: "全班同学都不喜欢这本书。" },
    ],
    correct: "a",
    solution: ['"全班都喜欢" 跟 "小明不喜欢" 矛盾. 应改 "几乎都喜欢" 等表达.'],
  }),
  pickChoice({
    id: "cn-u2-bad-007",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '下面这句话怎么修改最好? "琥珀里面包着一只小苍蝇和一些蜘蛛丝, 大约有几百只昆虫呢。"',
    options: [
      { id: "a", text: "琥珀里面包着一只小苍蝇和一些蜘蛛丝。 (删除 '大约有几百只昆虫呢')" },
      { id: "b", text: "琥珀里面包着几百只昆虫。", errorTag: "contradiction" },
      { id: "c", text: "琥珀里面有几百只蜘蛛丝。", errorTag: "mismatch" },
      { id: "d", text: "无需修改", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"一只苍蝇 + 一些蜘蛛丝" 跟 "几百只昆虫" 数量矛盾. 删掉冲突部分.'],
  }),
  pickChoice({
    id: "cn-u2-bad-008",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence"],
    difficulty: 4,
    stem: '哪句话有 "成分残缺" 病?',
    options: [
      { id: "a", text: "通过纳米技术研究, 我们了解了微观世界。" },
      { id: "b", text: "通过纳米技术研究, 了解了微观世界。", errorTag: "component_missing" },
      { id: "c", text: "我们了解了纳米技术研究的微观世界。" },
      { id: "d", text: "纳米技术研究让我们了解微观世界。" },
    ],
    correct: "b",
    solution: ['B 缺主语. "通过..." 是状语, 后面没主语 (谁了解?).'],
  }),
  pickChoice({
    id: "cn-u2-bad-009",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下面哪句话搭配不当?",
    options: [
      { id: "a", text: "科学家改善了人们的生活水平。", errorTag: "mismatch" },
      { id: "b", text: "科学家提高了人们的生活水平。" },
      { id: "c", text: "科学家改善了人们的生活条件。" },
      { id: "d", text: "科学家改变了人们的生活方式。" },
    ],
    correct: "a",
    solution: ['"改善" 配 "条件 / 关系 / 状况"; "水平" 应用 "提高". 这是常见搭配错.'],
  }),
  pickChoice({
    id: "cn-u2-bad-010",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下面这句怎么改? \"为了不再迟到, 小明每天 6 点 起床, 7 点出门。结果还是经常迟到。\"",
    options: [
      { id: "a", text: '逻辑矛盾: "为了不再迟到" 和 "结果还是迟到" 矛盾. 改 "尽管每天 6 点起床, 小明还是经常迟到".' },
      { id: "b", text: "改 '5 点起床'", errorTag: "wrong_fix" },
      { id: "c", text: "改 '不准迟到'", errorTag: "wrong_fix" },
      { id: "d", text: "无需修改", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['原句逻辑: 想不迟到 → 早起 → 还是迟到. 内在矛盾, 用 "尽管 / 但还是" 重组.'],
  }),
  pickChoice({
    id: "cn-u2-bad-011",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence"],
    difficulty: 3,
    stem: "下面哪句话没有语序问题?",
    options: [
      { id: "a", text: "科学家在实验室里做了很多有趣的实验。" },
      { id: "b", text: "在实验室里科学家做了实验很多有趣的。", errorTag: "subj_order_wrong" },
      { id: "c", text: "实验很多有趣的科学家在实验室里做了。", errorTag: "subj_order_wrong" },
      { id: "d", text: "科学家做了有趣的实验在实验室里很多。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['主语 (科学家) + 状语 (在实验室里) + 谓语 (做了) + 定语 (很多有趣的) + 宾语 (实验) 正确顺序.'],
  }),
  pickChoice({
    id: "cn-u2-bad-012",
    unit_id: U2,
    skill_id: BADSENT_U2,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: "找下面这段话的病句 — \"纳米技术使我们的衣服更加更耐穿. 通过这项技术, 让大家受益。\"",
    options: [
      { id: "a", text: "2 处病: '更加 + 更' 重复 + '通过 + 让' 缺主语" },
      { id: "b", text: "只有 '更加 + 更' 重复", errorTag: "miss_typo" },
      { id: "c", text: "只有 '通过 + 让' 缺主语", errorTag: "miss_typo" },
      { id: "d", text: "没有病句", errorTag: "miss_typo" },
    ],
    correct: "a",
    solution: ['典型 2 病. 修改 "更加耐穿" 或 "更耐穿"; "这项技术让大家受益" (删 "通过").'],
  }),

  // ============================================================
  // 第三单元 · 病句修改 (12 题)
  // ============================================================
  pickChoice({
    id: "cn-u3-bad-001",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence", "expression"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下面哪句话没有病句?",
    options: [
      { id: "a", text: "白桦树在月光下静静地站着。" },
      { id: "b", text: "在月光下白桦树静静地站着月光。", errorTag: "redundant" },
      { id: "c", text: "白桦树静静站着在月光下。", errorTag: "subj_order_wrong" },
      { id: "d", text: "静静地站着白桦树在月光下。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['主谓宾正确顺序. B 重复 "月光下"; C / D 语序错.'],
  }),
  pickChoice({
    id: "cn-u3-bad-002",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence"],
    difficulty: 4,
    stem: "下面这句怎么改? \"绿色的麦田一望无际, 大约有 100 多亩左右。\"",
    options: [
      { id: "a", text: "绿色的麦田一望无际, 大约有 100 亩。 (或 100 多亩)" },
      { id: "b", text: "麦田很大, 大约 100 多亩左右。", errorTag: "redundant" },
      { id: "c", text: "麦田 100 亩多左右。", errorTag: "redundant" },
      { id: "d", text: "无需修改", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"大约 + 多 + 左右" 三重 estimate. 只能留一个表估计.'],
  }),
  pickChoice({
    id: "cn-u3-bad-003",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence"],
    difficulty: 3,
    stem: "下面哪一句搭配不当?",
    options: [
      { id: "a", text: "晴朗的天空中飘着白云。" },
      { id: "b", text: "晴朗的天空中飘着风。", errorTag: "mismatch" },
      { id: "c", text: "晴朗的天空中传来鸟鸣。" },
      { id: "d", text: "晴朗的天空万里无云。" },
    ],
    correct: "b",
    solution: ['"飘" 配 "云 / 雪 / 雨", 不配 "风" (风用 "吹").'],
  }),
  pickChoice({
    id: "cn-u3-bad-004",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '下列哪句有 "成分残缺"?',
    options: [
      { id: "a", text: "通过反复朗读《白桦》, 我感受到了诗的美。" },
      { id: "b", text: "通过反复朗读《白桦》, 感受到了诗的美。", errorTag: "component_missing" },
      { id: "c", text: "通过反复朗读, 我感受到诗的美。" },
      { id: "d", text: "反复朗读, 我感受到诗的美。" },
    ],
    correct: "b",
    solution: ['B 缺主语 (谁感受到?). "通过..." 是状语, 后面没主语.'],
  }),
  pickChoice({
    id: "cn-u3-bad-005",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence"],
    difficulty: 4,
    stem: "下面这句话怎么改最好? \"在天晴了的时候, 我们一定会要去原野上散步。\"",
    options: [
      { id: "a", text: "在天晴了的时候, 我们一定要去原野上散步。" },
      { id: "b", text: "在天晴了的时候, 我们会要去原野上散步。", errorTag: "redundant" },
      { id: "c", text: "在天晴了, 我们一定要去原野上散步。", errorTag: "component_missing" },
      { id: "d", text: "无需修改", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"一定会 + 要" 重复, 只留一个 "一定要" 即可.'],
  }),
  pickChoice({
    id: "cn-u3-bad-006",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下面这句话有什么毛病? \"墨水瓶倒翻了, 所以墨水全部都洒了出来。\"",
    options: [
      { id: "a", text: '"全部" 和 "都" 重复, 只留一个' },
      { id: "b", text: "语序颠倒", errorTag: "wrong_diagnosis" },
      { id: "c", text: "搭配不当", errorTag: "wrong_diagnosis" },
      { id: "d", text: "没病句", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"全部都" 重复, 改 "全部洒了" 或 "都洒了".'],
  }),
  pickChoice({
    id: "cn-u3-bad-007",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence"],
    difficulty: 4,
    stem: "下面哪句话有逻辑顺序错误?",
    options: [
      { id: "a", text: "诗人先观察生活, 再用诗句表达。" },
      { id: "b", text: "诗人先表达诗句, 再观察生活。", errorTag: "logic_order" },
      { id: "c", text: "诗人通过观察生活写诗。" },
      { id: "d", text: "诗人用诗句表达对生活的观察。" },
    ],
    correct: "b",
    solution: ['必须先 "观察" 才能 "表达", B 颠倒了.'],
  }),
  pickChoice({
    id: "cn-u3-bad-008",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下面哪句有搭配不当?",
    options: [
      { id: "a", text: "我们要努力提高写作水平。" },
      { id: "b", text: "我们要努力增加写作水平。", errorTag: "mismatch" },
      { id: "c", text: "我们要努力扩大词汇量。" },
      { id: "d", text: "我们要努力锻炼身体。" },
    ],
    correct: "b",
    solution: ['"水平" 配 "提高 / 降低", 不配 "增加 / 增多". "数量" 才配 "增加".'],
  }),
  pickChoice({
    id: "cn-u3-bad-009",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下面这段话哪 1 处是语序颠倒? \"春风温暖地吹拂着原野. 我们走过田野去看花. 小燕子在歌唱树梢上.\"",
    options: [
      { id: "a", text: '"小燕子在歌唱树梢上" → "小燕子在树梢上歌唱"' },
      { id: "b", text: '"春风温暖地吹拂着原野" 错', errorTag: "wrong_diagnosis" },
      { id: "c", text: '"我们走过田野去看花" 错', errorTag: "wrong_diagnosis" },
      { id: "d", text: "都没错", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['状语 "在树梢上" 应该放在 "歌唱" 前, 不能放后.'],
  }),
  pickChoice({
    id: "cn-u3-bad-010",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence"],
    difficulty: 3,
    stem: "下面哪句话没有病句?",
    options: [
      { id: "a", text: "晶莹剔透的露珠在阳光下闪着光。" },
      { id: "b", text: "晶莹剔透着的露珠闪光阳光下在。", errorTag: "subj_order_wrong" },
      { id: "c", text: "露珠晶莹剔透闪光在阳光下。", errorTag: "subj_order_wrong" },
      { id: "d", text: "闪光在阳光下晶莹剔透的露珠。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['正确语序: 定语 (晶莹剔透的) + 主语 (露珠) + 状语 (在阳光下) + 谓语 (闪光).'],
  }),
  pickChoice({
    id: "cn-u3-bad-011",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下面这句怎么改? \"星星在天空中眨眼, 大家都喜欢仰望星空。\" 哪个看出毛病?",
    options: [
      { id: "a", text: "没病句, 此句通顺" },
      { id: "b", text: "搭配不当", errorTag: "wrong_diagnosis" },
      { id: "c", text: "成分残缺", errorTag: "wrong_diagnosis" },
      { id: "d", text: "前后矛盾", errorTag: "wrong_diagnosis" },
    ],
    correct: "a",
    solution: ['两句独立, 都通顺. 主语 + 谓语 + 宾语 / 状语都齐全.'],
  }),
  pickChoice({
    id: "cn-u3-bad-012",
    unit_id: U3,
    skill_id: BADSENT_U3,
    ability: ["sentence"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下列句子改后最准确的是? \"由于诗歌的语言美, 让我深深地喜欢上了写诗。\"",
    options: [
      { id: "a", text: "诗歌的语言美让我深深地喜欢上了写诗。 (删 '由于')" },
      { id: "b", text: "由于诗歌的语言美, 我深深地喜欢上了写诗。 (删 '让')" },
      { id: "c", text: "诗歌让我喜欢上写诗。", errorTag: "over_delete" },
      { id: "d", text: "A 或 B 都对" },
    ],
    correct: "d",
    solution: ['原句 "由于 + 让" 双主语缺失. 删 "由于" 或删 "让" 都修复.'],
  }),

  // ============================================================
  // 第四单元 · 病句修改 (13 题)
  // ============================================================
  pickChoice({
    id: "cn-u4-bad-001",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence", "expression"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下面哪句话没有病句?",
    options: [
      { id: "a", text: "我家的小猫蹑手蹑脚地走过来。" },
      { id: "b", text: "蹑手蹑脚地我家的小猫走过来。", errorTag: "subj_order_wrong" },
      { id: "c", text: "走过来我家的小猫蹑手蹑脚地。", errorTag: "subj_order_wrong" },
      { id: "d", text: "我家的小猫走过来蹑手蹑脚地。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['主语 + 状语 (蹑手蹑脚地) + 谓语 (走过来) 是正确语序.'],
  }),
  pickChoice({
    id: "cn-u4-bad-002",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence"],
    difficulty: 4,
    stem: "下面这句怎么改? \"那只老母鸡警惕地保护着大约 10 多只小鸡。\"",
    options: [
      { id: "a", text: "那只老母鸡警惕地保护着 10 多只小鸡。 (或 大约 10 只)" },
      { id: "b", text: "老母鸡警惕保护大约 10 多只小鸡。", errorTag: "redundant" },
      { id: "c", text: "老母鸡保护着 10 多大约只小鸡。", errorTag: "subj_order_wrong" },
      { id: "d", text: "无需修改", errorTag: "miss_diagnosis" },
    ],
    correct: "a",
    solution: ['"大约 + 多" 双估计重复, 只能留一个.'],
  }),
  pickChoice({
    id: "cn-u4-bad-003",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence"],
    difficulty: 3,
    stem: '下面哪句有 "搭配不当"?',
    options: [
      { id: "a", text: "白鹅迈着方步走来。" },
      { id: "b", text: "白鹅迈着圆步走来。", errorTag: "mismatch" },
      { id: "c", text: "猫蹑手蹑脚地走过来。" },
      { id: "d", text: "麻雀勇敢地保护小鸟。" },
    ],
    correct: "b",
    solution: ['"方步" 是固定搭配 (迈方步 — 步伐方正稳重). "圆步" 不存在.'],
  }),
  pickChoice({
    id: "cn-u4-bad-004",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: "下面这句的病在哪里? \"通过观察猫的行为, 让我学到了很多。\"",
    options: [
      { id: "a", text: '"通过 + 让" 主语残缺, 删一个' },
      { id: "b", text: "语序错", errorTag: "wrong_diagnosis" },
      { id: "c", text: "搭配不当", errorTag: "wrong_diagnosis" },
      { id: "d", text: "重复", errorTag: "wrong_diagnosis" },
    ],
    correct: "a",
    solution: ['"通过... 让..." 老错型. 删 "通过" → "观察让我学到"; 或删 "让" → "通过观察, 我学到".'],
  }),
  pickChoice({
    id: "cn-u4-bad-005",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence"],
    difficulty: 3,
    stem: "下面哪一句话搭配最自然?",
    options: [
      { id: "a", text: "猫的性格非常古怪。" },
      { id: "b", text: "猫的性格非常奇形怪状。", errorTag: "mismatch" },
      { id: "c", text: "猫的样子非常古怪。" },
      { id: "d", text: "猫的颜色非常古怪。", errorTag: "mismatch" },
    ],
    correct: "a",
    solution: ['"性格 + 古怪" 是 《猫》 课文原话. "奇形怪状" 配 "外形", "颜色" 一般不用 "古怪".'],
  }),
  pickChoice({
    id: "cn-u4-bad-006",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下面句子怎么改? \"母鸡领着 8 只一群小鸡走过来。\"",
    options: [
      { id: "a", text: "母鸡领着 8 只小鸡走过来。 (删 '一群')" },
      { id: "b", text: "母鸡领着一群小鸡走过来。 (删 '8 只')" },
      { id: "c", text: "母鸡领着 8 只小鸡群走过来。", errorTag: "mismatch" },
      { id: "d", text: "A 或 B 都对" },
    ],
    correct: "d",
    solution: ['"8 只" 跟 "一群" 都表数量, 留一个即可.'],
  }),
  pickChoice({
    id: "cn-u4-bad-007",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence"],
    difficulty: 3,
    stem: "下面哪句有前后矛盾?",
    options: [
      { id: "a", text: "全班同学都喜欢小猫, 只有小红怕猫。", errorTag: "contradiction" },
      { id: "b", text: "全班同学几乎都喜欢小猫, 只有小红怕猫。" },
      { id: "c", text: "全班同学都喜欢小猫。" },
      { id: "d", text: "小红怕猫, 其他人都喜欢猫。" },
    ],
    correct: "a",
    solution: ['"全班都喜欢" 跟 "小红怕" 矛盾, 应改 "几乎都" 或 "大部分".'],
  }),
  pickChoice({
    id: "cn-u4-bad-008",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下列哪一句没病?",
    options: [
      { id: "a", text: "白鹅高傲地把头伸得长长的。" },
      { id: "b", text: "高傲地白鹅头长长把伸得的。", errorTag: "subj_order_wrong" },
      { id: "c", text: "白鹅头长长把高傲地伸得的。", errorTag: "subj_order_wrong" },
      { id: "d", text: "伸得长长地白鹅高傲地把头。", errorTag: "subj_order_wrong" },
    ],
    correct: "a",
    solution: ['主语 (白鹅) + 状语 (高傲地) + 谓语 (伸得) + 补语 (长长的) 顺.'],
  }),
  pickChoice({
    id: "cn-u4-bad-009",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence"],
    difficulty: 4,
    stem: "下面句子修改最好的是? \"由于猫太贪睡, 使它经常错过吃饭时间。\"",
    options: [
      { id: "a", text: "由于猫太贪睡, 它经常错过吃饭时间。 (删 '使')" },
      { id: "b", text: "猫太贪睡, 使它经常错过吃饭时间。 (删 '由于')" },
      { id: "c", text: "猫太贪睡而错过吃饭时间。" },
      { id: "d", text: "都对 (A / B / C)" },
    ],
    correct: "d",
    solution: ['"由于 + 使" 双因式缺主语. 删任一即可, C 也是有效改写.'],
  }),
  pickChoice({
    id: "cn-u4-bad-010",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: "下面哪句有 \"重复啰嗦\" 病?",
    options: [
      { id: "a", text: "小麻雀非常很勇敢地保护小鸟。", errorTag: "redundant" },
      { id: "b", text: "小麻雀非常勇敢地保护小鸟。" },
      { id: "c", text: "小麻雀很勇敢地保护小鸟。" },
      { id: "d", text: "小麻雀勇敢地保护小鸟。" },
    ],
    correct: "a",
    solution: ['"非常 + 很" 双程度副词重复. 只留一个.'],
  }),
  pickChoice({
    id: "cn-u4-bad-011",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence"],
    difficulty: 3,
    stem: "下列哪句话搭配不当?",
    options: [
      { id: "a", text: "我们要发扬优良传统。" },
      { id: "b", text: "我们要发扬错误习惯。", errorTag: "mismatch" },
      { id: "c", text: "我们要克服错误习惯。" },
      { id: "d", text: "我们要继承优良传统。" },
    ],
    correct: "b",
    solution: ['"发扬" 配正面词 (传统 / 精神). "错误" 配 "克服 / 改正".'],
  }),
  pickChoice({
    id: "cn-u4-bad-012",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: "下面这段话哪几句有病? \"白鹅高傲. 它迈着方步走来. 它的步伐威武像将军一样. 它叫声响亮.\"",
    options: [
      { id: "a", text: "第 3 句 '威武像将军一样' 应改 '威武, 像将军一样'" },
      { id: "b", text: "全对", errorTag: "miss_diagnosis" },
      { id: "c", text: "第 1 句错", errorTag: "wrong_diagnosis" },
      { id: "d", text: "第 4 句错", errorTag: "wrong_diagnosis" },
    ],
    correct: "a",
    solution: ['"威武像将军一样" 缺逗号, 不通顺. 添逗号或者用 "像将军一样威武".'],
  }),
  pickChoice({
    id: "cn-u4-bad-013",
    unit_id: U4,
    skill_id: BADSENT_U4,
    ability: ["sentence"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下面句子修改最准确的是? \"通过《猫》这篇文章, 让我们了解到老舍对动物的喜爱之情。\"",
    options: [
      { id: "a", text: "《猫》这篇文章让我们了解到老舍对动物的喜爱之情。 (删 '通过')" },
      { id: "b", text: "通过《猫》这篇文章, 我们了解到老舍对动物的喜爱之情。 (删 '让')" },
      { id: "c", text: "通过《猫》让老舍喜爱动物。", errorTag: "over_delete" },
      { id: "d", text: "A 或 B 都对" },
    ],
    correct: "d",
    solution: ['典型 "通过 + 让" 病. 删 "通过" 或删 "让" 都修复成分.'],
  }),
];
