/**
 * 语文 · C4B 第八单元（童话故事）期末备考包 (v0.36.74, 爸爸 2026-05-21).
 *
 * 严格依据人教版四下课本第八单元:
 *  - 26 宝葫芦的秘密（张天翼，节选）: 王葆听奶奶讲张三/李四/王五/赵六得宝葫芦"要什么有
 *    什么"的故事，幻想自己也有一个；选做提示：靠宝葫芦不劳而获带来的不是幸福而是烦恼。
 *  - 27 巨人的花园（王尔德，巴金译）: 巨人筑墙赶孩子→花园终年冬天(雪/霜/北风/雹)→孩子
 *    爬进来春天回来→巨人醒悟"我多么自私啊"→拆墙→"孩子们是最美丽的花"。布告牌"禁止入内"。
 *  - 28 海的女儿（安徒生，叶君健译，开头）: 海底世界(水蓝像矢车菊瓣/清像玻璃/深；珊瑚墙、
 *    琥珀窗、蚌壳珍珠)；最小的公主最美丽(皮肤像玫瑰花瓣/眼睛像最深的湖水/下身鱼尾)，
 *    古怪、爱沉思、渴望看人类世界，满十五岁才能浮出水面。
 *  - 语文园地: 童话特点=奇妙想象+人物非凡能力+真善美形象；近义词辨析 慰藉/安慰、忘记/忘怀。
 *
 * 题型对齐期中卷情境化考点 + 童话阅读。id 前缀 cn-u8-*。
 * 约定: 双引号字符串内的引文一律用全角“”，避免与 JS 字符串定界符冲突。
 */

import type { Question } from "../../core/types";
import { pickChoice, dictation } from "./questionHelpers";

const U8 = "C4B_U8_FAIRYTALE";
const PINYIN = "C4B_U8_PINYIN";
const VOCAB = "C4B_U8_VOCAB";
const IMAGINE = "C4B_U8_IMAGINE";
const SENTENCE = "C4B_U8_SENTENCE";
const READ = "C4B_U8_READING";
const DICT = "C4B_U8_DICTATION";

// 阅读短文一：巨人的花园（课文原文片段·结尾）
const PASSAGE_GIANT = `📖 短文一·巨人的花园（节选）

巨人看见这个情景，心也软了。他对自己说：“我多么自私啊！现在我明白为什么春天不肯到这儿来了。”他十分后悔自己先前的举动。
他轻轻地走下楼，静悄悄地打开前门，走进花园里。孩子们看见他，非常害怕，立刻逃走了，花园里又出现了冬天的景象。只有那个小男孩没有跑开，因为他的眼里充满了泪水，看不见巨人走过。巨人悄悄地走到他后面，轻轻抱起他，放到树枝上。这棵树马上开花了，小鸟们也飞来歌唱。
从那以后，巨人的花园又成了孩子们的乐园。`;

// 阅读短文二：会分享的苹果树（原创童话，呼应"分享 / 真善美"主题）
const PASSAGE_TREE = `📖 短文二·会分享的苹果树（童话）

山坡上有一棵苹果树，秋天结满了又大又红的苹果。一只小刺猬走过来，怯生生地问：“苹果树爷爷，能给我一个苹果吗？”苹果树笑着抖了抖枝条，落下一个红苹果：“拿去吧，孩子！”小松鼠、小兔子也都来了，苹果树一个个都送给了它们。山下的老财主听说了，气呼呼地跑来，用篱笆把苹果树围了个严严实实，还挂上牌子：“私人苹果，不准动！”说来奇怪，从那以后，这棵树再也结不出一个苹果了，叶子也一片片落光，光秃秃地立在寒风里。直到有一天，老财主拆掉篱笆，把苹果分给了路过的孩子们，第二年春天，苹果树又开出了满树雪白的花。`;

// 阅读短文三：会飞的书包（原创童话，奇思妙想）
const PASSAGE_FLY = `📖 短文三·会飞的书包（童话）

丁丁有一个普通的蓝书包，可有一天，它忽然会说话了！“主人，我们去上学吧！”说着，书包背带变成了两只翅膀，驮着丁丁飞上了天。云朵软软的，像一团团棉花糖；小鸟在身边唱歌，太阳冲他眨眼睛。丁丁高兴极了。可飞到学校上空时，他看见小红正背着沉甸甸的书包，一步一步爬着长长的台阶，累得满头大汗。丁丁犹豫了一下，让书包轻轻降落，把翅膀分了一只给小红的书包。两个孩子一起飞进了教室。书包对丁丁说：“把快乐分给别人，快乐会变成两份。”从那以后，丁丁的书包总爱驮着同学们一起飞。`;

export const SEED_QUESTIONS_CHINESE_U8: Question[] = [
  // ============================================================
  // 字音 · 易错读音 / 多音字
  // ============================================================
  pickChoice({
    id: "cn-u8-py-001",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "《宝葫芦的秘密》“冲着他摇尾巴”中，“冲”的读音是？",
    options: [
      { id: "a", text: "chòng（对着、朝着）" },
      { id: "b", text: "chōng（冲锋、冲洗）", errorTag: "polyphone_confusion" },
      { id: "c", text: "zhòng", errorTag: "phonics_error" },
      { id: "d", text: "chóng", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['“冲”是多音字：chōng（冲锋、冲洗）/ chòng（对着，如“冲着他笑”）。这里读 chòng。'],
  }),
  pickChoice({
    id: "cn-u8-py-002",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "《宝葫芦的秘密》“可胳膊给奶奶拽住了”中，“拽”的读音是？",
    options: [
      { id: "a", text: "zhuài（拉、拖）" },
      { id: "b", text: "yè", errorTag: "phonics_error" },
      { id: "c", text: "zhuǎi", errorTag: "tone_confusion" },
      { id: "d", text: "zhuō", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['“拽”读 zhuài，意思是拉、拖。“拽住”就是拉住。'],
  }),
  pickChoice({
    id: "cn-u8-py-003",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“奶奶总是一面撵我，一面招手”中，“撵”的读音是？",
    options: [
      { id: "a", text: "niǎn（追赶、驱逐）" },
      { id: "b", text: "niàn", errorTag: "tone_confusion" },
      { id: "c", text: "liǎn", errorTag: "phonics_error" },
      { id: "d", text: "nián", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['“撵”读 niǎn，意思是追赶、驱逐。这里指奶奶一边追着“我”一边招手。'],
  }),
  pickChoice({
    id: "cn-u8-py-004",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: "《海的女儿》“水是那么蓝，像最美丽的矢车菊瓣”中，“矢”的读音是？",
    options: [
      { id: "a", text: "shǐ" },
      { id: "b", text: "shī", errorTag: "tone_confusion" },
      { id: "c", text: "shì", errorTag: "tone_confusion" },
      { id: "d", text: "yǐ", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['“矢”读 shǐ（本义是箭）。“矢车菊”是一种蓝色的花。'],
  }),
  pickChoice({
    id: "cn-u8-py-005",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics", "glyph"],
    difficulty: 2,
    stem: "下面加点字读音全部正确的一组是？",
    options: [
      { id: "a", text: "海王宫殿（diàn） 鲸鱼（jīng） 珊瑚（shān hú）" },
      { id: "b", text: "海王宫殿（diàn） 鲸鱼（jīn） 珊瑚（shān hú）", errorTag: "phonics_error" },
      { id: "c", text: "海王宫殿（diǎn） 鲸鱼（jīng） 珊瑚（shān hú）", errorTag: "phonics_error" },
      { id: "d", text: "海王宫殿（diàn） 鲸鱼（jīng） 珊瑚（shān hǔ）", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['殿 diàn、鲸 jīng、珊瑚 shān hú。均出自《海的女儿》。'],
  }),
  pickChoice({
    id: "cn-u8-py-006",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“几”是多音字。下面读音对应正确的一组是？",
    options: [
      { id: "a", text: "几乎（jī） 几个（jǐ）" },
      { id: "b", text: "几乎（jǐ） 几个（jī）", errorTag: "polyphone_confusion" },
      { id: "c", text: "几乎（jǐ） 几个（jǐ）", errorTag: "polyphone_confusion" },
      { id: "d", text: "几乎（jī） 几个（jī）", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“几”：jī（几乎、茶几）/ jǐ（几个、几时，表数目）。'],
  }),
  pickChoice({
    id: "cn-u8-py-007",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "《巨人的花园》“北风……整天在花园里呼啸着”中，“啸”的读音是？",
    options: [
      { id: "a", text: "xiào" },
      { id: "b", text: "sù", errorTag: "phonics_error" },
      { id: "c", text: "xiāo", errorTag: "tone_confusion" },
      { id: "d", text: "shù", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['“呼啸”读 hū xiào，形容发出高而长的声音。“啸”读 xiào。'],
  }),
  pickChoice({
    id: "cn-u8-py-008",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: "《巨人的花园》“秋天结出丰硕的果子”中，“硕”的读音是？",
    options: [
      { id: "a", text: "shuò" },
      { id: "b", text: "shì", errorTag: "phonics_error" },
      { id: "c", text: "suò", errorTag: "phonics_error" },
      { id: "d", text: "shùo", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['“硕”读 shuò，意思是大。“丰硕”指又多又大（多形容果实、成果）。'],
  }),
  pickChoice({
    id: "cn-u8-py-009",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: "《海的女儿》“随着水的流动可以自动开合”中，“蚌壳”的“蚌”读音是？",
    options: [
      { id: "a", text: "bàng" },
      { id: "b", text: "bāng", errorTag: "tone_confusion" },
      { id: "c", text: "fēng", errorTag: "phonics_error" },
      { id: "d", text: "pàng", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['“蚌”读 bàng，软体动物，壳里能产珍珠。课文写屋顶铺着黑色的蚌壳。'],
  }),
  pickChoice({
    id: "cn-u8-py-010",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“和”是多音字。下面读音对应正确的一组是？",
    options: [
      { id: "a", text: "和蔼（hé） 暖和（huo） 和面（huó）" },
      { id: "b", text: "和蔼（huó） 暖和（hé） 和面（huo）", errorTag: "polyphone_confusion" },
      { id: "c", text: "和蔼（huo） 暖和（hé） 和面（huó）", errorTag: "polyphone_confusion" },
      { id: "d", text: "和蔼（hé） 暖和（huó） 和面（huo）", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“和”：hé（和蔼、和平）/ huo（暖和、软和，轻声）/ huó（和面、和泥）/ huò（和药）。'],
  }),

  // ============================================================
  // 字形 · 错别字 / 形近字
  // ============================================================
  pickChoice({
    id: "cn-u8-gl-001",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    exam_priority: "MUST_BIG",
    stem: "选出没有错别字的一组（《巨人的花园》词语）：",
    options: [
      { id: "a", text: "丰硕 · 允许 · 砌墙 · 拆除" },
      { id: "b", text: "丰硕 · 充许 · 砌墙 · 拆除", errorTag: "glyph_homophone" },
      { id: "c", text: "丰硕 · 允许 · 沏墙 · 拆除", errorTag: "glyph_homophone" },
      { id: "d", text: "丰朔 · 允许 · 砌墙 · 折除", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“允许”不是“充许”；“砌墙”（石字旁）不是“沏墙”（沏茶用）；“拆除”不是“折除”。A 全对。'],
  }),
  pickChoice({
    id: "cn-u8-gl-002",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面词语中有错别字的一项是？",
    options: [
      { id: "a", text: "脸颊 · 踪迹 · 隐私", errorTag: "glyph_correct" },
      { id: "b", text: "惩罚 · 呼啸 · 牌子（错写为“脾子”）", errorTag: "glyph_homophone" },
      { id: "c", text: "向日葵 · 舔脚 · 瘦长", errorTag: "glyph_correct" },
      { id: "d", text: "妖怪 · 规矩 · 乖巧", errorTag: "glyph_correct" },
    ],
    correct: "b",
    solution: ['B 中“脾子”应为“牌子”（木字旁的“牌”）。本题选有错别字的一项。'],
  }),
  pickChoice({
    id: "cn-u8-gl-003",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "形近字组词，全部正确的一组是？",
    options: [
      { id: "a", text: "颊（脸颊）— 峡（峡谷）；瘦（瘦弱）— 搜（搜查）" },
      { id: "b", text: "颊（峡谷）— 峡（脸颊）；瘦（瘦弱）— 搜（搜查）", errorTag: "form_similar" },
      { id: "c", text: "颊（脸颊）— 峡（峡谷）；瘦（搜查）— 搜（瘦弱）", errorTag: "form_similar" },
      { id: "d", text: "颊（脸颊）— 峡（峡谷）；瘦（瘦查）— 搜（搜弱）", errorTag: "form_similar" },
    ],
    correct: "a",
    solution: ['“颊”页字旁（脸颊）—“峡”山字旁（峡谷）；“瘦”病字头（瘦弱）—“搜”提手旁（搜查）。A 全对。'],
  }),
  pickChoice({
    id: "cn-u8-gl-004",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "看拼音写词语：巨人在花园四周 qì 起了一道高墙（砌）。",
    options: [
      { id: "a", text: "砌" },
      { id: "b", text: "沏", errorTag: "glyph_homophone" },
      { id: "c", text: "彻", errorTag: "glyph_homophone" },
      { id: "d", text: "切", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“砌墙”用石字旁的“砌”（把砖石垒起来）。“沏”是沏茶，“切”是切开。'],
  }),
  pickChoice({
    id: "cn-u8-gl-005",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "下面书写完全正确的一项是（第八单元词语）？",
    options: [
      { id: "a", text: "妖怪 · 规矩 · 介绍 · 火烫" },
      { id: "b", text: "妖怪 · 规距 · 介绍 · 火烫", errorTag: "glyph_homophone" },
      { id: "c", text: "妖怪 · 规矩 · 介召 · 火烫", errorTag: "glyph_homophone" },
      { id: "d", text: "妖怪 · 规矩 · 介绍 · 火汤", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“规矩”不是“规距”；“介绍”不是“介召”；“火烫”不是“火汤”。A 全对。'],
  }),
  pickChoice({
    id: "cn-u8-gl-006",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "看拼音写词语：别的孩子看见巨人不再像先前那样 xiōng（凶）了。",
    options: [
      { id: "a", text: "凶" },
      { id: "b", text: "兄", errorTag: "glyph_homophone" },
      { id: "c", text: "汹", errorTag: "glyph_homophone" },
      { id: "d", text: "胸", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“凶”指凶狠。“兄”是兄弟，“汹”是汹涌，“胸”是胸膛，都不对。'],
  }),

  // ============================================================
  // 词语 · 近义词辨析 / 理解 / 搭配
  // ============================================================
  pickChoice({
    id: "cn-u8-vocab-001",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "选词填空：①每当我伤心难过时，总会得到好朋友的（  ）。②这时候，小小的天窗是你唯一的（  ）。（安慰 / 慰藉）",
    options: [
      { id: "a", text: "①安慰 ②慰藉" },
      { id: "b", text: "①慰藉 ②安慰", errorTag: "synonym_misuse" },
      { id: "c", text: "①安慰 ②安慰", errorTag: "synonym_misuse" },
      { id: "d", text: "①慰藉 ②慰藉", errorTag: "synonym_misuse" },
    ],
    correct: "a",
    solution: ['“安慰”多用于人对人，口语常用；“慰藉”书面色彩浓，多指事物给人的精神安慰（如天窗）。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-002",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 4,
    stem: "选词填空：①这个字怎么写？我（  ）了。②任岁月潇潇流淌，不能（  ）的，始终是老师深情的目光。（忘记 / 忘怀）",
    options: [
      { id: "a", text: "①忘记 ②忘怀" },
      { id: "b", text: "①忘怀 ②忘记", errorTag: "synonym_misuse" },
      { id: "c", text: "①忘记 ②忘记", errorTag: "synonym_misuse" },
      { id: "d", text: "①忘怀 ②忘怀", errorTag: "synonym_misuse" },
    ],
    correct: "a",
    solution: ['“忘记”指记不得（写法、事情），口语常用；“忘怀”指忘掉(感情、印象)，多用于难以割舍的人和事。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-003",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "《巨人的花园》“我自己的花园就是我自己的花园，他自言自语道”，“自言自语”的意思是？",
    options: [
      { id: "a", text: "自己跟自己说话" },
      { id: "b", text: "大声对别人说话", errorTag: "word_misunderstand" },
      { id: "c", text: "说自己的语言", errorTag: "word_misunderstand" },
      { id: "d", text: "自由地说话", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['“自言自语”指自己一个人小声地跟自己说话。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-004",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "下面词语搭配恰当的一组是？",
    options: [
      { id: "a", text: "丰硕的果子 · 凄凉的花园 · 动人的音乐" },
      { id: "b", text: "丰硕的音乐 · 凄凉的果子 · 动人的花园", errorTag: "collocation_error" },
      { id: "c", text: "丰硕的果子 · 凄凉的音乐 · 动人的花园", errorTag: "collocation_error" },
      { id: "d", text: "丰硕的花园 · 凄凉的果子 · 动人的音乐", errorTag: "collocation_error" },
    ],
    correct: "a",
    solution: ['“丰硕”修饰果子，“凄凉”修饰花园（巨人赶走孩子后的景象），“动人”修饰音乐，均搭配恰当。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-005",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "《海的女儿》中描写最小的公主“她是一个古怪的孩子，不大爱讲话，总是静静地在想着什么”，“古怪”在这里的意思是？",
    options: [
      { id: "a", text: "性情特别、与众不同" },
      { id: "b", text: "丑陋可怕", errorTag: "word_misunderstand" },
      { id: "c", text: "调皮捣蛋", errorTag: "word_misunderstand" },
      { id: "d", text: "胆子很小", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['这里“古怪”指小公主性情特别、与姐姐们不同——爱沉思、渴望了解人类世界，并非贬义。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-006",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: "看拼音写词语：王葆比赛种 xiàng rì kuí（向日葵），可总比不上别人。",
    options: [
      { id: "a", text: "向日葵" },
      { id: "b", text: "向日魁", errorTag: "glyph_homophone" },
      { id: "c", text: "向日揆", errorTag: "glyph_homophone" },
      { id: "d", text: "向曰葵", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“向日葵”指朝着太阳的葵花。“葵”是草字头。'],
  }),

  // ============================================================
  // 童话想象 / 复述 / 人物形象 / 寓意
  // ============================================================
  pickChoice({
    id: "cn-u8-imag-001",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "读童话时，我们能感受到的特点，下面概括最全面的一项是？",
    options: [
      { id: "a", text: "奇妙的想象、人物非凡的能力、真善美的形象" },
      { id: "b", text: "只有奇妙的想象", errorTag: "narrow_focus" },
      { id: "c", text: "只有真实的生活", errorTag: "opposite" },
      { id: "d", text: "只讲道理，没有故事", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['语文园地点明：童话充满奇妙的想象，人物大多拥有非凡的能力，还能让我们感受到真善美的形象。'],
  }),
  pickChoice({
    id: "cn-u8-imag-002",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "《巨人的花园》中，花园的景象前后发生了怎样的变化？",
    options: [
      { id: "a", text: "巨人筑墙赶走孩子后，花园终年是冬天；拆墙让孩子回来后，花园又有了春天" },
      { id: "b", text: "花园一直是春天", errorTag: "detail_wrong" },
      { id: "c", text: "花园一直是冬天", errorTag: "detail_wrong" },
      { id: "d", text: "花园变成了荒地", errorTag: "detail_wrong" },
    ],
    correct: "a",
    solution: ['巨人自私筑墙后，花园只有雪、霜、北风（终年冬天）；他醒悟拆墙、让孩子回来后，春天才重新降临。'],
  }),
  pickChoice({
    id: "cn-u8-imag-003",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "《巨人的花园》告诉我们的道理是？",
    options: [
      { id: "a", text: "快乐应当和大家分享，自私只会带来孤独和凄凉" },
      { id: "b", text: "自己的东西绝不能给别人", errorTag: "opposite" },
      { id: "c", text: "筑墙才能保护花园", errorTag: "opposite" },
      { id: "d", text: "孩子不应该到别人家玩", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['巨人自私时花园只有冬天，分享后春天回来、孩子是“最美丽的花”。说明快乐要与人分享，自私只带来孤独。'],
  }),
  pickChoice({
    id: "cn-u8-imag-004",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading"],
    difficulty: 3,
    stem: "《巨人的花园》中，巨人的转变可以概括为？",
    options: [
      { id: "a", text: "从自私、冷酷变得无私、和善" },
      { id: "b", text: "从善良变得凶狠", errorTag: "opposite" },
      { id: "c", text: "从勤劳变得懒惰", errorTag: "off_topic" },
      { id: "d", text: "一直没有变化", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['巨人原本自私地赶走孩子、筑墙，后来醒悟“我多么自私啊”，拆墙分享花园，变成无私和善的人。'],
  }),
  pickChoice({
    id: "cn-u8-imag-005",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading"],
    difficulty: 4,
    stem: "《宝葫芦的秘密》中，王葆为什么总想得到一个宝葫芦？",
    options: [
      { id: "a", text: "他听了奶奶讲的故事，幻想有了宝葫芦就能要什么有什么、不费力就能成功" },
      { id: "b", text: "他想把宝葫芦送给奶奶", errorTag: "off_topic" },
      { id: "c", text: "他想研究宝葫芦的科学原理", errorTag: "off_topic" },
      { id: "d", text: "他想把宝葫芦卖钱", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['王葆听奶奶讲张三、李四等人得宝葫芦“要什么有什么”，遇到困难（种向日葵、做算术题）就幻想自己也有一个。'],
  }),
  pickChoice({
    id: "cn-u8-imag-006",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: "《宝葫芦的秘密》整本书告诉我们：王葆真的得到宝葫芦后，靠它不劳而获，结果怎样？",
    options: [
      { id: "a", text: "带来的不是幸福，而是烦恼" },
      { id: "b", text: "从此过上了幸福的生活", errorTag: "opposite" },
      { id: "c", text: "变得很有学问", errorTag: "opposite" },
      { id: "d", text: "宝葫芦帮他考了第一名", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['课文“选做”提示：王葆逐渐认识到，靠宝葫芦不劳而获带给他的不是幸福，而是烦恼。说明幸福要靠自己努力得来。'],
  }),
  pickChoice({
    id: "cn-u8-imag-007",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading"],
    difficulty: 4,
    stem: "《海的女儿》中，最小的公主和姐姐们相比，最大的不同是？",
    options: [
      { id: "a", text: "她最爱沉思、最渴望了解人类世界，却要等最久才能浮出海面" },
      { id: "b", text: "她最爱说话、最调皮", errorTag: "detail_wrong" },
      { id: "c", text: "她最大、最先浮出海面", errorTag: "detail_wrong" },
      { id: "d", text: "她不喜欢花园", errorTag: "detail_wrong" },
    ],
    correct: "a",
    solution: ['小公主最美丽、最古怪、爱沉思，最渴望看人类世界，可她年纪最小，要等五年（满十五岁）才能浮上海面。'],
  }),
  pickChoice({
    id: "cn-u8-imag-008",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading"],
    difficulty: 3,
    stem: "《海的女儿》的作者是？",
    options: [
      { id: "a", text: "丹麦的安徒生" },
      { id: "b", text: "英国的王尔德", errorTag: "author_confusion" },
      { id: "c", text: "中国的张天翼", errorTag: "author_confusion" },
      { id: "d", text: "法国的雨果", errorTag: "author_confusion" },
    ],
    correct: "a",
    solution: ['《海的女儿》是丹麦童话作家安徒生的作品；《巨人的花园》作者是英国王尔德；《宝葫芦的秘密》作者是张天翼。'],
  }),

  // ============================================================
  // 句子 · 比喻 / 拟人 / 仿写
  // ============================================================
  pickChoice({
    id: "cn-u8-sent-001",
    unit_id: U8,
    skill_id: SENTENCE,
    ability: ["sentence"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "《海的女儿》“水是那么蓝，像最美丽的矢车菊瓣；又是那么清，像最明亮的玻璃。”用了什么修辞？",
    options: [
      { id: "a", text: "比喻（把海水比作矢车菊瓣、玻璃）" },
      { id: "b", text: "拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "排比", errorTag: "wrong_rhetoric" },
      { id: "d", text: "夸张", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['“像最美丽的矢车菊瓣”“像最明亮的玻璃”是比喻，写出海水又蓝又清的特点。'],
  }),
  pickChoice({
    id: "cn-u8-sent-002",
    unit_id: U8,
    skill_id: SENTENCE,
    ability: ["sentence"],
    difficulty: 3,
    stem: "《海的女儿》“树上的果子亮得像黄金，花朵开得像燃烧着的火”用了什么修辞？",
    options: [
      { id: "a", text: "比喻（把果子比作黄金、把花比作火）" },
      { id: "b", text: "拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "反问", errorTag: "wrong_rhetoric" },
      { id: "d", text: "设问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['“亮得像黄金”“像燃烧着的火”是比喻，写出海底花园色彩鲜艳、奇幻美丽。'],
  }),
  pickChoice({
    id: "cn-u8-sent-003",
    unit_id: U8,
    skill_id: SENTENCE,
    ability: ["sentence"],
    difficulty: 3,
    stem: "《巨人的花园》“雪用他的白色大衣覆盖着青草，霜把所有的树枝涂成了银色”用了什么修辞？",
    options: [
      { id: "a", text: "拟人（把雪、霜当作人来写）" },
      { id: "b", text: "比喻", errorTag: "wrong_rhetoric" },
      { id: "c", text: "排比", errorTag: "wrong_rhetoric" },
      { id: "d", text: "夸张", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['“雪用大衣覆盖”“霜把树枝涂成银色”把雪、霜当人来写，是拟人，写出花园终年冬天的景象。'],
  }),
  pickChoice({
    id: "cn-u8-sent-004",
    unit_id: U8,
    skill_id: SENTENCE,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: "照样子写句子。例：花朵开得像燃烧着的火。下面仿写最恰当的一句是？",
    options: [
      { id: "a", text: "枫叶红得像一片片晚霞。" },
      { id: "b", text: "枫叶红红的。", errorTag: "no_rhetoric" },
      { id: "c", text: "枫叶是红色的。", errorTag: "no_rhetoric" },
      { id: "d", text: "枫叶很多。", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['例句是“……得像……”的比喻句。A“红得像一片片晚霞”结构相同、用了比喻，仿写最恰当。'],
  }),
  pickChoice({
    id: "cn-u8-sent-005",
    unit_id: U8,
    skill_id: SENTENCE,
    ability: ["sentence"],
    difficulty: 4,
    stem: "《海的女儿》“鱼儿们在这些枝叶中间游来游去，像是天空中的飞鸟”这句话好在哪里？",
    options: [
      { id: "a", text: "用比喻把鱼儿比作飞鸟，写出海底世界像天空一样奇妙美丽" },
      { id: "b", text: "说明鱼会飞", errorTag: "literal_misread" },
      { id: "c", text: "说明海底有鸟", errorTag: "literal_misread" },
      { id: "d", text: "没有什么作用", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['把游动的鱼儿比作天空中的飞鸟，化海底为天空，写出海底世界的奇妙，激发读者想象。'],
  }),

  // ============================================================
  // 阅读理解 · 短文一 巨人的花园（节选）(5 题)
  // ============================================================
  pickChoice({
    id: "cn-u8-read-001",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_GIANT}\n\n🔹 第 1 题：巨人“心也软了”，是因为他看见了什么情景？`,
    options: [
      { id: "a", text: "孩子们爬进花园，桃树开花、小鸟歌唱，只有小男孩够不着树枝在哭" },
      { id: "b", text: "花园里下起了大雪", errorTag: "not_in_text" },
      { id: "c", text: "国王的乐队来了", errorTag: "not_in_text" },
      { id: "d", text: "北风把树吹倒了", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['上文写孩子们爬进花园带来春天，唯独小男孩太小够不着树枝、哭得厉害，巨人看见这情景心软了。'],
  }),
  pickChoice({
    id: "cn-u8-read-002",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_GIANT}\n\n🔹 第 2 题：“我多么自私啊！”这句话是谁说的？表现了什么？`,
    options: [
      { id: "a", text: "巨人说的；表现他认识到自己的错误、开始悔悟" },
      { id: "b", text: "小男孩说的；表现他很委屈", errorTag: "detail_wrong" },
      { id: "c", text: "孩子们说的；表现他们害怕", errorTag: "detail_wrong" },
      { id: "d", text: "桃树说的", errorTag: "detail_wrong" },
    ],
    correct: "a",
    solution: ['这是巨人的自言自语，他终于明白春天不来是因为自己自私赶走了孩子，开始后悔、悔悟。'],
  }),
  pickChoice({
    id: "cn-u8-read-003",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_GIANT}\n\n🔹 第 3 题：巨人把小男孩抱到树枝上后，发生了什么神奇的变化？`,
    options: [
      { id: "a", text: "这棵树马上开花了，小鸟们也飞来歌唱" },
      { id: "b", text: "树马上枯萎了", errorTag: "opposite" },
      { id: "c", text: "下起了大雪", errorTag: "opposite" },
      { id: "d", text: "小男孩跑走了", errorTag: "detail_wrong" },
    ],
    correct: "a",
    solution: ['“这棵树马上开花了，小鸟们也飞来歌唱”，用神奇的变化表现巨人的爱心唤回了春天。'],
  }),
  pickChoice({
    id: "cn-u8-read-004",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_GIANT}\n\n🔹 第 4 题：孩子们一开始看见巨人“立刻逃走了，花园里又出现了冬天的景象”，这样写的作用是？`,
    options: [
      { id: "a", text: "用花园景象的变化，衬托孩子们的离开和巨人的孤独，与后文分享后的春天形成对比" },
      { id: "b", text: "说明天气真的变冷了", errorTag: "literal_misread" },
      { id: "c", text: "没有作用", errorTag: "off_topic" },
      { id: "d", text: "说明孩子们不喜欢花园", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['花园随孩子来去而春去冬来，这种神奇的对应衬托主题：有了孩子、有了分享才有春天，与结尾形成对比。'],
  }),
  pickChoice({
    id: "cn-u8-read-005",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_GIANT}\n\n🔹 第 5 题：这段话告诉我们一个什么道理？`,
    options: [
      { id: "a", text: "分享和爱能带来快乐，自私只会带来冷清和孤独" },
      { id: "b", text: "花园要常常打扫", errorTag: "off_topic" },
      { id: "c", text: "小孩子不能爬树", errorTag: "off_topic" },
      { id: "d", text: "冬天比春天好", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['巨人由自私到分享，花园由冬到春。说明把快乐与人分享、心中有爱，才能拥有真正的快乐。'],
  }),

  // ============================================================
  // 阅读理解 · 短文二 会分享的苹果树 (5 题)
  // ============================================================
  pickChoice({
    id: "cn-u8-read-006",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_TREE}\n\n🔹 第 1 题：老财主用篱笆围住苹果树、挂上“私人苹果，不准动”的牌子后，发生了什么？`,
    options: [
      { id: "a", text: "苹果树再也结不出苹果，叶子落光，光秃秃地立在寒风里" },
      { id: "b", text: "苹果树结了更多苹果", errorTag: "opposite" },
      { id: "c", text: "苹果树开出了满树的花", errorTag: "opposite" },
      { id: "d", text: "小动物们更多了", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['老财主自私地围住、独占苹果树后，树再也结不出苹果、叶子落光，与前面慷慨分享时的丰收形成对比。'],
  }),
  pickChoice({
    id: "cn-u8-read-007",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_TREE}\n\n🔹 第 2 题：这篇童话和课文《巨人的花园》在道理上有什么相同之处？`,
    options: [
      { id: "a", text: "都说明分享带来美好、自私带来荒凉" },
      { id: "b", text: "都说明苹果很好吃", errorTag: "off_topic" },
      { id: "c", text: "都说明动物会说话", errorTag: "narrow_focus" },
      { id: "d", text: "都说明冬天会下雪", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['苹果树分享时硕果累累、被独占后枯萎，和巨人分享花园才有春天一样，都说明分享带来美好、自私带来荒凉。'],
  }),
  pickChoice({
    id: "cn-u8-read-008",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_TREE}\n\n🔹 第 3 题：老财主拆掉篱笆、把苹果分给孩子们后，第二年春天怎么样了？`,
    options: [
      { id: "a", text: "苹果树又开出了满树雪白的花" },
      { id: "b", text: "苹果树彻底枯死了", errorTag: "opposite" },
      { id: "c", text: "篱笆又长了出来", errorTag: "not_in_text" },
      { id: "d", text: "小动物们再也不来了", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['结尾写老财主拆篱笆、分苹果后，“第二年春天，苹果树又开出了满树雪白的花”，呼应分享带来生机。'],
  }),
  pickChoice({
    id: "cn-u8-read-009",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_TREE}\n\n🔹 第 4 题：这是一篇童话，下面属于它“童话特点”的一项是？`,
    options: [
      { id: "a", text: "苹果树会说话、会按人的善恶结果或枯萎，充满奇妙的想象" },
      { id: "b", text: "完全是真实发生的事", errorTag: "opposite" },
      { id: "c", text: "只讲科学知识", errorTag: "off_topic" },
      { id: "d", text: "没有人物形象", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['苹果树能说话、会因善恶而结果或枯萎，这种奇妙的想象正是童话的特点。'],
  }),
  pickChoice({
    id: "cn-u8-read-010",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_TREE}\n\n🔹 第 5 题：这篇童话主要想告诉我们？`,
    options: [
      { id: "a", text: "懂得分享、心中有爱，才能收获快乐和美好" },
      { id: "b", text: "苹果不能随便送人", errorTag: "opposite" },
      { id: "c", text: "种树一定要围篱笆", errorTag: "opposite" },
      { id: "d", text: "小动物不该向别人要东西", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['苹果树乐于分享时硕果累累，被独占后枯萎，分享后又开花。童话告诉我们：懂得分享、心中有爱才能收获美好。'],
  }),

  // ============================================================
  // 听写 (第八单元词语)
  // ============================================================
  dictation({
    id: "cn-u8-dict-001",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "允许",
    options: [
      { id: "a", text: "允许" },
      { id: "b", text: "充许", errorTag: "glyph_homophone" },
      { id: "c", text: "允诉", errorTag: "glyph_homophone" },
      { id: "d", text: "兄许", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“允许”指答应、许可。“允”不要写成“充”。'],
  }),
  dictation({
    id: "cn-u8-dict-002",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "丰硕",
    options: [
      { id: "a", text: "丰硕" },
      { id: "b", text: "丰朔", errorTag: "glyph_homophone" },
      { id: "c", text: "丰烁", errorTag: "glyph_homophone" },
      { id: "d", text: "锋硕", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“丰硕”指又多又大（多形容果实、成果）。“硕”是石字旁。'],
  }),
  dictation({
    id: "cn-u8-dict-003",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "脸颊",
    options: [
      { id: "a", text: "脸颊" },
      { id: "b", text: "脸峡", errorTag: "glyph_homophone" },
      { id: "c", text: "脸侠", errorTag: "glyph_homophone" },
      { id: "d", text: "脸夹", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“脸颊”指脸的两旁。“颊”是页字旁（与头脸有关）。'],
  }),
  dictation({
    id: "cn-u8-dict-004",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "珊瑚",
    options: [
      { id: "a", text: "珊瑚" },
      { id: "b", text: "姗瑚", errorTag: "glyph_homophone" },
      { id: "c", text: "珊湖", errorTag: "glyph_homophone" },
      { id: "d", text: "删瑚", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“珊瑚”是一种海洋生物，两字都是王字旁（玉）。《海的女儿》写海王宫殿的墙是珊瑚砌成的。'],
  }),
  dictation({
    id: "cn-u8-dict-005",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "规矩",
    options: [
      { id: "a", text: "规矩" },
      { id: "b", text: "规距", errorTag: "glyph_homophone" },
      { id: "c", text: "归矩", errorTag: "glyph_homophone" },
      { id: "d", text: "规拒", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“规矩”指一定的标准、习惯。“矩”是矢字旁，不要写成“距”（距离）。'],
  }),

  // ============================================================
  // 期末备考补充批次（爸爸 2026-05-21，补到 ~80）
  // ============================================================
  pickChoice({
    id: "cn-u8-py-011",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“兴”是多音字。下面读音对应正确的一组是？",
    options: [
      { id: "a", text: "兴奋（xīng） 高兴（xìng）" },
      { id: "b", text: "兴奋（xìng） 高兴（xīng）", errorTag: "polyphone_confusion" },
      { id: "c", text: "兴奋（xīng） 高兴（xīng）", errorTag: "polyphone_confusion" },
      { id: "d", text: "兴奋（xìng） 高兴（xìng）", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“兴”：xīng（兴奋、兴办、兴旺）/ xìng（高兴、兴趣、扫兴）。'],
  }),
  pickChoice({
    id: "cn-u8-py-012",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“着”是多音字。下面读音对应正确的一组是？",
    options: [
      { id: "a", text: "着火（zháo） 看着（zhe） 着重（zhuó）" },
      { id: "b", text: "着火（zhe） 看着（zháo） 着重（zhuó）", errorTag: "polyphone_confusion" },
      { id: "c", text: "着火（zhuó） 看着（zhe） 着重（zháo）", errorTag: "polyphone_confusion" },
      { id: "d", text: "着火（zháo） 看着（zhuó） 着重（zhe）", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“着”：zháo（着火、着急、睡着）/ zhe（看着，助词）/ zhuó（着重、着手、穿着）/ zhāo（着数）。'],
  }),
  pickChoice({
    id: "cn-u8-py-013",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“散”是多音字。下面读音对应正确的一组是？",
    options: [
      { id: "a", text: "散步（sàn） 散文（sǎn）" },
      { id: "b", text: "散步（sǎn） 散文（sàn）", errorTag: "polyphone_confusion" },
      { id: "c", text: "散步（sàn） 散文（sàn）", errorTag: "polyphone_confusion" },
      { id: "d", text: "散步（sǎn） 散文（sǎn）", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“散”：sàn（动词，散步、解散、散开）/ sǎn（形容词/名词，散文、松散、散漫）。'],
  }),
  pickChoice({
    id: "cn-u8-py-014",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["phonics", "glyph"],
    difficulty: 2,
    stem: "下面加点字读音全部正确的一组是？",
    options: [
      { id: "a", text: "踪迹（zōng） 隐私（sī） 惩罚（chéng）" },
      { id: "b", text: "踪迹（zhōng） 隐私（sī） 惩罚（chéng）", errorTag: "phonics_error" },
      { id: "c", text: "踪迹（zōng） 隐私（sī） 惩罚（chěng）", errorTag: "phonics_error" },
      { id: "d", text: "踪迹（zōng） 隐私（shī） 惩罚（chéng）", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['踪 zōng、私 sī、惩 chéng（注意不读 chěng）。均出自第八单元。'],
  }),
  pickChoice({
    id: "cn-u8-gl-007",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面没有错别字的一组是（《巨人的花园》词语）：",
    options: [
      { id: "a", text: "踪迹 · 惩罚 · 凄凉" },
      { id: "b", text: "踪迹 · 惩罚 · 凄良", errorTag: "glyph_homophone" },
      { id: "c", text: "踪绩 · 惩罚 · 凄凉", errorTag: "glyph_homophone" },
      { id: "d", text: "踪迹 · 征罚 · 凄凉", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“踪迹”不是“踪绩”；“惩罚”不是“征罚”；“凄凉”不是“凄良”。A 全对。'],
  }),
  pickChoice({
    id: "cn-u8-gl-008",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "辨字组词，全部正确的一组是？",
    options: [
      { id: "a", text: "硕（丰硕）— 朔（朔风）；拽（拽住）— 曳（摇曳）" },
      { id: "b", text: "硕（朔风）— 朔（丰硕）；拽（拽住）— 曳（摇曳）", errorTag: "form_similar" },
      { id: "c", text: "硕（丰硕）— 朔（朔风）；拽（摇曳）— 曳（拽住）", errorTag: "form_similar" },
      { id: "d", text: "硕（丰硕）— 朔（朔风）；拽（拽住）— 曳（拽住）", errorTag: "form_similar" },
    ],
    correct: "a",
    solution: ['“硕”页字旁（丰硕）—“朔”（朔风、农历初一）；“拽”提手旁（拽住、拉）—“曳”（摇曳、拖）。A 全对。'],
  }),
  pickChoice({
    id: "cn-u8-gl-009",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "看拼音写词语：巨人在花园四周筑墙，挂出布告牌：“禁止入内，违者重 chéng（惩）”。",
    options: [
      { id: "a", text: "惩" },
      { id: "b", text: "征", errorTag: "glyph_homophone" },
      { id: "c", text: "澄", errorTag: "glyph_homophone" },
      { id: "d", text: "撑", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“重惩”指重重地处罚。“惩”是心字底（惩罚、惩戒），不要写成“征”。'],
  }),
  pickChoice({
    id: "cn-u8-gl-010",
    unit_id: U8,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "看拼音写词语：每一个蚌壳里面都含有亮晶晶的 zhēn zhū（珍珠）。",
    options: [
      { id: "a", text: "珍珠" },
      { id: "b", text: "珍朱", errorTag: "glyph_homophone" },
      { id: "c", text: "真珠", errorTag: "glyph_homophone" },
      { id: "d", text: "珍株", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“珍珠”两字都是王字旁（玉），指蚌壳里的珠子。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-007",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "《巨人的花园》中，巨人赶走孩子后，花园变得“凄凉”。“凄凉”在这里的意思是？",
    options: [
      { id: "a", text: "冷清、孤寂、没有生气" },
      { id: "b", text: "天气很凉快", errorTag: "literal_misread" },
      { id: "c", text: "非常美丽", errorTag: "antonym_misuse" },
      { id: "d", text: "非常热闹", errorTag: "antonym_misuse" },
    ],
    correct: "a",
    solution: ['花园里只有雪、霜、北风，没有孩子、没有花和鸟，所以“凄凉”指冷清、孤寂、没有生气。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-008",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "《海的女儿》写海王的老母亲“对于自己高贵的出身总感到不可一世”。“不可一世”的意思是？",
    options: [
      { id: "a", text: "自以为了不起，狂妄自大" },
      { id: "b", text: "不能活一辈子", errorTag: "word_misunderstand" },
      { id: "c", text: "一生只有一次", errorTag: "word_misunderstand" },
      { id: "d", text: "非常谦虚", errorTag: "antonym_misuse" },
    ],
    correct: "a",
    solution: ['“不可一世”形容人极其狂妄自大，自以为当代没有人能比得上。这里写老母亲因出身高贵而自负。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-009",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: "下面词语搭配恰当的一组是？",
    options: [
      { id: "a", text: "动听的音乐 · 茂盛的垂柳 · 奇异的光彩" },
      { id: "b", text: "动听的垂柳 · 茂盛的音乐 · 奇异的光彩", errorTag: "collocation_error" },
      { id: "c", text: "动听的音乐 · 茂盛的光彩 · 奇异的垂柳", errorTag: "collocation_error" },
      { id: "d", text: "动听的光彩 · 茂盛的垂柳 · 奇异的音乐", errorTag: "collocation_error" },
    ],
    correct: "a",
    solution: ['“动听”修饰音乐，“茂盛”修饰垂柳（植物），“奇异”修饰光彩，均搭配恰当。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-010",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "选词填空：①小公主总是静静地坐着，（  ）地想着什么。②大家都（  ）地等待着春天的到来。（沉默 / 沉静）",
    options: [
      { id: "a", text: "①沉静 ②沉默" },
      { id: "b", text: "①沉默 ②沉静", errorTag: "synonym_misuse" },
      { id: "c", text: "①沉静 ②沉静", errorTag: "synonym_misuse" },
      { id: "d", text: "①沉默 ②沉默", errorTag: "synonym_misuse" },
    ],
    correct: "a",
    solution: ['“沉静”形容安静、平静的状态（坐着想事）；“沉默”侧重不说话。①重在安静地想，用“沉静”；②重在不出声地等，用“沉默”。'],
  }),
  pickChoice({
    id: "cn-u8-vocab-011",
    unit_id: U8,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: "看拼音写词语：海底最深的地方有一座海王的 gōng diàn（宫殿）。",
    options: [
      { id: "a", text: "宫殿" },
      { id: "b", text: "宫殴", errorTag: "glyph_homophone" },
      { id: "c", text: "官殿", errorTag: "glyph_homophone" },
      { id: "d", text: "宫淀", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“宫殿”指帝王居住的高大房屋。“殿”不要写成“殴”，“宫”不要写成“官”。'],
  }),
  pickChoice({
    id: "cn-u8-imag-009",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading"],
    difficulty: 3,
    stem: "《海的女儿》开头部分极力描写海底世界的奇异美丽，主要作用是？",
    options: [
      { id: "a", text: "营造奇幻的童话氛围，激发读者想象，为故事做铺垫" },
      { id: "b", text: "介绍海洋知识", errorTag: "off_topic" },
      { id: "c", text: "说明海底很危险", errorTag: "off_topic" },
      { id: "d", text: "凑字数", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['详写珊瑚宫殿、琥珀窗、珍珠等奇幻景象，营造出童话特有的瑰丽想象，引人入胜，为小公主的故事做铺垫。'],
  }),
  pickChoice({
    id: "cn-u8-imag-010",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: "童话常常借奇妙的故事讲道理。《宝葫芦的秘密》借王葆的故事告诉我们？",
    options: [
      { id: "a", text: "幸福要靠自己的努力，不劳而获带不来真正的快乐" },
      { id: "b", text: "有了宝葫芦就能样样如意", errorTag: "opposite" },
      { id: "c", text: "做梦能实现愿望", errorTag: "off_topic" },
      { id: "d", text: "种向日葵很难", errorTag: "narrow_focus" },
    ],
    correct: "a",
    solution: ['王葆幻想靠宝葫芦不劳而获，真得到后却只有烦恼。故事告诉我们：幸福和成功要靠自己努力，不能依赖侥幸。'],
  }),
  pickChoice({
    id: "cn-u8-imag-011",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading", "expression"],
    difficulty: 3,
    stem: "习作“故事新编”要求改编《龟兔赛跑》。下面属于合理“新编”想象的一项是？",
    options: [
      { id: "a", text: "兔子吸取教训不再睡觉，可半路遇到河流挡道，乌龟靠游泳赢了" },
      { id: "b", text: "兔子和乌龟都不参加比赛", errorTag: "off_topic" },
      { id: "c", text: "直接抄原来的故事，一字不改", errorTag: "no_imagine" },
      { id: "d", text: "把乌龟写成会开飞机的科学家，与故事毫无关系", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['“故事新编”要在原故事基础上合理想象、改变情节或结局（如赛道变化、路遇不测）。A 既有新意又合情理。'],
  }),
  pickChoice({
    id: "cn-u8-imag-012",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading"],
    difficulty: 3,
    stem: "下面对“童话”特点的理解，不正确的一项是？",
    options: [
      { id: "a", text: "童话写的都是真人真事，不能有想象", errorTag: "opposite" },
      { id: "b", text: "童话充满奇妙的想象" },
      { id: "c", text: "童话里的人物常有非凡的能力" },
      { id: "d", text: "童话能让我们感受到真善美" },
    ],
    correct: "a",
    solution: ['本题选不正确的一项。童话的突出特点正是“奇妙的想象”，A 说“不能有想象”恰恰说反了。'],
  }),
  pickChoice({
    id: "cn-u8-imag-013",
    unit_id: U8,
    skill_id: IMAGINE,
    ability: ["reading"],
    difficulty: 3,
    stem: "下面课文和它们所属类型，搭配正确的一项是？",
    options: [
      { id: "a", text: "《巨人的花园》《海的女儿》《宝葫芦的秘密》都是童话" },
      { id: "b", text: "《海的女儿》是写人记事的记叙文", errorTag: "category_confusion" },
      { id: "c", text: "《巨人的花园》是说明文", errorTag: "category_confusion" },
      { id: "d", text: "《宝葫芦的秘密》是古诗", errorTag: "category_confusion" },
    ],
    correct: "a",
    solution: ['第八单元是童话单元，《巨人的花园》《海的女儿》《宝葫芦的秘密》都是充满奇妙想象的童话。'],
  }),
  pickChoice({
    id: "cn-u8-sent-006",
    unit_id: U8,
    skill_id: SENTENCE,
    ability: ["sentence"],
    difficulty: 3,
    stem: "《巨人的花园》“北风……他说：‘这是个好地方，我们一定要请雹来玩一玩。’”这句话用了什么修辞？",
    options: [
      { id: "a", text: "拟人（把北风当作人，会说话、会邀请）" },
      { id: "b", text: "比喻", errorTag: "wrong_rhetoric" },
      { id: "c", text: "排比", errorTag: "wrong_rhetoric" },
      { id: "d", text: "反问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['北风会“说话”、会“请雹来玩”，把北风当作人来写，是拟人，写出花园终年寒冬的景象。'],
  }),
  pickChoice({
    id: "cn-u8-sent-007",
    unit_id: U8,
    skill_id: SENTENCE,
    ability: ["sentence"],
    difficulty: 4,
    stem: "《海的女儿》“当海非常沉静的时候，你可以瞥见太阳：它像一朵紫色的花，从它的花萼里射出各种颜色的光。”这句话主要用了什么修辞？",
    options: [
      { id: "a", text: "比喻（把太阳比作一朵紫色的花）" },
      { id: "b", text: "拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "夸张", errorTag: "wrong_rhetoric" },
      { id: "d", text: "设问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['“它像一朵紫色的花”是比喻，把透过海水看到的太阳比作紫色的花，写出海底看太阳的奇幻美丽。'],
  }),
  pickChoice({
    id: "cn-u8-sent-008",
    unit_id: U8,
    skill_id: SENTENCE,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: "照样子写句子。例：地上全是最细的沙子，蓝得像硫黄发出的光焰。下面仿写最恰当的一句是？",
    options: [
      { id: "a", text: "天上的晚霞红得像一团团燃烧的火。" },
      { id: "b", text: "天上的晚霞很红。", errorTag: "no_rhetoric" },
      { id: "c", text: "天上有晚霞。", errorTag: "no_rhetoric" },
      { id: "d", text: "晚霞在天上。", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['例句是“……得像……”的比喻句。A“红得像一团团燃烧的火”结构相同、用了比喻，仿写最恰当。'],
  }),
  // 阅读理解 · 短文三 会飞的书包 (5 题)
  pickChoice({
    id: "cn-u8-read-011",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_FLY}\n\n🔹 第 1 题：这篇短文“奇妙的想象”主要表现在哪里？`,
    options: [
      { id: "a", text: "普通的书包会说话、会长出翅膀带人飞" },
      { id: "b", text: "丁丁背着书包走路", errorTag: "narrow_focus" },
      { id: "c", text: "小红爬台阶", errorTag: "narrow_focus" },
      { id: "d", text: "太阳升起来了", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['书包会说话、长翅膀、驮着孩子飞翔，这种超越现实的想象正是童话“奇妙想象”的体现。'],
  }),
  pickChoice({
    id: "cn-u8-read-012",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_FLY}\n\n🔹 第 2 题：“云朵软软的，像一团团棉花糖”用了什么修辞？`,
    options: [
      { id: "a", text: "比喻（把云朵比作棉花糖）" },
      { id: "b", text: "拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "排比", errorTag: "wrong_rhetoric" },
      { id: "d", text: "反问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['“像一团团棉花糖”是比喻，把软软的云朵比作棉花糖，写出在天上飞的美好感受。'],
  }),
  pickChoice({
    id: "cn-u8-read-013",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_FLY}\n\n🔹 第 3 题：丁丁看见小红背着沉重的书包爬台阶，他是怎么做的？`,
    options: [
      { id: "a", text: "让书包降落，把一只翅膀分给小红的书包，一起飞进教室" },
      { id: "b", text: "自己先飞走了", errorTag: "opposite" },
      { id: "c", text: "嘲笑小红", errorTag: "opposite" },
      { id: "d", text: "把书包送给了小红", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['丁丁犹豫后让书包降落，把翅膀分了一只给小红的书包，两个孩子一起飞进教室，体现他乐于分享、关心同学。'],
  }),
  pickChoice({
    id: "cn-u8-read-014",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_FLY}\n\n🔹 第 4 题：书包说“把快乐分给别人，快乐会变成两份”，这句话的意思是？`,
    options: [
      { id: "a", text: "懂得分享，自己和别人都能得到快乐" },
      { id: "b", text: "快乐可以用数学加出来", errorTag: "literal_misread" },
      { id: "c", text: "把东西分掉就少了一半", errorTag: "opposite" },
      { id: "d", text: "书包会算数", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['这句话告诉我们：把快乐分享给别人，别人快乐，自己也更快乐，快乐就“变成两份”。'],
  }),
  pickChoice({
    id: "cn-u8-read-015",
    unit_id: U8,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_FLY}\n\n🔹 第 5 题：这篇童话主要想告诉我们？`,
    options: [
      { id: "a", text: "要乐于助人、懂得分享，把快乐带给别人" },
      { id: "b", text: "书包应该会飞", errorTag: "literal_misread" },
      { id: "c", text: "上学不用爬台阶", errorTag: "off_topic" },
      { id: "d", text: "飞行比走路快", errorTag: "narrow_focus" },
    ],
    correct: "a",
    solution: ['丁丁把翅膀分给小红、书包带同学一起飞，借奇妙的想象告诉我们：要乐于助人、懂得分享，快乐才会更多。'],
  }),
  dictation({
    id: "cn-u8-dict-006",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "踪迹",
    options: [
      { id: "a", text: "踪迹" },
      { id: "b", text: "踪绩", errorTag: "glyph_homophone" },
      { id: "c", text: "综迹", errorTag: "glyph_homophone" },
      { id: "d", text: "踪际", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“踪迹”指行动留下的痕迹。“踪”足字旁，“迹”走之旁。'],
  }),
  dictation({
    id: "cn-u8-dict-007",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "惩罚",
    options: [
      { id: "a", text: "惩罚" },
      { id: "b", text: "征罚", errorTag: "glyph_homophone" },
      { id: "c", text: "惩罪", errorTag: "glyph_homophone" },
      { id: "d", text: "澄罚", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“惩罚”指处罚。“惩”是心字底（惩戒），不要写成“征”。'],
  }),
  dictation({
    id: "cn-u8-dict-008",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "拆除",
    options: [
      { id: "a", text: "拆除" },
      { id: "b", text: "折除", errorTag: "glyph_homophone" },
      { id: "c", text: "拆涂", errorTag: "glyph_homophone" },
      { id: "d", text: "坼除", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“拆除”指把建筑物等拆掉。“拆”提手旁（chāi），不要写成“折”（zhé）。巨人最后拆除了围墙。'],
  }),
  dictation({
    id: "cn-u8-dict-009",
    unit_id: U8,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "向日葵",
    options: [
      { id: "a", text: "向日葵" },
      { id: "b", text: "向日揆", errorTag: "glyph_homophone" },
      { id: "c", text: "向日魁", errorTag: "glyph_homophone" },
      { id: "d", text: "向曰葵", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“向日葵”是朝着太阳的葵花。“葵”是草字头，“向日”不要写成“向曰”。'],
  }),
];
