/**
 * 语文 · C4B 难度梯度补充包 (v0.36.83+, 爸爸 2026-05-21).
 *
 * 背景: 原题库难度分布失衡 —— D1(很易) 仅 1 题、D5(很难) 为 0，自适应"做好升级 /
 * 做不好降级"缺料。本包给全 8 单元铺满 D1→D5 五个难度层并把各单元补到 ~100 平衡:
 *   - D1 送分基础题 (字音/字形/词义/作者常识，单点、直给)
 *   - D5 拔高综合题 (多音字综合辨析/易错字形/修辞综合/古诗文深层理解)
 *   - D2/D4 平衡题 (把偏薄单元补到 ~100)
 * 目标难度比例约 D1:D2:D3:D4:D5 ≈ 12:25:35:22:6。
 *
 * 内容均依据人教版四下课本与通行古诗文。id 前缀: cn-uN-e(易)/-h(难)/-b(平衡)。
 * 约定: 双引号字符串内的引文一律用全角“”。
 */

import type { Question } from "../../core/types";
import { pickChoice } from "./questionHelpers";

const U1 = "C4B_U1_NATURE";
const U2 = "C4B_U2_SCIENCE";
const U3 = "C4B_U3_POETRY";
const U4 = "C4B_U4_ANIMALS";
const U5 = "C4B_U5_TRAVEL";
const U6 = "C4B_U6_GROWTH";
const U7 = "C4B_U7_CHARACTER";
const U8 = "C4B_U8_FAIRYTALE";

export const SEED_QUESTIONS_CHINESE_DIFF: Question[] = [
  // ====================================================================
  // 第一单元 · D1 送分基础 (10)
  // ====================================================================
  pickChoice({ id: "cn-u1-e-001", unit_id: U1, skill_id: "C4B_U1_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“蜻蜓”的正确读音是？",
    options: [ { id: "a", text: "qīng tíng" }, { id: "b", text: "qíng tíng", errorTag: "tone_confusion" }, { id: "c", text: "jīng tíng", errorTag: "phonics_error" }, { id: "d", text: "qīng tíng（错读 tín）", errorTag: "tone_confusion" } ],
    correct: "a", solution: ["“蜻蜓”读 qīng tíng，一种益虫。两字都是虫字旁。"] }),
  pickChoice({ id: "cn-u1-e-002", unit_id: U1, skill_id: "C4B_U1_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "下面字全对的一组是？",
    options: [ { id: "a", text: "蝴蝶 · 篱笆" }, { id: "b", text: "蝴喋 · 篱笆", errorTag: "glyph_homophone" }, { id: "c", text: "蝴蝶 · 离笆", errorTag: "glyph_homophone" }, { id: "d", text: "胡蝶 · 篱笆", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“蝴蝶”都是虫字旁；“篱笆”都是竹字头（用竹子编的）。"] }),
  pickChoice({ id: "cn-u1-e-003", unit_id: U1, skill_id: "C4B_U1_POEM_RECITE", ability: ["accumulation"], difficulty: 1,
    stem: "《四时田园杂兴（其二十五）》的作者是？",
    options: [ { id: "a", text: "范成大" }, { id: "b", text: "杨万里", errorTag: "author_confusion" }, { id: "c", text: "辛弃疾", errorTag: "author_confusion" }, { id: "d", text: "李白", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《四时田园杂兴》是宋代范成大的田园诗。"] }),
  pickChoice({ id: "cn-u1-e-004", unit_id: U1, skill_id: "C4B_U1_POEM_RECITE", ability: ["accumulation"], difficulty: 1,
    stem: "默写填空：梅子金黄杏子肥，（  ）。",
    options: [ { id: "a", text: "麦花雪白菜花稀" }, { id: "b", text: "树头新绿未成阴", errorTag: "poem_mismatch" }, { id: "c", text: "茅檐低小", errorTag: "poem_mismatch" }, { id: "d", text: "溪上青青草", errorTag: "poem_mismatch" } ],
    correct: "a", solution: ["出自《四时田园杂兴》：“梅子金黄杏子肥，麦花雪白菜花稀。”"] }),
  pickChoice({ id: "cn-u1-e-005", unit_id: U1, skill_id: "C4B_U1_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“天高地阔”中“阔”的意思是？",
    options: [ { id: "a", text: "宽广" }, { id: "b", text: "有钱", errorTag: "word_misunderstand" }, { id: "c", text: "离开", errorTag: "word_misunderstand" }, { id: "d", text: "快乐", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“天高地阔”指天地宽广。“阔”是宽广的意思。"] }),
  pickChoice({ id: "cn-u1-e-006", unit_id: U1, skill_id: "C4B_U1_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "《乡下人家》中“瓜架”的“瓜”，下面词语用对的是？",
    options: [ { id: "a", text: "南瓜" }, { id: "b", text: "西爪", errorTag: "glyph_homophone" }, { id: "c", text: "瓜（写成“爪”）", errorTag: "glyph_homophone" }, { id: "d", text: "刮瓜", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“瓜”指葫芦科植物的果实，如南瓜、西瓜。注意“瓜”不要写成“爪”（zhǎo）。"] }),
  pickChoice({ id: "cn-u1-e-007", unit_id: U1, skill_id: "C4B_U1_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“归巢”的“巢”读音是？",
    options: [ { id: "a", text: "cháo" }, { id: "b", text: "cáo", errorTag: "phonics_error" }, { id: "c", text: "chāo", errorTag: "tone_confusion" }, { id: "d", text: "zhāo", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“巢”读 cháo，指鸟窝。“归巢”指鸟儿回到窝里。"] }),
  pickChoice({ id: "cn-u1-e-008", unit_id: U1, skill_id: "C4B_U1_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "《天窗》的作者是？",
    options: [ { id: "a", text: "茅盾" }, { id: "b", text: "老舍", errorTag: "author_confusion" }, { id: "c", text: "巴金", errorTag: "author_confusion" }, { id: "d", text: "叶圣陶", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《天窗》的作者是现代作家茅盾。"] }),
  pickChoice({ id: "cn-u1-e-009", unit_id: U1, skill_id: "C4B_U1_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "看拼音写词语：屋后种着一片 zhú lín（竹林）。",
    options: [ { id: "a", text: "竹林" }, { id: "b", text: "竹邻", errorTag: "glyph_homophone" }, { id: "c", text: "烛林", errorTag: "glyph_homophone" }, { id: "d", text: "竹琳", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“竹林”指竹子成片的树林。“林”是双木。"] }),
  pickChoice({ id: "cn-u1-e-010", unit_id: U1, skill_id: "C4B_U1_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“朴素”的意思最接近？",
    options: [ { id: "a", text: "朴实、不华丽" }, { id: "b", text: "聪明", errorTag: "word_misunderstand" }, { id: "c", text: "干净", errorTag: "synonym_misuse" }, { id: "d", text: "高贵", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["“朴素”指朴实、不浮华，如“纯朴的乡村”。"] }),

  // 第一单元 · D5 拔高综合 (6)
  pickChoice({ id: "cn-u1-h-001", unit_id: U1, skill_id: "C4B_U1_PINYIN", ability: ["phonics"], difficulty: 5,
    stem: "下面句子中加点的多音字读音全部正确的一项是（“剥莲蓬”“剥皮”“归宿”“一宿”）？",
    options: [ { id: "a", text: "剥莲蓬（bāo） 剥皮（bāo） 归宿（sù） 一宿（xiǔ）" }, { id: "b", text: "剥莲蓬（bō） 剥皮（bāo） 归宿（sù） 一宿（xiǔ）", errorTag: "polyphone_confusion" }, { id: "c", text: "剥莲蓬（bāo） 剥皮（bō） 归宿（xiǔ） 一宿（sù）", errorTag: "polyphone_confusion" }, { id: "d", text: "剥莲蓬（bāo） 剥皮（bāo） 归宿（xiǔ） 一宿（sù）", errorTag: "polyphone_confusion" } ],
    correct: "a", solution: ["“剥”口语读 bāo（剥莲蓬、剥皮），书面合成词读 bō（剥削）；“宿”：sù（归宿/住宿）、xiǔ（一宿，量词）、xiù（星宿）。"] }),
  pickChoice({ id: "cn-u1-h-002", unit_id: U1, skill_id: "C4B_U1_POEM_RECITE", ability: ["accumulation", "reading"], difficulty: 5,
    stem: "《宿新市徐公店》“儿童急走追黄蝶，飞入菜花无处寻”表现的是？",
    options: [ { id: "a", text: "儿童的天真活泼和田园的盎然春意" }, { id: "b", text: "农民劳动的辛苦", errorTag: "off_topic" }, { id: "c", text: "诗人思乡的愁绪", errorTag: "off_topic" }, { id: "d", text: "蝴蝶飞得太快抓不到的遗憾", errorTag: "narrow_focus" } ],
    correct: "a", solution: ["儿童奔跑追蝶、蝶入菜花无处寻，一动一静，写出儿童的天真烂漫和暮春田园的生机。"] }),
  pickChoice({ id: "cn-u1-h-003", unit_id: U1, skill_id: "C4B_U1_POEM_RECITE", ability: ["accumulation", "reading"], difficulty: 5,
    stem: "《清平乐·村居》“最喜小儿亡赖，溪头卧剥莲蓬”中，“亡赖”的意思是？",
    options: [ { id: "a", text: "同“无赖”，这里指顽皮、可爱（褒义）" }, { id: "b", text: "不讲道理的坏人", errorTag: "word_misunderstand" }, { id: "c", text: "没有依靠", errorTag: "word_misunderstand" }, { id: "d", text: "逃跑", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“亡赖”同“无赖”，在词中是爱称，形容小儿调皮、天真可爱，并非贬义。"] }),
  pickChoice({ id: "cn-u1-h-004", unit_id: U1, skill_id: "C4B_U1_VOCAB", ability: ["sentence", "expression"], difficulty: 5,
    stem: "《乡下人家》“几场春雨过后，到那里走走，常常会看见许多鲜嫩的笋，成群地从土里探出头来。”这句话好在哪里？",
    options: [ { id: "a", text: "用“探出头来”把春笋拟人化，写出春笋破土而出的生机和俏皮" }, { id: "b", text: "说明笋有头", errorTag: "literal_misread" }, { id: "c", text: "说明笋很多", errorTag: "narrow_focus" }, { id: "d", text: "没有修辞", errorTag: "wrong_rhetoric" } ],
    correct: "a", solution: ["“探出头来”是拟人，把春笋当人写，生动表现春笋纷纷破土、充满生机的样子。"] }),
  pickChoice({ id: "cn-u1-h-005", unit_id: U1, skill_id: "C4B_U1_VOCAB", ability: ["glyph", "vocabulary"], difficulty: 5,
    stem: "下面词语中，没有错别字且全部出自第一单元的一组是？",
    options: [ { id: "a", text: "屋檐 · 鸡冠 · 归巢 · 和谐" }, { id: "b", text: "屋檐 · 鸡冠 · 归潮 · 和谐", errorTag: "glyph_homophone" }, { id: "c", text: "屋沿 · 鸡冠 · 归巢 · 和协", errorTag: "glyph_homophone" }, { id: "d", text: "屋檐 · 鸡观 · 归巢 · 和谐", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“屋檐”不是“屋沿”；“归巢”不是“归潮”；“和谐”不是“和协”；“鸡冠”不是“鸡观”。A 全对。"] }),
  pickChoice({ id: "cn-u1-h-006", unit_id: U1, skill_id: "C4B_U1_POEM_RECITE", ability: ["accumulation", "reading"], difficulty: 5,
    stem: "三首古诗词都描写田园乡村。下面理解不正确的一项是？",
    options: [ { id: "a", text: "三首都表达了诗人对官场的厌倦和愤怒", errorTag: "over_reading" }, { id: "b", text: "《四时田园杂兴》写初夏江南田园风光" }, { id: "c", text: "《宿新市徐公店》写暮春儿童追蝶的情趣" }, { id: "d", text: "《清平乐·村居》写农家温馨和乐的生活" } ],
    correct: "a", solution: ["本题选不正确项。三首都借田园抒发对乡村生活的喜爱与闲适，A 说“厌倦愤怒”属过度解读。"] }),

  // ====================================================================
  // 第二单元 · D1 送分基础 (10)
  // ====================================================================
  pickChoice({ id: "cn-u2-e-001", unit_id: U2, skill_id: "C4B_U2_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“琥珀”的正确读音是？",
    options: [ { id: "a", text: "hǔ pò" }, { id: "b", text: "hú pò", errorTag: "tone_confusion" }, { id: "c", text: "hǔ bó", errorTag: "phonics_error" }, { id: "d", text: "hù pò", errorTag: "tone_confusion" } ],
    correct: "a", solution: ["“琥珀”读 hǔ pò，松脂的化石。两字都是王字旁。"] }),
  pickChoice({ id: "cn-u2-e-002", unit_id: U2, skill_id: "C4B_U2_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“恐龙”的“恐”读音是？",
    options: [ { id: "a", text: "kǒng" }, { id: "b", text: "gǒng", errorTag: "phonics_error" }, { id: "c", text: "kōng", errorTag: "tone_confusion" }, { id: "d", text: "qǒng", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“恐”读 kǒng，害怕、恐怕。“恐龙”是古代的爬行动物。"] }),
  pickChoice({ id: "cn-u2-e-003", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "1 纳米等于多少米？（《纳米技术就在我们身边》）",
    options: [ { id: "a", text: "10 亿分之一米" }, { id: "b", text: "1 万分之一米", errorTag: "fact_wrong" }, { id: "c", text: "1 厘米", errorTag: "fact_wrong" }, { id: "d", text: "1 毫米", errorTag: "fact_wrong" } ],
    correct: "a", solution: ["课文明确：1 纳米等于 10 亿分之一米，非常非常小。"] }),
  pickChoice({ id: "cn-u2-e-004", unit_id: U2, skill_id: "C4B_U2_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "下面字全对的一组是？",
    options: [ { id: "a", text: "蔬菜 · 钢铁" }, { id: "b", text: "梳菜 · 钢铁", errorTag: "glyph_homophone" }, { id: "c", text: "蔬菜 · 刚铁", errorTag: "glyph_homophone" }, { id: "d", text: "疏菜 · 钢铁", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“蔬菜”是草字头（可吃的菜）；“钢铁”的“钢”是金字旁。"] }),
  pickChoice({ id: "cn-u2-e-005", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“健康”的“健”意思是？",
    options: [ { id: "a", text: "身体强壮" }, { id: "b", text: "建造", errorTag: "word_misunderstand" }, { id: "c", text: "钥匙", errorTag: "word_misunderstand" }, { id: "d", text: "建议", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“健”指身体强壮，“健康”指身体好、没有疾病。"] }),
  pickChoice({ id: "cn-u2-e-006", unit_id: U2, skill_id: "C4B_U2_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“膨大”的“膨”读音是？",
    options: [ { id: "a", text: "péng" }, { id: "b", text: "bēng", errorTag: "phonics_error" }, { id: "c", text: "pēng", errorTag: "tone_confusion" }, { id: "d", text: "pán", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“膨”读 péng，“膨大、膨胀”指体积变大。"] }),
  pickChoice({ id: "cn-u2-e-007", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["glyph"], difficulty: 1,
    stem: "看拼音写词语：科学家做了大量的 shí yàn（实验）。",
    options: [ { id: "a", text: "实验" }, { id: "b", text: "实捡", errorTag: "glyph_homophone" }, { id: "c", text: "实念", errorTag: "glyph_homophone" }, { id: "d", text: "石验", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“实验”指为验证而进行的操作。“验”是马字旁。"] }),
  pickChoice({ id: "cn-u2-e-008", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“千年梦圆在今朝”里的“圆”，在“梦圆”中的意思是？",
    options: [ { id: "a", text: "实现（梦想实现了）" }, { id: "b", text: "圆形", errorTag: "literal_misread" }, { id: "c", text: "圆满的圆球", errorTag: "literal_misread" }, { id: "d", text: "团圆", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“梦圆”指梦想实现。指中国人飞天的千年梦想终于在今天实现了。"] }),
  pickChoice({ id: "cn-u2-e-009", unit_id: U2, skill_id: "C4B_U2_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“隐藏”的“隐”读音是？",
    options: [ { id: "a", text: "yǐn" }, { id: "b", text: "yìn", errorTag: "tone_confusion" }, { id: "c", text: "wěn", errorTag: "phonics_error" }, { id: "d", text: "yīn", errorTag: "tone_confusion" } ],
    correct: "a", solution: ["“隐”读 yǐn，“隐藏”指藏起来不让人看见。"] }),
  pickChoice({ id: "cn-u2-e-010", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "下面词语意思和“庞大”最接近的是？",
    options: [ { id: "a", text: "巨大" }, { id: "b", text: "细小", errorTag: "antonym_misuse" }, { id: "c", text: "美丽", errorTag: "synonym_misuse" }, { id: "d", text: "明亮", errorTag: "synonym_misuse" } ],
    correct: "a", solution: ["“庞大”指非常大，与“巨大”意思相近，与“细小”相反。"] }),

  // 第二单元 · D5 拔高综合 (6)
  pickChoice({ id: "cn-u2-h-001", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["reading", "expression"], difficulty: 5,
    stem: "《飞向蓝天的恐龙》中“一支(恐龙)逐渐演化成了今天的鸟类”，“演化”一词说明？",
    options: [ { id: "a", text: "鸟类是由一部分恐龙经过漫长岁月逐渐进化来的" }, { id: "b", text: "恐龙会表演变化", errorTag: "literal_misread" }, { id: "c", text: "恐龙突然变成了鸟", errorTag: "word_misunderstand" }, { id: "d", text: "鸟和恐龙没有关系", errorTag: "opposite" } ],
    correct: "a", solution: ["“演化”指生物经过漫长时间逐渐进化。课文推测一支恐龙慢慢演化成了今天的鸟类。"] }),
  pickChoice({ id: "cn-u2-h-002", unit_id: U2, skill_id: "C4B_U2_PINYIN", ability: ["phonics"], difficulty: 5,
    stem: "下面加点多音字读音全部正确的一项（“划船”“计划”“数不清”“数学”）？",
    options: [ { id: "a", text: "划船（huá） 计划（huà） 数不清（shǔ） 数学（shù）" }, { id: "b", text: "划船（huà） 计划（huá） 数不清（shǔ） 数学（shù）", errorTag: "polyphone_confusion" }, { id: "c", text: "划船（huá） 计划（huà） 数不清（shù） 数学（shǔ）", errorTag: "polyphone_confusion" }, { id: "d", text: "划船（huà） 计划（huà） 数不清（shù） 数学（shù）", errorTag: "polyphone_confusion" } ],
    correct: "a", solution: ["划：huá（划船）/huà（计划）；数：shǔ（数数、数不清，动词）/shù（数学、数字，名词）。"] }),
  pickChoice({ id: "cn-u2-h-003", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["reading"], difficulty: 5,
    stem: "《纳米技术就在我们身边》主要用了哪些说明方法？",
    options: [ { id: "a", text: "举例子、作比较、列数字（如“比头发丝细 5 万倍”）" }, { id: "b", text: "只讲故事，没有说明方法", errorTag: "method_wrong" }, { id: "c", text: "只有比喻", errorTag: "method_wrong" }, { id: "d", text: "全是抒情", errorTag: "method_wrong" } ],
    correct: "a", solution: ["课文用“10 亿分之一米”“细 5 万倍”（列数字、作比较）、纳米涂料/药物/材料（举例子）等说明方法把抽象的纳米讲清楚。"] }),
  pickChoice({ id: "cn-u2-h-004", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["glyph"], difficulty: 5,
    stem: "下面四组词中，全部没有错别字的一组是？",
    options: [ { id: "a", text: "腐烂 · 黏稠 · 翱翔 · 描绘" }, { id: "b", text: "腐烂 · 粘稠 · 翱翔 · 描会", errorTag: "glyph_homophone" }, { id: "c", text: "腐栏 · 黏稠 · 遨翔 · 描绘", errorTag: "glyph_homophone" }, { id: "d", text: "腐烂 · 黏稠 · 翱翔 · 苗绘", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“描绘”不是“描会/苗绘”；“腐烂”不是“腐栏”；“翱翔”不是“遨翔”。A 全对。"] }),
  pickChoice({ id: "cn-u2-h-005", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["reading", "expression"], difficulty: 5,
    stem: "《琥珀》一文中，科学家是怎样推测出琥珀形成过程的？",
    options: [ { id: "a", text: "根据琥珀里裹着的苍蝇和蜘蛛等细节，合理想象、推测出来的" }, { id: "b", text: "亲眼看见琥珀形成", errorTag: "fact_wrong" }, { id: "c", text: "凭空编造的", errorTag: "word_misunderstand" }, { id: "d", text: "问古人得知的", errorTag: "off_topic" } ],
    correct: "a", solution: ["《琥珀》依据琥珀中包裹的苍蝇、蜘蛛等真实细节，科学合理地推测出松脂滴落、包裹昆虫、变成化石的过程。"] }),
  pickChoice({ id: "cn-u2-h-006", unit_id: U2, skill_id: "C4B_U2_VOCAB", ability: ["reading"], difficulty: 5,
    stem: "《千年梦圆在今朝》中“千年梦”指的是？",
    options: [ { id: "a", text: "中华民族千百年来的飞天（航天）梦想" }, { id: "b", text: "睡了一千年的梦", errorTag: "literal_misread" }, { id: "c", text: "做一千个梦", errorTag: "literal_misread" }, { id: "d", text: "古代神话故事", errorTag: "narrow_focus" } ],
    correct: "a", solution: ["“千年梦”指中华民族千百年来渴望飞上天空的梦想，神舟飞船成功使这个梦“圆在今朝”。"] }),

  // ====================================================================
  // 第三单元 · D1 送分基础 (10)
  // ====================================================================
  pickChoice({ id: "cn-u3-e-001", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["accumulation"], difficulty: 1,
    stem: "《繁星》（七一、一三一、一五九）的作者是？",
    options: [ { id: "a", text: "冰心" }, { id: "b", text: "艾青", errorTag: "author_confusion" }, { id: "c", text: "叶赛宁", errorTag: "author_confusion" }, { id: "d", text: "戴望舒", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《短诗三首》（繁星）是现代作家冰心的作品。"] }),
  pickChoice({ id: "cn-u3-e-002", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“白桦”的“桦”读音是？",
    options: [ { id: "a", text: "huà" }, { id: "b", text: "huā", errorTag: "tone_confusion" }, { id: "c", text: "huá", errorTag: "tone_confusion" }, { id: "d", text: "kuà", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“桦”读 huà，一种落叶乔木。《白桦》作者是俄国诗人叶赛宁。"] }),
  pickChoice({ id: "cn-u3-e-003", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "下面字全对的一组是？",
    options: [ { id: "a", text: "朦胧 · 寂静" }, { id: "b", text: "蒙胧 · 寂静", errorTag: "glyph_homophone" }, { id: "c", text: "朦胧 · 寂净", errorTag: "glyph_homophone" }, { id: "d", text: "朦眬 · 寂静", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“朦胧”都是月字旁（模糊不清）；“寂静”指安静没声音。"] }),
  pickChoice({ id: "cn-u3-e-004", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["accumulation"], difficulty: 1,
    stem: "《绿》的作者是？",
    options: [ { id: "a", text: "艾青" }, { id: "b", text: "冰心", errorTag: "author_confusion" }, { id: "c", text: "杨万里", errorTag: "author_confusion" }, { id: "d", text: "茅盾", errorTag: "author_confusion" } ],
    correct: "a", solution: ["现代诗《绿》的作者是诗人艾青。"] }),
  pickChoice({ id: "cn-u3-e-005", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“波涛”的“涛”读音是？",
    options: [ { id: "a", text: "tāo" }, { id: "b", text: "dāo", errorTag: "phonics_error" }, { id: "c", text: "táo", errorTag: "tone_confusion" }, { id: "d", text: "shòu", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“涛”读 tāo，指大的波浪，“波涛”。三点水旁。"] }),
  pickChoice({ id: "cn-u3-e-006", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["accumulation"], difficulty: 1,
    stem: "默写填空：《繁星（一五九）》——母亲啊！天上的风雨来了，鸟儿躲到它的巢里；心中的风雨来了，我只躲到（  ）。",
    options: [ { id: "a", text: "你的怀里" }, { id: "b", text: "它的巢里", errorTag: "poem_mismatch" }, { id: "c", text: "大海里", errorTag: "poem_mismatch" }, { id: "d", text: "藤萝的叶下", errorTag: "poem_mismatch" } ],
    correct: "a", solution: ["《繁星（一五九）》：“心中的风雨来了，我只躲到你的怀里。”表达对母亲的依恋。"] }),
  pickChoice({ id: "cn-u3-e-007", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "看拼音写词语：雨过天晴，空气格外 qīng xīn（清新）。",
    options: [ { id: "a", text: "清新" }, { id: "b", text: "青新", errorTag: "glyph_homophone" }, { id: "c", text: "清辛", errorTag: "glyph_homophone" }, { id: "d", text: "轻新", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“清新”指清爽新鲜。“清”三点水。"] }),
  pickChoice({ id: "cn-u3-e-008", unit_id: U3, skill_id: "C4B_U3_RHETORIC", ability: ["sentence"], difficulty: 1,
    stem: "“好像绿色的墨水瓶倒翻了，到处是绿的。”这句话用了什么修辞？",
    options: [ { id: "a", text: "比喻" }, { id: "b", text: "拟人", errorTag: "wrong_rhetoric" }, { id: "c", text: "排比", errorTag: "wrong_rhetoric" }, { id: "d", text: "反问", errorTag: "wrong_rhetoric" } ],
    correct: "a", solution: ["“好像……倒翻了”是比喻，写出《绿》中到处是绿的景象。"] }),
  pickChoice({ id: "cn-u3-e-009", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“漫灭”的“漫”读音是？",
    options: [ { id: "a", text: "màn" }, { id: "b", text: "mān", errorTag: "tone_confusion" }, { id: "c", text: "wàn", errorTag: "phonics_error" }, { id: "d", text: "mǎn", errorTag: "tone_confusion" } ],
    correct: "a", solution: ["“漫”读 màn，“永不漫灭”指永不磨灭。"] }),
  pickChoice({ id: "cn-u3-e-010", unit_id: U3, skill_id: "C4B_U3_RHETORIC", ability: ["vocabulary"], difficulty: 1,
    stem: "“在天晴了的时候”里“晴”的反义词是？",
    options: [ { id: "a", text: "阴（雨）" }, { id: "b", text: "亮", errorTag: "word_misunderstand" }, { id: "c", text: "热", errorTag: "word_misunderstand" }, { id: "d", text: "白", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“晴”指晴天，反义词是“阴”（阴天/下雨）。"] }),

  // 第三单元 · D5 拔高综合 (6)
  pickChoice({ id: "cn-u3-h-001", unit_id: U3, skill_id: "C4B_U3_RHETORIC", ability: ["sentence", "reading"], difficulty: 5,
    stem: "《繁星（一三一）》“哪一颗星没有光？哪一朵花没有香？”连用两个问句，这种修辞和作用是？",
    options: [ { id: "a", text: "反问 + 排比；强烈地表达“每颗星都有光、每朵花都有香”，引出对大海的赞美" }, { id: "b", text: "设问；自问自答", errorTag: "wrong_rhetoric" }, { id: "c", text: "比喻；把星比作花", errorTag: "wrong_rhetoric" }, { id: "d", text: "夸张", errorTag: "wrong_rhetoric" } ],
    correct: "a", solution: ["两个“哪一……没有……”是反问，又结构相同连用构成排比，加强语气，引出对大海（母亲）的深情。"] }),
  pickChoice({ id: "cn-u3-h-002", unit_id: U3, skill_id: "C4B_U3_RHETORIC", ability: ["reading", "expression"], difficulty: 5,
    stem: "《白桦》中诗人反复描写白桦的洁白、挺拔，借白桦表达的是？",
    options: [ { id: "a", text: "对高洁、坚强品格的赞美和对家乡的热爱" }, { id: "b", text: "白桦树的种植方法", errorTag: "off_topic" }, { id: "c", text: "对冬天的厌恶", errorTag: "off_topic" }, { id: "d", text: "白桦木材的用途", errorTag: "off_topic" } ],
    correct: "a", solution: ["《白桦》借洁白挺拔的白桦，寄托诗人对高洁坚强品格的赞美和对故乡、对祖国的热爱（托物言志）。"] }),
  pickChoice({ id: "cn-u3-h-003", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["glyph"], difficulty: 5,
    stem: "下面四组词中全部没有错别字的一组是？",
    options: [ { id: "a", text: "潇洒 · 镀金 · 朦胧 · 流苏" }, { id: "b", text: "潇洒 · 渡金 · 朦胧 · 流苏", errorTag: "glyph_homophone" }, { id: "c", text: "萧洒 · 镀金 · 蒙胧 · 流苏", errorTag: "glyph_homophone" }, { id: "d", text: "潇洒 · 镀金 · 朦胧 · 流梳", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“潇洒”不是“萧洒”；“镀金”不是“渡金”；“朦胧”不是“蒙胧”；“流苏”不是“流梳”。A 全对。"] }),
  pickChoice({ id: "cn-u3-h-004", unit_id: U3, skill_id: "C4B_U3_RHETORIC", ability: ["sentence", "expression"], difficulty: 5,
    stem: "现代诗常常分行、押韵、富有想象。下面对“现代诗特点”理解不正确的一项是？",
    options: [ { id: "a", text: "现代诗必须像古诗一样每句字数相同、严格对仗", errorTag: "fact_wrong" }, { id: "b", text: "现代诗形式自由、分行排列" }, { id: "c", text: "现代诗语言凝练，富有想象和情感" }, { id: "d", text: "现代诗常借景或物抒发感情" } ],
    correct: "a", solution: ["本题选不正确项。现代诗形式自由，不要求字数相同、严格对仗，这正是它与古诗的区别。"] }),
  pickChoice({ id: "cn-u3-h-005", unit_id: U3, skill_id: "C4B_U3_RHETORIC", ability: ["reading", "expression"], difficulty: 5,
    stem: "《繁星（七一）》“月明的园中，藤萝的叶下，母亲的膝上”，三个短语并列，表达了？",
    options: [ { id: "a", text: "对童年和母爱的温馨回忆与眷恋" }, { id: "b", text: "园中景物的位置关系", errorTag: "literal_misread" }, { id: "c", text: "藤萝的生长环境", errorTag: "off_topic" }, { id: "d", text: "母亲的身高", errorTag: "off_topic" } ],
    correct: "a", solution: ["三个画面式短语层层推进，定格在“母亲的膝上”，抒发对童年时光和母爱的温馨回忆与眷恋。"] }),
  pickChoice({ id: "cn-u3-h-006", unit_id: U3, skill_id: "C4B_U3_PINYIN", ability: ["phonics"], difficulty: 5,
    stem: "下面加点字读音全部正确的一项（“朦胧”“流苏”“春潮”“膝盖”）？",
    options: [ { id: "a", text: "朦胧（méng lóng） 流苏（sū） 春潮（cháo） 膝盖（xī）" }, { id: "b", text: "朦胧（méng lǒng） 流苏（sū） 春潮（cháo） 膝盖（xī）", errorTag: "phonics_error" }, { id: "c", text: "朦胧（méng lóng） 流苏（shū） 春潮（cháo） 膝盖（xī）", errorTag: "phonics_error" }, { id: "d", text: "朦胧（méng lóng） 流苏（sū） 春潮（zhāo） 膝盖（qī）", errorTag: "phonics_error" } ],
    correct: "a", solution: ["朦胧 méng lóng、苏 sū、潮 cháo、膝 xī。注意“膝”不读 qī。"] }),

  // ====================================================================
  // 第四单元 · D1 送分基础 (10) + D5 拔高 (6) + D2/D4 平衡 (6)
  // ====================================================================
  pickChoice({ id: "cn-u4-e-001", unit_id: U4, skill_id: "C4B_U4_PINYIN", ability: ["accumulation"], difficulty: 1,
    stem: "《猫》和《母鸡》的作者都是？",
    options: [ { id: "a", text: "老舍" }, { id: "b", text: "丰子恺", errorTag: "author_confusion" }, { id: "c", text: "巴金", errorTag: "author_confusion" }, { id: "d", text: "冰心", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《猫》《母鸡》都是老舍的作品；《白鹅》的作者是丰子恺。"] }),
  pickChoice({ id: "cn-u4-e-002", unit_id: U4, skill_id: "C4B_U4_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“高傲”的“傲”读音是？",
    options: [ { id: "a", text: "ào" }, { id: "b", text: "áo", errorTag: "tone_confusion" }, { id: "c", text: "òu", errorTag: "phonics_error" }, { id: "d", text: "wù", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“傲”读 ào，“高傲”形容自以为了不起。《白鹅》写白鹅的高傲。"] }),
  pickChoice({ id: "cn-u4-e-003", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["glyph"], difficulty: 1,
    stem: "下面字全对的一组是？",
    options: [ { id: "a", text: "贪玩 · 尽职" }, { id: "b", text: "贫玩 · 尽职", errorTag: "glyph_homophone" }, { id: "c", text: "贪玩 · 尽织", errorTag: "glyph_homophone" }, { id: "d", text: "贪顽 · 尽职", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“贪玩”不是“贫玩”；“尽职”指尽到职责。"] }),
  pickChoice({ id: "cn-u4-e-004", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "《猫》中说猫的性格“古怪”，“古怪”这里指？",
    options: [ { id: "a", text: "性情特别、让人捉摸不透" }, { id: "b", text: "丑陋", errorTag: "word_misunderstand" }, { id: "c", text: "古老", errorTag: "word_misunderstand" }, { id: "d", text: "凶恶", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["老舍说猫“古怪”，指它的性格又老实又贪玩、又胆小又勇猛，让人捉摸不透（含喜爱）。"] }),
  pickChoice({ id: "cn-u4-e-005", unit_id: U4, skill_id: "C4B_U4_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“蹭”（猫在你脚边蹭）的读音是？",
    options: [ { id: "a", text: "cèng" }, { id: "b", text: "céng", errorTag: "tone_confusion" }, { id: "c", text: "zèng", errorTag: "phonics_error" }, { id: "d", text: "chèng", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“蹭”读 cèng，指摩擦。猫用身子蹭你的腿表示亲昵。"] }),
  pickChoice({ id: "cn-u4-e-006", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["glyph"], difficulty: 1,
    stem: "看拼音写词语：这只猫尽职尽责，一连几个钟头 níng shén（凝神）地等着老鼠。",
    options: [ { id: "a", text: "凝神" }, { id: "b", text: "疑神", errorTag: "glyph_homophone" }, { id: "c", text: "凝伸", errorTag: "glyph_homophone" }, { id: "d", text: "拧神", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“凝神”指集中精神。“凝”是两点水（冫）旁。"] }),
  pickChoice({ id: "cn-u4-e-007", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“讨厌”的反义词是？",
    options: [ { id: "a", text: "喜欢" }, { id: "b", text: "厌恶", errorTag: "synonym_misuse" }, { id: "c", text: "害怕", errorTag: "word_misunderstand" }, { id: "d", text: "讨论", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“讨厌”指厌恶，反义词是“喜欢”。"] }),
  pickChoice({ id: "cn-u4-e-008", unit_id: U4, skill_id: "C4B_U4_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“侍候”的“侍”读音是？",
    options: [ { id: "a", text: "shì" }, { id: "b", text: "sì", errorTag: "phonics_error" }, { id: "c", text: "shí", errorTag: "tone_confusion" }, { id: "d", text: "chí", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“侍”读 shì，“侍候”指陪伴照料。《白鹅》写主人要小心侍候这位“鹅老爷”。"] }),
  pickChoice({ id: "cn-u4-e-009", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "《白鹅》主要从哪几方面写白鹅的高傲？",
    options: [ { id: "a", text: "叫声、步态、吃相（和姿态）" }, { id: "b", text: "颜色、味道、价钱", errorTag: "off_topic" }, { id: "c", text: "飞行、游泳、唱歌", errorTag: "fact_wrong" }, { id: "d", text: "捉鼠、看家", errorTag: "fact_wrong" } ],
    correct: "a", solution: ["丰子恺从白鹅的姿态、叫声、步态、吃相几方面，写出它的高傲可爱。"] }),
  pickChoice({ id: "cn-u4-e-010", unit_id: U4, skill_id: "C4B_GLYPH_RADICAL", ability: ["glyph"], difficulty: 1,
    stem: "“猫、狗、猪”三个字相同的偏旁是？它们大多表示？",
    options: [ { id: "a", text: "反犬旁（犭）；多与动物有关" }, { id: "b", text: "提手旁；与手有关", errorTag: "radical_confusion" }, { id: "c", text: "三点水；与水有关", errorTag: "radical_confusion" }, { id: "d", text: "草字头；与植物有关", errorTag: "radical_confusion" } ],
    correct: "a", solution: ["“猫、狗、猪”都是反犬旁（犭），这类字大多和兽类动物有关。"] }),

  // 第四单元 · D5 拔高 (6)
  pickChoice({ id: "cn-u4-h-001", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["reading", "expression"], difficulty: 5,
    stem: "《母鸡》开头说“我一向讨厌母鸡”，结尾却说“我不敢再讨厌母鸡了”，这样写的好处是？",
    options: [ { id: "a", text: "前后对比，突出母爱的伟大，使情感变化更打动人" }, { id: "b", text: "作者前后矛盾，写错了", errorTag: "logic_wrong" }, { id: "c", text: "说明母鸡变好看了", errorTag: "off_topic" }, { id: "d", text: "没有作用", errorTag: "off_topic" } ],
    correct: "a", solution: ["由“讨厌”到“不敢讨厌”的转变，是因为看到母鸡负责、慈爱、勇敢、辛苦——前后对比突出了母爱的伟大。"] }),
  pickChoice({ id: "cn-u4-h-002", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["sentence", "expression"], difficulty: 5,
    stem: "老舍《猫》“它要是高兴，能比谁都温柔可亲……可是，它若是不高兴啊，无论谁说多少好话，它也一声不出。”这种写法的妙处是？",
    options: [ { id: "a", text: "用对比写出猫性格的“古怪”，字里行间流露出对猫的喜爱" }, { id: "b", text: "批评猫脾气坏", errorTag: "opposite" }, { id: "c", text: "说明猫听不懂话", errorTag: "off_topic" }, { id: "d", text: "没有感情", errorTag: "off_topic" } ],
    correct: "a", solution: ["用“高兴”与“不高兴”的对比写猫的“古怪”，看似说缺点，实则满含喜爱，是老舍语言的幽默亲切。"] }),
  pickChoice({ id: "cn-u4-h-003", unit_id: U4, skill_id: "C4B_U4_PINYIN", ability: ["phonics"], difficulty: 5,
    stem: "下面加点多音字读音全部正确的一项（“屏息凝视”“屏风”“的确”“目的”）？",
    options: [ { id: "a", text: "屏息（bǐng） 屏风（píng） 的确（dí） 目的（dì）" }, { id: "b", text: "屏息（píng） 屏风（bǐng） 的确（dí） 目的（dì）", errorTag: "polyphone_confusion" }, { id: "c", text: "屏息（bǐng） 屏风（píng） 的确（de） 目的（dí）", errorTag: "polyphone_confusion" }, { id: "d", text: "屏息（bǐng） 屏风（píng） 的确（dì） 目的（dí）", errorTag: "polyphone_confusion" } ],
    correct: "a", solution: ["屏：bǐng（屏息、屏气）/píng（屏风、屏障）；的：dí（的确）/dì（目的）/de（好的）。"] }),
  pickChoice({ id: "cn-u4-h-004", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["glyph"], difficulty: 5,
    stem: "下面四组词中全部没有错别字的一组是？",
    options: [ { id: "a", text: "尽职 · 凝视 · 譬如 · 侍候" }, { id: "b", text: "尽职 · 疑视 · 譬如 · 侍候", errorTag: "glyph_homophone" }, { id: "c", text: "尽织 · 凝视 · 璧如 · 侍候", errorTag: "glyph_homophone" }, { id: "d", text: "尽职 · 凝视 · 譬如 · 待候", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“凝视”不是“疑视”；“譬如”不是“璧如”；“侍候”不是“待候”。A 全对。"] }),
  pickChoice({ id: "cn-u4-h-005", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["reading"], difficulty: 5,
    stem: "三篇课文（《猫》《母鸡》《白鹅》）在表达对动物的感情上，共同点是？",
    options: [ { id: "a", text: "都用看似“嫌弃”、实则喜爱的笔调，写出对动物的喜爱之情" }, { id: "b", text: "都表达了对动物的厌恶", errorTag: "opposite" }, { id: "c", text: "都在介绍动物的科学知识", errorTag: "off_topic" }, { id: "d", text: "都很害怕这些动物", errorTag: "off_topic" } ],
    correct: "a", solution: ["三篇都用幽默、亲昵的笔调，看似写“古怪、高傲、讨厌”，实则字里行间充满对动物的喜爱。"] }),
  pickChoice({ id: "cn-u4-h-006", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["sentence"], difficulty: 5,
    stem: "《白鹅》“鹅的步态，更是傲慢了。大体上与鸭相似，但鸭的步调急速，有局促不安之相；鹅的步调从容……”这里把鹅和鸭对比，作用是？",
    options: [ { id: "a", text: "用鸭的“急速局促”反衬鹅的“从容傲慢”，突出鹅的特点" }, { id: "b", text: "说明鸭比鹅好", errorTag: "opposite" }, { id: "c", text: "介绍鸭的习性", errorTag: "off_topic" }, { id: "d", text: "凑字数", errorTag: "off_topic" } ],
    correct: "a", solution: ["拿鸭子作对比（反衬），用鸭的急促局促衬托出鹅步态的从容、傲慢，更突出白鹅的特点。"] }),

  // 第四单元 · D2/D4 平衡 (6)
  pickChoice({ id: "cn-u4-b-001", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "“屏息凝视”形容的是？",
    options: [ { id: "a", text: "抑制呼吸、聚精会神地看" }, { id: "b", text: "大声呼喊", errorTag: "antonym_misuse" }, { id: "c", text: "闭着眼睛", errorTag: "word_misunderstand" }, { id: "d", text: "东张西望", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["“屏息凝视”指屏住呼吸、集中注意力地看。《猫》写猫等老鼠时屏息凝视。"] }),
  pickChoice({ id: "cn-u4-b-002", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "下面词语搭配恰当的一组是？",
    options: [ { id: "a", text: "尽职的猫 · 高傲的鹅 · 慈爱的母鸡" }, { id: "b", text: "尽职的鹅 · 高傲的母鸡 · 慈爱的猫", errorTag: "collocation_error" }, { id: "c", text: "尽职的母鸡 · 高傲的猫 · 慈爱的鹅", errorTag: "collocation_error" }, { id: "d", text: "高傲的猫 · 尽职的母鸡 · 慈爱的鹅", errorTag: "collocation_error" } ],
    correct: "a", solution: ["《猫》写猫尽职，《白鹅》写鹅高傲，《母鸡》写母鸡的慈爱。A 搭配最贴合课文。"] }),
  pickChoice({ id: "cn-u4-b-003", unit_id: U4, skill_id: "C4B_U4_PINYIN", ability: ["glyph"], difficulty: 2,
    stem: "看拼音写词语：母鸡负责、慈爱、勇敢、辛苦，是一位 wěi dà（伟大）的母亲。",
    options: [ { id: "a", text: "伟大" }, { id: "b", text: "纬大", errorTag: "glyph_homophone" }, { id: "c", text: "伟达", errorTag: "glyph_homophone" }, { id: "d", text: "维大", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“伟大”指品格崇高、令人敬佩。“伟”单人旁。"] }),
  pickChoice({ id: "cn-u4-b-004", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["sentence"], difficulty: 4,
    stem: "“它若是不高兴啊，无论谁说多少好话，它也一声不出。”句中加点的“无论……也……”说明？",
    options: [ { id: "a", text: "条件关系：不管怎么劝，结果都一样（猫都不出声）" }, { id: "b", text: "转折关系", errorTag: "relation_wrong" }, { id: "c", text: "因果关系", errorTag: "relation_wrong" }, { id: "d", text: "并列关系", errorTag: "relation_wrong" } ],
    correct: "a", solution: ["“无论……也……”是表条件的关联词，说明在任何条件下结果都不变，写出猫“古怪”的脾气。"] }),
  pickChoice({ id: "cn-u4-b-005", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["reading"], difficulty: 4,
    stem: "《母鸡》中作者列举母鸡“警戒、掩护、喂食、彻夜啼叫”等表现，目的是？",
    options: [ { id: "a", text: "用具体事例说明母鸡负责、慈爱、勇敢、辛苦，赞美母爱" }, { id: "b", text: "说明母鸡很吵", errorTag: "off_topic" }, { id: "c", text: "教人怎么养鸡", errorTag: "off_topic" }, { id: "d", text: "说明母鸡很凶", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["这些具体事例从不同角度表现母鸡作为母亲的负责、慈爱、勇敢、辛苦，从而赞美伟大的母爱。"] }),
  pickChoice({ id: "cn-u4-b-006", unit_id: U4, skill_id: "C4B_U4_VOCAB", ability: ["vocabulary"], difficulty: 4,
    stem: "选词填空：这只猫尽职尽责，捉老鼠时（  ）地等着，一连就是几个钟头。（屏息凝视 / 三心二意）",
    options: [ { id: "a", text: "屏息凝视" }, { id: "b", text: "三心二意", errorTag: "antonym_misuse" }, { id: "c", text: "心不在焉", errorTag: "antonym_misuse" }, { id: "d", text: "东张西望", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["捉老鼠要专注，用“屏息凝视”。其余三个都表示分心、不专注，与“尽职”矛盾。"] }),

  // ====================================================================
  // 第五单元 · D1 送分 (10)
  // ====================================================================
  pickChoice({ id: "cn-u5-e-001", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["accumulation"], difficulty: 1,
    stem: "《海上日出》的作者是？",
    options: [ { id: "a", text: "巴金" }, { id: "b", text: "叶圣陶", errorTag: "author_confusion" }, { id: "c", text: "老舍", errorTag: "author_confusion" }, { id: "d", text: "袁鹰", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《海上日出》作者是巴金；《记金华的双龙洞》作者是叶圣陶。"] }),
  pickChoice({ id: "cn-u5-e-002", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“范围”的“范”读音是？",
    options: [ { id: "a", text: "fàn" }, { id: "b", text: "fǎn", errorTag: "tone_confusion" }, { id: "c", text: "fáng", errorTag: "phonics_error" }, { id: "d", text: "fān", errorTag: "tone_confusion" } ],
    correct: "a", solution: ["“范”读 fàn，“范围”指一定的界限。"] }),
  pickChoice({ id: "cn-u5-e-003", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "下面字全对的一组是？",
    options: [ { id: "a", text: "努力 · 紫色" }, { id: "b", text: "怒力 · 紫色", errorTag: "glyph_homophone" }, { id: "c", text: "努力 · 紫包", errorTag: "glyph_homophone" }, { id: "d", text: "努历 · 紫色", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“努力”不是“怒力”；“紫色”指红蓝合成的颜色。"] }),
  pickChoice({ id: "cn-u5-e-004", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“奇观”的意思是？",
    options: [ { id: "a", text: "雄伟美丽而少见的景象" }, { id: "b", text: "奇怪的样子", errorTag: "word_misunderstand" }, { id: "c", text: "看一看", errorTag: "word_misunderstand" }, { id: "d", text: "奇数", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“奇观”指雄伟、美丽而又罕见的景象。《海上日出》说海上日出是“伟大的奇观”。"] }),
  pickChoice({ id: "cn-u5-e-005", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“浙江”的“浙”读音是？",
    options: [ { id: "a", text: "zhè" }, { id: "b", text: "zhé", errorTag: "tone_confusion" }, { id: "c", text: "zě", errorTag: "phonics_error" }, { id: "d", text: "shì", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“浙”读 zhè，浙江省。金华在浙江。"] }),
  pickChoice({ id: "cn-u5-e-006", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "《记金华的双龙洞》游览的第一站是？",
    options: [ { id: "a", text: "路上" }, { id: "b", text: "内洞", errorTag: "order_wrong" }, { id: "c", text: "孔隙", errorTag: "order_wrong" }, { id: "d", text: "出洞", errorTag: "order_wrong" } ],
    correct: "a", solution: ["游览顺序：路上→洞口→外洞→孔隙→内洞→出洞，第一站是“路上”。"] }),
  pickChoice({ id: "cn-u5-e-007", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "看拼音写词语：颐和园的长廊一眼望不到 tóu（头）。",
    options: [ { id: "a", text: "头" }, { id: "b", text: "投", errorTag: "glyph_homophone" }, { id: "c", text: "偷", errorTag: "glyph_homophone" }, { id: "d", text: "透", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“一眼望不到头”指长廊很长。这里是“头”（尽头），不是“投/偷/透”。"] }),
  pickChoice({ id: "cn-u5-e-008", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“蜿蜒”常用来形容？",
    options: [ { id: "a", text: "弯弯曲曲地延伸" }, { id: "b", text: "笔直", errorTag: "antonym_misuse" }, { id: "c", text: "很高", errorTag: "word_misunderstand" }, { id: "d", text: "很亮", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“蜿蜒”形容像蛇爬行那样弯弯曲曲地延伸，如山路蜿蜒、双龙蜿蜒在洞顶。"] }),
  pickChoice({ id: "cn-u5-e-009", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["accumulation"], difficulty: 1,
    stem: "《七月的天山》写的是哪个地方的景色？",
    options: [ { id: "a", text: "新疆天山" }, { id: "b", text: "浙江金华", errorTag: "fact_wrong" }, { id: "c", text: "北京颐和园", errorTag: "fact_wrong" }, { id: "d", text: "海上", errorTag: "fact_wrong" } ],
    correct: "a", solution: ["《七月的天山》写的是新疆天山七月的美景，作者碧野。"] }),
  pickChoice({ id: "cn-u5-e-010", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“五彩斑斓”的意思是？",
    options: [ { id: "a", text: "色彩繁多、灿烂耀眼" }, { id: "b", text: "只有五种颜色", errorTag: "literal_misread" }, { id: "c", text: "黑白分明", errorTag: "antonym_misuse" }, { id: "d", text: "颜色很暗", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["“五彩斑斓”形容颜色繁多、错杂灿烂。"] }),

  // 第五单元 · D5 拔高 (6)
  pickChoice({ id: "cn-u5-h-001", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["phonics"], difficulty: 5,
    stem: "下面加点多音字读音全部正确的一项（“负着重荷”“一刹那”“系着绳子”“变换调子”）？",
    options: [ { id: "a", text: "重荷（hè） 一刹那（chà） 系着（jì） 调子（diào）" }, { id: "b", text: "重荷（hé） 一刹那（shā） 系着（xì） 调子（tiáo）", errorTag: "polyphone_confusion" }, { id: "c", text: "重荷（hè） 一刹那（shā） 系着（jì） 调子（diào）", errorTag: "polyphone_confusion" }, { id: "d", text: "重荷（hè） 一刹那（chà） 系着（xì） 调子（tiáo）", errorTag: "polyphone_confusion" } ],
    correct: "a", solution: ["重荷 hè、一刹那 chà、系着绳子 jì、变换调子 diào，四个多音字都取这一义项的读音。"] }),
  pickChoice({ id: "cn-u5-h-002", unit_id: U5, skill_id: "C4B_U5_RHETORIC", ability: ["sentence", "reading"], difficulty: 5,
    stem: "《记金华的双龙洞》写过孔隙时“我又感觉要是把头稍微抬起一点儿，准会撞破额角，擦伤鼻子”。这样写的好处是？",
    options: [ { id: "a", text: "用自己的真实感受，从侧面突出孔隙的狭小、低矮" }, { id: "b", text: "说明作者胆子小", errorTag: "off_topic" }, { id: "c", text: "说明小船很危险", errorTag: "narrow_focus" }, { id: "d", text: "没有作用", errorTag: "off_topic" } ],
    correct: "a", solution: ["作者不直接说孔隙多小，而写自己仰卧船中、稍抬头就会撞伤的感受，从侧面具体地突出孔隙的狭小低矮。"] }),
  pickChoice({ id: "cn-u5-h-003", unit_id: U5, skill_id: "C4B_U5_RHETORIC", ability: ["sentence"], difficulty: 5,
    stem: "下面句子修辞判断完全正确的一项是？",
    options: [ { id: "a", text: "“昆明湖静得像一面镜子”是比喻；“太阳负着重荷努力上升”是拟人" }, { id: "b", text: "两句都是比喻", errorTag: "wrong_rhetoric" }, { id: "c", text: "两句都是拟人", errorTag: "wrong_rhetoric" }, { id: "d", text: "两句都是夸张", errorTag: "wrong_rhetoric" } ],
    correct: "a", solution: ["“静得像镜子”有本体喻体，是比喻；“太阳负着重荷努力上升”把太阳当人写，是拟人。"] }),
  pickChoice({ id: "cn-u5-h-004", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["glyph"], difficulty: 5,
    stem: "下面四组词中全部没有错别字的一组是？",
    options: [ { id: "a", text: "蜿蜒 · 突兀 · 镶嵌 · 油桐" }, { id: "b", text: "蜿蜒 · 突屹 · 镶嵌 · 油桐", errorTag: "glyph_homophone" }, { id: "c", text: "婉蜒 · 突兀 · 镶嵌 · 油铜", errorTag: "glyph_homophone" }, { id: "d", text: "蜿蜒 · 突兀 · 镶钳 · 油桐", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“突兀”不是“突屹/突屹”；“蜿蜒”不是“婉蜒”；“镶嵌”不是“镶钳”；“油桐”不是“油铜”。A 全对。"] }),
  pickChoice({ id: "cn-u5-h-005", unit_id: U5, skill_id: "C4B_U5_ORDER", ability: ["reading", "expression"], difficulty: 5,
    stem: "三篇游记（《双龙洞》《颐和园》《七月的天山》）在写法上的共同点是？",
    options: [ { id: "a", text: "都按一定的游览（移步换景）顺序写景，并用过渡句使转换自然" }, { id: "b", text: "都按时间从早到晚写", errorTag: "method_wrong" }, { id: "c", text: "都只写一处景物", errorTag: "method_wrong" }, { id: "d", text: "都没有顺序", errorTag: "method_wrong" } ],
    correct: "a", solution: ["三篇都按游览顺序、移步换景地写，并用过渡句（如“走完长廊，就来到了万寿山脚下”）使景物转换自然。"] }),
  pickChoice({ id: "cn-u5-h-006", unit_id: U5, skill_id: "C4B_U5_RHETORIC", ability: ["sentence", "expression"], difficulty: 5,
    stem: "仿照《七月的天山》排比句“像锦缎，像霞光，像彩虹”，下面仿写最恰当的一项是？",
    options: [ { id: "a", text: "节日的焰火，像盛开的菊花，像飞舞的流星，像撒落的珍珠。" }, { id: "b", text: "节日的焰火很漂亮，大家都来看。", errorTag: "no_rhetoric" }, { id: "c", text: "焰火是彩色的。", errorTag: "no_rhetoric" }, { id: "d", text: "天上有焰火。", errorTag: "off_topic" } ],
    correct: "a", solution: ["原句是三个“像……”的排比 + 比喻。A 连用三个比喻、结构相同，构成排比，仿写最恰当。"] }),

  // 第五单元 · D2/D4 平衡 (10)
  pickChoice({ id: "cn-u5-b-001", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "“盘曲而上”形容山路？",
    options: [ { id: "a", text: "弯弯曲曲地向上" }, { id: "b", text: "笔直向上", errorTag: "antonym_misuse" }, { id: "c", text: "向下", errorTag: "antonym_misuse" }, { id: "d", text: "很平", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“盘曲而上”指公路弯弯曲曲地盘旋上山。“曲”读 qū。"] }),
  pickChoice({ id: "cn-u5-b-002", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "下面词语搭配恰当的一组是？",
    options: [ { id: "a", text: "明艳的景色 · 高耸的雪峰 · 茂密的森林" }, { id: "b", text: "明艳的雪峰 · 高耸的森林 · 茂密的景色", errorTag: "collocation_error" }, { id: "c", text: "明艳的森林 · 高耸的景色 · 茂密的雪峰", errorTag: "collocation_error" }, { id: "d", text: "高耸的景色 · 明艳的森林 · 茂密的雪峰", errorTag: "collocation_error" } ],
    correct: "a", solution: ["“明艳”修饰景色，“高耸”修饰雪峰，“茂密”修饰森林，均搭配恰当。"] }),
  pickChoice({ id: "cn-u5-b-003", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["glyph"], difficulty: 2,
    stem: "看拼音写词语：山上沙土呈 fěn hóng sè（粉红色）。",
    options: [ { id: "a", text: "粉红色" }, { id: "b", text: "粉虹色", errorTag: "glyph_homophone" }, { id: "c", text: "纷红色", errorTag: "glyph_homophone" }, { id: "d", text: "粉宏色", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“粉红色”是浅红色。注意“粉”米字旁，“红”绞丝旁。"] }),
  pickChoice({ id: "cn-u5-b-004", unit_id: U5, skill_id: "C4B_U5_ORDER", ability: ["reading"], difficulty: 4,
    stem: "《颐和园》中“走完长廊，就来到了万寿山脚下”和“从万寿山下来，就是昆明湖”，这两句的共同作用是？",
    options: [ { id: "a", text: "都是过渡句，使游览地点的转换自然清楚" }, { id: "b", text: "都是总起句", errorTag: "wrong_function" }, { id: "c", text: "都是比喻句", errorTag: "wrong_function" }, { id: "d", text: "都是反问句", errorTag: "wrong_function" } ],
    correct: "a", solution: ["两句都承上启下，把游览地点从长廊→万寿山→昆明湖自然地连接起来，是过渡句。"] }),
  pickChoice({ id: "cn-u5-b-005", unit_id: U5, skill_id: "C4B_U5_RHETORIC", ability: ["sentence"], difficulty: 4,
    stem: "《海上日出》“这不是很伟大的奇观吗？”这句话的表达效果是？",
    options: [ { id: "a", text: "用反问加强语气，强烈地表达对日出奇观的赞美" }, { id: "b", text: "表示疑问，不知道是不是奇观", errorTag: "word_misunderstand" }, { id: "c", text: "表示否定", errorTag: "sentence_meaning_flip" }, { id: "d", text: "没有感情", errorTag: "off_topic" } ],
    correct: "a", solution: ["这是反问句，用问的形式表达肯定，比陈述句“这是很伟大的奇观”语气更强烈，突出赞叹之情。"] }),
  pickChoice({ id: "cn-u5-b-006", unit_id: U5, skill_id: "C4B_U5_READING", ability: ["reading"], difficulty: 4,
    stem: "《七月的天山》描写顺序的标志语句，下面一组排列正确的是？",
    options: [ { id: "a", text: "进入天山 → 再往里走 → 走进天山深处" }, { id: "b", text: "走进天山深处 → 进入天山 → 再往里走", errorTag: "order_wrong" }, { id: "c", text: "再往里走 → 走进天山深处 → 进入天山", errorTag: "order_wrong" }, { id: "d", text: "进入天山 → 走进天山深处 → 再往里走", errorTag: "order_wrong" } ],
    correct: "a", solution: ["课文用“进入天山”“再往里走”“走进天山深处”由外到里、移步换景地写天山美景。"] }),
  pickChoice({ id: "cn-u5-b-007", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["vocabulary"], difficulty: 4,
    stem: "选词填空：太阳像负着重荷似的，一步一步，慢慢地（  ）上升。（努力 / 用力）",
    options: [ { id: "a", text: "努力" }, { id: "b", text: "用力", errorTag: "synonym_misuse" }, { id: "c", text: "使劲", errorTag: "synonym_misuse" }, { id: "d", text: "拼命", errorTag: "synonym_misuse" } ],
    correct: "a", solution: ["课文原句是“慢慢地努力上升”。“努力”含坚持、不放弃之意，与“一步一步”“慢慢地”更协调。"] }),
  pickChoice({ id: "cn-u5-b-008", unit_id: U5, skill_id: "C4B_U5_PINYIN", ability: ["phonics"], difficulty: 2,
    stem: "“石笋”的“笋”读音是？",
    options: [ { id: "a", text: "sǔn" }, { id: "b", text: "shǔn", errorTag: "phonics_error" }, { id: "c", text: "yǔn", errorTag: "phonics_error" }, { id: "d", text: "xún", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“笋”读 sǔn，竹字头。洞内的石钟乳和石笋形状变化多端。"] }),
  pickChoice({ id: "cn-u5-b-009", unit_id: U5, skill_id: "C4B_U5_VOCAB", ability: ["vocabulary"], difficulty: 4,
    stem: "“即使不比作什么，也很值得观赏”中“即使……也……”表示？",
    options: [ { id: "a", text: "假设让步关系（哪怕不比喻，也值得看）" }, { id: "b", text: "因果关系", errorTag: "relation_wrong" }, { id: "c", text: "并列关系", errorTag: "relation_wrong" }, { id: "d", text: "转折关系", errorTag: "relation_wrong" } ],
    correct: "a", solution: ["“即使……也……”表示假设让步：退一步说，哪怕不去想象成什么，石钟乳石笋也很值得观赏。"] }),
  pickChoice({ id: "cn-u5-b-010", unit_id: U5, skill_id: "C4B_U5_READING", ability: ["reading"], difficulty: 4,
    stem: "《颐和园》开头“北京的颐和园是个美丽的大公园”和结尾“颐和园到处有美丽的景色，说也说不尽”，这种写法是？",
    options: [ { id: "a", text: "首尾呼应（总—分—总），表达对颐和园的赞美" }, { id: "b", text: "前后矛盾", errorTag: "logic_wrong" }, { id: "c", text: "重复啰嗦", errorTag: "logic_wrong" }, { id: "d", text: "没有关系", errorTag: "off_topic" } ],
    correct: "a", solution: ["开头总说颐和园美丽，中间分写各处景点，结尾再总说，首尾呼应，结构清楚，突出赞美之情。"] }),

  // ====================================================================
  // 第六单元 · D1 送分 (10)
  // ====================================================================
  pickChoice({ id: "cn-u6-e-001", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation"], difficulty: 1,
    stem: "《囊萤夜读》中“萤”指的是？",
    options: [ { id: "a", text: "萤火虫" }, { id: "b", text: "蝴蝶", errorTag: "word_misunderstand" }, { id: "c", text: "蜡烛", errorTag: "word_misunderstand" }, { id: "d", text: "星星", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“萤”指萤火虫。车胤用口袋装萤火虫照明读书，所以叫“囊萤夜读”。"] }),
  pickChoice({ id: "cn-u6-e-002", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation"], difficulty: 1,
    stem: "《铁杵成针》的主人公是？",
    options: [ { id: "a", text: "李白（李太白）" }, { id: "b", text: "车胤", errorTag: "story_confusion" }, { id: "c", text: "匡衡", errorTag: "story_confusion" }, { id: "d", text: "黄继光", errorTag: "story_confusion" } ],
    correct: "a", solution: ["《铁杵成针》讲的是李白（李太白）受老媪磨铁杵启发，回去完成学业的故事。"] }),
  pickChoice({ id: "cn-u6-e-003", unit_id: U6, skill_id: "C4B_U6_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "《小英雄雨来》中，雨来是哪个村的孩子？",
    options: [ { id: "a", text: "芦花村" }, { id: "b", text: "油麻地", errorTag: "fact_wrong" }, { id: "c", text: "草房子村", errorTag: "fact_wrong" }, { id: "d", text: "双龙村", errorTag: "fact_wrong" } ],
    correct: "a", solution: ["雨来是还乡河边芦花村的孩子，因芦花开时像盖了白雪而得名。"] }),
  pickChoice({ id: "cn-u6-e-004", unit_id: U6, skill_id: "C4B_U6_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "下面字全对的一组是？",
    options: [ { id: "a", text: "枪栓 · 慌忙" }, { id: "b", text: "枪拴 · 慌忙", errorTag: "glyph_homophone" }, { id: "c", text: "枪栓 · 谎忙", errorTag: "glyph_homophone" }, { id: "d", text: "枪栓 · 荒忙", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“枪栓”是木字旁；“慌忙”是竖心旁（心里慌）。"] }),
  pickChoice({ id: "cn-u6-e-005", unit_id: U6, skill_id: "C4B_U6_SUMMARY", ability: ["reading"], difficulty: 1,
    stem: "为什么称雨来是“小英雄”？最主要的是？",
    options: [ { id: "a", text: "他机智勇敢，掩护李大叔、不向敌人屈服" }, { id: "b", text: "他游泳本领高", errorTag: "narrow_focus" }, { id: "c", text: "他会念书", errorTag: "narrow_focus" }, { id: "d", text: "他跑得快", errorTag: "narrow_focus" } ],
    correct: "a", solution: ["雨来掩护交通员李大叔，面对敌人毒打、利诱坚决不说，机智脱险，所以是小英雄。"] }),
  pickChoice({ id: "cn-u6-e-006", unit_id: U6, skill_id: "C4B_U6_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“倔强”的意思是？",
    options: [ { id: "a", text: "性格刚强、不肯屈服" }, { id: "b", text: "胆小怕事", errorTag: "antonym_misuse" }, { id: "c", text: "懒惰", errorTag: "word_misunderstand" }, { id: "d", text: "聪明", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“倔强”（jué jiàng）指性格刚强，不肯轻易屈服、低头。"] }),
  pickChoice({ id: "cn-u6-e-007", unit_id: U6, skill_id: "C4B_U6_PINYIN", ability: ["accumulation"], difficulty: 1,
    stem: "《芦花鞋》选自哪部作品？作者是谁？",
    options: [ { id: "a", text: "《青铜葵花》，曹文轩" }, { id: "b", text: "《城南旧事》，林海音", errorTag: "author_confusion" }, { id: "c", text: "《草房子》，张天翼", errorTag: "author_confusion" }, { id: "d", text: "《呼兰河传》，萧红", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《芦花鞋》选自曹文轩的小说《青铜葵花》。"] }),
  pickChoice({ id: "cn-u6-e-008", unit_id: U6, skill_id: "C4B_U6_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "看拼音写词语：芦花鞋很厚实，像暖和和的 niǎo wō（鸟窝）。",
    options: [ { id: "a", text: "鸟窝" }, { id: "b", text: "鸟卧", errorTag: "glyph_homophone" }, { id: "c", text: "乌窝", errorTag: "glyph_homophone" }, { id: "d", text: "鸟涡", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“鸟窝”指鸟住的窝。注意“鸟”不要写成“乌”，“窝”是穴宝盖。"] }),
  pickChoice({ id: "cn-u6-e-009", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation"], difficulty: 1,
    stem: "“恭勤不倦”中“倦”的意思是？",
    options: [ { id: "a", text: "疲倦" }, { id: "b", text: "美丽", errorTag: "word_misunderstand" }, { id: "c", text: "卷起", errorTag: "word_misunderstand" }, { id: "d", text: "回来", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“倦”指疲倦。“恭勤不倦”指肃敬勤勉、不知疲倦。"] }),
  pickChoice({ id: "cn-u6-e-010", unit_id: U6, skill_id: "C4B_U6_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“嘱咐”的意思最接近？",
    options: [ { id: "a", text: "叮嘱、吩咐" }, { id: "b", text: "嘱托买东西", errorTag: "word_misunderstand" }, { id: "c", text: "嘱咐写成“瞩咐”才对", errorTag: "glyph_homophone" }, { id: "d", text: "命令", errorTag: "synonym_misuse" } ],
    correct: "a", solution: ["“嘱咐”指叮嘱、吩咐，两字都是口字旁。"] }),

  // 第六单元 · D5 拔高 (6)
  pickChoice({ id: "cn-u6-h-001", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation", "reading"], difficulty: 5,
    stem: "翻译：“家贫不常得油，夏月则练囊盛数十萤火以照书。”下面最准确的一项是？",
    options: [ { id: "a", text: "家里穷不能常买到灯油，夏天就用白绢口袋装几十只萤火虫来照着读书" }, { id: "b", text: "家里穷得不到油，夏天的月亮装在口袋里照书", errorTag: "sentence_meaning_flip" }, { id: "c", text: "家里没有油吃，夏天用口袋装萤火虫玩", errorTag: "word_misunderstand" }, { id: "d", text: "家里很富，夏天用油灯读书", errorTag: "opposite" } ],
    correct: "a", solution: ["“家贫不常得油”家穷不常得灯油；“夏月”夏夜；“练囊”白绢口袋；“盛数十萤火”装几十只萤火虫；“以照书”用来照书。"] }),
  pickChoice({ id: "cn-u6-h-002", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation", "reading"], difficulty: 5,
    stem: "下面对《囊萤夜读》《铁杵成针》理解不正确的一项是？",
    options: [ { id: "a", text: "两文都告诉我们，遇到困难应该绕开、另找捷径", errorTag: "opposite" }, { id: "b", text: "《囊萤夜读》赞扬车胤勤奋好学" }, { id: "c", text: "《铁杵成针》说明做事要有恒心" }, { id: "d", text: "两文都启发我们要勤奋、坚持" } ],
    correct: "a", solution: ["本题选不正确项。两文都强调勤奋、坚持、克服困难，而不是“绕开困难找捷径”，A 说反了。"] }),
  pickChoice({ id: "cn-u6-h-003", unit_id: U6, skill_id: "C4B_U6_SUMMARY", ability: ["reading", "expression"], difficulty: 5,
    stem: "《小英雄雨来》多处描写还乡河的景色（如开头的芦花、结尾的浮云）。综合分析其作用，最全面的是？",
    options: [ { id: "a", text: "交代环境、推动情节，并用景物烘托人物和情感（如结尾的红霞烘托乡亲的悲喜）" }, { id: "b", text: "只是单纯写景，与故事无关", errorTag: "off_topic" }, { id: "c", text: "为了介绍还乡河风景区", errorTag: "off_topic" }, { id: "d", text: "凑字数", errorTag: "off_topic" } ],
    correct: "a", solution: ["开头芦花美景交代环境、引出人物；中间、结尾的景色（如浮云像红绸子）烘托情节和乡亲们悲喜交加的心情，环境描写为人物和主题服务。"] }),
  pickChoice({ id: "cn-u6-h-004", unit_id: U6, skill_id: "C4B_U6_SUMMARY", ability: ["reading", "expression"], difficulty: 5,
    stem: "《芦花鞋》结尾，青铜把自己脚上唯一的芦花鞋也卖了、赤脚踏雪回家。作者这样安排结尾的用意是？",
    options: [ { id: "a", text: "以“赤脚踏雪”的细节，把青铜的善良、懂事、为他人着想推向高潮，感人至深" }, { id: "b", text: "说明青铜很穷买不起鞋", errorTag: "narrow_focus" }, { id: "c", text: "说明青铜很粗心", errorTag: "opposite" }, { id: "d", text: "为了凑字数", errorTag: "off_topic" } ],
    correct: "a", solution: ["青铜宁愿自己赤脚受冻也成全买鞋人，结尾“赤脚踏雪”这一细节把他的善良、懂事、为他人着想推向高潮，格外动人。"] }),
  pickChoice({ id: "cn-u6-h-005", unit_id: U6, skill_id: "C4B_U6_PINYIN", ability: ["phonics"], difficulty: 5,
    stem: "下面加点多音字读音全部正确的一项（“扫荡”“扫帚”“把书塞进”“边塞”）？",
    options: [ { id: "a", text: "扫荡（sǎo） 扫帚（sào） 塞进（sāi） 边塞（sài）" }, { id: "b", text: "扫荡（sào） 扫帚（sǎo） 塞进（sài） 边塞（sāi）", errorTag: "polyphone_confusion" }, { id: "c", text: "扫荡（sǎo） 扫帚（sǎo） 塞进（sāi） 边塞（sāi）", errorTag: "polyphone_confusion" }, { id: "d", text: "扫荡（sǎo） 扫帚（sào） 塞进（sè） 边塞（sài）", errorTag: "polyphone_confusion" } ],
    correct: "a", solution: ["扫：sǎo（扫荡、打扫）/sào（扫帚）；塞：sāi（塞进）/sài（边塞）/sè（阻塞）。"] }),
  pickChoice({ id: "cn-u6-h-006", unit_id: U6, skill_id: "C4B_U6_SUMMARY", ability: ["reading"], difficulty: 5,
    stem: "把握长文章主要内容，最恰当的做法是？",
    options: [ { id: "a", text: "先借助序号、小标题或空行把课文分成几部分，概括每部分意思，再连起来" }, { id: "b", text: "只读第一段就下结论", errorTag: "method_wrong" }, { id: "c", text: "把全文一字不漏地背下来", errorTag: "method_wrong" }, { id: "d", text: "只看插图猜内容", errorTag: "method_wrong" } ],
    correct: "a", solution: ["长文章常分部分写，先分部分、概括各部分主要意思，再把它们连起来，就能准确把握全文主要内容。"] }),

  // 第六单元 · D2/D4 平衡 (4)
  pickChoice({ id: "cn-u6-b-001", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation"], difficulty: 2,
    stem: "“以夜继日”的意思是？",
    options: [ { id: "a", text: "夜晚接着白天（不停地学习）" }, { id: "b", text: "白天接着夜晚睡觉", errorTag: "word_misunderstand" }, { id: "c", text: "夜里比白天长", errorTag: "word_misunderstand" }, { id: "d", text: "只在夜里读书", errorTag: "narrow_focus" } ],
    correct: "a", solution: ["“以夜继日”即“夜以继日”，夜晚接着白天，形容车胤勤学不辍。"] }),
  pickChoice({ id: "cn-u6-b-002", unit_id: U6, skill_id: "C4B_U6_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "“沮丧”的反义词是？",
    options: [ { id: "a", text: "振奋（高兴）" }, { id: "b", text: "灰心", errorTag: "synonym_misuse" }, { id: "c", text: "失望", errorTag: "synonym_misuse" }, { id: "d", text: "难过", errorTag: "synonym_misuse" } ],
    correct: "a", solution: ["“沮丧”指灰心失望，反义词是“振奋、高兴”。其余三个都是近义词。"] }),
  pickChoice({ id: "cn-u6-b-003", unit_id: U6, skill_id: "C4B_U6_SUMMARY", ability: ["reading"], difficulty: 4,
    stem: "《我们家的男子汉》三个小标题“他对食物的兴趣、他对独立的要求、他面对生活挑战的沉着”，这种结构方式叫？",
    options: [ { id: "a", text: "用小标题分部分，从不同方面写出人物特点" }, { id: "b", text: "按时间顺序写", errorTag: "method_wrong" }, { id: "c", text: "按地点变换写", errorTag: "method_wrong" }, { id: "d", text: "总分总结构", errorTag: "method_wrong" } ],
    correct: "a", solution: ["课文用三个小标题，从食物、独立、面对挑战三个方面分别写孩子的特点，是“用小标题分部分、多方面写人”的方法。"] }),
  pickChoice({ id: "cn-u6-b-004", unit_id: U6, skill_id: "C4B_U6_SUMMARY", ability: ["sentence"], difficulty: 4,
    stem: "“雨来浑身光溜溜的像条小泥鳅，怎么也抓不住。”和“一只胖胖的小手……像一条倔强的活鱼一样挣扎着。”这两句的共同点是？",
    options: [ { id: "a", text: "都用比喻，把人比作鱼，写出灵活、不肯就范的样子" }, { id: "b", text: "都是拟人", errorTag: "wrong_rhetoric" }, { id: "c", text: "都是夸张", errorTag: "wrong_rhetoric" }, { id: "d", text: "都没有修辞", errorTag: "wrong_rhetoric" } ],
    correct: "a", solution: ["两句都用比喻：把雨来比作小泥鳅、把小手比作倔强的活鱼，生动写出人物灵活、不肯就范的样子。"] }),

  // ====================================================================
  // 第七单元 · D1 送分 (10)
  // ====================================================================
  pickChoice({ id: "cn-u7-e-001", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation"], difficulty: 1,
    stem: "《芙蓉楼送辛渐》的作者是？",
    options: [ { id: "a", text: "王昌龄" }, { id: "b", text: "卢纶", errorTag: "author_confusion" }, { id: "c", text: "王冕", errorTag: "author_confusion" }, { id: "d", text: "杜甫", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《芙蓉楼送辛渐》是唐代王昌龄的送别诗。"] }),
  pickChoice({ id: "cn-u7-e-002", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation"], difficulty: 1,
    stem: "默写填空：洛阳亲友如相问，（  ）。",
    options: [ { id: "a", text: "一片冰心在玉壶" }, { id: "b", text: "大雪满弓刀", errorTag: "poem_mismatch" }, { id: "c", text: "只留清气满乾坤", errorTag: "poem_mismatch" }, { id: "d", text: "平明送客楚山孤", errorTag: "poem_mismatch" } ],
    correct: "a", solution: ["出自《芙蓉楼送辛渐》：“洛阳亲友如相问，一片冰心在玉壶。”"] }),
  pickChoice({ id: "cn-u7-e-003", unit_id: U7, skill_id: "C4B_U7_PINYIN", ability: ["accumulation"], difficulty: 1,
    stem: "《黄继光》故事发生在哪场战役中？",
    options: [ { id: "a", text: "上甘岭战役（抗美援朝）" }, { id: "b", text: "百团大战", errorTag: "fact_wrong" }, { id: "c", text: "辽沈战役", errorTag: "fact_wrong" }, { id: "d", text: "淮海战役", errorTag: "fact_wrong" } ],
    correct: "a", solution: ["黄继光是在 1952 年抗美援朝的上甘岭战役中，用胸膛堵住敌人枪口而牺牲的。"] }),
  pickChoice({ id: "cn-u7-e-004", unit_id: U7, skill_id: "C4B_U7_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“爆炸”的“爆”读音是？",
    options: [ { id: "a", text: "bào" }, { id: "b", text: "pù", errorTag: "phonics_error" }, { id: "c", text: "bāo", errorTag: "tone_confusion" }, { id: "d", text: "pào", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“爆”读 bào，火字旁，“爆炸”指猛然破裂。"] }),
  pickChoice({ id: "cn-u7-e-005", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation"], difficulty: 1,
    stem: "《墨梅》的作者王冕是哪个朝代的？",
    options: [ { id: "a", text: "元代" }, { id: "b", text: "唐代", errorTag: "dynasty_confusion" }, { id: "c", text: "宋代", errorTag: "dynasty_confusion" }, { id: "d", text: "清代", errorTag: "dynasty_confusion" } ],
    correct: "a", solution: ["《墨梅》是元代诗人、画家王冕的题画诗。"] }),
  pickChoice({ id: "cn-u7-e-006", unit_id: U7, skill_id: "C4B_U7_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "下面字全对的一组是？",
    options: [ { id: "a", text: "维持 · 秩序" }, { id: "b", text: "唯持 · 秩序", errorTag: "glyph_homophone" }, { id: "c", text: "维持 · 秩绪", errorTag: "glyph_homophone" }, { id: "d", text: "维持 · 帙序", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“维持”是绞丝旁；“秩序”指有条理的次序。"] }),
  pickChoice({ id: "cn-u7-e-007", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading"], difficulty: 1,
    stem: "《“诺曼底号”遇难记》的主人公是？",
    options: [ { id: "a", text: "哈尔威船长" }, { id: "b", text: "黄继光", errorTag: "story_confusion" }, { id: "c", text: "挑山工", errorTag: "story_confusion" }, { id: "d", text: "李太白", errorTag: "story_confusion" } ],
    correct: "a", solution: ["《“诺曼底号”遇难记》的主人公是忠于职守、舍己救人的哈尔威船长，作者雨果。"] }),
  pickChoice({ id: "cn-u7-e-008", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading"], difficulty: 1,
    stem: "《挑山工》中挑山工登山为什么走“折尺形”路线？",
    options: [ { id: "a", text: "为了让挑的东西不碰台阶，还能省力气" }, { id: "b", text: "因为迷路了", errorTag: "off_topic" }, { id: "c", text: "因为喜欢绕路", errorTag: "off_topic" }, { id: "d", text: "因为折尺形更短", errorTag: "opposite" } ],
    correct: "a", solution: ["折尺形路线能使挂在扁担前头的东西不碰台阶，还能省力气；直上走膝盖受不住。"] }),
  pickChoice({ id: "cn-u7-e-009", unit_id: U7, skill_id: "C4B_U7_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "看拼音写词语：救援工作进行得 jǐng rán yǒu xù（井然有序）。",
    options: [ { id: "a", text: "井然有序" }, { id: "b", text: "井然有绪", errorTag: "glyph_homophone" }, { id: "c", text: "景然有序", errorTag: "glyph_homophone" }, { id: "d", text: "井燃有序", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“井然有序”形容整齐而有条理。“序”是次序，不是“绪”。"] }),
  pickChoice({ id: "cn-u7-e-010", unit_id: U7, skill_id: "C4B_U7_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“临危不惧”中“惧”的意思是？",
    options: [ { id: "a", text: "害怕" }, { id: "b", text: "聚集", errorTag: "word_misunderstand" }, { id: "c", text: "工具", errorTag: "word_misunderstand" }, { id: "d", text: "巨大", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“惧”指害怕。“临危不惧”指面临危险毫不畏惧。"] }),

  // 第七单元 · D5 拔高 (6)
  pickChoice({ id: "cn-u7-h-001", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation", "reading"], difficulty: 5,
    stem: "下面对三首古诗的理解，不正确的一项是？",
    options: [ { id: "a", text: "《塞下曲》借“大雪满弓刀”表达将士因怕冷而退缩", errorTag: "opposite" }, { id: "b", text: "《芙蓉楼送辛渐》借“冰心玉壶”表明高洁品格" }, { id: "c", text: "《墨梅》借梅花“清气”托物言志" }, { id: "d", text: "《塞下曲》写雪夜追敌，表现将士英勇" } ],
    correct: "a", solution: ["本题选不正确项。“大雪满弓刀”恰恰反衬将士不畏严寒、英勇追敌，而非“怕冷退缩”。"] }),
  pickChoice({ id: "cn-u7-h-002", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation", "reading"], difficulty: 5,
    stem: "《墨梅》是“题画诗”。下面对“托物言志”理解最准确的一项是？",
    options: [ { id: "a", text: "借描写墨梅不要人夸、只留清气，寄托诗人不慕虚名、坚守高洁的志向" }, { id: "b", text: "只是单纯描写一幅梅花画", errorTag: "narrow_focus" }, { id: "c", text: "借梅花说明画画技巧", errorTag: "off_topic" }, { id: "d", text: "借梅花写思念家乡", errorTag: "off_topic" } ],
    correct: "a", solution: ["“托物言志”即借描写事物寄托志向。王冕借墨梅“不要人夸”“只留清气”表达自己不慕虚名、清白高洁的志向。"] }),
  pickChoice({ id: "cn-u7-h-003", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading", "expression"], difficulty: 5,
    stem: "《黄继光》大量描写他“爬、站起来、举起右臂、猛扑、用胸膛堵枪口”，这些动作描写的共同作用是？",
    options: [ { id: "a", text: "层层递进地表现黄继光不怕牺牲、英勇顽强的英雄气概" }, { id: "b", text: "说明他动作很慢", errorTag: "off_topic" }, { id: "c", text: "说明战场很乱", errorTag: "narrow_focus" }, { id: "d", text: "没有作用", errorTag: "off_topic" } ],
    correct: "a", solution: ["从“爬”到“站起来”再到“猛扑”“堵枪口”，一系列动作层层推进，集中表现黄继光英勇顽强、舍身报国的英雄气概。"] }),
  pickChoice({ id: "cn-u7-h-004", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading", "expression"], difficulty: 5,
    stem: "《“诺曼底号”遇难记》中“实际上一共有六十一人，但是他把自己给忘了”。这句话的深意是？",
    options: [ { id: "a", text: "船长心里只装着别人、唯独没有自己，突出他舍己救人的崇高" }, { id: "b", text: "船长记性不好，数错了", errorTag: "literal_misread" }, { id: "c", text: "船上人太多数不清", errorTag: "off_topic" }, { id: "d", text: "船长不在乎自己的生命，太冲动", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“把自己给忘了”不是真忘，而是危急关头他一心救别人、唯独不顾自己，突出他舍己救人、忠于职守的崇高品质。"] }),
  pickChoice({ id: "cn-u7-h-005", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading", "expression"], difficulty: 5,
    stem: "本单元几位人物（黄继光、哈尔威船长、挑山工）给我们的共同启示是？",
    options: [ { id: "a", text: "伟大的品格往往体现在平凡或危急的行动中，要从行动看人的精神" }, { id: "b", text: "只有打仗才算英雄", errorTag: "narrow_focus" }, { id: "c", text: "做人要争强好胜", errorTag: "off_topic" }, { id: "d", text: "他们的事迹与我们无关", errorTag: "off_topic" } ],
    correct: "a", solution: ["黄继光的英勇、船长的忠于职守、挑山工的脚踏实地，都说明伟大的品格体现在行动中——本单元正是要从语言动作感受人物品质。"] }),
  pickChoice({ id: "cn-u7-h-006", unit_id: U7, skill_id: "C4B_U7_PINYIN", ability: ["glyph"], difficulty: 5,
    stem: "下面四组词中全部没有错别字的一组是？",
    options: [ { id: "a", text: "弥漫 · 葬身 · 履行 · 镇定自若" }, { id: "b", text: "弥漫 · 葬身 · 复行 · 镇定自若", errorTag: "glyph_homophone" }, { id: "c", text: "弥曼 · 葬身 · 履行 · 震定自若", errorTag: "glyph_homophone" }, { id: "d", text: "弥漫 · 莽身 · 履行 · 镇定自若", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“履行”不是“复行”；“弥漫”不是“弥曼”；“葬身”不是“莽身”；“镇定”不是“震定”。A 全对。"] }),

  // 第七单元 · D2/D4 平衡 (4)
  pickChoice({ id: "cn-u7-b-001", unit_id: U7, skill_id: "C4B_U7_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "“镇定自若”的意思是？",
    options: [ { id: "a", text: "遇事沉着冷静，像平常一样" }, { id: "b", text: "非常慌张", errorTag: "antonym_misuse" }, { id: "c", text: "镇定地坐着", errorTag: "literal_misread" }, { id: "d", text: "自由自在", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“镇定自若”形容遇到紧急情况沉着冷静、神态如常。"] }),
  pickChoice({ id: "cn-u7-b-002", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation"], difficulty: 2,
    stem: "默写填空：月黑雁飞高，（  ）。",
    options: [ { id: "a", text: "单于夜遁逃" }, { id: "b", text: "大雪满弓刀", errorTag: "poem_mismatch" }, { id: "c", text: "一片冰心在玉壶", errorTag: "poem_mismatch" }, { id: "d", text: "欲将轻骑逐", errorTag: "poem_mismatch" } ],
    correct: "a", solution: ["《塞下曲》：“月黑雁飞高，单于夜遁逃。”"] }),
  pickChoice({ id: "cn-u7-b-003", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading"], difficulty: 4,
    stem: "《挑山工》中作者从挑山工身上悟出的道理，可以用下面哪句话概括？",
    options: [ { id: "a", text: "认准目标、脚踏实地、坚持不懈，就能后来居上" }, { id: "b", text: "走得越慢越好", errorTag: "word_misunderstand" }, { id: "c", text: "登山要靠运气", errorTag: "off_topic" }, { id: "d", text: "游玩比赶路重要", errorTag: "opposite" } ],
    correct: "a", solution: ["挑山工“一个劲儿往前走”、脚踏实地、不三心二意，启示我们认准目标、坚持不懈就能取得成功。"] }),
  pickChoice({ id: "cn-u7-b-004", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["sentence"], difficulty: 4,
    stem: "“子弹像冰雹一样射过来”和“他犹如铁铸，纹丝不动”，这两句的修辞分别是？",
    options: [ { id: "a", text: "都是比喻" }, { id: "b", text: "前者比喻，后者拟人", errorTag: "wrong_rhetoric" }, { id: "c", text: "前者拟人，后者比喻", errorTag: "wrong_rhetoric" }, { id: "d", text: "都是夸张", errorTag: "wrong_rhetoric" } ],
    correct: "a", solution: ["“像冰雹一样”把子弹比作冰雹，“犹如铁铸”把船长比作铁铸的雕像，两句都是比喻。"] }),

  // ====================================================================
  // 第八单元 · D1 送分 (10)
  // ====================================================================
  pickChoice({ id: "cn-u8-e-001", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 1,
    stem: "《海的女儿》的作者是？",
    options: [ { id: "a", text: "安徒生（丹麦）" }, { id: "b", text: "王尔德（英国）", errorTag: "author_confusion" }, { id: "c", text: "格林兄弟", errorTag: "author_confusion" }, { id: "d", text: "张天翼", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《海的女儿》是丹麦童话作家安徒生的作品。"] }),
  pickChoice({ id: "cn-u8-e-002", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 1,
    stem: "《巨人的花园》的作者是？",
    options: [ { id: "a", text: "王尔德（英国）" }, { id: "b", text: "安徒生", errorTag: "author_confusion" }, { id: "c", text: "叶圣陶", errorTag: "author_confusion" }, { id: "d", text: "冰心", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《巨人的花园》是英国作家王尔德的童话，巴金译。"] }),
  pickChoice({ id: "cn-u8-e-003", unit_id: U8, skill_id: "C4B_U8_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“珊瑚”的读音是？",
    options: [ { id: "a", text: "shān hú" }, { id: "b", text: "shàn hú", errorTag: "tone_confusion" }, { id: "c", text: "shān hǔ", errorTag: "tone_confusion" }, { id: "d", text: "sān hú", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“珊瑚”读 shān hú，一种海洋生物，两字都是王字旁。"] }),
  pickChoice({ id: "cn-u8-e-004", unit_id: U8, skill_id: "C4B_U8_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "下面字全对的一组是？",
    options: [ { id: "a", text: "允许 · 拆除" }, { id: "b", text: "充许 · 拆除", errorTag: "glyph_homophone" }, { id: "c", text: "允许 · 折除", errorTag: "glyph_homophone" }, { id: "d", text: "允诉 · 拆除", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“允许”不是“充许”；“拆除”不是“折除”。"] }),
  pickChoice({ id: "cn-u8-e-005", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 1,
    stem: "《宝葫芦的秘密》中，王葆想要一个宝葫芦，是因为？",
    options: [ { id: "a", text: "他幻想有了宝葫芦就能要什么有什么、不费力就能成功" }, { id: "b", text: "他想送给奶奶", errorTag: "off_topic" }, { id: "c", text: "他想卖钱", errorTag: "off_topic" }, { id: "d", text: "他想做实验", errorTag: "off_topic" } ],
    correct: "a", solution: ["王葆听了奶奶讲的故事，幻想有了宝葫芦就能“要什么有什么”、轻松解决困难。"] }),
  pickChoice({ id: "cn-u8-e-006", unit_id: U8, skill_id: "C4B_U8_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“丰硕”常用来形容？",
    options: [ { id: "a", text: "果实又多又大（也指成果大）" }, { id: "b", text: "颜色鲜艳", errorTag: "word_misunderstand" }, { id: "c", text: "味道好", errorTag: "word_misunderstand" }, { id: "d", text: "很小", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["“丰硕”指（果实）又多又大，也比喻成果丰富、巨大。"] }),
  pickChoice({ id: "cn-u8-e-007", unit_id: U8, skill_id: "C4B_U8_PINYIN", ability: ["phonics"], difficulty: 1,
    stem: "“呼啸”的“啸”读音是？",
    options: [ { id: "a", text: "xiào" }, { id: "b", text: "xiāo", errorTag: "tone_confusion" }, { id: "c", text: "sù", errorTag: "phonics_error" }, { id: "d", text: "shù", errorTag: "phonics_error" } ],
    correct: "a", solution: ["“啸”读 xiào，“呼啸”形容发出高而长的声音，如北风呼啸。"] }),
  pickChoice({ id: "cn-u8-e-008", unit_id: U8, skill_id: "C4B_U8_PINYIN", ability: ["glyph"], difficulty: 1,
    stem: "看拼音写词语：巨人最后 chāi chú（拆除）了围墙。",
    options: [ { id: "a", text: "拆除" }, { id: "b", text: "折除", errorTag: "glyph_homophone" }, { id: "c", text: "拆涂", errorTag: "glyph_homophone" }, { id: "d", text: "坼除", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“拆除”指把建筑物拆掉。“拆”读 chāi（提手旁），不是“折”。"] }),
  pickChoice({ id: "cn-u8-e-009", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 1,
    stem: "第八单元几篇课文（《巨人的花园》《海的女儿》《宝葫芦的秘密》）都属于哪种体裁？",
    options: [ { id: "a", text: "童话" }, { id: "b", text: "古诗", errorTag: "category_confusion" }, { id: "c", text: "说明文", errorTag: "category_confusion" }, { id: "d", text: "新闻", errorTag: "category_confusion" } ],
    correct: "a", solution: ["第八单元是童话单元，三篇都是充满奇妙想象的童话。"] }),
  pickChoice({ id: "cn-u8-e-010", unit_id: U8, skill_id: "C4B_U8_VOCAB", ability: ["vocabulary"], difficulty: 1,
    stem: "“自言自语”的意思是？",
    options: [ { id: "a", text: "自己跟自己说话" }, { id: "b", text: "大声对别人说", errorTag: "antonym_misuse" }, { id: "c", text: "说自己的语言", errorTag: "word_misunderstand" }, { id: "d", text: "不说话", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["“自言自语”指自己小声跟自己说话。巨人“自言自语”说要赶走孩子。"] }),

  // 第八单元 · D5 拔高 (6)
  pickChoice({ id: "cn-u8-h-001", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading", "expression"], difficulty: 5,
    stem: "《巨人的花园》中，花园“春去冬来”随孩子的来去而变化。这种奇妙安排的用意是？",
    options: [ { id: "a", text: "用花园景象与孩子（爱与分享）一一对应，揭示“有爱有分享才有春天”的主题" }, { id: "b", text: "说明那里气候反常", errorTag: "literal_misread" }, { id: "c", text: "只是为了好看", errorTag: "off_topic" }, { id: "d", text: "和主题无关", errorTag: "off_topic" } ],
    correct: "a", solution: ["花园随孩子来则春、孩子走则冬，这种神奇对应正是为了揭示主题：有了孩子、有了爱与分享，才有春天般的快乐。"] }),
  pickChoice({ id: "cn-u8-h-002", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading", "expression"], difficulty: 5,
    stem: "《宝葫芦的秘密》整本书中，王葆得到宝葫芦后却烦恼不断。这个童话想说明的道理是？",
    options: [ { id: "a", text: "幸福和成功要靠自己的劳动和努力，不劳而获带不来真正的快乐" }, { id: "b", text: "宝葫芦真的存在", errorTag: "literal_misread" }, { id: "c", text: "做梦能心想事成", errorTag: "off_topic" }, { id: "d", text: "应该多向别人要东西", errorTag: "opposite" } ],
    correct: "a", solution: ["王葆靠宝葫芦不劳而获，结果只有烦恼。童话借此说明：幸福和成功要靠自己努力，依赖侥幸不可取。"] }),
  pickChoice({ id: "cn-u8-h-003", unit_id: U8, skill_id: "C4B_U8_SENTENCE", ability: ["sentence", "reading"], difficulty: 5,
    stem: "《海的女儿》开头“水是那么蓝，像最美丽的矢车菊瓣……同时它又是那么深，深得任何铁锚都达不到底”，这样写的作用是？",
    options: [ { id: "a", text: "用比喻和夸张，渲染海底世界的奇异、瑰丽，营造童话氛围" }, { id: "b", text: "介绍海水的科学成分", errorTag: "off_topic" }, { id: "c", text: "说明海很危险", errorTag: "narrow_focus" }, { id: "d", text: "没有作用", errorTag: "off_topic" } ],
    correct: "a", solution: ["“像矢车菊瓣”“像玻璃”是比喻，“深得铁锚都达不到底”是夸张，共同渲染海底世界的奇异瑰丽，营造童话氛围。"] }),
  pickChoice({ id: "cn-u8-h-004", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 5,
    stem: "读童话时，下面理解最全面的一项是？",
    options: [ { id: "a", text: "既要欣赏奇妙的想象和人物的非凡能力，也要体会其中真善美的形象和道理" }, { id: "b", text: "只看热闹的情节就行", errorTag: "narrow_focus" }, { id: "c", text: "童话都是骗小孩的，没有意义", errorTag: "opposite" }, { id: "d", text: "只需记住人物名字", errorTag: "narrow_focus" } ],
    correct: "a", solution: ["语文园地指出：读童话既要感受奇妙的想象、人物的非凡能力，更要体会其中真善美的形象和蕴含的道理。"] }),
  pickChoice({ id: "cn-u8-h-005", unit_id: U8, skill_id: "C4B_U8_PINYIN", ability: ["phonics"], difficulty: 5,
    stem: "下面加点多音字读音全部正确的一项（“冲着他笑”“冲锋”“几乎”“几个”）？",
    options: [ { id: "a", text: "冲着（chòng） 冲锋（chōng） 几乎（jī） 几个（jǐ）" }, { id: "b", text: "冲着（chōng） 冲锋（chòng） 几乎（jǐ） 几个（jī）", errorTag: "polyphone_confusion" }, { id: "c", text: "冲着（chòng） 冲锋（chōng） 几乎（jǐ） 几个（jī）", errorTag: "polyphone_confusion" }, { id: "d", text: "冲着（chōng） 冲锋（chōng） 几乎（jī） 几个（jǐ）", errorTag: "polyphone_confusion" } ],
    correct: "a", solution: ["冲：chòng（冲着、对着）/chōng（冲锋、冲洗）；几：jī（几乎、茶几）/jǐ（几个、几时）。"] }),
  pickChoice({ id: "cn-u8-h-006", unit_id: U8, skill_id: "C4B_U8_PINYIN", ability: ["glyph"], difficulty: 5,
    stem: "下面四组词中全部没有错别字的一组是？",
    options: [ { id: "a", text: "惩罚 · 踪迹 · 隐私 · 脸颊" }, { id: "b", text: "征罚 · 踪迹 · 隐私 · 脸颊", errorTag: "glyph_homophone" }, { id: "c", text: "惩罚 · 踪绩 · 隐私 · 脸峡", errorTag: "glyph_homophone" }, { id: "d", text: "惩罚 · 踪迹 · 隐丝 · 脸颊", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“惩罚”不是“征罚”；“踪迹”不是“踪绩”；“隐私”不是“隐丝”；“脸颊”不是“脸峡”。A 全对。"] }),

  // 第八单元 · D2/D4 平衡 (4)
  pickChoice({ id: "cn-u8-b-001", unit_id: U8, skill_id: "C4B_U8_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "“凄凉”的意思是？",
    options: [ { id: "a", text: "冷清、孤寂、没有生气" }, { id: "b", text: "凉快", errorTag: "literal_misread" }, { id: "c", text: "热闹", errorTag: "antonym_misuse" }, { id: "d", text: "美丽", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["“凄凉”形容冷清、孤寂、没有生气。巨人赶走孩子后花园一片凄凉。"] }),
  pickChoice({ id: "cn-u8-b-002", unit_id: U8, skill_id: "C4B_U8_SENTENCE", ability: ["sentence"], difficulty: 2,
    stem: "“雪用他的白色大衣覆盖着青草”这句话用了什么修辞？",
    options: [ { id: "a", text: "拟人" }, { id: "b", text: "比喻", errorTag: "wrong_rhetoric" }, { id: "c", text: "排比", errorTag: "wrong_rhetoric" }, { id: "d", text: "夸张", errorTag: "wrong_rhetoric" } ],
    correct: "a", solution: ["“雪用大衣覆盖”把雪当作人来写，是拟人。"] }),
  pickChoice({ id: "cn-u8-b-003", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 4,
    stem: "《巨人的花园》中巨人的转变过程是？",
    options: [ { id: "a", text: "自私筑墙赶孩子 → 醒悟“我多么自私” → 拆墙分享，变得无私和善" }, { id: "b", text: "一直很善良", errorTag: "detail_wrong" }, { id: "c", text: "由善变恶", errorTag: "opposite" }, { id: "d", text: "始终没有变化", errorTag: "opposite" } ],
    correct: "a", solution: ["巨人由自私筑墙、赶走孩子，到看见小男孩后醒悟“我多么自私啊”，最后拆墙、分享花园，变得无私和善。"] }),
  pickChoice({ id: "cn-u8-b-004", unit_id: U8, skill_id: "C4B_U8_SENTENCE", ability: ["sentence", "expression"], difficulty: 4,
    stem: "照样子写句子。例：花朵开得像燃烧着的火。下面仿写最恰当的一项是？",
    options: [ { id: "a", text: "湖水绿得像一块碧玉。" }, { id: "b", text: "湖水很绿。", errorTag: "no_rhetoric" }, { id: "c", text: "湖水是绿色的。", errorTag: "no_rhetoric" }, { id: "d", text: "湖里有水。", errorTag: "off_topic" } ],
    correct: "a", solution: ["例句是“……得像……”的比喻句。A“绿得像一块碧玉”结构相同、用了比喻，仿写最恰当。"] }),
];
