/**
 * 语文 · C4B 平衡 + 难度比例补充包 (v0.36.85+, 爸爸 2026-05-21 "继续 loop").
 *
 * 目的: 把偏低单元往 ~116 靠拢、补足 D2(易)档占比(原 18% 偏低)。本批全部 D2，
 * 用全新的字词/课文角度，不与既有题重复。每批后过 audit:chinese。
 *
 * 内容依据人教版四下课本。id 前缀 cn-uN-bal-。
 * 约定: 双引号字符串内引文一律用全角“”。
 */

import type { Question } from "../../core/types";
import { pickChoice } from "./questionHelpers";

const U6 = "C4B_U6_GROWTH";
const U7 = "C4B_U7_CHARACTER";
const U8 = "C4B_U8_FAIRYTALE";

export const SEED_QUESTIONS_CHINESE_BALANCE: Question[] = [
  // ===== 第六单元 D2 (10) =====
  pickChoice({ id: "cn-u6-bal-001", unit_id: U6, skill_id: "C4B_U6_PINYIN", ability: ["phonics"], difficulty: 2,
    stem: "“钻”是多音字。下面读音对应正确的一组是？",
    options: [ { id: "a", text: "钻进（zuān） 钻石（zuàn）" }, { id: "b", text: "钻进（zuàn） 钻石（zuān）", errorTag: "polyphone_confusion" }, { id: "c", text: "钻进（zuān） 钻石（zuān）", errorTag: "polyphone_confusion" }, { id: "d", text: "钻进（zuàn） 钻石（zuàn）", errorTag: "polyphone_confusion" } ],
    correct: "a", solution: ["“钻”：zuān（动词，钻进、钻研）/ zuàn（名词，钻石、电钻）。"] }),
  pickChoice({ id: "cn-u6-bal-002", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation"], difficulty: 2,
    stem: "《铁杵成针》“问之，曰：‘欲作针。’”中，“曰”的意思是？",
    options: [ { id: "a", text: "说" }, { id: "b", text: "叫", errorTag: "word_misunderstand" }, { id: "c", text: "写", errorTag: "word_misunderstand" }, { id: "d", text: "想", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["文言文中“曰”是“说”的意思。“曰：‘欲作针。’”即（老媪）说：“想做一根针。”"] }),
  pickChoice({ id: "cn-u6-bal-003", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation", "reading"], difficulty: 2,
    stem: "《铁杵成针》“问之”中的“之”指的是？",
    options: [ { id: "a", text: "老媪（老妇人）" }, { id: "b", text: "铁杵", errorTag: "word_misunderstand" }, { id: "c", text: "李白自己", errorTag: "word_misunderstand" }, { id: "d", text: "针", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“问之”是（李白）问她（老媪）。“之”作代词，指正在磨铁杵的老媪。"] }),
  pickChoice({ id: "cn-u6-bal-004", unit_id: U6, skill_id: "C4B_U6_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "“倔强”的反义词是？",
    options: [ { id: "a", text: "温顺" }, { id: "b", text: "刚强", errorTag: "synonym_misuse" }, { id: "c", text: "固执", errorTag: "synonym_misuse" }, { id: "d", text: "勇敢", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“倔强”指刚强不屈，反义词是“温顺”。“刚强、固执”是近义词。"] }),
  pickChoice({ id: "cn-u6-bal-005", unit_id: U6, skill_id: "C4B_U6_SUMMARY", ability: ["reading"], difficulty: 2,
    stem: "《小英雄雨来》中，雨来掩护的是谁？",
    options: [ { id: "a", text: "交通员李大叔" }, { id: "b", text: "女老师", errorTag: "detail_wrong" }, { id: "c", text: "三钻儿", errorTag: "detail_wrong" }, { id: "d", text: "铁头", errorTag: "detail_wrong" } ],
    correct: "a", solution: ["雨来把区上的交通员李大叔藏进地洞，自己面对鬼子毫不屈服，掩护了李大叔。"] }),
  pickChoice({ id: "cn-u6-bal-006", unit_id: U6, skill_id: "C4B_U6_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "选词填空：母亲对孩子总是那么（  ）。（慈爱 / 慈善）",
    options: [ { id: "a", text: "慈爱" }, { id: "b", text: "慈善", errorTag: "synonym_misuse" }, { id: "c", text: "慈悲", errorTag: "synonym_misuse" }, { id: "d", text: "和善", errorTag: "synonym_misuse" } ],
    correct: "a", solution: ["“慈爱”指长辈对晚辈的爱，多用于母亲、长辈；“慈善”多指做善事、救济。"] }),
  pickChoice({ id: "cn-u6-bal-007", unit_id: U6, skill_id: "C4B_U6_SUMMARY", ability: ["reading"], difficulty: 2,
    stem: "《我们家的男子汉》中，最能体现孩子“对独立的要求”的一件事是？",
    options: [ { id: "a", text: "他坚持自己拿着钱去柜台买东西" }, { id: "b", text: "他爱吃东西", errorTag: "wrong_part" }, { id: "c", text: "他去托儿所哭了", errorTag: "wrong_part" }, { id: "d", text: "他学醉拳", errorTag: "wrong_part" } ],
    correct: "a", solution: ["“他对独立的要求”一节，写他不要大人帮忙、坚持自己去买东西、自己换橘子水，体现独立。"] }),
  pickChoice({ id: "cn-u6-bal-008", unit_id: U6, skill_id: "C4B_U6_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "下面词语搭配恰当的一组是？",
    options: [ { id: "a", text: "勤奋地读书 · 顽强地战斗 · 耐心地等待" }, { id: "b", text: "勤奋地战斗 · 顽强地等待 · 耐心地读书", errorTag: "collocation_error" }, { id: "c", text: "勤奋地等待 · 顽强地读书 · 耐心地战斗", errorTag: "collocation_error" }, { id: "d", text: "顽强地读书 · 勤奋地等待 · 耐心地战斗", errorTag: "collocation_error" } ],
    correct: "a", solution: ["“勤奋”配读书、“顽强”配战斗、“耐心”配等待，搭配最恰当。"] }),
  pickChoice({ id: "cn-u6-bal-009", unit_id: U6, skill_id: "C4B_U6_WENYAN", ability: ["accumulation"], difficulty: 2,
    stem: "“囊萤夜读”这个成语现在常用来比喻？",
    options: [ { id: "a", text: "家境贫寒仍勤奋苦读" }, { id: "b", text: "晚上捉萤火虫玩", errorTag: "literal_misread" }, { id: "c", text: "夏天乘凉", errorTag: "off_topic" }, { id: "d", text: "白天睡觉晚上工作", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["“囊萤夜读”由车胤囊萤照读的故事而来，现在比喻家境贫寒却勤奋好学。"] }),
  pickChoice({ id: "cn-u6-bal-010", unit_id: U6, skill_id: "C4B_U6_PINYIN", ability: ["glyph"], difficulty: 2,
    stem: "看拼音写词语：屋里遭了 jié nàn（劫难），连枕头都被刺刀挑破了。",
    options: [ { id: "a", text: "劫难" }, { id: "b", text: "节难", errorTag: "glyph_homophone" }, { id: "c", text: "劫南", errorTag: "glyph_homophone" }, { id: "d", text: "结难", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“劫难”指灾难。“劫”指强取、灾难，不要写成“节/结”。"] }),

  // ===== 第七单元 D2 (10) =====
  pickChoice({ id: "cn-u7-bal-001", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation"], difficulty: 2,
    stem: "默写填空：不要人夸好颜色，（  ）。",
    options: [ { id: "a", text: "只留清气满乾坤" }, { id: "b", text: "一片冰心在玉壶", errorTag: "poem_mismatch" }, { id: "c", text: "大雪满弓刀", errorTag: "poem_mismatch" }, { id: "d", text: "朵朵花开淡墨痕", errorTag: "poem_mismatch" } ],
    correct: "a", solution: ["《墨梅》：“不要人夸好颜色，只留清气满乾坤。”"] }),
  pickChoice({ id: "cn-u7-bal-002", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation", "reading"], difficulty: 2,
    stem: "《塞下曲》“单于夜遁逃”中“遁逃”的意思是？",
    options: [ { id: "a", text: "逃跑" }, { id: "b", text: "躲藏起来", errorTag: "word_misunderstand" }, { id: "c", text: "投降", errorTag: "word_misunderstand" }, { id: "d", text: "追赶", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["“遁”就是逃，“遁逃”指（敌人首领趁夜）逃跑。"] }),
  pickChoice({ id: "cn-u7-bal-003", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation"], difficulty: 2,
    stem: "《墨梅》“我家洗砚池头树”中的“洗砚池”，传说和哪位古代书法家有关？",
    options: [ { id: "a", text: "王羲之" }, { id: "b", text: "李白", errorTag: "person_confusion" }, { id: "c", text: "杜甫", errorTag: "person_confusion" }, { id: "d", text: "颜真卿", errorTag: "person_confusion" } ],
    correct: "a", solution: ["注释：传说会稽山下有晋代大书法家王羲之的洗砚池，因常洗笔砚，池水都染黑了。"] }),
  pickChoice({ id: "cn-u7-bal-004", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading"], difficulty: 2,
    stem: "《黄继光》中，黄继光最后是怎样摧毁敌人火力点的？",
    options: [ { id: "a", text: "用自己的胸膛堵住了敌人的枪口" }, { id: "b", text: "扔手榴弹炸毁的", errorTag: "detail_wrong" }, { id: "c", text: "开炮轰掉的", errorTag: "detail_wrong" }, { id: "d", text: "绕到后面偷袭", errorTag: "detail_wrong" } ],
    correct: "a", solution: ["黄继光身负重伤，最后张开双臂，用自己的胸膛堵住了敌人的枪口，为部队冲锋扫清了障碍。"] }),
  pickChoice({ id: "cn-u7-bal-005", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading"], difficulty: 2,
    stem: "《“诺曼底号”遇难记》中船长下令“妇女先走”，这体现了？",
    options: [ { id: "a", text: "保护弱者（先救妇女儿童）" }, { id: "b", text: "重男轻女", errorTag: "word_misunderstand" }, { id: "c", text: "船长怕女乘客", errorTag: "off_topic" }, { id: "d", text: "随便安排", errorTag: "opposite" } ],
    correct: "a", solution: ["危急时刻“妇女先走，其他乘客跟上，船员断后”，体现船长保护弱者、临危不乱的崇高品质。"] }),
  pickChoice({ id: "cn-u7-bal-006", unit_id: U7, skill_id: "C4B_U7_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "下面与“沉着”意思最接近的词是？",
    options: [ { id: "a", text: "镇定" }, { id: "b", text: "慌张", errorTag: "antonym_misuse" }, { id: "c", text: "沉重", errorTag: "word_misunderstand" }, { id: "d", text: "沉默", errorTag: "synonym_misuse" } ],
    correct: "a", solution: ["“沉着”指遇事不慌、冷静，与“镇定”最接近；与“慌张”相反。"] }),
  pickChoice({ id: "cn-u7-bal-007", unit_id: U7, skill_id: "C4B_U7_CHARACTER_SKILL", ability: ["reading"], difficulty: 2,
    stem: "《挑山工》一文给我们的启示，用一句俗语来概括，最恰当的是？",
    options: [ { id: "a", text: "脚踏实地，一步一个脚印" }, { id: "b", text: "三天打鱼，两天晒网", errorTag: "antonym_misuse" }, { id: "c", text: "三心二意", errorTag: "antonym_misuse" }, { id: "d", text: "投机取巧", errorTag: "antonym_misuse" } ],
    correct: "a", solution: ["挑山工一个劲儿往前走、脚踏实地，启示我们做事要踏实、专一、坚持，正是“一步一个脚印”。"] }),
  pickChoice({ id: "cn-u7-bal-008", unit_id: U7, skill_id: "C4B_U7_PINYIN", ability: ["glyph"], difficulty: 2,
    stem: "看拼音写词语：哈尔威船长 zhōng yú zhí shǒu（忠于职守）。",
    options: [ { id: "a", text: "忠于职守" }, { id: "b", text: "中于职守", errorTag: "glyph_homophone" }, { id: "c", text: "忠于职手", errorTag: "glyph_homophone" }, { id: "d", text: "忠余职守", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“忠于职守”指忠诚地坚守岗位。“忠”心字底，“守”宝盖头。"] }),
  pickChoice({ id: "cn-u7-bal-009", unit_id: U7, skill_id: "C4B_U7_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "下面词语搭配恰当的一组是？",
    options: [ { id: "a", text: "猛烈的炮火 · 顽强的意志 · 崇高的品质" }, { id: "b", text: "猛烈的意志 · 顽强的品质 · 崇高的炮火", errorTag: "collocation_error" }, { id: "c", text: "崇高的炮火 · 猛烈的品质 · 顽强的意志", errorTag: "collocation_error" }, { id: "d", text: "顽强的炮火 · 崇高的意志 · 猛烈的品质", errorTag: "collocation_error" } ],
    correct: "a", solution: ["“猛烈”配炮火、“顽强”配意志、“崇高”配品质，搭配最恰当。"] }),
  pickChoice({ id: "cn-u7-bal-010", unit_id: U7, skill_id: "C4B_U7_POEM", ability: ["accumulation"], difficulty: 2,
    stem: "《芙蓉楼送辛渐》中“吴”“楚”指的是？",
    options: [ { id: "a", text: "古代的地名（这一带古属吴地、楚地）" }, { id: "b", text: "两个人的名字", errorTag: "word_misunderstand" }, { id: "c", text: "两座桥", errorTag: "word_misunderstand" }, { id: "d", text: "两种花", errorTag: "word_misunderstand" } ],
    correct: "a", solution: ["注释：镇江一带古代属吴地，长江中下游北岸的山古代属楚地范围。“吴”“楚”都是古地名。"] }),

  // ===== 第八单元 D2 (10) =====
  pickChoice({ id: "cn-u8-bal-001", unit_id: U8, skill_id: "C4B_U8_PINYIN", ability: ["phonics"], difficulty: 2,
    stem: "“给”是多音字。下面读音对应正确的一组是？",
    options: [ { id: "a", text: "给予（jǐ） 给你（gěi）" }, { id: "b", text: "给予（gěi） 给你（jǐ）", errorTag: "polyphone_confusion" }, { id: "c", text: "给予（jǐ） 给你（jǐ）", errorTag: "polyphone_confusion" }, { id: "d", text: "给予（gěi） 给你（gěi）", errorTag: "polyphone_confusion" } ],
    correct: "a", solution: ["“给”：jǐ（书面，给予、供给、自给自足）/ gěi（口语，给你、送给）。"] }),
  pickChoice({ id: "cn-u8-bal-002", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 2,
    stem: "《海的女儿》中，最小的公主要满多少岁才能浮到海面上去？",
    options: [ { id: "a", text: "十五岁" }, { id: "b", text: "十岁", errorTag: "fact_wrong" }, { id: "c", text: "二十岁", errorTag: "fact_wrong" }, { id: "d", text: "十八岁", errorTag: "fact_wrong" } ],
    correct: "a", solution: ["老祖母说，满了十五岁就准许浮到水面上去。小公主年纪最小，要等最久。"] }),
  pickChoice({ id: "cn-u8-bal-003", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 2,
    stem: "《巨人的花园》中，巨人离家去看朋友，一住就是多少年？",
    options: [ { id: "a", text: "七年" }, { id: "b", text: "三年", errorTag: "fact_wrong" }, { id: "c", text: "十年", errorTag: "fact_wrong" }, { id: "d", text: "一年", errorTag: "fact_wrong" } ],
    correct: "a", solution: ["课文写巨人“离家去看朋友，在那里一住就是七年”，回来后看见孩子在花园里玩。"] }),
  pickChoice({ id: "cn-u8-bal-004", unit_id: U8, skill_id: "C4B_U8_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "“凄凉”的反义词是？",
    options: [ { id: "a", text: "热闹" }, { id: "b", text: "冷清", errorTag: "synonym_misuse" }, { id: "c", text: "孤寂", errorTag: "synonym_misuse" }, { id: "d", text: "荒凉", errorTag: "synonym_misuse" } ],
    correct: "a", solution: ["“凄凉”指冷清孤寂，反义词是“热闹”。其余三个都是近义词。"] }),
  pickChoice({ id: "cn-u8-bal-005", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 2,
    stem: "《宝葫芦的秘密》的作者是？",
    options: [ { id: "a", text: "张天翼" }, { id: "b", text: "安徒生", errorTag: "author_confusion" }, { id: "c", text: "王尔德", errorTag: "author_confusion" }, { id: "d", text: "叶君健", errorTag: "author_confusion" } ],
    correct: "a", solution: ["《宝葫芦的秘密》的作者是中国作家张天翼。"] }),
  pickChoice({ id: "cn-u8-bal-006", unit_id: U8, skill_id: "C4B_U8_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "选词填空：①小公主静静地坐着，（  ）地想着什么。②她常常一个人（  ），不爱说话。（沉思 / 沉默）",
    options: [ { id: "a", text: "①沉思 ②沉默" }, { id: "b", text: "①沉默 ②沉思", errorTag: "synonym_misuse" }, { id: "c", text: "①沉思 ②沉思", errorTag: "synonym_misuse" }, { id: "d", text: "①沉默 ②沉默", errorTag: "synonym_misuse" } ],
    correct: "a", solution: ["“沉思”指深深地思考（想着什么）；“沉默”指不说话。①重在想，②重在不出声。"] }),
  pickChoice({ id: "cn-u8-bal-007", unit_id: U8, skill_id: "C4B_U8_SENTENCE", ability: ["sentence"], difficulty: 2,
    stem: "“鱼儿们在这些枝叶中间游来游去，像是天空中的飞鸟。”这句话用了什么修辞？",
    options: [ { id: "a", text: "比喻（把鱼儿比作飞鸟）" }, { id: "b", text: "拟人", errorTag: "wrong_rhetoric" }, { id: "c", text: "排比", errorTag: "wrong_rhetoric" }, { id: "d", text: "夸张", errorTag: "wrong_rhetoric" } ],
    correct: "a", solution: ["“像是天空中的飞鸟”把游动的鱼儿比作飞鸟，是比喻，写出海底世界的奇妙。"] }),
  pickChoice({ id: "cn-u8-bal-008", unit_id: U8, skill_id: "C4B_U8_PINYIN", ability: ["glyph"], difficulty: 2,
    stem: "看拼音写词语：巨人挂出布告牌：“禁止入内，违者重 chéng（惩）。”",
    options: [ { id: "a", text: "惩" }, { id: "b", text: "征", errorTag: "glyph_homophone" }, { id: "c", text: "诚", errorTag: "glyph_homophone" }, { id: "d", text: "承", errorTag: "glyph_homophone" } ],
    correct: "a", solution: ["“重惩”指重重处罚。“惩”是心字底（惩罚、惩戒）。"] }),
  pickChoice({ id: "cn-u8-bal-009", unit_id: U8, skill_id: "C4B_U8_IMAGINE", ability: ["reading"], difficulty: 2,
    stem: "《巨人的花园》结尾，巨人说“孩子们是最美丽的花”，这句话的意思是？",
    options: [ { id: "a", text: "巨人懂得了：有孩子、有爱与分享，才是最美的" }, { id: "b", text: "孩子真的变成了花", errorTag: "literal_misread" }, { id: "c", text: "花比孩子好看", errorTag: "opposite" }, { id: "d", text: "巨人喜欢种花", errorTag: "off_topic" } ],
    correct: "a", solution: ["巨人由自私变得无私后明白：花园里许多美丽的花，可孩子们才是最美丽的花——有爱、有分享才最美好。"] }),
  pickChoice({ id: "cn-u8-bal-010", unit_id: U8, skill_id: "C4B_U8_VOCAB", ability: ["vocabulary"], difficulty: 2,
    stem: "下面词语搭配恰当的一组是？",
    options: [ { id: "a", text: "奇异的光彩 · 美丽的公主 · 高大的宫殿" }, { id: "b", text: "奇异的公主 · 美丽的宫殿 · 高大的光彩", errorTag: "collocation_error" }, { id: "c", text: "高大的光彩 · 奇异的宫殿 · 美丽的公主", errorTag: "collocation_error" }, { id: "d", text: "美丽的光彩 · 高大的公主 · 奇异的宫殿", errorTag: "collocation_error" } ],
    correct: "a", solution: ["“奇异”配光彩、“美丽”配公主、“高大”配宫殿，搭配最恰当。"] }),
];
