/**
 * 语文 · C4B 第五单元（游记）期末备考扩量包 (v0.36.74, 爸爸 2026-05-21).
 *
 * 背景: U5 原仅 ~25 题, 期末考全册, 这里补到 ~80。内容严格依据人教版四下课本:
 *  - 16 海上日出 (巴金): 扩/范/努/刹/烂/替/镶/紫/仪; 多音字 重荷(hè)/刹那(chà);
 *    加点句赏析"太阳好像负着重荷似的……努力上升"; 反问"这不是很伟大的奇观吗?"
 *  - 17 记金华的双龙洞 (叶圣陶): 浙/罗/杜/鹃/窄/郁/肩/臀/移/额/陆/乳/笋/端/源;
 *    游览顺序 路上→洞口→外洞→孔隙→内洞→出洞; 映山红=杜鹃花; 孔隙之小; 系(jì)绳子。
 *  - 习作例文 颐和园 (袁鹰): 长廊700多米273间; 过渡句; 昆明湖"静得像镜子,绿得像碧玉";
 *    十七孔桥。 七月的天山 (碧野): 顺序"进入→再往里走→走进深处"; 排比比喻"像锦缎,
 *    像霞光,像彩虹"; 柔嫩/柔美; 矫健(jiǎo)。
 *
 * 题型对齐期中卷情境化考点: 看拼音选词 / 多音字 / 错别字 / 近义词辨析 (柔嫩-柔软) /
 * 修辞辨认 / 过渡句 / 词语理解 / 游览顺序 / 阅读多问 / 听写。
 *
 * id 前缀 cn-u5-x*, 与原 U5 题 (cn-u5-pinyin/vocab/order/dict/fill/poly/syn) 不撞。
 */

import type { Question } from "../../core/types";
import { pickChoice, dictation } from "./questionHelpers";

const U5 = "C4B_U5_TRAVEL";
const PINYIN = "C4B_U5_PINYIN";
const VOCAB = "C4B_U5_VOCAB";
const ORDER = "C4B_U5_ORDER";
const DICT = "C4B_U5_DICTATION";
const RHET = "C4B_U5_RHETORIC";
const READ = "C4B_U5_READING";

// 阅读短文 (写景 / 游记风格, 仿课文, 原创以保证内容可控)
const PASSAGE_A = `📖 短文一·登山观日（写景）

清晨四点多，我们就摸黑爬上了山顶，等着看日出。那时天还没有亮，四周一片寂静，只听见风吹过松林的声音。过了一会儿，东方的天边露出一道淡淡的红霞，慢慢地扩大着、加亮着。忽然，一个红red的圆东西从云海里冒出小半边脸，红是真红，却没有亮光。它好像背着很重的东西，一点一点地往上挪。终于，太阳一下子跳出了云海，发出夺目的光芒，把旁边的云彩染成了金色、紫色。我望着这壮丽的景象，心里想：这不就是大自然最伟大的奇观吗？`;

const PASSAGE_B = `📖 短文二·游天池（游记）

暑假里，我们一家去新疆游天池。一路上，戈壁滩的炎热被远远地抛在后面，山里送来的凉风让人神清气爽。进入山口，迎面是大片大片的云杉林，密密的枝叶像撑开的绿伞，挡住了火辣辣的太阳。再往里走，溪流声越来越清脆，溪水清得能看见水底的石子。走到天池边，只见湖水绿得像一块碧玉，静得像一面镜子，远处的雪峰倒映在水里，美得让人舍不得离开。虽然山外是盛夏，可这里却凉爽得像秋天，真是个避暑的好地方。`;

export const SEED_QUESTIONS_CHINESE_U5_EXAM: Question[] = [
  // ============================================================
  // 字音 · 多音字 / 易错读音 (海上日出 · 双龙洞 · 七月的天山)
  // ============================================================
  pickChoice({
    id: "cn-u5-xpy-001",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: '《海上日出》"太阳好像负着重荷似的"中，"重荷"的"荷"读音是？',
    options: [
      { id: "a", text: "hè（负荷、重荷）" },
      { id: "b", text: "hé（荷花、荷叶）", errorTag: "polyphone_confusion" },
      { id: "c", text: "hē", errorTag: "tone_confusion" },
      { id: "d", text: "hú", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"荷"是多音字：hé（荷花，植物）/ hè（负荷、重荷，担子、负担）。"重荷"指沉重的担子，读 hè。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-002",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: '《海上日出》"一刹那间"的"刹"读音是？',
    options: [
      { id: "a", text: "chà（刹那）" },
      { id: "b", text: "shā（刹车）", errorTag: "polyphone_confusion" },
      { id: "c", text: "sà", errorTag: "phonics_error" },
      { id: "d", text: "chā", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['"刹"是多音字：chà（一刹那，极短时间）/ shā（刹车，止住）。"一刹那"读 chà。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-003",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: '《记金华的双龙洞》"船两头都系着绳子"中，"系"读音是？',
    options: [
      { id: "a", text: "jì（系绳子、系鞋带）" },
      { id: "b", text: "xì（关系、联系）", errorTag: "polyphone_confusion" },
      { id: "c", text: "xī", errorTag: "tone_confusion" },
      { id: "d", text: "jí", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"系"是多音字：jì（用绳子打结、捆，如系鞋带）/ xì（关系、系统）。"系着绳子"读 jì。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-004",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: '《记金华的双龙洞》"公路盘曲而上"的"曲"读音是？',
    options: [
      { id: "a", text: "qū（弯曲、盘曲）" },
      { id: "b", text: "qǔ（歌曲、乐曲）", errorTag: "polyphone_confusion" },
      { id: "c", text: "qù", errorTag: "tone_confusion" },
      { id: "d", text: "qiū", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"曲"是多音字：qū（弯曲、盘曲而上）/ qǔ（歌曲）。"盘曲而上"指路弯弯曲曲向上，读 qū。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-005",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: '《记金华的双龙洞》"溪声也时时变换调子"中，"调"读音是？',
    options: [
      { id: "a", text: "diào（调子、声调、腔调）" },
      { id: "b", text: "tiáo（调皮、调和）", errorTag: "polyphone_confusion" },
      { id: "c", text: "diāo", errorTag: "tone_confusion" },
      { id: "d", text: "zhōu", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"调"是多音字：diào（调子、声调）/ tiáo（调皮、调和）。"变换调子"指声音高低变化，读 diào。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-006",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: '《七月的天山》"马走在花海中，显得格外矫健"中，"矫"读音是？',
    options: [
      { id: "a", text: "jiǎo（矫健、矫正）" },
      { id: "b", text: "jiāo", errorTag: "tone_confusion" },
      { id: "c", text: "qiáo", errorTag: "phonics_error" },
      { id: "d", text: "jiào", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['"矫健"读 jiǎo jiàn，形容强壮有力。"矫"读第三声 jiǎo。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-007",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics", "glyph"],
    difficulty: 2,
    stem: '下面加点字读音全部正确的一组是？',
    options: [
      { id: "a", text: "臀部（tún） 浙江（zhè） 石笋（sǔn）" },
      { id: "b", text: "臀部（diàn） 浙江（zhè） 石笋（sǔn）", errorTag: "phonics_error" },
      { id: "c", text: "臀部（tún） 浙江（zhé） 石笋（shǔn）", errorTag: "phonics_error" },
      { id: "d", text: "臀部（tún） 浙江（zhè） 石笋（yǔn）", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['臀 tún、浙 zhè、笋 sǔn，均出自《记金华的双龙洞》生字。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-008",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: '"蜿蜒"一词的正确读音是？（《记金华的双龙洞》：蜿蜒在洞顶的双龙）',
    options: [
      { id: "a", text: "wān yán" },
      { id: "b", text: "wǎn yán", errorTag: "tone_confusion" },
      { id: "c", text: "wān yǎn", errorTag: "tone_confusion" },
      { id: "d", text: "wǎn yǎn", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['"蜿蜒"读 wān yán，形容弯弯曲曲地延伸，像龙蛇爬行。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-009",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: '《七月的天山》"白皑皑群峰的雪线以下"中，"皑皑"读音是？',
    options: [
      { id: "a", text: "ái ái（洁白的样子）" },
      { id: "b", text: "kǎi kǎi", errorTag: "phonics_error" },
      { id: "c", text: "qǐ qǐ", errorTag: "phonics_error" },
      { id: "d", text: "ái āi", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['"白皑皑"读 bái ái ái，形容雪、霜洁白。两个"皑"都读 ái。'],
  }),
  pickChoice({
    id: "cn-u5-xpy-010",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: '"五彩斑斓"的"斓"读音是？',
    options: [
      { id: "a", text: "lán" },
      { id: "b", text: "làn", errorTag: "tone_confusion" },
      { id: "c", text: "jiān", errorTag: "phonics_error" },
      { id: "d", text: "lài", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"斑斓"读 bān lán，形容色彩错杂灿烂。"斓"读 lán。'],
  }),

  // ============================================================
  // 字形 · 错别字 / 形近字
  // ============================================================
  pickChoice({
    id: "cn-u5-xgl-001",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    exam_priority: "MUST_BIG",
    stem: "选出没有错别字的一组（《海上日出》词语）：",
    options: [
      { id: "a", text: "扩大 · 范围 · 努力 · 一刹那" },
      { id: "b", text: "扩大 · 范围 · 怒力 · 一刹那", errorTag: "glyph_homophone" },
      { id: "c", text: "括大 · 范围 · 努力 · 一霎那", errorTag: "glyph_homophone" },
      { id: "d", text: "扩大 · 犯围 · 努力 · 一刹哪", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"努力"不是"怒力"；"扩大"不是"括大"；"刹那"不是"霎那/刹哪"。A 组全对。'],
  }),
  pickChoice({
    id: "cn-u5-xgl-002",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "选出没有错别字的一组（《记金华的双龙洞》词语）：",
    options: [
      { id: "a", text: "杜鹃 · 突兀 · 蜿蜒 · 石钟乳" },
      { id: "b", text: "杜娟 · 突兀 · 蜿蜒 · 石钟乳", errorTag: "glyph_homophone" },
      { id: "c", text: "杜鹃 · 突屼 · 婉蜒 · 石钟乳", errorTag: "glyph_homophone" },
      { id: "d", text: "杜鹃 · 突兀 · 蜿蜒 · 石钟孔", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"杜鹃"（鸟/花名）不是"杜娟"；"蜿蜒"不是"婉蜒"。A 组全对。'],
  }),
  pickChoice({
    id: "cn-u5-xgl-003",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面词语中，有错别字的一项是？",
    options: [
      { id: "a", text: "明艳 · 盘曲 · 蜿蜒", errorTag: "glyph_correct" },
      { id: "b", text: "脏（赃）水 · 漆黑 · 仰卧", errorTag: "glyph_homophone" },
      { id: "c", text: "孔隙 · 臀部 · 额角", errorTag: "glyph_correct" },
      { id: "d", text: "石笋 · 上源 · 移动", errorTag: "glyph_correct" },
    ],
    correct: "b",
    solution: ['B 中"赃水"应为"脏水"（不干净）；"赃"指赃物。其余三组无错别字。本题选有错别字的一项。'],
  }),
  pickChoice({
    id: "cn-u5-xgl-004",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: '《海上日出》"替黑云镶了一道发光的金边"，"镶"字选哪个偏旁组成的字才对？',
    options: [
      { id: "a", text: "镶（金字旁，把东西嵌进去）" },
      { id: "b", text: "嚷（口字旁，大声喊）", errorTag: "form_similar" },
      { id: "c", text: "壤（土字旁，土壤）", errorTag: "form_similar" },
      { id: "d", text: "攘（提手旁，扰攘）", errorTag: "form_similar" },
    ],
    correct: "a",
    solution: ['"镶金边"是把金边嵌在边缘上，与金属有关，用"金"字旁，写"镶"。'],
  }),
  pickChoice({
    id: "cn-u5-xgl-005",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面哪一组字字形相近、容易写错（形近字）？",
    options: [
      { id: "a", text: "臀（臀部）— 臂（手臂）" },
      { id: "b", text: "臀 — 殿（宫殿）", errorTag: "form_similar" },
      { id: "c", text: "臀 — 殿 — 臂，三个字下半完全相同", errorTag: "form_similar" },
      { id: "d", text: "臀 — 笋（竹笋）", errorTag: "form_similar" },
    ],
    correct: "a",
    solution: ['"臀"和"臂"下半都是"月"（肉月旁），都和身体部位有关，字形相近易混。'],
  }),
  pickChoice({
    id: "cn-u5-xgl-006",
    unit_id: U5,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "下面书写完全正确的一项是（《颐和园》《七月的天山》词语）？",
    options: [
      { id: "a", text: "琉璃 · 葱郁 · 锦缎 · 绚丽" },
      { id: "b", text: "流璃 · 葱郁 · 锦缎 · 绚丽", errorTag: "glyph_homophone" },
      { id: "c", text: "琉璃 · 葱欲 · 棉缎 · 绚丽", errorTag: "glyph_homophone" },
      { id: "d", text: "琉璃 · 葱郁 · 锦缎 · 询丽", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"琉璃"不是"流璃"；"葱郁"不是"葱欲"；"锦缎"不是"棉缎"；"绚丽"不是"询丽"。A 全对。'],
  }),

  // ============================================================
  // 词语 · 近义词辨析 / 词语理解 / 看拼音选词
  // ============================================================
  pickChoice({
    id: "cn-u5-xvocab-001",
    unit_id: U5,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: '选词填空：走进天山深处，山色逐渐变得（  ），山形也逐渐变得柔美。（柔嫩 / 柔软）',
    options: [
      { id: "a", text: "柔嫩（多形容颜色、草木娇嫩）" },
      { id: "b", text: "柔软（多形容物体软，如棉花、头发）", errorTag: "synonym_misuse" },
      { id: "c", text: "柔弱（软弱无力）", errorTag: "synonym_misuse" },
      { id: "d", text: "软弱（不坚强）", errorTag: "synonym_misuse" },
    ],
    correct: "a",
    solution: ['课文原句"山色逐渐变得柔嫩"。"柔嫩"形容颜色、草木娇嫩可爱；"柔软"多形容物体质地软。'],
  }),
  pickChoice({
    id: "cn-u5-xvocab-002",
    unit_id: U5,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '《记金华的双龙洞》中"映山红"指的是什么？',
    options: [
      { id: "a", text: "杜鹃花" },
      { id: "b", text: "映在山上的红霞", errorTag: "literal_misread" },
      { id: "c", text: "一种红色的山", errorTag: "literal_misread" },
      { id: "d", text: "红色的枫叶", errorTag: "literal_misread" },
    ],
    correct: "a",
    solution: ['"映山红"是杜鹃花的别名。课文说"山上开满了映山红……比盆栽的杜鹃显得有精神"。'],
  }),
  pickChoice({
    id: "cn-u5-xvocab-003",
    unit_id: U5,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '"突兀森郁"形容的是？（《记金华的双龙洞》：山相当高，突兀森郁）',
    options: [
      { id: "a", text: "山势高耸、树木茂密" },
      { id: "b", text: "山路弯曲难走", errorTag: "word_misunderstand" },
      { id: "c", text: "天气阴沉", errorTag: "word_misunderstand" },
      { id: "d", text: "洞里漆黑一片", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['"突兀"指高高耸起；"森郁"指树木茂盛。合起来形容山高大、林木繁密、很有气势。'],
  }),
  pickChoice({
    id: "cn-u5-xvocab-004",
    unit_id: U5,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: '"颐和园到处有美丽的景色，说也说不尽"中，"说不尽"的意思是？',
    options: [
      { id: "a", text: "美景很多，说不完" },
      { id: "b", text: "不能说出来", errorTag: "word_misunderstand" },
      { id: "c", text: "说错了", errorTag: "word_misunderstand" },
      { id: "d", text: "不让人说", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['"说也说不尽"是说颐和园美景太多，怎么说也说不完，表达赞美和留恋。'],
  }),
  pickChoice({
    id: "cn-u5-xvocab-005",
    unit_id: U5,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: '看拼音选词语：山里送来的凉风，使人感到 shén qīng qì shuǎng。',
    options: [
      { id: "a", text: "神清气爽" },
      { id: "b", text: "神清气塽", errorTag: "glyph_homophone" },
      { id: "c", text: "深清气爽", errorTag: "glyph_homophone" },
      { id: "d", text: "神情气爽", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"神清气爽"形容心情舒畅、精神爽快。注意"神""爽"的写法。'],
  }),
  pickChoice({
    id: "cn-u5-xvocab-006",
    unit_id: U5,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '下面词语搭配恰当的一组是？',
    options: [
      { id: "a", text: "明艳的山色 · 闪耀的银链 · 漆黑的内洞" },
      { id: "b", text: "明艳的声音 · 闪耀的银链 · 漆黑的内洞", errorTag: "collocation_error" },
      { id: "c", text: "明艳的山色 · 闪耀的小船 · 漆黑的内洞", errorTag: "collocation_error" },
      { id: "d", text: "明艳的山色 · 闪耀的银链 · 漆黑的阳光", errorTag: "collocation_error" },
    ],
    correct: "a",
    solution: ['"明艳"修饰颜色/景色，"闪耀"修饰发光的银链，"漆黑"修饰内洞，均搭配恰当。'],
  }),
  pickChoice({
    id: "cn-u5-xvocab-007",
    unit_id: U5,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '"溪流时而宽，时而窄，时而缓，时而急"中，"时而……时而……"说明了？',
    options: [
      { id: "a", text: "溪流随着山势不断变化" },
      { id: "b", text: "溪流一直很宽", errorTag: "opposite" },
      { id: "c", text: "溪流停止流动", errorTag: "opposite" },
      { id: "d", text: "作者走得很慢", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['"时而……时而……"表示情况交替出现，说明溪流随山势忽宽忽窄、忽缓忽急地变化。'],
  }),
  pickChoice({
    id: "cn-u5-xvocab-008",
    unit_id: U5,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: '看拼音选词语：进了大门，绕过大殿，就来到有名的 cháng láng。',
    options: [
      { id: "a", text: "长廊" },
      { id: "b", text: "长郎", errorTag: "glyph_homophone" },
      { id: "c", text: "长榔", errorTag: "glyph_homophone" },
      { id: "d", text: "常廊", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"长廊"指又长又有顶的走廊。《颐和园》中长廊有七百多米长。注意"廊"是广字头。'],
  }),

  // ============================================================
  // 句子 · 修辞 / 过渡句 / 仿写
  // ============================================================
  pickChoice({
    id: "cn-u5-xrhet-001",
    unit_id: U5,
    skill_id: RHET,
    ability: ["sentence"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: '"昆明湖静得像一面镜子，绿得像一块碧玉。"这句话用了什么修辞？',
    options: [
      { id: "a", text: "比喻（把湖比作镜子和碧玉）" },
      { id: "b", text: "拟人（把物当人写）", errorTag: "wrong_rhetoric" },
      { id: "c", text: "夸张（故意放大）", errorTag: "wrong_rhetoric" },
      { id: "d", text: "反问（用问句表达肯定）", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['"静得像镜子""绿得像碧玉"是比喻，写出昆明湖又静又绿的特点。'],
  }),
  pickChoice({
    id: "cn-u5-xrhet-002",
    unit_id: U5,
    skill_id: RHET,
    ability: ["sentence"],
    difficulty: 3,
    stem: '"野花……像织不完的锦缎那么绵延，像天边的霞光那么耀眼，像高空的彩虹那么绚丽。"这句话用了什么修辞？',
    options: [
      { id: "a", text: "排比 + 比喻" },
      { id: "b", text: "只有拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "只有夸张", errorTag: "wrong_rhetoric" },
      { id: "d", text: "设问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['三个"像……那么……"结构相同、连用，是排比；又把野花比作锦缎、霞光、彩虹，是比喻。'],
  }),
  pickChoice({
    id: "cn-u5-xrhet-003",
    unit_id: U5,
    skill_id: RHET,
    ability: ["sentence"],
    difficulty: 3,
    stem: '"太阳好像负着重荷似的，一步一步，慢慢地努力上升。"这句话用了什么修辞？',
    options: [
      { id: "a", text: "拟人（把太阳当人，写它努力上升）" },
      { id: "b", text: "比喻", errorTag: "wrong_rhetoric" },
      { id: "c", text: "排比", errorTag: "wrong_rhetoric" },
      { id: "d", text: "反问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['"负着重荷""努力上升"把太阳当作人来写，是拟人，写出太阳上升的吃力和缓慢。'],
  }),
  pickChoice({
    id: "cn-u5-xrhet-004",
    unit_id: U5,
    skill_id: RHET,
    ability: ["sentence"],
    difficulty: 3,
    stem: '"这不是很伟大的奇观吗？"改成意思不变的陈述句是？',
    options: [
      { id: "a", text: "这是很伟大的奇观。" },
      { id: "b", text: "这不是很伟大的奇观。", errorTag: "sentence_meaning_flip" },
      { id: "c", text: "这是不是很伟大的奇观？", errorTag: "sentence_type_wrong" },
      { id: "d", text: "这真不伟大啊。", errorTag: "sentence_meaning_flip" },
    ],
    correct: "a",
    solution: ['反问句"这不是……吗？"表达的是肯定。改陈述句去掉"不""吗"和问号：这是很伟大的奇观。'],
  }),
  pickChoice({
    id: "cn-u5-xrhet-005",
    unit_id: U5,
    skill_id: RHET,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '照样子写句子。例：湖水绿得像一块碧玉。下面仿写最恰当的一句是？',
    options: [
      { id: "a", text: "枫叶红得像一团火。" },
      { id: "b", text: "枫叶很红很红。", errorTag: "no_rhetoric" },
      { id: "c", text: "枫叶是红色的。", errorTag: "no_rhetoric" },
      { id: "d", text: "枫叶在树上。", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['例句是"……得像……"的比喻句。A"红得像一团火"结构相同、用了比喻，仿写最恰当。'],
  }),
  pickChoice({
    id: "cn-u5-xrhet-006",
    unit_id: U5,
    skill_id: ORDER,
    ability: ["reading", "expression"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: '《颐和园》中"走完长廊，就来到了万寿山脚下"这句话的作用是？',
    options: [
      { id: "a", text: "过渡句，使游览地点的转换更自然" },
      { id: "b", text: "总起句，概括全文", errorTag: "wrong_function" },
      { id: "c", text: "中心句，点明主题", errorTag: "wrong_function" },
      { id: "d", text: "比喻句，写景物美", errorTag: "wrong_function" },
    ],
    correct: "a",
    solution: ['这句承上启下，把从"长廊"到"万寿山"的游览转换连接起来，是过渡句。'],
  }),
  pickChoice({
    id: "cn-u5-xrhet-007",
    unit_id: U5,
    skill_id: RHET,
    ability: ["sentence"],
    difficulty: 3,
    stem: '"太阳好像负着重荷似的，一步一步，慢慢地努力上升"中，加点的"一步一步""慢慢地""努力"好在哪里？',
    options: [
      { id: "a", text: "写出了太阳上升缓慢、吃力的过程，让画面更生动" },
      { id: "b", text: "说明太阳升得很快", errorTag: "opposite" },
      { id: "c", text: "说明作者看得不清楚", errorTag: "off_topic" },
      { id: "d", text: "没有什么作用", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['这几个词把太阳拟人化，细致地写出它一点点、缓慢、吃力地上升，画面如在眼前。'],
  }),

  // ============================================================
  // 游览顺序 / 写作顺序 (说明 · 概括)
  // ============================================================
  pickChoice({
    id: "cn-u5-xorder-001",
    unit_id: U5,
    skill_id: ORDER,
    ability: ["reading"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: '《记金华的双龙洞》作者的游览顺序是？',
    options: [
      { id: "a", text: "路上 → 洞口 → 外洞 → 孔隙 → 内洞 → 出洞" },
      { id: "b", text: "洞口 → 内洞 → 外洞 → 孔隙 → 出洞", errorTag: "order_wrong" },
      { id: "c", text: "外洞 → 孔隙 → 路上 → 内洞 → 出洞", errorTag: "order_wrong" },
      { id: "d", text: "路上 → 内洞 → 孔隙 → 外洞 → 出洞", errorTag: "order_wrong" },
    ],
    correct: "a",
    solution: ['课文按游览顺序写：路上→洞口→外洞→（过）孔隙→内洞→出洞。这是游记常用的游览顺序。'],
  }),
  pickChoice({
    id: "cn-u5-xorder-002",
    unit_id: U5,
    skill_id: ORDER,
    ability: ["reading"],
    difficulty: 3,
    stem: '《颐和园》的游览顺序是？',
    options: [
      { id: "a", text: "长廊 → 万寿山 → 昆明湖" },
      { id: "b", text: "昆明湖 → 长廊 → 万寿山", errorTag: "order_wrong" },
      { id: "c", text: "万寿山 → 昆明湖 → 长廊", errorTag: "order_wrong" },
      { id: "d", text: "长廊 → 昆明湖 → 万寿山", errorTag: "order_wrong" },
    ],
    correct: "a",
    solution: ['课文用过渡句"走完长廊，就来到了万寿山脚下""从万寿山下来，就是昆明湖"标明顺序：长廊→万寿山→昆明湖。'],
  }),
  pickChoice({
    id: "cn-u5-xorder-003",
    unit_id: U5,
    skill_id: ORDER,
    ability: ["reading"],
    difficulty: 3,
    stem: '《海上日出》第2、3自然段主要是按什么顺序来写的？',
    options: [
      { id: "a", text: "按太阳变化（升起）的顺序" },
      { id: "b", text: "按游览地点转换的顺序", errorTag: "order_wrong" },
      { id: "c", text: "按从早到晚一整天的顺序", errorTag: "order_wrong" },
      { id: "d", text: "按从上到下的方位顺序", errorTag: "order_wrong" },
    ],
    correct: "a",
    solution: ['《海上日出》写日出，是按太阳从"小半边脸"到"冲破云霞、跳出海面"的变化顺序写的。'],
  }),
  pickChoice({
    id: "cn-u5-xorder-004",
    unit_id: U5,
    skill_id: ORDER,
    ability: ["reading"],
    difficulty: 3,
    stem: '《记金华的双龙洞》重点写了哪一处景物？',
    options: [
      { id: "a", text: "外洞和内洞之间的孔隙" },
      { id: "b", text: "路上的映山红", errorTag: "not_focus" },
      { id: "c", text: "金华城", errorTag: "not_focus" },
      { id: "d", text: "罗店", errorTag: "not_focus" },
    ],
    correct: "a",
    solution: ['作者把最吸引人的"孔隙"作为重点，详写小船之小和过孔隙时的挤压感受。'],
  }),
  pickChoice({
    id: "cn-u5-xorder-005",
    unit_id: U5,
    skill_id: ORDER,
    ability: ["reading"],
    difficulty: 3,
    stem: '《七月的天山》是按什么顺序写景的？',
    options: [
      { id: "a", text: "按由外到里、向天山深处前进的游览顺序" },
      { id: "b", text: "按一年四季变化的顺序", errorTag: "order_wrong" },
      { id: "c", text: "按时间从早到晚的顺序", errorTag: "order_wrong" },
      { id: "d", text: "按颜色由浅到深的顺序", errorTag: "order_wrong" },
    ],
    correct: "a",
    solution: ['课文用"进入天山""再往里走""走进天山深处"等语句，按由外向里的游览顺序写景。'],
  }),

  // ============================================================
  // 阅读理解 · 短文一 登山观日 (5 题)
  // ============================================================
  pickChoice({
    id: "cn-u5-xread-001",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_A}\n\n🔹 第 1 题：短文主要写的是什么？`,
    options: [
      { id: "a", text: "在山顶看日出的过程和壮丽景象" },
      { id: "b", text: "怎样爬山", errorTag: "narrow_focus" },
      { id: "c", text: "松林的声音", errorTag: "detail_only" },
      { id: "d", text: "云彩的颜色", errorTag: "detail_only" },
    ],
    correct: "a",
    solution: ['短文从"等日出"到"太阳跳出云海"，写的是看日出的过程和壮丽景象。'],
  }),
  pickChoice({
    id: "cn-u5-xread-002",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_A}\n\n🔹 第 2 题：短文是按什么顺序写日出的？`,
    options: [
      { id: "a", text: "按太阳变化的顺序（红霞 → 小半边脸 → 跳出云海）" },
      { id: "b", text: "按地点转换的顺序", errorTag: "order_wrong" },
      { id: "c", text: "按四季变化的顺序", errorTag: "order_wrong" },
      { id: "d", text: "没有顺序", errorTag: "order_wrong" },
    ],
    correct: "a",
    solution: ['短文先写红霞，再写太阳冒出小半边脸，最后跳出云海，是按太阳变化的顺序写的。'],
  }),
  pickChoice({
    id: "cn-u5-xread-003",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_A}\n\n🔹 第 3 题："它好像背着很重的东西，一点一点地往上挪"用了什么修辞？`,
    options: [
      { id: "a", text: "拟人（把太阳当人写）" },
      { id: "b", text: "比喻", errorTag: "wrong_rhetoric" },
      { id: "c", text: "排比", errorTag: "wrong_rhetoric" },
      { id: "d", text: "夸张", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['"背着很重的东西""一点一点地往上挪"把太阳当人写，是拟人，写出太阳上升的吃力。'],
  }),
  pickChoice({
    id: "cn-u5-xread-004",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 3,
    stem: `${PASSAGE_A}\n\n🔹 第 4 题：太阳跳出云海后，把旁边的云彩染成了什么颜色？`,
    options: [
      { id: "a", text: "金色、紫色" },
      { id: "b", text: "黑色、灰色", errorTag: "not_in_text" },
      { id: "c", text: "蓝色、绿色", errorTag: "not_in_text" },
      { id: "d", text: "白色", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['短文写"把旁边的云彩染成了金色、紫色"。属直接信息检索。'],
  }),
  pickChoice({
    id: "cn-u5-xread-005",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_A}\n\n🔹 第 5 题：末句"这不就是大自然最伟大的奇观吗？"表达了作者怎样的感情？`,
    options: [
      { id: "a", text: "对日出奇观的赞美和惊叹" },
      { id: "b", text: "对早起的抱怨", errorTag: "off_topic" },
      { id: "c", text: "对松林的喜爱", errorTag: "narrow_focus" },
      { id: "d", text: "觉得日出很普通", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['这是反问句，表达的是强烈的肯定——日出是大自然最伟大的奇观，抒发赞美与惊叹之情。'],
  }),

  // ============================================================
  // 阅读理解 · 短文二 游天池 (5 题)
  // ============================================================
  pickChoice({
    id: "cn-u5-xread-006",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_B}\n\n🔹 第 1 题：短文是按什么顺序游天池的？`,
    options: [
      { id: "a", text: "按游览顺序（进入山口 → 再往里走 → 走到天池边）" },
      { id: "b", text: "按时间顺序（早 → 午 → 晚）", errorTag: "order_wrong" },
      { id: "c", text: "按四季顺序", errorTag: "order_wrong" },
      { id: "d", text: "按从高到低的顺序", errorTag: "order_wrong" },
    ],
    correct: "a",
    solution: ['短文用"进入山口""再往里走""走到天池边"标明由外向里的游览顺序。'],
  }),
  pickChoice({
    id: "cn-u5-xread-007",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_B}\n\n🔹 第 2 题："湖水绿得像一块碧玉，静得像一面镜子"用了什么修辞？`,
    options: [
      { id: "a", text: "比喻（把湖水比作碧玉、镜子）" },
      { id: "b", text: "拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "夸张", errorTag: "wrong_rhetoric" },
      { id: "d", text: "反问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['"绿得像碧玉""静得像镜子"是比喻，写出天池水又绿又静的特点。'],
  }),
  pickChoice({
    id: "cn-u5-xread-008",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 3,
    stem: `${PASSAGE_B}\n\n🔹 第 3 题："密密的枝叶像撑开的绿伞"中，把什么比作了"绿伞"？`,
    options: [
      { id: "a", text: "云杉密密的枝叶" },
      { id: "b", text: "天池的湖水", errorTag: "not_in_text" },
      { id: "c", text: "远处的雪峰", errorTag: "not_in_text" },
      { id: "d", text: "山口的凉风", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['"密密的枝叶像撑开的绿伞，挡住了火辣辣的太阳"，把云杉枝叶比作绿伞。'],
  }),
  pickChoice({
    id: "cn-u5-xread-009",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_B}\n\n🔹 第 4 题：短文说天池是"避暑的好地方"，主要原因是？`,
    options: [
      { id: "a", text: "山外是盛夏，山里却凉爽得像秋天" },
      { id: "b", text: "天池离家很近", errorTag: "not_in_text" },
      { id: "c", text: "可以游泳", errorTag: "not_in_text" },
      { id: "d", text: "有很多游客", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['末句"虽然山外是盛夏，可这里却凉爽得像秋天，真是个避暑的好地方"点明原因。'],
  }),
  pickChoice({
    id: "cn-u5-xread-010",
    unit_id: U5,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_B}\n\n🔹 第 5 题：这篇短文表达了作者怎样的感情？`,
    options: [
      { id: "a", text: "对天池美景的喜爱和留恋" },
      { id: "b", text: "对炎热天气的抱怨", errorTag: "off_topic" },
      { id: "c", text: "对长途旅行的厌倦", errorTag: "off_topic" },
      { id: "d", text: "对云杉林的害怕", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['全文写美景、写凉爽，末句"美得让人舍不得离开""避暑的好地方"流露喜爱与留恋。'],
  }),

  // ============================================================
  // 听写 (第五单元词语)
  // ============================================================
  dictation({
    id: "cn-u5-xdict-001",
    unit_id: U5,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "扩大",
    options: [
      { id: "a", text: "扩大" },
      { id: "b", text: "括大", errorTag: "glyph_homophone" },
      { id: "c", text: "阔大", errorTag: "glyph_homophone" },
      { id: "d", text: "扩达", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"扩大"：使范围变大。提手旁的"扩"。'],
  }),
  dictation({
    id: "cn-u5-xdict-002",
    unit_id: U5,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "杜鹃",
    options: [
      { id: "a", text: "杜鹃" },
      { id: "b", text: "杜娟", errorTag: "glyph_homophone" },
      { id: "c", text: "杜捐", errorTag: "glyph_homophone" },
      { id: "d", text: "牡鹃", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"杜鹃"既是鸟名，也是花名（映山红）。"鹃"是鸟字旁。'],
  }),
  dictation({
    id: "cn-u5-xdict-003",
    unit_id: U5,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "孔隙",
    options: [
      { id: "a", text: "孔隙" },
      { id: "b", text: "孔细", errorTag: "glyph_homophone" },
      { id: "c", text: "恐隙", errorTag: "glyph_homophone" },
      { id: "d", text: "孔郤", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"孔隙"指窟窿、缝隙。《双龙洞》中外洞到内洞要从孔隙乘小船过。"隙"是双耳旁加"小日小"。'],
  }),
  dictation({
    id: "cn-u5-xdict-004",
    unit_id: U5,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "琉璃",
    options: [
      { id: "a", text: "琉璃" },
      { id: "b", text: "流璃", errorTag: "glyph_homophone" },
      { id: "c", text: "琉离", errorTag: "glyph_homophone" },
      { id: "d", text: "硫璃", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"琉璃"：一种有色釉料。《颐和园》"黄色的琉璃瓦闪闪发光"。两字都是王字旁（玉）。'],
  }),
  dictation({
    id: "cn-u5-xdict-005",
    unit_id: U5,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "锦缎",
    options: [
      { id: "a", text: "锦缎" },
      { id: "b", text: "棉缎", errorTag: "glyph_homophone" },
      { id: "c", text: "锦段", errorTag: "glyph_homophone" },
      { id: "d", text: "绵缎", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"锦缎"：精美的丝织品。《七月的天山》"像织不完的锦缎"。"锦"金字旁、"缎"绞丝旁。'],
  }),
];
