/**
 * 语文 · C4B 第七单元（人物品质 + 古诗）期末备考包 (v0.36.74, 爸爸 2026-05-21).
 *
 * 严格依据人教版四下课本第七单元:
 *  - 22 古诗三首
 *    · 芙蓉楼送辛渐 [唐]王昌龄: 寒雨连江夜入吴，平明送客楚山孤。洛阳亲友如相问，
 *      一片冰心在玉壶。 注释: 平明=天刚亮; 冰心=像冰一样晶莹纯洁的心。要求默写。
 *    · 塞下曲 [唐]卢纶: 月黑雁飞高，单于夜遁逃。欲将轻骑逐，大雪满弓刀。
 *      注释: 单于(chán yú)=敌军首领; 骑(qí)=骑兵。
 *    · 墨梅 [元]王冕: 我家洗砚池头树，朵朵花开淡墨痕。不要人夸好颜色，只留清气满乾坤。
 *      注释: 乾坤(qián kūn)=天地间。
 *  - 23 黄继光: 1952 上甘岭战役, 597.9 高地; 动作"爬/站起来/举起右臂/猛扑/用胸膛堵枪口";
 *    名句"让祖国人民听我们胜利的消息吧!"; 子弹像冰雹; 照明弹"黑夜变成了白天"(环境衬托)。
 *  - 24 "诺曼底号"遇难记（雨果）: 哈尔威船长指挥救人(妇女先走/船员断后), 忠于职守、舍己
 *    救人、镇定自若; 结尾犹如铁铸随船沉入深渊。
 *  - 25 挑山工（冯骥才）: 泰山, 折尺形路线, 路程比游人多一倍却不慢; 哲理=脚踏实地、一个劲
 *    儿往前走、不三心二意、坚持不懈就能到达目标。
 *  - 语文园地: 从动作/语言描写感受人物品质; 表现品质心情的词语 临危不惧/彬彬有礼/焦躁不安/
 *    心急如焚/和蔼/慷慨/贤惠/悲戚。
 *
 * 题型对齐期中卷 + 古诗鉴赏 + 人物品质阅读。id 前缀 cn-u7-*。
 * 约定: 双引号字符串内的引文一律用全角“”，避免与 JS 字符串定界符冲突。
 */

import type { Question } from "../../core/types";
import { pickChoice, dictation } from "./questionHelpers";

const U7 = "C4B_U7_CHARACTER";
const PINYIN = "C4B_U7_PINYIN";
const VOCAB = "C4B_U7_VOCAB";
const POEM = "C4B_U7_POEM";
const CHAR = "C4B_U7_CHARACTER_SKILL";
const READ = "C4B_U7_READING";
const DICT = "C4B_U7_DICTATION";

// 阅读短文一：挑山工的话（课文原文片段，期末现代文阅读真实形式）
const PASSAGE_TIAO = `📖 短文一·挑山工（节选）

他说：“我们哪里有近道，还不是和你们走的同一条道？你们肩膀上没有挑子，是走得快，可是一路上东看西看，玩玩闹闹，总得停下来嘛！我们跟你们不一样，不像你们那么随便，高兴怎么就怎么。一步踩不实不行，更不能耽误工夫。我们得一个劲儿往前走。别看我们慢，走长了就跑到你们前边去了。”

我心悦诚服地点着头，感到这位山民的几句朴素的话，似乎包蕴着意味深长的哲理。`;

// 阅读短文二：平凡岗位上的人（原创，第七单元"人物品质"主题）
const PASSAGE_GUARD = `📖 短文二·路口的“活红灯”

我家小区门口有个十字路口，每天上学放学，总站着一位戴红袖章的老爷爷。无论刮风下雨，他都准时出现。一次下大雨，雨点像鞭子一样抽打着地面，同学们都躲到屋檐下，可老爷爷依旧站在路中央，一手举着小旗，一手张开，护送一个个孩子过马路。雨水顺着他的帽檐往下淌，他却像没事儿似的，一遍遍喊着：“慢点儿，别跑！”有人劝他：“雨这么大，歇会儿吧。”他摆摆手说：“孩子们的安全要紧，我多站一会儿不算什么。”望着他被雨水打湿的背影，我心里热乎乎的。`;

export const SEED_QUESTIONS_CHINESE_U7: Question[] = [
  // ============================================================
  // 字音 · 易错读音 / 多音字
  // ============================================================
  pickChoice({
    id: "cn-u7-py-001",
    unit_id: U7,
    skill_id: POEM,
    ability: ["phonics", "accumulation"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "《塞下曲》“单于夜遁逃”中，“单于”的读音是？",
    options: [
      { id: "a", text: "chán yú（古代匈奴等游牧民族的首领）" },
      { id: "b", text: "dān yú", errorTag: "polyphone_confusion" },
      { id: "c", text: "shàn yú", errorTag: "polyphone_confusion" },
      { id: "d", text: "chán yǔ", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['“单”是多音字：dān（单独）/ shàn（姓）/ chán（单于）。“单于”是首领，读 chán yú。'],
  }),
  pickChoice({
    id: "cn-u7-py-002",
    unit_id: U7,
    skill_id: POEM,
    ability: ["phonics", "accumulation"],
    difficulty: 3,
    stem: "《塞下曲》“欲将轻骑逐”中，“骑”的读音是？",
    options: [
      { id: "a", text: "qí（骑兵；骑马）" },
      { id: "b", text: "jì", errorTag: "polyphone_confusion" },
      { id: "c", text: "qǐ", errorTag: "tone_confusion" },
      { id: "d", text: "jī", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['现代汉语中“骑”统读 qí。“轻骑”指轻装的骑兵。'],
  }),
  pickChoice({
    id: "cn-u7-py-003",
    unit_id: U7,
    skill_id: POEM,
    ability: ["phonics", "accumulation"],
    difficulty: 2,
    stem: "《墨梅》“只留清气满乾坤”中，“乾坤”的读音和意思是？",
    options: [
      { id: "a", text: "qián kūn，指天地间" },
      { id: "b", text: "gān kūn，指干净", errorTag: "phonics_error" },
      { id: "c", text: "qián kǔn，指乾隆", errorTag: "phonics_error" },
      { id: "d", text: "gàn kūn，指能干", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['“乾坤”读 qián kūn，意思是天地之间。注意“乾”在这里不读 gān。'],
  }),
  pickChoice({
    id: "cn-u7-py-004",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: "《黄继光》“战士们屡次突击”中，“屡”的读音是？",
    options: [
      { id: "a", text: "lǚ（屡次、多次）" },
      { id: "b", text: "lóu", errorTag: "phonics_error" },
      { id: "c", text: "lǒu", errorTag: "phonics_error" },
      { id: "d", text: "lù", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['“屡”读 lǚ，意思是多次、一次又一次。“屡次突击”指多次冲击。'],
  }),
  pickChoice({
    id: "cn-u7-py-005",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    stem: "下面加点字读音全部正确的一组是？",
    options: [
      { id: "a", text: "摧毁（cuī） 冰雹（báo） 晕倒（yūn）" },
      { id: "b", text: "摧毁（cuǐ） 冰雹（báo） 晕倒（yūn）", errorTag: "phonics_error" },
      { id: "c", text: "摧毁（cuī） 冰雹（bào） 晕倒（yūn）", errorTag: "phonics_error" },
      { id: "d", text: "摧毁（cuī） 冰雹（báo） 晕倒（yùn）", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['摧 cuī、雹 báo、晕倒的“晕”读 yūn（昏倒）。“晕”另读 yùn（晕车、月晕）。'],
  }),
  pickChoice({
    id: "cn-u7-py-006",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "《“诺曼底号”遇难记》“轮机火炉被海浪呛得嘶嘶地直喘粗气”中，“呛”的读音是？",
    options: [
      { id: "a", text: "qiàng" },
      { id: "b", text: "qiāng", errorTag: "tone_confusion" },
      { id: "c", text: "cāng", errorTag: "phonics_error" },
      { id: "d", text: "qiǎng", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['这里“呛”读 qiàng，指水进入器官引起不适。“呛”另读 qiāng（呛咳）。'],
  }),
  pickChoice({
    id: "cn-u7-py-007",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: "下面加点字读音全部正确的一组是？",
    options: [
      { id: "a", text: "弥漫（mí） 秩序（zhì） 胸膛（táng）" },
      { id: "b", text: "弥漫（mǐ） 秩序（zhì） 胸膛（táng）", errorTag: "phonics_error" },
      { id: "c", text: "弥漫（mí） 秩序（chì） 胸膛（táng）", errorTag: "phonics_error" },
      { id: "d", text: "弥漫（mí） 秩序（zhì） 胸膛（tāng）", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['弥 mí、秩 zhì、膛 táng。均出自第七单元课文。'],
  }),
  pickChoice({
    id: "cn-u7-py-008",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“调”是多音字。《挑山工》“更不能耽误工夫”里没有“调”，但下面读音对应正确的一组是？",
    options: [
      { id: "a", text: "调动（diào） 调皮（tiáo）" },
      { id: "b", text: "调动（tiáo） 调皮（diào）", errorTag: "polyphone_confusion" },
      { id: "c", text: "调动（diào） 调皮（diào）", errorTag: "polyphone_confusion" },
      { id: "d", text: "调动（tiáo） 调皮（tiáo）", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“调”：diào（调动、调查、声调）/ tiáo（调皮、调和、调节）。'],
  }),
  pickChoice({
    id: "cn-u7-py-009",
    unit_id: U7,
    skill_id: POEM,
    ability: ["phonics", "accumulation"],
    difficulty: 2,
    stem: "《墨梅》“我家洗砚池头树”中，“砚”的读音是？",
    options: [
      { id: "a", text: "yàn（砚台，磨墨的文具）" },
      { id: "b", text: "yán", errorTag: "tone_confusion" },
      { id: "c", text: "xiàn", errorTag: "phonics_error" },
      { id: "d", text: "jiàn", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['“砚”读 yàn，指砚台。“洗砚池”是传说王羲之洗砚的池子。'],
  }),
  pickChoice({
    id: "cn-u7-py-010",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: "《挑山工》“他们肩上搭一根光溜溜的扁担”中，“担”在“扁担”和“担心”中分别读？",
    options: [
      { id: "a", text: "dàn（扁担，名词） / dān（担心，动词）" },
      { id: "b", text: "dān（扁担） / dàn（担心）", errorTag: "polyphone_confusion" },
      { id: "c", text: "dàn / dàn", errorTag: "polyphone_confusion" },
      { id: "d", text: "dān / dān", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“担”：dàn（扁担、一担水，名词/量词）/ dān（担心、担任，动词）。'],
  }),

  // ============================================================
  // 字形 · 错别字 / 形近字
  // ============================================================
  pickChoice({
    id: "cn-u7-gl-001",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    exam_priority: "MUST_BIG",
    stem: "选出没有错别字的一组（《黄继光》词语）：",
    options: [
      { id: "a", text: "营长 · 射击 · 子弹 · 爆炸" },
      { id: "b", text: "营长 · 射击 · 子弹 · 暴炸", errorTag: "glyph_homophone" },
      { id: "c", text: "营长 · 谢击 · 子弹 · 爆炸", errorTag: "glyph_homophone" },
      { id: "d", text: "宫长 · 射击 · 子弹 · 爆炸", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“爆炸”不是“暴炸”；“射击”不是“谢击”；“营长”不是“宫长”。A 全对。'],
  }),
  pickChoice({
    id: "cn-u7-gl-002",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面词语中有错别字的一项是？",
    options: [
      { id: "a", text: "履行 · 维持 · 秩序", errorTag: "glyph_correct" },
      { id: "b", text: "镇定自若 · 忠于职守 · 井然有续（序）", errorTag: "glyph_homophone" },
      { id: "c", text: "胸膛 · 摧毁 · 葬身鱼腹", errorTag: "glyph_correct" },
      { id: "d", text: "弥漫 · 剖开 · 失魂落魄", errorTag: "glyph_correct" },
    ],
    correct: "b",
    solution: ['B 中“井然有续”应为“井然有序”（次序的“序”）。本题选有错别字的一项。'],
  }),
  pickChoice({
    id: "cn-u7-gl-003",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "形近字组词，全部正确的一组是？",
    options: [
      { id: "a", text: "炸（爆炸）— 作（作业）；遣（派遣）— 遗（遗失）" },
      { id: "b", text: "炸（爆作）— 作（爆炸）；遣（派遣）— 遗（遗失）", errorTag: "form_similar" },
      { id: "c", text: "炸（爆炸）— 作（作业）；遣（遗失）— 遗（派遣）", errorTag: "form_similar" },
      { id: "d", text: "炸（爆炸）— 作（作业）；遣（派遗）— 遗（遣失）", errorTag: "form_similar" },
    ],
    correct: "a",
    solution: ['“炸”火字旁（爆炸）；“作”单人旁（作业）。“遣”（派遣）和“遗”（遗失）字形相近、易混。'],
  }),
  pickChoice({
    id: "cn-u7-gl-004",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "看拼音写词语：哈尔威船长一生都要求自己 zhōng yú zhí shǒu（忠于职守）。",
    options: [
      { id: "a", text: "忠于职守" },
      { id: "b", text: "衷于职守", errorTag: "glyph_homophone" },
      { id: "c", text: "忠于职手", errorTag: "glyph_homophone" },
      { id: "d", text: "忠于织守", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“忠于职守”指忠诚地坚守自己的岗位。“忠”心字底；“职守”是职责岗位。'],
  }),
  pickChoice({
    id: "cn-u7-gl-005",
    unit_id: U7,
    skill_id: POEM,
    ability: ["glyph", "accumulation"],
    difficulty: 3,
    stem: "默写《芙蓉楼送辛渐》，下面书写完全正确的一句是？",
    options: [
      { id: "a", text: "一片冰心在玉壶" },
      { id: "b", text: "一片冰心在玉湖", errorTag: "glyph_homophone" },
      { id: "c", text: "一片冰新在玉壶", errorTag: "glyph_homophone" },
      { id: "d", text: "一篇冰心在玉壶", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“一片冰心在玉壶”。“玉壶”不是“玉湖”；“冰心”不是“冰新”；量词是“一片”不是“一篇”。'],
  }),
  pickChoice({
    id: "cn-u7-gl-006",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "看拼音写词语：救援工作进行得 jǐng rán yǒu xù（井然有序）。",
    options: [
      { id: "a", text: "井然有序" },
      { id: "b", text: "井然有绪", errorTag: "glyph_homophone" },
      { id: "c", text: "景然有序", errorTag: "glyph_homophone" },
      { id: "d", text: "井燃有序", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“井然有序”形容整齐而有条理。“序”是次序，不是“绪”（情绪）。'],
  }),
  pickChoice({
    id: "cn-u7-gl-007",
    unit_id: U7,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "下面书写完全正确的一项是（第七单元词语）？",
    options: [
      { id: "a", text: "泰山 · 拐杖 · 拘束 · 蕴含" },
      { id: "b", text: "泰山 · 拐仗 · 拘束 · 蕴含", errorTag: "glyph_homophone" },
      { id: "c", text: "泰山 · 拐杖 · 拘束 · 韵含", errorTag: "glyph_homophone" },
      { id: "d", text: "秦山 · 拐杖 · 拘束 · 蕴含", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“拐杖”不是“拐仗”；“蕴含”不是“韵含”；“泰山”不是“秦山”。A 全对。'],
  }),

  // ============================================================
  // 古诗三首 · 字词义 / 诗意 / 品格 / 默写
  // ============================================================
  pickChoice({
    id: "cn-u7-poem-001",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "《芙蓉楼送辛渐》的作者和朝代是？",
    options: [
      { id: "a", text: "唐代 · 王昌龄" },
      { id: "b", text: "唐代 · 王维", errorTag: "author_confusion" },
      { id: "c", text: "宋代 · 王昌龄", errorTag: "dynasty_confusion" },
      { id: "d", text: "元代 · 王冕", errorTag: "author_confusion" },
    ],
    correct: "a",
    solution: ['《芙蓉楼送辛渐》是唐代诗人王昌龄的送别诗。'],
  }),
  pickChoice({
    id: "cn-u7-poem-002",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation", "reading"],
    difficulty: 3,
    stem: "《芙蓉楼送辛渐》“平明送客楚山孤”中，“平明”的意思是？",
    options: [
      { id: "a", text: "天刚亮的时候" },
      { id: "b", text: "平静明亮", errorTag: "word_misunderstand" },
      { id: "c", text: "公平明白", errorTag: "word_misunderstand" },
      { id: "d", text: "平时明天", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['注释：“平明”指天刚亮。这句写清晨送别友人辛渐。'],
  }),
  pickChoice({
    id: "cn-u7-poem-003",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "《芙蓉楼送辛渐》“一片冰心在玉壶”表达了诗人怎样的品格？",
    options: [
      { id: "a", text: "表明自己心地纯洁、不与世俗同流的高洁品格" },
      { id: "b", text: "说明天气很冷", errorTag: "literal_misread" },
      { id: "c", text: "想喝一壶酒", errorTag: "off_topic" },
      { id: "d", text: "舍不得离开洛阳", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['“冰心”指像冰一样晶莹纯洁的心。诗人借此告诉亲友：自己依然清白正直、不改高洁品格。'],
  }),
  pickChoice({
    id: "cn-u7-poem-004",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation"],
    difficulty: 3,
    stem: "《塞下曲》的作者卢纶是哪个朝代的诗人？",
    options: [
      { id: "a", text: "唐代" },
      { id: "b", text: "宋代", errorTag: "dynasty_confusion" },
      { id: "c", text: "元代", errorTag: "dynasty_confusion" },
      { id: "d", text: "明代", errorTag: "dynasty_confusion" },
    ],
    correct: "a",
    solution: ['《塞下曲》是唐代诗人卢纶的作品，描写边塞将士的英勇。'],
  }),
  pickChoice({
    id: "cn-u7-poem-005",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: "《塞下曲》“月黑雁飞高，单于夜遁逃”描写的情景是？",
    options: [
      { id: "a", text: "没有月光的夜里，敌人首领趁黑逃跑" },
      { id: "b", text: "月亮很黑，大雁不敢飞", errorTag: "word_misunderstand" },
      { id: "c", text: "将军在赏月看大雁", errorTag: "off_topic" },
      { id: "d", text: "单于在打猎", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['“月黑”指没有月光的黑夜；“单于夜遁逃”指敌军首领趁夜逃跑。写出敌人狼狈逃窜。'],
  }),
  pickChoice({
    id: "cn-u7-poem-006",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "《塞下曲》“欲将轻骑逐，大雪满弓刀”表现了将士怎样的精神？",
    options: [
      { id: "a", text: "不畏严寒、英勇无畏、奋勇杀敌" },
      { id: "b", text: "怕冷不敢追击", errorTag: "opposite" },
      { id: "c", text: "喜欢在雪地里玩", errorTag: "off_topic" },
      { id: "d", text: "急着回家过年", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['将军正要率轻骑追敌，大雪落满弓刀也毫不退缩，表现将士不畏严寒、英勇善战的精神。'],
  }),
  pickChoice({
    id: "cn-u7-poem-007",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation"],
    difficulty: 3,
    stem: "《墨梅》的作者王冕是哪个朝代的人？",
    options: [
      { id: "a", text: "元代" },
      { id: "b", text: "唐代", errorTag: "dynasty_confusion" },
      { id: "c", text: "宋代", errorTag: "dynasty_confusion" },
      { id: "d", text: "明代", errorTag: "dynasty_confusion" },
    ],
    correct: "a",
    solution: ['《墨梅》是元代诗人、画家王冕的题画诗。'],
  }),
  pickChoice({
    id: "cn-u7-poem-008",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: "《墨梅》“不要人夸好颜色，只留清气满乾坤”表达了诗人怎样的志向？",
    options: [
      { id: "a", text: "不慕虚名、鄙视流俗，要保持高洁的品格" },
      { id: "b", text: "希望别人夸他画得好", errorTag: "opposite" },
      { id: "c", text: "喜欢梅花的颜色", errorTag: "narrow_focus" },
      { id: "d", text: "想把梅花卖个好价钱", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['诗人借墨梅“不要人夸”“只留清气”托物言志，表达自己不图虚名、坚守高洁品格的志向。'],
  }),
  pickChoice({
    id: "cn-u7-poem-009",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation"],
    difficulty: 3,
    stem: "下面对《墨梅》写作方法的判断，正确的是？",
    options: [
      { id: "a", text: "托物言志（借墨梅表达自己的志向品格）" },
      { id: "b", text: "借景抒情写思乡", errorTag: "method_wrong" },
      { id: "c", text: "叙事写一件事", errorTag: "method_wrong" },
      { id: "d", text: "说明梅花的种类", errorTag: "method_wrong" },
    ],
    correct: "a",
    solution: ['《墨梅》是题画诗，借梅花的清香高洁寄托诗人自己的志向，属于“托物言志”。'],
  }),
  pickChoice({
    id: "cn-u7-poem-010",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation"],
    difficulty: 3,
    stem: "默写填空：洛阳亲友如相问，（  ）。",
    options: [
      { id: "a", text: "一片冰心在玉壶" },
      { id: "b", text: "大雪满弓刀", errorTag: "poem_mismatch" },
      { id: "c", text: "只留清气满乾坤", errorTag: "poem_mismatch" },
      { id: "d", text: "平明送客楚山孤", errorTag: "poem_mismatch" },
    ],
    correct: "a",
    solution: ['出自《芙蓉楼送辛渐》：“洛阳亲友如相问，一片冰心在玉壶。”'],
  }),
  pickChoice({
    id: "cn-u7-poem-011",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation"],
    difficulty: 3,
    stem: "默写填空：欲将轻骑逐，（  ）。",
    options: [
      { id: "a", text: "大雪满弓刀" },
      { id: "b", text: "一片冰心在玉壶", errorTag: "poem_mismatch" },
      { id: "c", text: "单于夜遁逃", errorTag: "poem_mismatch" },
      { id: "d", text: "只留清气满乾坤", errorTag: "poem_mismatch" },
    ],
    correct: "a",
    solution: ['出自《塞下曲》：“欲将轻骑逐，大雪满弓刀。”'],
  }),
  pickChoice({
    id: "cn-u7-poem-012",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: "《墨梅》“朵朵花开淡墨痕”中，梅花为什么是“淡墨痕”？",
    options: [
      { id: "a", text: "因为这是用淡墨画出来的梅花（题画诗）" },
      { id: "b", text: "因为梅花被墨水弄脏了", errorTag: "literal_misread" },
      { id: "c", text: "因为天黑看不清", errorTag: "off_topic" },
      { id: "d", text: "因为梅花本来就是黑色的", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['《墨梅》是题在水墨画上的诗，画中的梅花用淡墨点染，所以“朵朵花开淡墨痕”。'],
  }),
  pickChoice({
    id: "cn-u7-poem-013",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation"],
    difficulty: 3,
    stem: "下面三首古诗，属于送别诗的是？",
    options: [
      { id: "a", text: "《芙蓉楼送辛渐》" },
      { id: "b", text: "《塞下曲》", errorTag: "category_confusion" },
      { id: "c", text: "《墨梅》", errorTag: "category_confusion" },
      { id: "d", text: "三首都是送别诗", errorTag: "category_confusion" },
    ],
    correct: "a",
    solution: ['《芙蓉楼送辛渐》是送别诗；《塞下曲》写边塞军旅；《墨梅》是题画言志诗。'],
  }),
  pickChoice({
    id: "cn-u7-poem-014",
    unit_id: U7,
    skill_id: POEM,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: "《芙蓉楼送辛渐》“寒雨连江夜入吴”中，“寒雨”渲染了怎样的气氛？",
    options: [
      { id: "a", text: "凄凉、孤寂的离别气氛" },
      { id: "b", text: "欢乐、热闹的气氛", errorTag: "opposite" },
      { id: "c", text: "紧张的战斗气氛", errorTag: "off_topic" },
      { id: "d", text: "温暖的春天气氛", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['“寒雨连江”写出秋夜冷雨笼罩江天，渲染出送别时凄凉、孤寂的气氛，为下句“楚山孤”做铺垫。'],
  }),

  // ============================================================
  // 人物品质（黄继光 · 诺曼底号 · 挑山工）
  // ============================================================
  pickChoice({
    id: "cn-u7-char-001",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "《黄继光》中“他张开双臂，向喷射着火舌的火力点猛扑上去，用自己的胸膛堵住了敌人的枪口”，主要通过什么描写表现人物？",
    options: [
      { id: "a", text: "动作描写（张开、猛扑、堵住），表现黄继光的英勇献身" },
      { id: "b", text: "外貌描写", errorTag: "wrong_method" },
      { id: "c", text: "环境描写", errorTag: "wrong_method" },
      { id: "d", text: "心理描写", errorTag: "wrong_method" },
    ],
    correct: "a",
    solution: ['“张开双臂”“猛扑上去”“堵住”都是动作，从动作描写中可以感受到黄继光不怕牺牲、英勇顽强的英雄气概。'],
  }),
  pickChoice({
    id: "cn-u7-char-002",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["reading"],
    difficulty: 3,
    stem: "《黄继光》中“让祖国人民听我们胜利的消息吧!”这句话主要表现了黄继光的？",
    options: [
      { id: "a", text: "对祖国和人民的热爱，以及必胜的决心" },
      { id: "b", text: "想出名", errorTag: "off_topic" },
      { id: "c", text: "害怕牺牲", errorTag: "opposite" },
      { id: "d", text: "想休息", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['这句话是黄继光出发前喊的，表现他爱国爱民、为胜利不惜牺牲的崇高精神。'],
  }),
  pickChoice({
    id: "cn-u7-char-003",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "《“诺曼底号”遇难记》中，哈尔威船长下令“妇女先走，其他乘客跟上，船员断后”，从中可以看出他怎样的品质？",
    options: [
      { id: "a", text: "临危不乱、舍己救人、保护弱者" },
      { id: "b", text: "胆小怕事", errorTag: "opposite" },
      { id: "c", text: "只顾自己逃命", errorTag: "opposite" },
      { id: "d", text: "做事没有条理", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['危急时刻，船长镇定地安排妇女先走、船员断后，把生的希望留给别人，表现他临危不乱、舍己救人。'],
  }),
  pickChoice({
    id: "cn-u7-char-004",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["reading"],
    difficulty: 4,
    stem: "《“诺曼底号”遇难记》结尾，哈尔威船长“犹如铁铸，纹丝不动，随着轮船一起沉入了深渊”，这表现了他？",
    options: [
      { id: "a", text: "忠于职守、与船共存亡的崇高精神" },
      { id: "b", text: "来不及逃跑", errorTag: "word_misunderstand" },
      { id: "c", text: "不会游泳", errorTag: "off_topic" },
      { id: "d", text: "舍不得轮船", errorTag: "narrow_focus" },
    ],
    correct: "a",
    solution: ['船长本可以脱险，却选择与船共存亡，“一生都要求自己忠于职守，履行做人之道”，表现他崇高的责任感。'],
  }),
  pickChoice({
    id: "cn-u7-char-005",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "《挑山工》中，挑山工登山路程比游人多一倍，却常常走在游人前面。其中包含的哲理是？",
    options: [
      { id: "a", text: "脚踏实地、目标专一、坚持不懈，就能成功" },
      { id: "b", text: "走得越慢越好", errorTag: "word_misunderstand" },
      { id: "c", text: "挑山工有近道", errorTag: "opposite" },
      { id: "d", text: "游人体力太差", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['挑山工“一个劲儿往前走”“一步踩不实不行”，不像游人东看西看、走走停停。说明做事要脚踏实地、目标专一、坚持不懈。'],
  }),
  pickChoice({
    id: "cn-u7-char-006",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["reading"],
    difficulty: 3,
    stem: "《挑山工》中，挑山工为什么不走直线，而走“折尺形”的路线？",
    options: [
      { id: "a", text: "这样能使挑的东西不碰台阶，还能省些力气" },
      { id: "b", text: "因为他们迷路了", errorTag: "off_topic" },
      { id: "c", text: "因为折尺形路更短", errorTag: "opposite" },
      { id: "d", text: "因为他们喜欢绕路", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['课文说：折尺形路线能使挂在扁担前头的东西不碰台阶，还可以省些力气；若直上走，膝盖会受不住。'],
  }),
  pickChoice({
    id: "cn-u7-char-007",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["reading"],
    difficulty: 3,
    stem: "本单元的主题是从人物的语言、动作描写中感受人物品质。下面理解不正确的一项是？",
    options: [
      { id: "a", text: "只要写了人物，就一定能表现品质", errorTag: "logic_wrong" },
      { id: "b", text: "动作描写能让我们感受到人物的品质" },
      { id: "c", text: "语言描写能看出人物的特点" },
      { id: "d", text: "可以从多个方面写出人物的特点" },
    ],
    correct: "a",
    solution: ['本题选理解不正确的一项。A 太绝对：要通过有特点的语言、动作等描写才能表现品质，并非“写了人物就一定能”。'],
  }),
  pickChoice({
    id: "cn-u7-char-008",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["reading"],
    difficulty: 3,
    stem: "下面人物和他们的主要品质，搭配正确的一项是？",
    options: [
      { id: "a", text: "黄继光——英勇献身；哈尔威船长——忠于职守；挑山工——脚踏实地" },
      { id: "b", text: "黄继光——忠于职守；哈尔威船长——脚踏实地；挑山工——英勇献身", errorTag: "match_wrong" },
      { id: "c", text: "黄继光——脚踏实地；哈尔威船长——英勇献身；挑山工——忠于职守", errorTag: "match_wrong" },
      { id: "d", text: "三个人品质完全一样", errorTag: "match_wrong" },
    ],
    correct: "a",
    solution: ['黄继光用胸膛堵枪口（英勇献身）；哈尔威船长与船共存亡（忠于职守）；挑山工一个劲儿往前走（脚踏实地）。'],
  }),

  // ============================================================
  // 句子 · 比喻 / 环境描写作用 / 词语
  // ============================================================
  pickChoice({
    id: "cn-u7-sent-001",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["sentence"],
    difficulty: 3,
    stem: "《黄继光》“火力点里的敌人把机枪对准黄继光，子弹像冰雹一样射过来”用了什么修辞？有什么作用？",
    options: [
      { id: "a", text: "比喻；写出子弹又密又猛，突出处境危险、黄继光的英勇" },
      { id: "b", text: "拟人；说明子弹会思考", errorTag: "wrong_rhetoric" },
      { id: "c", text: "夸张；说明真的下冰雹了", errorTag: "literal_misread" },
      { id: "d", text: "排比；列举三件事", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['把子弹比作冰雹，是比喻，写出子弹密集猛烈，衬托出环境危险和黄继光不顾生死、顽强前进的英雄气概。'],
  }),
  pickChoice({
    id: "cn-u7-sent-002",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["sentence", "reading"],
    difficulty: 4,
    stem: "《黄继光》“几发照明弹升上天空，黑夜变成了白天。炮弹在他们周围爆炸。”这段环境描写的作用是？",
    options: [
      { id: "a", text: "渲染战斗的紧张和危险，衬托黄继光等人的英勇" },
      { id: "b", text: "说明那天晚上天气好", errorTag: "off_topic" },
      { id: "c", text: "没有作用", errorTag: "off_topic" },
      { id: "d", text: "说明照明弹很漂亮", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['“黑夜变成白天”“炮弹爆炸”写出战场环境危险紧张，烘托出战士冒死前进的英勇，环境描写为表现人物服务。'],
  }),
  pickChoice({
    id: "cn-u7-sent-003",
    unit_id: U7,
    skill_id: CHAR,
    ability: ["sentence"],
    difficulty: 3,
    stem: "《“诺曼底号”遇难记》“他犹如铁铸，纹丝不动”用了什么修辞？",
    options: [
      { id: "a", text: "比喻（把船长比作铁铸的雕像）" },
      { id: "b", text: "拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "排比", errorTag: "wrong_rhetoric" },
      { id: "d", text: "反问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['“犹如铁铸”把船长比作铁铸的雕像，写出他临危不惧、坚定不动的形象。'],
  }),
  pickChoice({
    id: "cn-u7-vocab-001",
    unit_id: U7,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "下面词语中，可以用来形容哈尔威船长的一组是？",
    options: [
      { id: "a", text: "临危不惧 · 镇定自若 · 舍己救人" },
      { id: "b", text: "焦躁不安 · 惊慌失措 · 贪生怕死", errorTag: "antonym_misuse" },
      { id: "c", text: "彬彬有礼 · 和蔼可亲 · 贤惠", errorTag: "word_mismatch" },
      { id: "d", text: "心急如焚 · 悲戚 · 拘束", errorTag: "word_mismatch" },
    ],
    correct: "a",
    solution: ['哈尔威船长面对危难临危不惧、镇定自若，把生的希望让给别人，是舍己救人。'],
  }),
  pickChoice({
    id: "cn-u7-vocab-002",
    unit_id: U7,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "“临危不惧”的意思是？",
    options: [
      { id: "a", text: "遇到危险一点儿也不害怕" },
      { id: "b", text: "遇到危险非常害怕", errorTag: "antonym_misuse" },
      { id: "c", text: "害怕临时的危险", errorTag: "word_misunderstand" },
      { id: "d", text: "面临考试不紧张", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['“惧”是害怕；“临危不惧”指面临危险毫不畏惧，形容人勇敢镇定。'],
  }),
  pickChoice({
    id: "cn-u7-vocab-003",
    unit_id: U7,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "选词填空：他被关在拘留所里，受到无休止的折磨，看守人员每隔十分钟就来开一次灯，使他无法（  ）。（休息 / 休戚）",
    options: [
      { id: "a", text: "休息" },
      { id: "b", text: "休戚（指欢乐和忧愁）", errorTag: "synonym_misuse" },
      { id: "c", text: "休克", errorTag: "word_misunderstand" },
      { id: "d", text: "休养", errorTag: "synonym_misuse" },
    ],
    correct: "a",
    solution: ['这里指无法睡觉、歇息，用“休息”。“休戚”指欢乐和忧愁（休戚相关）。（语段出自阅读链接《祖国，我终于回来了》）'],
  }),

  // ============================================================
  // 阅读理解 · 短文一 挑山工节选 (5 题)
  // ============================================================
  pickChoice({
    id: "cn-u7-read-001",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_TIAO}\n\n🔹 第 1 题：挑山工说自己能走到游人前面，最主要的原因是？`,
    options: [
      { id: "a", text: "他们一个劲儿往前走，不东看西看、不停下来" },
      { id: "b", text: "他们走的是近道", errorTag: "opposite" },
      { id: "c", text: "他们力气比游人大", errorTag: "not_in_text" },
      { id: "d", text: "游人故意走得慢", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['挑山工说“我们得一个劲儿往前走”，不像游人“东看西看，玩玩闹闹，总得停下来”，所以反而走在前面。'],
  }),
  pickChoice({
    id: "cn-u7-read-002",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_TIAO}\n\n🔹 第 2 题：“一步踩不实不行”这句话说明挑山工做事？`,
    options: [
      { id: "a", text: "脚踏实地、认真稳当" },
      { id: "b", text: "粗心大意", errorTag: "opposite" },
      { id: "c", text: "走得很慢", errorTag: "narrow_focus" },
      { id: "d", text: "胆子很小", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['“一步踩不实不行”说明挑山工每一步都踩稳、不马虎，体现脚踏实地、认真稳当的态度。'],
  }),
  pickChoice({
    id: "cn-u7-read-003",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading", "vocabulary"],
    difficulty: 4,
    stem: `${PASSAGE_TIAO}\n\n🔹 第 3 题：“我心悦诚服地点着头”中，“心悦诚服”的意思是？`,
    options: [
      { id: "a", text: "从心里佩服、真诚地信服" },
      { id: "b", text: "心里很不高兴", errorTag: "antonym_misuse" },
      { id: "c", text: "假装服气", errorTag: "antonym_misuse" },
      { id: "d", text: "心情愉快", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['“心悦诚服”指从心里高兴地、真诚地信服。作者听了挑山工的话，由衷地佩服其中的道理。'],
  }),
  pickChoice({
    id: "cn-u7-read-004",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_TIAO}\n\n🔹 第 4 题：挑山工“朴素的话”中包蕴的“意味深长的哲理”是？`,
    options: [
      { id: "a", text: "做事要目标专一、脚踏实地、坚持不懈，才能后来居上" },
      { id: "b", text: "走路一定要走折尺形", errorTag: "narrow_focus" },
      { id: "c", text: "登山不能带挑子", errorTag: "off_topic" },
      { id: "d", text: "游山玩水最重要", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['挑山工“一个劲儿往前走”、不三心二意，启示我们：认准目标、脚踏实地、坚持不懈，就能走在前面、取得成功。'],
  }),
  pickChoice({
    id: "cn-u7-read-005",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_TIAO}\n\n🔹 第 5 题：作者后来画了一幅挑山工登山图挂在书桌前，是因为？`,
    options: [
      { id: "a", text: "他需要挑山工脚踏实地、坚持不懈的精神激励自己" },
      { id: "b", text: "这幅画很值钱", errorTag: "off_topic" },
      { id: "c", text: "他喜欢画画", errorTag: "narrow_focus" },
      { id: "d", text: "为了纪念去泰山旅游", errorTag: "narrow_focus" },
    ],
    correct: "a",
    solution: ['作者说“因为我需要它”，是因为挑山工脚踏实地、坚持向前的精神值得自己时时学习、激励自己。'],
  }),

  // ============================================================
  // 阅读理解 · 短文二 路口的"活红灯" (5 题)
  // ============================================================
  pickChoice({
    id: "cn-u7-read-006",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_GUARD}\n\n🔹 第 1 题：短文主要写了一位老爷爷的什么事？`,
    options: [
      { id: "a", text: "他无论刮风下雨都坚持在路口护送孩子过马路" },
      { id: "b", text: "他在路口卖小旗", errorTag: "off_topic" },
      { id: "c", text: "他在躲雨", errorTag: "opposite" },
      { id: "d", text: "他在路口散步", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['短文写老爷爷每天准时出现、风雨无阻地护送孩子过马路，重点写大雨中他坚守岗位。'],
  }),
  pickChoice({
    id: "cn-u7-read-007",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_GUARD}\n\n🔹 第 2 题："雨点像鞭子一样抽打着地面"用了什么修辞？作用是？`,
    options: [
      { id: "a", text: "比喻；写出雨下得又大又猛，衬托老爷爷坚守的可贵" },
      { id: "b", text: "拟人；说明雨会打人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "夸张；说明真有鞭子", errorTag: "literal_misread" },
      { id: "d", text: "排比", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['把雨点比作鞭子，是比喻，写出雨势大而猛；这样恶劣的天气更衬托出老爷爷坚守岗位的可贵。'],
  }),
  pickChoice({
    id: "cn-u7-read-008",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_GUARD}\n\n🔹 第 3 题：从老爷爷的语言"孩子们的安全要紧，我多站一会儿不算什么"，可以看出他？`,
    options: [
      { id: "a", text: "尽职尽责、心里装着孩子、无私奉献" },
      { id: "b", text: "怕麻烦", errorTag: "opposite" },
      { id: "c", text: "想得到表扬", errorTag: "off_topic" },
      { id: "d", text: "只是随便说说", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['这句语言描写表明老爷爷把孩子的安全放在第一位、不怕辛苦，体现他尽职尽责、无私奉献的品质。'],
  }),
  pickChoice({
    id: "cn-u7-read-009",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_GUARD}\n\n🔹 第 4 题：短文为什么把老爷爷称为路口的"活红灯"？`,
    options: [
      { id: "a", text: "因为他像红绿灯一样指挥交通、守护孩子的安全" },
      { id: "b", text: "因为他穿着红衣服", errorTag: "literal_misread" },
      { id: "c", text: "因为他脸很红", errorTag: "off_topic" },
      { id: "d", text: "因为他会发光", errorTag: "literal_misread" },
    ],
    correct: "a",
    solution: ['老爷爷举旗护送、指挥孩子安全过马路，作用像红绿灯，又是活生生的人，所以亲切地称他“活红灯”。'],
  }),
  pickChoice({
    id: "cn-u7-read-010",
    unit_id: U7,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_GUARD}\n\n🔹 第 5 题：结尾"望着他被雨水打湿的背影，我心里热乎乎的"表达了"我"怎样的感情？`,
    options: [
      { id: "a", text: "对老爷爷的敬佩和感激" },
      { id: "b", text: "对下雨的讨厌", errorTag: "off_topic" },
      { id: "c", text: "对迟到的着急", errorTag: "off_topic" },
      { id: "d", text: "觉得老爷爷很可怜", errorTag: "narrow_focus" },
    ],
    correct: "a",
    solution: ['“心里热乎乎的”是被老爷爷尽职奉献的精神打动，表达对他的敬佩和感激之情。'],
  }),

  // ============================================================
  // 听写 (第七单元词语)
  // ============================================================
  dictation({
    id: "cn-u7-dict-001",
    unit_id: U7,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "爆炸",
    options: [
      { id: "a", text: "爆炸" },
      { id: "b", text: "暴炸", errorTag: "glyph_homophone" },
      { id: "c", text: "爆诈", errorTag: "glyph_homophone" },
      { id: "d", text: "瀑炸", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“爆炸”两字都是火字旁，与火、突然破裂有关。不要写成“暴”。'],
  }),
  dictation({
    id: "cn-u7-dict-002",
    unit_id: U7,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "维持",
    options: [
      { id: "a", text: "维持" },
      { id: "b", text: "维诗", errorTag: "glyph_homophone" },
      { id: "c", text: "唯持", errorTag: "glyph_homophone" },
      { id: "d", text: "维待", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“维持”指保持、使继续存在。“维”绞丝旁，“持”提手旁。'],
  }),
  dictation({
    id: "cn-u7-dict-003",
    unit_id: U7,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "胸膛",
    options: [
      { id: "a", text: "胸膛" },
      { id: "b", text: "胸堂", errorTag: "glyph_homophone" },
      { id: "c", text: "凶膛", errorTag: "glyph_homophone" },
      { id: "d", text: "胸唐", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“胸膛”指胸部。两字都是月字旁（与身体有关）。黄继光用胸膛堵住敌人枪口。'],
  }),
  dictation({
    id: "cn-u7-dict-004",
    unit_id: U7,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "乾坤",
    options: [
      { id: "a", text: "乾坤" },
      { id: "b", text: "乾昆", errorTag: "glyph_homophone" },
      { id: "c", text: "虔坤", errorTag: "glyph_homophone" },
      { id: "d", text: "钱坤", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“乾坤”（qián kūn）指天地间。《墨梅》“只留清气满乾坤”。'],
  }),
  dictation({
    id: "cn-u7-dict-005",
    unit_id: U7,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "玉壶",
    options: [
      { id: "a", text: "玉壶" },
      { id: "b", text: "玉葫", errorTag: "glyph_homophone" },
      { id: "c", text: "玉湖", errorTag: "glyph_homophone" },
      { id: "d", text: "玉胡", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“玉壶”指玉做的壶。《芙蓉楼送辛渐》“一片冰心在玉壶”。不要写成“玉湖”。'],
  }),
];
