/**
 * 语文 · C4B 第六单元（成长故事 + 文言文）期末备考包 (v0.36.74, 爸爸 2026-05-21).
 *
 * 严格依据人教版四下课本第六单元:
 *  - 18 文言文二则
 *    · 囊萤夜读《晋书·车胤传》: "胤恭勤不倦，博学多通。家贫不常得油，夏月则练囊
 *      盛数十萤火以照书，以夜继日焉。" 注释: 恭勤=肃敬勤勉; 通=通晓; 练囊=白绢口袋。
 *    · 铁杵成针 宋·祝穆《方舆胜览·眉州》: "磨针溪，在象耳山下。世传李太白读书山中，
 *      未成，弃去。过是溪，逢老媪方磨铁杵。问之，曰：'欲作针。'太白感其意，还卒业。"
 *      注释: 是=这; 方=正在; 感其意=被她的意志感动; 还卒业=回去完成了学业。
 *  - 19 小英雄雨来（节选，管桦）: 还乡河/芦花村/十二岁雨来; 6 部分(游泳/夜校/掩护李大叔
 *    /勇斗鬼子/河沿枪声/雨来没死); 名句"我们是中国人，我们爱自己的祖国""有志不在年高"。
 *  - 20 我们家的男子汉（王安忆）: 3 小标题(他对食物的兴趣/他对独立的要求/他面对生活挑战
 *    的沉着); 倔强(jué jiàng)。
 *  - 21 芦花鞋（曹文轩《青铜葵花》）: 编/卖芦花鞋; 青铜把脚上唯一的鞋也卖了，赤脚踏雪回家。
 *  - 语文园地: 把握长文章主要内容=把每部分主要意思连起来; 读书成语 囊萤夜读/悬梁刺股/
 *    凿壁偷光/铁杵成针/程门立雪/手不释卷。
 *
 * 题型对齐期中卷情境化考点 + 文言文阅读多问。id 前缀 cn-u6-*。
 */

import type { Question } from "../../core/types";
import { pickChoice, dictation } from "./questionHelpers";

const U6 = "C4B_U6_GROWTH";
const PINYIN = "C4B_U6_PINYIN";
const VOCAB = "C4B_U6_VOCAB";
const WENYAN = "C4B_U6_WENYAN";
const SUMMARY = "C4B_U6_SUMMARY";
const READ = "C4B_U6_READING";
const DICT = "C4B_U6_DICTATION";

// 文言文阅读短文（课文原文 + 注释，期末文言文阅读题真实形式）
const WENYAN_NANG = `📜 文言文阅读·囊萤夜读

胤恭勤不倦，博学多通。家贫不常得油，夏月则练囊盛数十萤火以照书，以夜继日焉。

【注释】①胤：车胤，人名。②恭勤：肃敬勤勉。③通：通晓，明白。④练囊：白色薄绢做的口袋。`;

// 现代文成长故事短文（原创，第六单元"成长 / 坚持"主题）
const PASSAGE_GROW = `📖 短文·学骑车

我一直很想学会骑自行车。第一次上车，我刚踩了两下，车子就歪倒了，膝盖磕破了皮，疼得我直想哭。爸爸扶起车说：“摔一次怕什么？囊萤夜读的车胤、磨铁杵的老婆婆，哪一个不是吃了苦才成功的？”听了这话，我擦干眼泪，又骑了上去。一次、两次、十次……不知摔了多少跤，我的腿上青一块紫一块。可是渐渐地，车子在我手里听话了，我居然能稳稳地骑出去好远。那一刻，我明白了：只要肯下功夫，再难的事也能学会，就像铁杵也能磨成针。`;

export const SEED_QUESTIONS_CHINESE_U6: Question[] = [
  // ============================================================
  // 字音 · 多音字 / 易错读音
  // ============================================================
  pickChoice({
    id: "cn-u6-py-001",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "《我们家的男子汉》中“一条倔强的活鱼”的“倔强”，读音是？",
    options: [
      { id: "a", text: "jué jiàng" },
      { id: "b", text: "juè jiàng", errorTag: "tone_confusion" },
      { id: "c", text: "jué qiáng", errorTag: "polyphone_confusion" },
      { id: "d", text: "qū jiàng", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"倔强"读 jué jiàng，形容性格刚强不屈。"强"是多音字（qiáng/qiǎng/jiàng），这里读 jiàng。'],
  }),
  pickChoice({
    id: "cn-u6-py-002",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "《小英雄雨来》中“鬼子又扫荡了”的“扫”，在“打扫”和“扫帚”中分别读？",
    options: [
      { id: "a", text: "sǎo（打扫） / sào（扫帚）" },
      { id: "b", text: "sào（打扫） / sǎo（扫帚）", errorTag: "polyphone_confusion" },
      { id: "c", text: "sǎo / sǎo", errorTag: "polyphone_confusion" },
      { id: "d", text: "sào / sào", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['"扫"是多音字：sǎo（打扫、扫荡，动作）/ sào（扫帚，名词）。'],
  }),
  pickChoice({
    id: "cn-u6-py-003",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: '"塞"是多音字。下面读音正确的一组是？',
    options: [
      { id: "a", text: "把书塞进怀里（sāi） / 边塞（sài） / 阻塞（sè）" },
      { id: "b", text: "把书塞进怀里（sài） / 边塞（sāi） / 阻塞（sè）", errorTag: "polyphone_confusion" },
      { id: "c", text: "把书塞进怀里（sè） / 边塞（sài） / 阻塞（sāi）", errorTag: "polyphone_confusion" },
      { id: "d", text: "三处都读 sāi", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['"塞"：sāi（塞进，动作）/ sài（边塞、要塞）/ sè（阻塞、堵塞，书面语）。'],
  }),
  pickChoice({
    id: "cn-u6-py-004",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: '《小英雄雨来》"扭身就到炕上抓笤帚"中，"炕"读音是？',
    options: [
      { id: "a", text: "kàng" },
      { id: "b", text: "káng", errorTag: "tone_confusion" },
      { id: "c", text: "háng", errorTag: "phonics_error" },
      { id: "d", text: "kēng", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"炕"读 kàng，北方用砖坯砌成、可以烧火取暖的床。火字旁。'],
  }),
  pickChoice({
    id: "cn-u6-py-005",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics", "glyph"],
    difficulty: 2,
    stem: "下面加点字读音全部正确的一组是？",
    options: [
      { id: "a", text: "胳膊（gē bo） 铅笔（qiān） 晋察冀（jìn）" },
      { id: "b", text: "胳膊（gé bó） 铅笔（qiān） 晋察冀（jìn）", errorTag: "phonics_error" },
      { id: "c", text: "胳膊（gē bo） 铅笔（yán） 晋察冀（jìn）", errorTag: "phonics_error" },
      { id: "d", text: "胳膊（gē bo） 铅笔（qiān） 晋察冀（jìng）", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['胳膊 gē bo（"膊"读轻声）、铅 qiān、晋 jìn。均出自《小英雄雨来》。'],
  }),
  pickChoice({
    id: "cn-u6-py-006",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: '《芦花鞋》"将它们均匀地搓进草绳里"中，"搓"读音是？',
    options: [
      { id: "a", text: "cuō" },
      { id: "b", text: "chā", errorTag: "phonics_error" },
      { id: "c", text: "cā", errorTag: "phonics_error" },
      { id: "d", text: "zuǒ", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"搓"读 cuō，两个手掌反复摩擦或搓东西。提手旁。'],
  }),
  pickChoice({
    id: "cn-u6-py-007",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["phonics", "accumulation"],
    difficulty: 3,
    stem: '《铁杵成针》"逢老媪方磨铁杵"中，"杵"和"媪"的读音是？',
    options: [
      { id: "a", text: "chǔ / ǎo" },
      { id: "b", text: "wǔ / wēn", errorTag: "phonics_error" },
      { id: "c", text: "chǔ / wēn", errorTag: "phonics_error" },
      { id: "d", text: "wǔ / ǎo", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"杵"读 chǔ（舂米或捣衣的铁棒）；"媪"读 ǎo（年老的妇人）。'],
  }),
  pickChoice({
    id: "cn-u6-py-008",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["phonics", "accumulation"],
    difficulty: 2,
    stem: '《囊萤夜读》"练囊盛数十萤火"中，"囊"和"萤"的读音是？',
    options: [
      { id: "a", text: "náng / yíng" },
      { id: "b", text: "nāng / yín", errorTag: "tone_confusion" },
      { id: "c", text: "ráng / yíng", errorTag: "phonics_error" },
      { id: "d", text: "náng / yín", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['"囊"读 náng（口袋）；"萤"读 yíng（萤火虫）。'],
  }),
  pickChoice({
    id: "cn-u6-py-009",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: '《小英雄雨来》"嘟嘟囔囔地说"中，"囔"读音是？',
    options: [
      { id: "a", text: "nāng（轻声，嘟囔）" },
      { id: "b", text: "ráng", errorTag: "phonics_error" },
      { id: "c", text: "náng", errorTag: "tone_confusion" },
      { id: "d", text: "nǎng", errorTag: "tone_confusion" },
    ],
    correct: "a",
    solution: ['"嘟囔""嘟嘟囔囔"指含混不清地自言自语，"囔"读轻声 nang（本音 nāng）。'],
  }),
  pickChoice({
    id: "cn-u6-py-010",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 2,
    stem: '《小英雄雨来》"浑身光溜溜的像条小泥鳅"中，"鳅"读音是？',
    options: [
      { id: "a", text: "qiū" },
      { id: "b", text: "qiú", errorTag: "tone_confusion" },
      { id: "c", text: "chōu", errorTag: "phonics_error" },
      { id: "d", text: "jiū", errorTag: "phonics_error" },
    ],
    correct: "a",
    solution: ['"泥鳅"读 ní qiū，一种身体滑溜的小鱼。"鳅"读 qiū。'],
  }),

  // ============================================================
  // 字形 · 错别字 / 形近字
  // ============================================================
  pickChoice({
    id: "cn-u6-gl-001",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    exam_priority: "MUST_BIG",
    stem: "选出没有错别字的一组（《小英雄雨来》词语）：",
    options: [
      { id: "a", text: "扭身 · 捆绑 · 枪栓 · 慌忙" },
      { id: "b", text: "扭身 · 困绑 · 枪栓 · 慌忙", errorTag: "glyph_homophone" },
      { id: "c", text: "扭身 · 捆绑 · 枪拴 · 慌忙", errorTag: "glyph_homophone" },
      { id: "d", text: "扭身 · 捆绑 · 枪栓 · 谎忙", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"捆绑"不是"困绑"；"枪栓"（木字旁，枪上零件）不是"枪拴"；"慌忙"（竖心旁，慌张）不是"谎忙"。'],
  }),
  pickChoice({
    id: "cn-u6-gl-002",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面词语中有错别字的一项是？",
    options: [
      { id: "a", text: "倔强 · 嘱咐 · 沮丧", errorTag: "glyph_correct" },
      { id: "b", text: "拌饭 · 沮丧 · 防碍（妨碍）", errorTag: "glyph_homophone" },
      { id: "c", text: "搓绳 · 葵花 · 遗憾", errorTag: "glyph_correct" },
      { id: "d", text: "祈求 · 污迹 · 雪屑", errorTag: "glyph_correct" },
    ],
    correct: "b",
    solution: ['B 中"防碍"应为"妨碍"（妨：女字旁，阻碍的意思）。"防"是防备。本题选有错别字的一项。'],
  }),
  pickChoice({
    id: "cn-u6-gl-003",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: '形近字组词，全部正确的一组是？',
    options: [
      { id: "a", text: "绸（绸子）— 稠（稠密）；敌（敌人）— 故（故事）" },
      { id: "b", text: "绸（稠子）— 稠（绸密）；敌（敌人）— 故（故事）", errorTag: "form_similar" },
      { id: "c", text: "绸（绸子）— 稠（稠密）；敌（故人）— 故（敌事）", errorTag: "form_similar" },
      { id: "d", text: "绸（绸子）— 稠（稠密）；敌（敌人）— 故（敌事）", errorTag: "form_similar" },
    ],
    correct: "a",
    solution: ['"绸"绞丝旁，绸子（丝织品）；"稠"禾木旁，稠密。"敌"敌人；"故"故事、原因。A 全对。'],
  }),
  pickChoice({
    id: "cn-u6-gl-004",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "看拼音写词语，正确的一项是：yí hàn（《芦花鞋》：心里很为那人感到 yí hàn）。",
    options: [
      { id: "a", text: "遗憾" },
      { id: "b", text: "遗撼", errorTag: "glyph_homophone" },
      { id: "c", text: "遣憾", errorTag: "glyph_homophone" },
      { id: "d", text: "遗感", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"遗憾"指惋惜、不称心。"憾"是竖心旁（心里的感受），不是提手旁的"撼"（摇撼）。'],
  }),
  pickChoice({
    id: "cn-u6-gl-005",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "下面书写完全正确的一项是（《我们家的男子汉》词语）？",
    options: [
      { id: "a", text: "安徽 · 嘴唇 · 嘱咐 · 沮丧" },
      { id: "b", text: "安微 · 嘴唇 · 嘱咐 · 沮丧", errorTag: "glyph_homophone" },
      { id: "c", text: "安徽 · 嘴唇 · 嘱付 · 沮丧", errorTag: "glyph_homophone" },
      { id: "d", text: "安徽 · 嘴唇 · 嘱咐 · 阻丧", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"安徽"不是"安微"；"嘱咐"（口字旁）不是"嘱付"；"沮丧"不是"阻丧"。A 全对。'],
  }),
  pickChoice({
    id: "cn-u6-gl-006",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: '《小英雄雨来》"识字课本"的"识"，在"认识"和"博闻强识"中分别读 shí / zhì。下面对"识"的理解正确的是？',
    options: [
      { id: "a", text: "shí 时表示认得、知道；zhì 时同“志”，指记住" },
      { id: "b", text: "两个读音意思完全一样", errorTag: "word_misunderstand" },
      { id: "c", text: "都读 shí", errorTag: "polyphone_confusion" },
      { id: "d", text: "都读 zhì", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['"识"是多音字：shí（认识、识字）/ zhì（同"志"，记住，如"博闻强识"）。'],
  }),
  pickChoice({
    id: "cn-u6-gl-007",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "看拼音写词语：青铜把芦花 cuō jìn 草绳里，再编织成鞋。",
    options: [
      { id: "a", text: "搓进" },
      { id: "b", text: "磋进", errorTag: "glyph_homophone" },
      { id: "c", text: "差进", errorTag: "glyph_homophone" },
      { id: "d", text: "挫进", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"搓"是提手旁，表示用手反复摩擦。"磋"指商量（磋商），"挫"指失败（挫折）。'],
  }),

  // ============================================================
  // 词语 · 理解 / 搭配 / 近义词
  // ============================================================
  pickChoice({
    id: "cn-u6-vocab-001",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '《芦花鞋》"全家人都很兴奋，觉得心里亮堂堂的"中，"亮堂堂"形容的是？',
    options: [
      { id: "a", text: "心里充满希望、很高兴" },
      { id: "b", text: "屋子里灯很亮", errorTag: "literal_misread" },
      { id: "c", text: "天气晴朗", errorTag: "literal_misread" },
      { id: "d", text: "芦花鞋很白", errorTag: "literal_misread" },
    ],
    correct: "a",
    solution: ['"心里亮堂堂"是想到这笔重要收入，全家充满希望、心情明朗高兴，不是真的"明亮"。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-002",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '《我们家的男子汉》"嘴里啧啧地感叹不已"中，"不已"的意思是？',
    options: [
      { id: "a", text: "不停止" },
      { id: "b", text: "不可以", errorTag: "word_misunderstand" },
      { id: "c", text: "不自己", errorTag: "word_misunderstand" },
      { id: "d", text: "不知道", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['"已"是停止的意思，"不已"即不停止。"感叹不已"指不停地赞叹。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-003",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: "下面词语搭配恰当的一组是？",
    options: [
      { id: "a", text: "倔强的活鱼 · 厚实的芦花鞋 · 镇静地打量" },
      { id: "b", text: "倔强的芦花鞋 · 厚实的活鱼 · 镇静地打量", errorTag: "collocation_error" },
      { id: "c", text: "倔强的活鱼 · 厚实的芦花鞋 · 镇静地芦花", errorTag: "collocation_error" },
      { id: "d", text: "倔强的打量 · 厚实的芦花鞋 · 镇静地活鱼", errorTag: "collocation_error" },
    ],
    correct: "a",
    solution: ['"倔强"修饰活鱼（挣扎），"厚实"修饰芦花鞋，"镇静地"修饰"打量"，均搭配恰当。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-004",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '"有志不在年高"这句话的意思是？',
    options: [
      { id: "a", text: "有志气不在于年纪大小（年纪小也能有作为）" },
      { id: "b", text: "年纪越大越有志气", errorTag: "word_misunderstand" },
      { id: "c", text: "只有年纪大的人才有志气", errorTag: "opposite" },
      { id: "d", text: "志气和年龄没有关系，越老越好", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['乡亲们夸雨来"有志不在年高"，是说有志气不取决于年纪大小，年纪虽小也能做出英雄的事。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-005",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '选词填空：营业员只顾和大人做生意，看都不看他一眼，他满头大汗地（  ）等待着。（耐心 / 耐烦）',
    options: [
      { id: "a", text: "耐心（不急躁、能坚持）" },
      { id: "b", text: "耐烦（多用于否定，如“不耐烦”）", errorTag: "synonym_misuse" },
      { id: "c", text: "烦心（心里烦）", errorTag: "synonym_misuse" },
      { id: "d", text: "细心（仔细）", errorTag: "synonym_misuse" },
    ],
    correct: "a",
    solution: ['课文写孩子"耐心地等待着"，表现他要自己买东西的坚持。"耐烦"多用于否定句。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-006",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: "看拼音写词语：女老师 zhǔ fù（嘱咐）我们要认真读书。",
    options: [
      { id: "a", text: "嘱咐" },
      { id: "b", text: "属咐", errorTag: "glyph_homophone" },
      { id: "c", text: "嘱付", errorTag: "glyph_homophone" },
      { id: "d", text: "瞩咐", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"嘱咐"指叮嘱、吩咐，两字都是口字旁（用嘴说）。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-007",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: '《芦花鞋》"那人失望地一摊手，并叹息了一声"，"叹息"的意思最接近？',
    options: [
      { id: "a", text: "叹气" },
      { id: "b", text: "休息", errorTag: "synonym_misuse" },
      { id: "c", text: "消息", errorTag: "word_misunderstand" },
      { id: "d", text: "欢呼", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['"叹息"就是叹气，表示因为买不到芦花鞋而失望、惋惜。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-008",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: '下列词语全部是描写人物动作的一组是？',
    options: [
      { id: "a", text: "扭身 · 撒腿 · 攀上 · 蹬着" },
      { id: "b", text: "倔强 · 沮丧 · 镇静 · 兴奋", errorTag: "word_category" },
      { id: "c", text: "扭身 · 倔强 · 攀上 · 兴奋", errorTag: "word_category" },
      { id: "d", text: "亮堂堂 · 撒腿 · 沮丧 · 蹬着", errorTag: "word_category" },
    ],
    correct: "a",
    solution: ['扭身、撒腿、攀上、蹬着都是动作词。B 组全是形容心情/性格的词。'],
  }),

  // ============================================================
  // 文言文 · 词义 / 句意 / 朗读 / 道理 (囊萤夜读 · 铁杵成针)
  // ============================================================
  pickChoice({
    id: "cn-u6-wy-001",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: '《囊萤夜读》"恭勤不倦"中，"倦"的意思是？',
    options: [
      { id: "a", text: "疲倦、劳累" },
      { id: "b", text: "卷起来", errorTag: "word_misunderstand" },
      { id: "c", text: "可爱", errorTag: "word_misunderstand" },
      { id: "d", text: "卷子", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['"恭勤不倦"指肃敬勤勉、不知疲倦。"倦"是疲倦、劳累的意思。'],
  }),
  pickChoice({
    id: "cn-u6-wy-002",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: '《囊萤夜读》"练囊盛数十萤火以照书"中，"练囊"指的是？',
    options: [
      { id: "a", text: "用白色薄绢做的口袋" },
      { id: "b", text: "练习用的本子", errorTag: "word_misunderstand" },
      { id: "c", text: "一串萤火虫", errorTag: "word_misunderstand" },
      { id: "d", text: "练武的袋子", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['注释明确："练囊"指白色薄绢做的口袋。车胤用它装萤火虫照明读书。'],
  }),
  pickChoice({
    id: "cn-u6-wy-003",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: '《囊萤夜读》"以夜继日焉"的意思是？',
    options: [
      { id: "a", text: "用夜晚接着白天（继续读书），夜以继日" },
      { id: "b", text: "白天接着夜晚睡觉", errorTag: "sentence_meaning_flip" },
      { id: "c", text: "夜里和白天都在玩", errorTag: "off_topic" },
      { id: "d", text: "晚上比白天更亮", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['"以夜继日"即"夜以继日"，夜晚接着白天地读书，形容车胤刻苦勤学。'],
  }),
  pickChoice({
    id: "cn-u6-wy-004",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: '《铁杵成针》"过是溪"中，"是"的意思是？',
    options: [
      { id: "a", text: "这（这条）" },
      { id: "b", text: "表示判断（是不是的“是”）", errorTag: "word_misunderstand" },
      { id: "c", text: "正确", errorTag: "word_misunderstand" },
      { id: "d", text: "于是", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['文言文中"是"常作"这"讲。"过是溪"就是"路过这条小溪"。'],
  }),
  pickChoice({
    id: "cn-u6-wy-005",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: '《铁杵成针》"逢老媪方磨铁杵"中，"方"的意思是？',
    options: [
      { id: "a", text: "正在" },
      { id: "b", text: "方向", errorTag: "word_misunderstand" },
      { id: "c", text: "方形", errorTag: "word_misunderstand" },
      { id: "d", text: "刚才", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['注释："方"指正在。"老媪方磨铁杵"即老妇人正在磨铁棒。'],
  }),
  pickChoice({
    id: "cn-u6-wy-006",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: '《铁杵成针》"太白感其意，还卒业"的意思是？',
    options: [
      { id: "a", text: "李白被老妇人的意志感动，回去完成了学业" },
      { id: "b", text: "李白觉得没意思，回家毕业了", errorTag: "word_misunderstand" },
      { id: "c", text: "李白感谢老妇人，留下来磨针", errorTag: "off_topic" },
      { id: "d", text: "李白生气了，再也不读书", errorTag: "sentence_meaning_flip" },
    ],
    correct: "a",
    solution: ['"感其意"=被她的意志感动；"还卒业"=回去完成了学业。李白受老妇人启发，回去苦读成才。'],
  }),
  pickChoice({
    id: "cn-u6-wy-007",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: '《铁杵成针》故事告诉我们的道理是？',
    options: [
      { id: "a", text: "只要有恒心、肯下功夫，再难的事也能成功" },
      { id: "b", text: "磨针比读书更重要", errorTag: "off_topic" },
      { id: "c", text: "读书没有用", errorTag: "opposite" },
      { id: "d", text: "遇到困难就应该放弃", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['"只要功夫深，铁杵磨成针"。故事说明只要有恒心、肯坚持，就能成功。'],
  }),
  pickChoice({
    id: "cn-u6-wy-008",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation"],
    difficulty: 3,
    stem: '下面成语都与古人读书求学有关。其中"凿壁偷光"讲的是谁的故事？',
    options: [
      { id: "a", text: "匡衡（凿穿墙壁，借邻居的灯光读书）" },
      { id: "b", text: "车胤（用萤火虫照明读书）", errorTag: "story_confusion" },
      { id: "c", text: "李白（铁杵磨成针）", errorTag: "story_confusion" },
      { id: "d", text: "孙敬（头悬梁苦读）", errorTag: "story_confusion" },
    ],
    correct: "a",
    solution: ['"凿壁偷光"讲匡衡凿墙借光读书；车胤是"囊萤夜读"；孙敬是"悬梁"；苏秦是"刺股"。'],
  }),
  pickChoice({
    id: "cn-u6-wy-009",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 3,
    stem: '《囊萤夜读》朗读节奏划分最恰当的一项是？',
    options: [
      { id: "a", text: "胤/恭勤/不倦，博学/多通。" },
      { id: "b", text: "胤恭/勤不/倦，博/学多通。", errorTag: "rhythm_wrong" },
      { id: "c", text: "胤恭勤/不/倦博/学多通。", errorTag: "rhythm_wrong" },
      { id: "d", text: "胤/恭/勤/不/倦/博/学/多/通。", errorTag: "rhythm_wrong" },
    ],
    correct: "a",
    solution: ['按意义停顿："胤（人名）/恭勤（勤勉）/不倦，博学/多通"，读起来通顺、合乎文意。'],
  }),
  pickChoice({
    id: "cn-u6-wy-010",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation"],
    difficulty: 3,
    stem: '《囊萤夜读》选自下面哪一部书？',
    options: [
      { id: "a", text: "《晋书·车胤传》" },
      { id: "b", text: "《方舆胜览·眉州》", errorTag: "source_confusion" },
      { id: "c", text: "《史记》", errorTag: "source_confusion" },
      { id: "d", text: "《论语》", errorTag: "source_confusion" },
    ],
    correct: "a",
    solution: ['《囊萤夜读》选自《晋书·车胤传》；《铁杵成针》选自宋代祝穆《方舆胜览·眉州》。'],
  }),

  // 文言文阅读多问（囊萤夜读，5 题）
  pickChoice({
    id: "cn-u6-wyread-001",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["reading", "accumulation"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${WENYAN_NANG}\n\n🔹 第 1 题：车胤为什么要"练囊盛数十萤火以照书"？`,
    options: [
      { id: "a", text: "因为家里穷，常常没有灯油，只好用萤火虫照明读书" },
      { id: "b", text: "因为他喜欢玩萤火虫", errorTag: "off_topic" },
      { id: "c", text: "因为萤火虫比灯油更亮", errorTag: "word_misunderstand" },
      { id: "d", text: "因为白天没空读书", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['"家贫不常得油"说明家里穷、缺灯油，所以夏天用萤火虫照明，坚持夜读。'],
  }),
  pickChoice({
    id: "cn-u6-wyread-002",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["reading", "accumulation"],
    difficulty: 4,
    stem: `${WENYAN_NANG}\n\n🔹 第 2 题："博学多通"中"通"的意思是？`,
    options: [
      { id: "a", text: "通晓、明白" },
      { id: "b", text: "通过", errorTag: "word_misunderstand" },
      { id: "c", text: "通行", errorTag: "word_misunderstand" },
      { id: "d", text: "全部", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['注释："通"指通晓、明白。"博学多通"形容车胤知识广博、学问精通。'],
  }),
  pickChoice({
    id: "cn-u6-wyread-003",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["reading", "accumulation"],
    difficulty: 4,
    stem: `${WENYAN_NANG}\n\n🔹 第 3 题："夏月则练囊盛数十萤火以照书"翻译正确的是？`,
    options: [
      { id: "a", text: "夏天就用白绢口袋装几十只萤火虫来照着书本（读书）" },
      { id: "b", text: "夏天的月亮像白口袋一样照着书", errorTag: "sentence_meaning_flip" },
      { id: "c", text: "夏天把书装进口袋里", errorTag: "word_misunderstand" },
      { id: "d", text: "夏天点几十盏灯读书", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['"夏月"指夏天的夜晚；"练囊"白绢口袋；"盛数十萤火"装几十只萤火虫；"以照书"用来照着书。'],
  }),
  pickChoice({
    id: "cn-u6-wyread-004",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["reading", "accumulation"],
    difficulty: 4,
    stem: `${WENYAN_NANG}\n\n🔹 第 4 题：这则文言文主要赞扬车胤的什么品质？`,
    options: [
      { id: "a", text: "勤奋好学、不怕困难" },
      { id: "b", text: "聪明伶俐", errorTag: "narrow_focus" },
      { id: "c", text: "爱护小动物", errorTag: "off_topic" },
      { id: "d", text: "节约用钱", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['车胤家贫缺油，仍想办法囊萤照读、夜以继日，赞扬的是他勤奋好学、克服困难的精神。'],
  }),
  pickChoice({
    id: "cn-u6-wyread-005",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["reading", "accumulation"],
    difficulty: 4,
    stem: `${WENYAN_NANG}\n\n🔹 第 5 题：和这则故事意思最相近的成语是？`,
    options: [
      { id: "a", text: "凿壁偷光" },
      { id: "b", text: "守株待兔", errorTag: "idiom_misuse" },
      { id: "c", text: "画蛇添足", errorTag: "idiom_misuse" },
      { id: "d", text: "亡羊补牢", errorTag: "idiom_misuse" },
    ],
    correct: "a",
    solution: ['"凿壁偷光"（匡衡借光读书）和"囊萤夜读"都讲家贫仍刻苦读书，意思最相近。'],
  }),

  // ============================================================
  // 把握长文章主要内容 / 人物品质
  // ============================================================
  pickChoice({
    id: "cn-u6-sum-001",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: '把握一篇很长的文章的主要内容，最好的方法是？',
    options: [
      { id: "a", text: "把每个部分的主要意思连起来" },
      { id: "b", text: "只看开头第一句", errorTag: "method_wrong" },
      { id: "c", text: "只记住最后一段", errorTag: "method_wrong" },
      { id: "d", text: "把每个字都背下来", errorTag: "method_wrong" },
    ],
    correct: "a",
    solution: ['语文园地点明：长文章常分几部分写，把每部分主要意思连起来，就能把握全文主要内容。'],
  }),
  pickChoice({
    id: "cn-u6-sum-002",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading"],
    difficulty: 3,
    stem: '《小英雄雨来》《我们家的男子汉》《芦花鞋》分别用什么方式把长文章分成几部分？',
    options: [
      { id: "a", text: "雨来用序号、男子汉用小标题、芦花鞋用空行" },
      { id: "b", text: "三篇都用序号", errorTag: "detail_wrong" },
      { id: "c", text: "三篇都用小标题", errorTag: "detail_wrong" },
      { id: "d", text: "三篇都不分部分", errorTag: "detail_wrong" },
    ],
    correct: "a",
    solution: ['《小英雄雨来》用一二三…序号；《我们家的男子汉》用小标题；《芦花鞋》用空行分部分。'],
  }),
  pickChoice({
    id: "cn-u6-sum-003",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading"],
    difficulty: 3,
    stem: '《小英雄雨来》第一部分的小标题"游泳本领高"概括的是？',
    options: [
      { id: "a", text: "雨来在还乡河游泳，仰浮的本领最高" },
      { id: "b", text: "雨来上夜校念书", errorTag: "wrong_part" },
      { id: "c", text: "雨来掩护李大叔", errorTag: "wrong_part" },
      { id: "d", text: "雨来勇斗鬼子", errorTag: "wrong_part" },
    ],
    correct: "a",
    solution: ['第一部分写雨来和小伙伴在还乡河游泳，雨来"仰浮的本领最高"，所以小标题是"游泳本领高"。'],
  }),
  pickChoice({
    id: "cn-u6-sum-004",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: '为什么说雨来是"小英雄"？最准确的理解是？',
    options: [
      { id: "a", text: "他年纪虽小，却机智勇敢，宁死也不向鬼子说出李大叔的下落" },
      { id: "b", text: "因为他游泳本领最高", errorTag: "narrow_focus" },
      { id: "c", text: "因为他会念书识字", errorTag: "narrow_focus" },
      { id: "d", text: "因为他长得漂亮", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['雨来为掩护李大叔，面对鬼子的毒打、利诱坚决不说，最后机智脱险。他爱国、勇敢、机智，是小英雄。'],
  }),
  pickChoice({
    id: "cn-u6-sum-005",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading"],
    difficulty: 3,
    stem: '《我们家的男子汉》中，作者用三个小标题写了孩子的三件事，下面属于课文小标题的一组是？',
    options: [
      { id: "a", text: "他对食物的兴趣 / 他对独立的要求 / 他面对生活挑战的沉着" },
      { id: "b", text: "他爱哭 / 他贪玩 / 他胆小", errorTag: "detail_wrong" },
      { id: "c", text: "游泳本领高 / 上夜校 / 掩护李大叔", errorTag: "wrong_text" },
      { id: "d", text: "编芦花鞋 / 卖芦花鞋 / 赤脚回家", errorTag: "wrong_text" },
    ],
    correct: "a",
    solution: ['课文用三个小标题：他对食物的兴趣、他对独立的要求、他面对生活挑战的沉着。'],
  }),
  pickChoice({
    id: "cn-u6-sum-006",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: '《芦花鞋》结尾，青铜把脚上唯一的一双芦花鞋也卖给了别人，赤脚踏雪回家。这表现了青铜怎样的品质？',
    options: [
      { id: "a", text: "善良、为家庭着想、肯为别人付出" },
      { id: "b", text: "粗心大意", errorTag: "wrong_trait" },
      { id: "c", text: "贪图钱财", errorTag: "opposite" },
      { id: "d", text: "胆小怕事", errorTag: "wrong_trait" },
    ],
    correct: "a",
    solution: ['芦花鞋是家里重要的收入；青铜见买鞋人喜欢，宁愿自己赤脚受冻也成全别人，表现他善良、懂事、肯付出。'],
  }),
  pickChoice({
    id: "cn-u6-sum-007",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading"],
    difficulty: 4,
    stem: '《小英雄雨来》中多次写到还乡河的景色，这样写的主要作用是？',
    options: [
      { id: "a", text: "用美丽的景色衬托人物，使故事更生动，也烘托情感" },
      { id: "b", text: "凑字数，没有作用", errorTag: "off_topic" },
      { id: "c", text: "说明还乡河风景区很有名", errorTag: "off_topic" },
      { id: "d", text: "提醒读者注意安全", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['开头写芦花美景交代环境、引出人物；结尾"浮云像红绸子"等景色烘托出乡亲悲喜交加的心情。环境描写为人物和情节服务。'],
  }),
  pickChoice({
    id: "cn-u6-sum-008",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: '"我们是中国人，我们爱自己的祖国。"这句话在《小英雄雨来》中反复出现，作用是？',
    options: [
      { id: "a", text: "点明雨来爱国的精神来源，是他勇敢不屈的力量" },
      { id: "b", text: "只是夜校的一句普通课文", errorTag: "narrow_focus" },
      { id: "c", text: "说明雨来字写得好", errorTag: "off_topic" },
      { id: "d", text: "和雨来没有关系", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['这句话是雨来在夜校学的，在他受刑时鼓舞他坚强不屈，反复出现强调了爱国是雨来勇敢的力量源泉。'],
  }),

  // ============================================================
  // 句子 · 比喻 / 名句
  // ============================================================
  pickChoice({
    id: "cn-u6-sent-001",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["sentence"],
    difficulty: 3,
    stem: '"远远望去，黄绿的芦苇上好像盖了一层厚厚的白雪。"这句话用了什么修辞？',
    options: [
      { id: "a", text: "比喻（把芦花比作白雪）" },
      { id: "b", text: "拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "排比", errorTag: "wrong_rhetoric" },
      { id: "d", text: "反问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['"芦苇上好像盖了一层白雪"把白茫茫的芦花比作白雪，是比喻，写出芦花村的美。'],
  }),
  pickChoice({
    id: "cn-u6-sent-002",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["sentence"],
    difficulty: 3,
    stem: '"雨来浑身光溜溜的像条小泥鳅，怎么也抓不住。"这句话好在哪里？',
    options: [
      { id: "a", text: "用比喻写出雨来灵活、滑溜、不容易被抓住" },
      { id: "b", text: "说明雨来很脏", errorTag: "word_misunderstand" },
      { id: "c", text: "说明雨来是一条鱼", errorTag: "literal_misread" },
      { id: "d", text: "没有什么好处", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['把雨来比作小泥鳅，生动地写出他游泳灵活、身体滑溜、妈妈抓不住的样子。'],
  }),
  pickChoice({
    id: "cn-u6-sent-003",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["sentence"],
    difficulty: 3,
    stem: '"蓝蓝的天上飘着的浮云像一块一块红绸子，映在还乡河上，像开了一大朵一大朵鸡冠花。"这句话用了什么修辞？',
    options: [
      { id: "a", text: "比喻（把浮云比作红绸子、鸡冠花）" },
      { id: "b", text: "只有拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "只有夸张", errorTag: "wrong_rhetoric" },
      { id: "d", text: "设问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['把傍晚的浮云比作"红绸子""鸡冠花"，是比喻，烘托出河沿枪声后乡亲们沉重的心情。'],
  }),
  pickChoice({
    id: "cn-u6-sent-004",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["sentence"],
    difficulty: 3,
    stem: '《芦花鞋》"那鞋很厚实，像暖和和的鸟窝。"这句话把芦花鞋比作？',
    options: [
      { id: "a", text: "暖和的鸟窝" },
      { id: "b", text: "白雪", errorTag: "wrong_object" },
      { id: "c", text: "稻草", errorTag: "wrong_object" },
      { id: "d", text: "棉花", errorTag: "wrong_object" },
    ],
    correct: "a",
    solution: ['"像暖和和的鸟窝"把芦花鞋比作鸟窝，写出鞋子厚实、暖和的特点。'],
  }),
  pickChoice({
    id: "cn-u6-sent-005",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '照样子写句子。例：雨来浑身光溜溜的像条小泥鳅。下面仿写最恰当的一句是？',
    options: [
      { id: "a", text: "弟弟胖乎乎的像个小皮球。" },
      { id: "b", text: "弟弟很胖很胖。", errorTag: "no_rhetoric" },
      { id: "c", text: "弟弟是个小孩。", errorTag: "no_rhetoric" },
      { id: "d", text: "弟弟在玩泥鳅。", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['例句是"……像……"的比喻句。A"胖乎乎的像个小皮球"结构相同、用了比喻，仿写最恰当。'],
  }),
  pickChoice({
    id: "cn-u6-sent-006",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["sentence"],
    difficulty: 3,
    stem: '"十二岁的雨来使尽气力，才把缸挪回到原地。"这句话主要表现了？',
    options: [
      { id: "a", text: "缸很重，雨来年纪小，但仍尽力掩护李大叔" },
      { id: "b", text: "雨来力气很大", errorTag: "opposite" },
      { id: "c", text: "雨来在搬家", errorTag: "off_topic" },
      { id: "d", text: "缸是空的", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['"使尽气力，才……"说明缸很重、雨来年纪小很吃力，却仍坚持把缸挪回原处，掩护李大叔，可见他机智勇敢。'],
  }),

  // ============================================================
  // 阅读理解 · 现代文 学骑车 (5 题)
  // ============================================================
  pickChoice({
    id: "cn-u6-read-001",
    unit_id: U6,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_GROW}\n\n🔹 第 1 题：短文主要写了一件什么事？`,
    options: [
      { id: "a", text: "我经过反复练习，终于学会了骑自行车" },
      { id: "b", text: "我摔破了膝盖", errorTag: "detail_only" },
      { id: "c", text: "爸爸给我讲故事", errorTag: "detail_only" },
      { id: "d", text: "车胤和老婆婆的故事", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['短文从"想学骑车"到"摔了很多跤"再到"稳稳骑出去"，写的是"我"学会骑车的过程。'],
  }),
  pickChoice({
    id: "cn-u6-read-002",
    unit_id: U6,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 4,
    stem: `${PASSAGE_GROW}\n\n🔹 第 2 题：爸爸为什么要提"囊萤夜读的车胤、磨铁杵的老婆婆"？`,
    options: [
      { id: "a", text: "用古人吃苦成功的故事鼓励“我”不要怕困难、坚持下去" },
      { id: "b", text: "想让“我”去读文言文", errorTag: "off_topic" },
      { id: "c", text: "怕“我”再摔跤", errorTag: "narrow_focus" },
      { id: "d", text: "想换一辆新车", errorTag: "not_in_text" },
    ],
    correct: "a",
    solution: ['爸爸举车胤、老婆婆的例子，是用古人坚持吃苦终获成功的道理，鼓励"我"别怕摔、坚持练。'],
  }),
  pickChoice({
    id: "cn-u6-read-003",
    unit_id: U6,
    skill_id: READ,
    ability: ["reading"],
    difficulty: 3,
    stem: `${PASSAGE_GROW}\n\n🔹 第 3 题："我的腿上青一块紫一块"说明了什么？`,
    options: [
      { id: "a", text: "学车摔了很多次，很不容易" },
      { id: "b", text: "我生病了", errorTag: "word_misunderstand" },
      { id: "c", text: "天气很冷", errorTag: "off_topic" },
      { id: "d", text: "我不想学了", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['"青一块紫一块"是摔跤碰伤留下的痕迹，说明学车过程中摔了很多次、很辛苦。'],
  }),
  pickChoice({
    id: "cn-u6-read-004",
    unit_id: U6,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: `${PASSAGE_GROW}\n\n🔹 第 4 题："就像铁杵也能磨成针"这句话在文中的意思是？`,
    options: [
      { id: "a", text: "只要肯下功夫、坚持，再难的事也能学会" },
      { id: "b", text: "铁棒真的能变成针", errorTag: "literal_misread" },
      { id: "c", text: "学骑车要用到针", errorTag: "off_topic" },
      { id: "d", text: "骑车比磨针难", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['这里借"铁杵磨成针"的道理，说明只要肯下功夫、坚持不懈，再难的事也能成功。'],
  }),
  pickChoice({
    id: "cn-u6-read-005",
    unit_id: U6,
    skill_id: READ,
    ability: ["reading", "expression"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: `${PASSAGE_GROW}\n\n🔹 第 5 题：这篇短文告诉我们一个什么道理？`,
    options: [
      { id: "a", text: "做事要有恒心、肯坚持，就能克服困难取得成功" },
      { id: "b", text: "学骑车一定会受伤", errorTag: "narrow_focus" },
      { id: "c", text: "遇到困难要找爸爸帮忙", errorTag: "narrow_focus" },
      { id: "d", text: "不会的事就不要做", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['短文借学骑车的经历，说明只要肯下功夫、坚持到底，再难的事也能学会，和"铁杵成针"道理一致。'],
  }),

  // ============================================================
  // 听写 (第六单元词语)
  // ============================================================
  dictation({
    id: "cn-u6-dict-001",
    unit_id: U6,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "倔强",
    options: [
      { id: "a", text: "倔强" },
      { id: "b", text: "倔犟", errorTag: "glyph_homophone" },
      { id: "c", text: "崛强", errorTag: "glyph_homophone" },
      { id: "d", text: "倔僵", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"倔强"（jué jiàng）形容刚强不屈。"倔"单人旁，"强"是弓字旁。'],
  }),
  dictation({
    id: "cn-u6-dict-002",
    unit_id: U6,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "嘱咐",
    options: [
      { id: "a", text: "嘱咐" },
      { id: "b", text: "嘱付", errorTag: "glyph_homophone" },
      { id: "c", text: "属咐", errorTag: "glyph_homophone" },
      { id: "d", text: "瞩咐", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"嘱咐"指叮嘱吩咐，两字都是口字旁（用口说）。'],
  }),
  dictation({
    id: "cn-u6-dict-003",
    unit_id: U6,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "遗憾",
    options: [
      { id: "a", text: "遗憾" },
      { id: "b", text: "遗撼", errorTag: "glyph_homophone" },
      { id: "c", text: "遗感", errorTag: "glyph_homophone" },
      { id: "d", text: "遣憾", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"遗憾"指惋惜。"憾"是竖心旁（心里的感受）。'],
  }),
  dictation({
    id: "cn-u6-dict-004",
    unit_id: U6,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "捆绑",
    options: [
      { id: "a", text: "捆绑" },
      { id: "b", text: "困绑", errorTag: "glyph_homophone" },
      { id: "c", text: "捆梆", errorTag: "glyph_homophone" },
      { id: "d", text: "捆邦", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"捆绑"指用绳子捆住。两字都是提手旁/绞丝旁，与手和绳有关。'],
  }),
  dictation({
    id: "cn-u6-dict-005",
    unit_id: U6,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "祈求",
    options: [
      { id: "a", text: "祈求" },
      { id: "b", text: "祁求", errorTag: "glyph_homophone" },
      { id: "c", text: "祈球", errorTag: "glyph_homophone" },
      { id: "d", text: "圻求", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['"祈求"指恳切地希望。"祈"是示字旁（与祭祀、祝愿有关），不是"祁"（姓氏/地名）。'],
  }),

  // ============================================================
  // 期末备考补充批次（爸爸 2026-05-21，补到 ~80）
  // ============================================================
  pickChoice({
    id: "cn-u6-py-011",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“露”是多音字。下面读音对应正确的一组是？",
    options: [
      { id: "a", text: "暴露（lù） 露馅儿（lòu）" },
      { id: "b", text: "暴露（lòu） 露馅儿（lù）", errorTag: "polyphone_confusion" },
      { id: "c", text: "暴露（lù） 露馅儿（lù）", errorTag: "polyphone_confusion" },
      { id: "d", text: "暴露（lòu） 露馅儿（lòu）", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“露”：lù（书面，露珠、暴露、露天）/ lòu（口语，露馅儿、露面、露怯）。'],
  }),
  pickChoice({
    id: "cn-u6-py-012",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["phonics"],
    difficulty: 3,
    stem: "“模”是多音字。“他学会了一套足以乱真的醉拳……向往着去少林寺”里没有“模”，但下面读音正确的一组是？",
    options: [
      { id: "a", text: "模仿（mó） 模样（mú）" },
      { id: "b", text: "模仿（mú） 模样（mó）", errorTag: "polyphone_confusion" },
      { id: "c", text: "模仿（mó） 模样（mó）", errorTag: "polyphone_confusion" },
      { id: "d", text: "模仿（mú） 模样（mú）", errorTag: "polyphone_confusion" },
    ],
    correct: "a",
    solution: ['“模”：mó（模仿、模范、模型）/ mú（模样、模子、一模一样）。'],
  }),
  pickChoice({
    id: "cn-u6-gl-008",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面没有错别字的一组是（《我们家的男子汉》词语）：",
    options: [
      { id: "a", text: "沮丧 · 倔强 · 镇静" },
      { id: "b", text: "沮丧 · 倔犟 · 镇静", errorTag: "glyph_homophone" },
      { id: "c", text: "阻丧 · 倔强 · 镇静", errorTag: "glyph_homophone" },
      { id: "d", text: "沮丧 · 倔强 · 震静", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“沮丧”不是“阻丧”；“倔强”不是“倔犟”；“镇静”不是“震静”。A 全对。'],
  }),
  pickChoice({
    id: "cn-u6-gl-009",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 3,
    stem: "辨字组词，全部正确的一组是？",
    options: [
      { id: "a", text: "慌（慌张）— 谎（谎话）— 荒（荒地）" },
      { id: "b", text: "慌（谎话）— 谎（慌张）— 荒（荒地）", errorTag: "form_similar" },
      { id: "c", text: "慌（荒地）— 谎（谎话）— 荒（慌张）", errorTag: "form_similar" },
      { id: "d", text: "慌（慌张）— 谎（荒地）— 荒（谎话）", errorTag: "form_similar" },
    ],
    correct: "a",
    solution: ['“慌”竖心旁（慌张）、“谎”言字旁（谎话）、“荒”草字头（荒地），三字同音形近，要按偏旁区分。'],
  }),
  pickChoice({
    id: "cn-u6-gl-010",
    unit_id: U6,
    skill_id: PINYIN,
    ability: ["glyph"],
    difficulty: 2,
    stem: "看拼音写词语：青铜挑那些 péng sōng sōng（蓬松松）、闪着银光的芦花。",
    options: [
      { id: "a", text: "蓬松松" },
      { id: "b", text: "篷松松", errorTag: "glyph_homophone" },
      { id: "c", text: "蓬松忪", errorTag: "glyph_homophone" },
      { id: "d", text: "鹏松松", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“蓬松”形容毛发草叶等松散，草字头的“蓬”；“篷”是车篷、帐篷的篷。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-009",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "《小英雄雨来》“鹅毛般的苇絮就飘飘悠悠地飞起来”，“飘飘悠悠”这种叠词的作用是？",
    options: [
      { id: "a", text: "使描写更生动，写出苇絮轻柔、缓慢飘飞的样子" },
      { id: "b", text: "说明苇絮很重", errorTag: "opposite" },
      { id: "c", text: "凑字数，没有作用", errorTag: "off_topic" },
      { id: "d", text: "说明风很大", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['“飘飘悠悠”是 ABAB 式叠词，把苇絮轻盈、缓缓飘飞的样子写得更柔美、更有画面感。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-010",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 3,
    stem: "“沮丧”的意思最接近？",
    options: [
      { id: "a", text: "灰心失望" },
      { id: "b", text: "兴高采烈", errorTag: "antonym_misuse" },
      { id: "c", text: "心平气和", errorTag: "synonym_misuse" },
      { id: "d", text: "不慌不忙", errorTag: "synonym_misuse" },
    ],
    correct: "a",
    solution: ['“沮丧”指灰心、失望，情绪低落。与“兴高采烈”意思相反。'],
  }),
  pickChoice({
    id: "cn-u6-vocab-011",
    unit_id: U6,
    skill_id: VOCAB,
    ability: ["vocabulary"],
    difficulty: 2,
    stem: "下面词语中，全部含有近义词的一组是（如“东张西望”含“张=望”）？",
    options: [
      { id: "a", text: "一声不吭 · 千言万语" },
      { id: "b", text: "东张西望 · 左顾右盼" },
      { id: "c", text: "前因后果 · 黑白分明", errorTag: "word_category" },
      { id: "d", text: "大同小异 · 七上八下", errorTag: "word_category" },
    ],
    correct: "b",
    solution: ['“东张西望”“左顾右盼”都是含近义语素（张≈望、顾≈盼）的并列式成语，意思都指四处看。'],
  }),
  pickChoice({
    id: "cn-u6-wy-011",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: "《铁杵成针》“世传李太白读书山中，未成，弃去”中，“弃去”的意思是？",
    options: [
      { id: "a", text: "放弃（学业）离开" },
      { id: "b", text: "扔掉东西", errorTag: "word_misunderstand" },
      { id: "c", text: "去世", errorTag: "word_misunderstand" },
      { id: "d", text: "回去", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['“未成”指学业没完成；“弃去”指放弃学业离开。后来李白受老媪启发才“还卒业”。'],
  }),
  pickChoice({
    id: "cn-u6-wy-012",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation"],
    difficulty: 3,
    stem: "《铁杵成针》中“铁杵”指的是？",
    options: [
      { id: "a", text: "用来舂米或捣衣的铁棒" },
      { id: "b", text: "一根铁针", errorTag: "word_misunderstand" },
      { id: "c", text: "铁做的杯子", errorTag: "word_misunderstand" },
      { id: "d", text: "铁做的拐杖", errorTag: "word_misunderstand" },
    ],
    correct: "a",
    solution: ['注释：“铁杵”是用来舂米或捣衣的铁棒。老媪要把这么粗的铁棒磨成针。'],
  }),
  pickChoice({
    id: "cn-u6-wy-013",
    unit_id: U6,
    skill_id: WENYAN,
    ability: ["accumulation", "reading"],
    difficulty: 4,
    stem: "《囊萤夜读》和《铁杵成针》两个故事的共同点是？",
    options: [
      { id: "a", text: "都告诉我们学习要勤奋、有恒心，不怕困难" },
      { id: "b", text: "都讲打仗的故事", errorTag: "off_topic" },
      { id: "c", text: "都讲做生意", errorTag: "off_topic" },
      { id: "d", text: "都告诉我们读书没有用", errorTag: "opposite" },
    ],
    correct: "a",
    solution: ['车胤囊萤苦读、李白受老媪启发还卒业，两个故事都告诉我们：学习要勤奋刻苦、有恒心、不怕困难。'],
  }),
  pickChoice({
    id: "cn-u6-sum-009",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading"],
    difficulty: 4,
    stem: "给《芦花鞋》分部分并列小标题，下面最合理的一组是？",
    options: [
      { id: "a", text: "编芦花鞋 → 卖芦花鞋 → 雪天卖鞋 → 赤脚回家" },
      { id: "b", text: "游泳本领高 → 上夜校 → 掩护李大叔", errorTag: "wrong_text" },
      { id: "c", text: "他对食物的兴趣 → 他对独立的要求", errorTag: "wrong_text" },
      { id: "d", text: "囊萤夜读 → 铁杵成针", errorTag: "wrong_text" },
    ],
    correct: "a",
    solution: ['《芦花鞋》用空行分部分，可概括为：编芦花鞋、卖芦花鞋、雪天坚持卖鞋、把脚上的鞋也卖了赤脚回家。'],
  }),
  pickChoice({
    id: "cn-u6-sum-010",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["reading", "expression"],
    difficulty: 4,
    stem: "《我们家的男子汉》写孩子坚持自己去买东西、自己爬火车，作者称他“男子汉”，主要是赞扬他？",
    options: [
      { id: "a", text: "独立、勇敢、有主见、面对困难沉着" },
      { id: "b", text: "长得高大强壮", errorTag: "literal_misread" },
      { id: "c", text: "力气很大", errorTag: "literal_misread" },
      { id: "d", text: "很会打架", errorTag: "off_topic" },
    ],
    correct: "a",
    solution: ['“男子汉”不是指身体，而是赞扬这个小男孩独立、勇敢、有主见、遇事沉着——具有男子汉的精神品格。'],
  }),
  pickChoice({
    id: "cn-u6-sent-007",
    unit_id: U6,
    skill_id: SUMMARY,
    ability: ["sentence"],
    difficulty: 3,
    stem: "《芦花鞋》“两双鞋，既像四只鸟窝，又像两对鸟”这句话用了什么修辞？",
    options: [
      { id: "a", text: "比喻（把芦花鞋比作鸟窝、鸟）" },
      { id: "b", text: "拟人", errorTag: "wrong_rhetoric" },
      { id: "c", text: "夸张", errorTag: "wrong_rhetoric" },
      { id: "d", text: "反问", errorTag: "wrong_rhetoric" },
    ],
    correct: "a",
    solution: ['“既像……又像……”把芦花鞋比作鸟窝和鸟，是比喻，写出芦花鞋的柔软、好看和温暖。'],
  }),
  dictation({
    id: "cn-u6-dict-006",
    unit_id: U6,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "安徽",
    options: [
      { id: "a", text: "安徽" },
      { id: "b", text: "安微", errorTag: "glyph_homophone" },
      { id: "c", text: "安徵", errorTag: "glyph_homophone" },
      { id: "d", text: "安挥", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“安徽”是省名。注意“徽”中间是“糸”加“攵”，不要写成“微”。'],
  }),
  dictation({
    id: "cn-u6-dict-007",
    unit_id: U6,
    skill_id: DICT,
    ability: ["phonics", "glyph"],
    difficulty: 3,
    audio_text: "镇静",
    options: [
      { id: "a", text: "镇静" },
      { id: "b", text: "震静", errorTag: "glyph_homophone" },
      { id: "c", text: "镇净", errorTag: "glyph_homophone" },
      { id: "d", text: "镇靖", errorTag: "glyph_homophone" },
    ],
    correct: "a",
    solution: ['“镇静”指情绪稳定、不慌乱。“镇”金字旁，不要写成“震”（地震、震动）。'],
  }),
];
