/**
 * 语文 · C4B 仿写句子题包 (Phase 2 P2-3, v0.35.98).
 *
 * 期中考第 16-17 题 "用调动颜色 / 拟人 / 比喻描写句子" 中难考点.
 * G4B 学生在仿写题失分多 — 因为难以辨别"合格仿写".
 *
 * 题型设计 (4 选 1):
 *  - "下面哪句是上面例句的合格仿写?" 给 example, 选合格仿写
 *  - "下列哪句用了与例句相同的修辞?" (比喻/拟人/排比 辨认 + 仿写综合)
 *  - "用 [指定修辞] 写一句话, 哪句最对?" (颜色/拟人/比喻/排比)
 *  - 综合: 哪句话风格最接近原句?
 *
 * 仿写类型 (5 大类, 期中考全覆盖):
 *  - color_imitation (调动颜色描写)
 *  - personification (拟人句)
 *  - simile (比喻句 "A 像 B")
 *  - parallelism (排比句 "山在动 / 海在笑 / 森林在歌唱")
 *  - mixed (综合修辞)
 *
 * 50 题分布:
 *  - U1 古诗 + 乡村田园 (13 题)
 *  - U2 自然科技 (12 题)
 *  - U3 现代诗 (12 题)
 *  - U4 动物 (13 题)
 */

import type { Question } from "../../core/types";
import { pickChoice } from "./questionHelpers";

const U1 = "C4B_U1_NATURE";
const U2 = "C4B_U2_SCIENCE";
const U3 = "C4B_U3_POETRY";
const U4 = "C4B_U4_ANIMALS";

const IMITATE_U1 = "C4B_U1_IMITATE";
const IMITATE_U2 = "C4B_U2_IMITATE";
const IMITATE_U3 = "C4B_U3_IMITATE";
const IMITATE_U4 = "C4B_U4_IMITATE";

export const SEED_QUESTIONS_CHINESE_IMITATE: Question[] = [
  // ============================================================
  // 第一单元 · 仿写句子 (13 题)
  // ============================================================
  pickChoice({
    id: "cn-u1-imitate-001",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句: "桃花红得像火, 樱花白得像雪。"\n\n下面哪句最像上面的写法 (颜色 + 比喻)?',
    options: [
      { id: "a", text: "向日葵金得像太阳, 蒲公英黄得像小灯。" },
      { id: "b", text: "向日葵很黄, 蒲公英很美。", errorTag: "no_imitation" },
      { id: "c", text: "我喜欢向日葵和蒲公英。", errorTag: "no_imitation" },
      { id: "d", text: "向日葵开了, 蒲公英也开了。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['例句 = 颜色 + 像 + 喻体. 仿写也要 "色彩词 + 像 + 形象比喻".'],
  }),
  pickChoice({
    id: "cn-u1-imitate-002",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句 (拟人): "春风轻轻地走过田野。"\n\n下面哪句也是拟人?',
    options: [
      { id: "a", text: "小溪在山间唱着欢快的歌。" },
      { id: "b", text: "小溪从山里流出来。", errorTag: "no_personification" },
      { id: "c", text: "山间有一条小溪。", errorTag: "no_personification" },
      { id: "d", text: "小溪的水很清澈。", errorTag: "no_personification" },
    ],
    correct: "a",
    solution: ['拟人 = 把物当人写. "唱着歌" 是人的动作, 给 "小溪" 拟人.'],
  }),
  pickChoice({
    id: "cn-u1-imitate-003",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '例句 (排比): "山在动, 海在笑, 森林在歌唱。"\n\n下面哪句也用了排比?',
    options: [
      { id: "a", text: "花儿在笑, 蝴蝶在飞, 蜜蜂在采蜜。" },
      { id: "b", text: "花儿很美。", errorTag: "no_parallelism" },
      { id: "c", text: "花儿和蝴蝶都很美。", errorTag: "no_parallelism" },
      { id: "d", text: "花儿在风中飘动。", errorTag: "no_parallelism" },
    ],
    correct: "a",
    solution: ['排比 = 3 个或以上结构相同 / 内容相关的句子. A 句 3 个 "在 + 动词".'],
  }),
  pickChoice({
    id: "cn-u1-imitate-004",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '"枝头抽出嫩黄的新芽, 不久后, 洁白的樱花依次绽放。"\n\n按上面 "颜色 + 描写" 风格仿写, 哪句最对?',
    options: [
      { id: "a", text: "草地长出嫩绿的小苗, 不久后, 鲜艳的野花处处开放。" },
      { id: "b", text: "草地长出小苗, 然后野花开了。", errorTag: "no_color" },
      { id: "c", text: "我看到草地上有小苗和野花。", errorTag: "no_imitation" },
      { id: "d", text: "草地上小苗野花都很多。", errorTag: "no_color" },
    ],
    correct: "a",
    solution: ['原句两个描写都带颜色 (嫩黄 / 洁白). 仿写要保留 "嫩绿 / 鲜艳" 等色彩词.'],
  }),
  pickChoice({
    id: "cn-u1-imitate-005",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "燕子在屋檐下筑起了温暖的小巢。"\n\n哪句结构最像 (主语 + 在哪里 + 怎么样 + 做什么)?',
    options: [
      { id: "a", text: "蜜蜂在花丛中采集着甜蜜的花粉。" },
      { id: "b", text: "蜜蜂采花粉。", errorTag: "too_simple" },
      { id: "c", text: "蜜蜂很勤劳。", errorTag: "no_imitation" },
      { id: "d", text: "我喜欢蜜蜂。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['结构 = 主 + 在哪里 + 怎么样 + 做什么. A: "蜜蜂 + 在花丛中 + 采集 + 甜蜜的花粉".'],
  }),
  pickChoice({
    id: "cn-u1-imitate-006",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句: "天空蓝得像一块刚洗过的蓝布。"\n\n哪句仿写最好?',
    options: [
      { id: "a", text: "湖水清得像一面刚擦过的镜子。" },
      { id: "b", text: "湖水很清澈。", errorTag: "no_simile" },
      { id: "c", text: "湖水蓝蓝的。", errorTag: "no_simile" },
      { id: "d", text: "我看到了湖水。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['例句 = 主 + 形容词 + 得像 + 喻体. A 完整匹配: "湖水 + 清 + 得像 + 镜子".'],
  }),
  pickChoice({
    id: "cn-u1-imitate-007",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '例句 (拟人): "桃花羞红了脸。"\n\n哪句也是拟人?',
    options: [
      { id: "a", text: "麦穗低下了头。" },
      { id: "b", text: "麦穗熟了。", errorTag: "no_personification" },
      { id: "c", text: "麦穗在田里。", errorTag: "no_personification" },
      { id: "d", text: "麦穗有很多。", errorTag: "no_personification" },
    ],
    correct: "a",
    solution: ['"低下了头" 是人的动作, 给麦穗拟人 (其实是麦穗熟了下垂).'],
  }),
  pickChoice({
    id: "cn-u1-imitate-008",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence"],
    difficulty: 4,
    stem: '例句: "乡下人家的小院里, 种着许多五颜六色的花。"\n\n哪句仿写最好 (位置 + 数量 + 颜色)?',
    options: [
      { id: "a", text: "我家的阳台上, 摆着许多绿油油的盆栽。" },
      { id: "b", text: "阳台上有盆栽。", errorTag: "too_simple" },
      { id: "c", text: "我喜欢我家的阳台。", errorTag: "no_imitation" },
      { id: "d", text: "我家有阳台和盆栽。", errorTag: "no_color" },
    ],
    correct: "a",
    solution: ['原句 = 位置 (小院) + 数量 (许多) + 颜色 (五颜六色). 仿写要全保留三要素.'],
  }),
  pickChoice({
    id: "cn-u1-imitate-009",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句 (排比): "春天的乡下, 桃花笑了, 燕子归了, 麦苗绿了。"\n\n哪句结构最像?',
    options: [
      { id: "a", text: "秋天的果园, 苹果红了, 梨子黄了, 葡萄紫了。" },
      { id: "b", text: "秋天有很多水果。", errorTag: "no_parallelism" },
      { id: "c", text: "我喜欢秋天的果园。", errorTag: "no_imitation" },
      { id: "d", text: "苹果梨子葡萄都熟了。", errorTag: "no_parallelism" },
    ],
    correct: "a",
    solution: ['排比 + 颜色: 3 个 "X 红了 / 黄了 / 紫了". A 完整匹配.'],
  }),
  pickChoice({
    id: "cn-u1-imitate-010",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "嫩绿的麦苗在春风中轻轻摇摆。"\n\n哪句仿写最好?',
    options: [
      { id: "a", text: "鲜艳的桃花在春风中悄悄绽放。" },
      { id: "b", text: "桃花开了。", errorTag: "too_simple" },
      { id: "c", text: "我喜欢看桃花。", errorTag: "no_imitation" },
      { id: "d", text: "桃花在春天。", errorTag: "no_color" },
    ],
    correct: "a",
    solution: ['原句 = 颜色形容 (嫩绿) + 主语 + 状语 (春风中) + 状语 (轻轻) + 谓语. A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u1-imitate-011",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句 (双重修辞 拟人 + 颜色): "金黄的稻穗向我点头微笑。"\n\n哪句保持了两种修辞?',
    options: [
      { id: "a", text: "雪白的棉花朝我招手致意。" },
      { id: "b", text: "棉花是白的。", errorTag: "lose_personification" },
      { id: "c", text: "棉花在田里点头。", errorTag: "lose_color" },
      { id: "d", text: "我看到了棉花。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 颜色 (金黄) + 拟人 (点头微笑). A = 颜色 (雪白) + 拟人 (招手致意). 完整保留.'],
  }),
  pickChoice({
    id: "cn-u1-imitate-012",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "天窗外, 雨点像顽皮的孩子在跳舞。"\n\n哪句是合格仿写 (比喻 + 拟人)?',
    options: [
      { id: "a", text: "夜空中, 星星像调皮的精灵在眨眼。" },
      { id: "b", text: "夜空中有很多星星。", errorTag: "no_simile" },
      { id: "c", text: "星星很亮。", errorTag: "no_imitation" },
      { id: "d", text: "我喜欢看星星。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 喻体 (顽皮的孩子) + 拟人 (跳舞). A = 喻体 (调皮的精灵) + 拟人 (眨眼). 完美.'],
  }),
  pickChoice({
    id: "cn-u1-imitate-013",
    unit_id: U1,
    skill_id: IMITATE_U1,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句: "牧童骑黄牛, 歌声振林樾。"\n\n哪句用了相似的画面感 (人 + 物 + 动作 + 效果)?',
    options: [
      { id: "a", text: "小孩追蝴蝶, 笑声满山谷。" },
      { id: "b", text: "小孩很喜欢蝴蝶。", errorTag: "no_imitation" },
      { id: "c", text: "蝴蝶飞了。", errorTag: "too_simple" },
      { id: "d", text: "山谷里有蝴蝶。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原句结构 = 人 + 物 + 动作 + 效果. A: 小孩 + 蝴蝶 + 追 + 笑声满山谷. 完美.'],
  }),

  // ============================================================
  // 第二单元 · 仿写句子 (12 题)
  // ============================================================
  pickChoice({
    id: "cn-u2-imitate-001",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句: "纳米技术像一把神奇的钥匙, 打开了科学世界的大门。"\n\n哪句保持了 "A 像 B + 作用" 的结构?',
    options: [
      { id: "a", text: "书本像一艘小船, 载着我们驶向知识的海洋。" },
      { id: "b", text: "书本很重要。", errorTag: "no_simile" },
      { id: "c", text: "我喜欢看书。", errorTag: "no_imitation" },
      { id: "d", text: "书本里有知识。", errorTag: "no_simile" },
    ],
    correct: "a",
    solution: ['原 = 主语 + 像 + 喻体 + 作用. A 完整保留: "书本 + 像 + 小船 + 载着...".'],
  }),
  pickChoice({
    id: "cn-u2-imitate-002",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句 (排比): "琥珀里有蜘蛛, 有蜘蛛的脚印, 还有蜘蛛挣扎的痕迹。"\n\n哪句结构最相似?',
    options: [
      { id: "a", text: "化石里有恐龙, 有恐龙的骨头, 还有恐龙生活的记录。" },
      { id: "b", text: "化石里有很多东西。", errorTag: "no_parallelism" },
      { id: "c", text: "我看到了恐龙化石。", errorTag: "no_imitation" },
      { id: "d", text: "化石和恐龙。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['排比 3 项: 物 + 物的部分 + 物的痕迹. A 完整匹配.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-003",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '例句 (拟人): "电脑会思考, 会学习, 会回答问题。"\n\n哪句也用了拟人 (用人的动作描写物)?',
    options: [
      { id: "a", text: "机器人会跳舞, 会唱歌, 会陪我玩。" },
      { id: "b", text: "机器人是机器。", errorTag: "no_personification" },
      { id: "c", text: "我喜欢机器人。", errorTag: "no_imitation" },
      { id: "d", text: "机器人有很多种。", errorTag: "no_personification" },
    ],
    correct: "a",
    solution: ['拟人 = 把物当人写. 3 个 "会 + 人的动作" 排比 + 拟人.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-004",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence"],
    difficulty: 4,
    stem: '例句: "恐龙在远古时代生活, 它们高大威武。"\n\n哪句仿写结构最对 (描写 + 评价)?',
    options: [
      { id: "a", text: "鲸鱼在大海里生活, 它们巨大壮观。" },
      { id: "b", text: "鲸鱼很大。", errorTag: "too_simple" },
      { id: "c", text: "我看过鲸鱼。", errorTag: "no_imitation" },
      { id: "d", text: "鲸鱼是动物。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 主语 + 在哪里 + 生活 + 评价 (高大威武). A 完美保留.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-005",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '例句 (颜色): "金色的阳光洒在实验室的窗台上。"\n\n哪句保留了颜色描写?',
    options: [
      { id: "a", text: "银白的月光照在教室的黑板上。" },
      { id: "b", text: "月光照在黑板上。", errorTag: "no_color" },
      { id: "c", text: "我看到月光。", errorTag: "no_imitation" },
      { id: "d", text: "黑板很黑。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 颜色 + 主语 + 动作 + 位置. A: 银白 + 月光 + 照 + 黑板上.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-006",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence"],
    difficulty: 4,
    stem: '例句 (比喻): "千年梦圆, 飞船像一条腾空的巨龙。"\n\n哪句保留了比喻?',
    options: [
      { id: "a", text: "百年期盼, 高铁像一条飞驰的银箭。" },
      { id: "b", text: "高铁跑得很快。", errorTag: "no_simile" },
      { id: "c", text: "我坐过高铁。", errorTag: "no_imitation" },
      { id: "d", text: "高铁是新发明。", errorTag: "no_simile" },
    ],
    correct: "a",
    solution: ['原 = 状语 + 主 + 像 + 喻体. A: 百年期盼 + 高铁 + 像 + 银箭.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-007",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句 (排比): "科学家观察, 思考, 实验, 终于解开了谜团。"\n\n哪句也是排比?',
    options: [
      { id: "a", text: "学生听课, 笔记, 复习, 最终掌握了知识。" },
      { id: "b", text: "学生要好好学习。", errorTag: "no_parallelism" },
      { id: "c", text: "我每天都听课。", errorTag: "no_imitation" },
      { id: "d", text: "听课很重要。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['排比 3 个动词 + 结果. A: 听课 / 笔记 / 复习 + 掌握了知识.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-008",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "纳米技术虽然很小, 但作用很大。"\n\n哪句用了 "虽然... 但..." 的转折?',
    options: [
      { id: "a", text: "蚂蚁虽然很小, 但能搬动比自己大的东西。" },
      { id: "b", text: "蚂蚁很厉害。", errorTag: "no_contrast" },
      { id: "c", text: "我看到了蚂蚁。", errorTag: "no_imitation" },
      { id: "d", text: "蚂蚁是昆虫。", errorTag: "no_contrast" },
    ],
    correct: "a",
    solution: ['转折结构 "虽然 X, 但 Y". A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-009",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句 (拟人 + 比喻): "夜空像一块巨大的黑色幕布, 星星眨着调皮的眼睛。"\n\n哪句保留了两种修辞?',
    options: [
      { id: "a", text: "湖面像一面平静的镜子, 鱼儿吐着调皮的泡泡。" },
      { id: "b", text: "湖里有鱼。", errorTag: "no_simile_no_personification" },
      { id: "c", text: "湖水很平静。", errorTag: "lose_personification" },
      { id: "d", text: "我喜欢湖。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 比喻 (夜空像幕布) + 拟人 (星星眨眼睛). A 同时保留两种.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-010",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句 (因果): "因为有了科学家, 所以我们才有今天的便利生活。"\n\n哪句也是因果结构?',
    options: [
      { id: "a", text: "因为有了书本, 所以我们才能学到知识。" },
      { id: "b", text: "书本很有用。", errorTag: "no_causal" },
      { id: "c", text: "我每天看书。", errorTag: "no_imitation" },
      { id: "d", text: "书是知识的来源。", errorTag: "no_causal" },
    ],
    correct: "a",
    solution: ['"因为... 所以..." 因果结构. A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-011",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句: "实验室里, 显微镜下藏着一个神奇的世界。"\n\n哪句保留了 "在哪里 + 找到 + 神奇" 风格?',
    options: [
      { id: "a", text: "天文台上, 望远镜里飞着一颗颗闪烁的星辰。" },
      { id: "b", text: "天文台很高。", errorTag: "too_simple" },
      { id: "c", text: "望远镜可以看星星。", errorTag: "no_imitation" },
      { id: "d", text: "我想去天文台。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原句结构: 状语 (实验室里) + 工具 + 隐藏的世界. A 完整保留意境.'],
  }),
  pickChoice({
    id: "cn-u2-imitate-012",
    unit_id: U2,
    skill_id: IMITATE_U2,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "科技让我们的生活更美好, 让我们的世界更精彩。"\n\n哪句也是 "X 让 ... 更..." 结构?',
    options: [
      { id: "a", text: "阅读让我们的视野更开阔, 让我们的心灵更丰富。" },
      { id: "b", text: "我喜欢阅读。", errorTag: "no_imitation" },
      { id: "c", text: "阅读很有用。", errorTag: "too_simple" },
      { id: "d", text: "书本是好东西。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['排比 + "让 X 更 Y" 结构. A 完整保留, 2 个 "让... 更...".'],
  }),

  // ============================================================
  // 第三单元 · 仿写句子 (12 题)
  // ============================================================
  pickChoice({
    id: "cn-u3-imitate-001",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句 (现代诗): "好像绿色的墨水瓶倒翻了, 染绿了整个春天。"\n\n哪句保留了 "好像 + 喻体 + 效果" 风格?',
    options: [
      { id: "a", text: "好像金色的颜料桶打翻了, 染金了整个秋天。" },
      { id: "b", text: "秋天的金黄色很美丽。", errorTag: "no_simile" },
      { id: "c", text: "我喜欢秋天。", errorTag: "no_imitation" },
      { id: "d", text: "秋天的颜色很多。", errorTag: "no_simile" },
    ],
    correct: "a",
    solution: ['原 = 好像 + 喻体动作 + 染了 + 季节. A 完整保留 "金色颜料桶 / 打翻 / 染金 / 秋天".'],
  }),
  pickChoice({
    id: "cn-u3-imitate-002",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence"],
    difficulty: 4,
    stem: '例句 (拟人): "白桦树姑娘披着雪白的衬衫站在小道旁。"\n\n哪句也是拟人 + 颜色?',
    options: [
      { id: "a", text: "梧桐树叔叔穿着深绿的外套立在马路边。" },
      { id: "b", text: "梧桐树很高大。", errorTag: "no_personification" },
      { id: "c", text: "梧桐树是绿色的。", errorTag: "lose_personification" },
      { id: "d", text: "马路旁有梧桐树。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 拟人 (姑娘披着衬衫站在) + 颜色 (雪白). A 同时保留: 叔叔穿外套立 + 深绿.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-003",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '例句 (排比): "在天晴了的时候, 我们去原野上散步, 在草地上嬉戏, 在小溪边玩耍。"\n\n哪句结构最相似?',
    options: [
      { id: "a", text: "在春暖花开的时候, 我们去公园里赏花, 在湖畔散步, 在树下读书。" },
      { id: "b", text: "春天我们去玩。", errorTag: "no_parallelism" },
      { id: "c", text: "我喜欢春天。", errorTag: "no_imitation" },
      { id: "d", text: "公园很美。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['原 = "在 X 的时候, 我们 + 3 个动作排比". A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-004",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句 (比喻): "月亮像一艘小船在夜空中航行。"\n\n哪句也是合格比喻句?',
    options: [
      { id: "a", text: "太阳像一盏明灯照亮了大地。" },
      { id: "b", text: "太阳很亮。", errorTag: "no_simile" },
      { id: "c", text: "我喜欢太阳。", errorTag: "no_imitation" },
      { id: "d", text: "太阳是恒星。", errorTag: "no_simile" },
    ],
    correct: "a",
    solution: ['"X 像 Y + 作用". A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-005",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句 (颜色 + 比喻): "墨绿的叶子像一把把小伞撑开在树枝上。"\n\n哪句保留了颜色 + 比喻?',
    options: [
      { id: "a", text: "雪白的花朵像一盏盏小灯亮起在田野上。" },
      { id: "b", text: "花朵是白色的。", errorTag: "lose_simile" },
      { id: "c", text: "我看见了花朵。", errorTag: "no_imitation" },
      { id: "d", text: "花开了。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['原 = 颜色 (墨绿) + 主语 + 像 + 喻体 + 动作. A: 颜色 (雪白) + 花朵 + 像 + 小灯 + 亮起.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-006",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence"],
    difficulty: 4,
    stem: '例句 (拟人): "晴朗的天空中, 风轻轻地走过田野。"\n\n哪句也是拟人?',
    options: [
      { id: "a", text: "宁静的山谷里, 雨悄悄地敲打着窗台。" },
      { id: "b", text: "山谷里有雨。", errorTag: "no_personification" },
      { id: "c", text: "雨下了。", errorTag: "no_imitation" },
      { id: "d", text: "我喜欢雨。", errorTag: "no_personification" },
    ],
    correct: "a",
    solution: ['原 = 状语 + 主语 + 副词 + 人的动作 + 宾语. A: 山谷里 + 雨 + 悄悄地 + 敲打 (拟人) + 窗台.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-007",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句 (排比 + 颜色): "山是绿的, 草是绿的, 树是绿的, 一片绿油油的世界。"\n\n哪句风格最像?',
    options: [
      { id: "a", text: "梅是红的, 灯笼是红的, 春联是红的, 一片红彤彤的喜庆。" },
      { id: "b", text: "春节很热闹。", errorTag: "no_parallelism" },
      { id: "c", text: "我喜欢春节。", errorTag: "no_imitation" },
      { id: "d", text: "红色很喜气。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['排比 + 颜色: "X 是绿/红的" × 3 + 总结句. A 完整匹配.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-008",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句: "雨后的彩虹, 五颜六色, 像一座弯弯的桥。"\n\n哪句保留 "状语 + 颜色 + 比喻"?',
    options: [
      { id: "a", text: "霜后的菊花, 五彩缤纷, 像一团燃烧的火焰。" },
      { id: "b", text: "菊花很漂亮。", errorTag: "no_simile" },
      { id: "c", text: "我喜欢菊花。", errorTag: "no_imitation" },
      { id: "d", text: "霜后菊花开了。", errorTag: "no_simile" },
    ],
    correct: "a",
    solution: ['原 = 状语 (雨后的) + 主 + 颜色 + 像 + 喻体. A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-009",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "小溪欢快地流向远方。"\n\n哪句也是拟人?',
    options: [
      { id: "a", text: "白云悠闲地飘向天边。" },
      { id: "b", text: "白云在天空。", errorTag: "no_personification" },
      { id: "c", text: "天空有白云。", errorTag: "no_personification" },
      { id: "d", text: "白云白白的。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['"欢快地 / 悠闲地" 是描写人心情的副词, 给物拟人.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-010",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句: "春风吹过田野, 唤醒了沉睡的麦苗。"\n\n哪句保留 "拟人 + 因果"?',
    options: [
      { id: "a", text: "暖阳洒过山岗, 融化了厚厚的积雪。" },
      { id: "b", text: "山上的雪化了。", errorTag: "no_personification" },
      { id: "c", text: "暖阳很温暖。", errorTag: "too_simple" },
      { id: "d", text: "我喜欢春天。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['"吹 / 唤醒" + "洒 / 融化" 都是 主语 + 动作 + 因果效果, 拟人化大自然.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-011",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "短诗虽然简短, 但能描绘动人的画面。"\n\n哪句用了 "X 虽然 Y, 但 Z" 转折?',
    options: [
      { id: "a", text: "钢琴曲虽然简单, 但能感动人心。" },
      { id: "b", text: "钢琴很好听。", errorTag: "no_contrast" },
      { id: "c", text: "我喜欢钢琴。", errorTag: "no_imitation" },
      { id: "d", text: "钢琴曲不简单。", errorTag: "no_contrast" },
    ],
    correct: "a",
    solution: ['"X 虽然 Y, 但 Z" 转折结构. A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u3-imitate-012",
    unit_id: U3,
    skill_id: IMITATE_U3,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句 (反问): "难道我们不应该爱护这片绿色的森林吗?"\n\n哪句也是反问?',
    options: [
      { id: "a", text: "难道我们不应该珍惜这美好的时光吗?" },
      { id: "b", text: "我们要珍惜时光。", errorTag: "no_rhetoric" },
      { id: "c", text: "时光是宝贵的。", errorTag: "no_rhetoric" },
      { id: "d", text: "我珍惜每一刻。", errorTag: "no_rhetoric" },
    ],
    correct: "a",
    solution: ['反问句式 "难道 X 不... 吗?" A 完整保留.'],
  }),

  // ============================================================
  // 第四单元 · 仿写句子 (13 题)
  // ============================================================
  pickChoice({
    id: "cn-u4-imitate-001",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句 (《猫》原句): "我家的猫真有趣, 它一会儿温柔, 一会儿淘气。"\n\n哪句保留 "X 真 Y, 一会儿 ... 一会儿 ..."?',
    options: [
      { id: "a", text: "我家的小狗真活泼, 它一会儿跳跃, 一会儿趴下。" },
      { id: "b", text: "小狗很可爱。", errorTag: "no_parallelism" },
      { id: "c", text: "我喜欢小狗。", errorTag: "no_imitation" },
      { id: "d", text: "小狗会跳。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['原 = X 真 Y + "一会儿..., 一会儿..." 排比. A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-002",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence"],
    difficulty: 4,
    stem: '例句 (老舍《猫》): "猫蹑手蹑脚地走过来, 像一位偷食的小偷。"\n\n哪句保留了 "动作 + 比喻"?',
    options: [
      { id: "a", text: "麻雀小心翼翼地飞下来, 像一个谨慎的探险家。" },
      { id: "b", text: "麻雀飞下来。", errorTag: "too_simple" },
      { id: "c", text: "麻雀很机灵。", errorTag: "no_simile" },
      { id: "d", text: "我看见麻雀。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 主语 + 副词修饰动作 + 像 + 喻体. A 完整保留 "蹑手蹑脚 / 小心翼翼" 风格.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-003",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句 (拟人, 《白鹅》): "白鹅高傲地把头伸得长长的, 看着远方的客人。"\n\n哪句保留了拟人 + 描写?',
    options: [
      { id: "a", text: "孔雀优雅地把尾巴展得宽宽的, 迎接眼前的游客。" },
      { id: "b", text: "孔雀很美。", errorTag: "no_personification" },
      { id: "c", text: "我喜欢孔雀。", errorTag: "no_imitation" },
      { id: "d", text: "孔雀有大尾巴。", errorTag: "no_personification" },
    ],
    correct: "a",
    solution: ['原 = 主语 + 副词 + 动作 + 程度 + 目的. A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-004",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句 (排比): "猫会跳, 会跑, 会捉老鼠。"\n\n哪句也是排比?',
    options: [
      { id: "a", text: "狗会守家, 会牧羊, 会陪伴主人。" },
      { id: "b", text: "狗很忠诚。", errorTag: "no_parallelism" },
      { id: "c", text: "我喜欢狗。", errorTag: "no_imitation" },
      { id: "d", text: "狗会跑。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['"X 会 V1, 会 V2, 会 V3" 排比. A 完整保留, 3 个 "会".'],
  }),
  pickChoice({
    id: "cn-u4-imitate-005",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句 (颜色 + 描写): "黑白相间的小猫躺在柔软的垫子上。"\n\n哪句保留了 "颜色 + 状态 + 位置"?',
    options: [
      { id: "a", text: "金黄艳丽的金鱼游在清澈的鱼缸里。" },
      { id: "b", text: "金鱼很美。", errorTag: "no_color" },
      { id: "c", text: "我有金鱼。", errorTag: "no_imitation" },
      { id: "d", text: "鱼缸里有金鱼。", errorTag: "no_color" },
    ],
    correct: "a",
    solution: ['原 = 颜色 (黑白相间) + 主 + 状态 + 位置. A: 颜色 (金黄艳丽) + 金鱼 + 游 + 鱼缸里.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-006",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句 (拟人 + 比喻): "母鸡警惕地保护着小鸡, 像一位勇敢的战士。"\n\n哪句保留了拟人 + 比喻?',
    options: [
      { id: "a", text: "大象温柔地照顾着小象, 像一位慈祥的母亲。" },
      { id: "b", text: "大象是好妈妈。", errorTag: "lose_simile" },
      { id: "c", text: "我喜欢大象。", errorTag: "no_imitation" },
      { id: "d", text: "象群很温馨。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['原 = 主语 + 副词 + 动作 + 像 + 喻体. A: 大象 + 温柔地 + 照顾 + 像 + 慈祥的母亲.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-007",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "麻雀虽然小, 但勇气大。"\n\n哪句用了 "X 虽然 Y, 但 Z" 转折?',
    options: [
      { id: "a", text: "蚂蚁虽然弱, 但团结强。" },
      { id: "b", text: "蚂蚁是昆虫。", errorTag: "no_contrast" },
      { id: "c", text: "我喜欢蚂蚁。", errorTag: "no_imitation" },
      { id: "d", text: "蚂蚁很多。", errorTag: "no_contrast" },
    ],
    correct: "a",
    solution: ['"X 虽然 Y, 但 Z" 转折. A 完整保留, 写出对立的小 / 团结.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-008",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence", "expression"],
    difficulty: 4,
    stem: '例句 (《白鹅》原句): "鹅, 鹅, 鹅, 曲项向天歌。白毛浮绿水, 红掌拨清波。"\n\n哪句保留了诗的画面 (颜色对比 + 动态)?',
    options: [
      { id: "a", text: "蝶, 蝶, 蝶, 翩翩绕花飞。彩翅扇春风, 细足点鲜花。" },
      { id: "b", text: "蝴蝶很美。", errorTag: "too_simple" },
      { id: "c", text: "我喜欢蝴蝶。", errorTag: "no_imitation" },
      { id: "d", text: "蝴蝶在花丛里。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 三呼物名 + 动作画面 + 颜色对比 + 动态描写. A 完整保留 (鹅→蝶, 白绿→彩鲜, 浮拨→扇点).'],
  }),
  pickChoice({
    id: "cn-u4-imitate-009",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句 (排比): "猫的眼睛, 白天像两条线, 夜里像两盏灯, 神奇极了。"\n\n哪句也是 "X 像 Y" 排比?',
    options: [
      { id: "a", text: "蝴蝶的翅膀, 白天像两片花瓣, 夜里像两团彩云, 美丽极了。" },
      { id: "b", text: "蝴蝶很美。", errorTag: "no_parallelism" },
      { id: "c", text: "蝴蝶有翅膀。", errorTag: "too_simple" },
      { id: "d", text: "我喜欢蝴蝶。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['"X, A 像 B, C 像 D, Z 极了" 排比比喻 + 评价. A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-010",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence", "expression"],
    difficulty: 3,
    stem: '例句 (颜色 + 拟人): "金黄的鸡冠在阳光下闪着光, 像挂在头顶的小灯笼。"\n\n哪句保留两个修辞?',
    options: [
      { id: "a", text: "鲜红的尾羽在风中摇着尾, 像挂在身后的小旗帜。" },
      { id: "b", text: "尾羽是红的。", errorTag: "lose_simile" },
      { id: "c", text: "我看见尾羽。", errorTag: "no_imitation" },
      { id: "d", text: "鸟有尾羽。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['原 = 颜色 + 主 + 拟人 (闪着光) + 像 + 喻体. A 全保留.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-011",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence"],
    difficulty: 4,
    stem: '例句: "母鸡领着 8 只小鸡, 在院子里寻食, 在树荫下休息, 在水边喝水。"\n\n哪句保留 "X 领着 Y, 在 A, 在 B, 在 C" 排比?',
    options: [
      { id: "a", text: "老师领着学生们, 在教室里学习, 在操场上活动, 在食堂里吃饭。" },
      { id: "b", text: "老师很辛苦。", errorTag: "no_parallelism" },
      { id: "c", text: "我喜欢学校。", errorTag: "no_imitation" },
      { id: "d", text: "学生们在学习。", errorTag: "too_simple" },
    ],
    correct: "a",
    solution: ['"X 领着 Y + 在 A / 在 B / 在 C" 3 项排比. A 完整保留.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-012",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence", "expression"],
    difficulty: 4,
    exam_priority: "HIGH_BIG",
    stem: '例句 (拟人 + 反问): "白鹅难道不像一位高傲的将军吗?"\n\n哪句也是拟人 + 反问?',
    options: [
      { id: "a", text: "雄狮难道不像一位威武的国王吗?" },
      { id: "b", text: "雄狮是百兽之王。", errorTag: "no_rhetoric" },
      { id: "c", text: "我喜欢狮子。", errorTag: "no_imitation" },
      { id: "d", text: "狮子很威武。", errorTag: "lose_rhetoric" },
    ],
    correct: "a",
    solution: ['"X 难道不像 + 喻体 + 吗?" 拟人 (人的身份) + 反问. A 完整.'],
  }),
  pickChoice({
    id: "cn-u4-imitate-013",
    unit_id: U4,
    skill_id: IMITATE_U4,
    ability: ["sentence"],
    difficulty: 3,
    stem: '例句: "麻雀勇敢地保护小鸟, 不让猎狗欺凌它。"\n\n哪句保留 "X 勇敢地 + 动作 + 不让 Y"?',
    options: [
      { id: "a", text: "母鸡警惕地照顾小鸡, 不让黄鼠狼伤害它们。" },
      { id: "b", text: "母鸡很厉害。", errorTag: "too_simple" },
      { id: "c", text: "我看过母鸡。", errorTag: "no_imitation" },
      { id: "d", text: "母鸡有小鸡。", errorTag: "no_imitation" },
    ],
    correct: "a",
    solution: ['原 = 主 + 副词 + 动作 + 宾 + 不让 + 敌 + 害. A 完整保留.'],
  }),
];
