/**
 * 语文 · C4B 错别字题包 (Phase 2 P2-1, v0.35.93).
 *
 * 期中考第 4 题型: "李强来信 3 处错别字 + 1 处错用标点". G4B 高频丢分点.
 *
 * 题型设计:
 * - "下列哪个词没有错别字?" (4 选 1, 1 对 + 3 错)
 * - "下面哪句话有错别字?" (4 选 1, 1 错 + 3 对)
 * - "下列词语中, 错别字最多的是哪一组?" 较难变体
 *
 * 错别字来源:
 * - 形近字 (蓝/篮, 暮/幕, 蝶/喋)
 * - 同音字 (在/再, 副/付, 像/象)
 * - 多笔少笔 (漂/飘, 漫/慢)
 * - 偏旁错 (篮 蓝 vs 草字头/竹字头)
 * - 课文典型 (健康 / 慰藉 / 潇洒 / 推测 — 期中卷拼音题原话)
 *
 * 50+ 题分布:
 * - U1 第一单元 (古诗 + 乡村田园): 13 题
 * - U2 第二单元 (自然科技): 12 题
 * - U3 第三单元 (现代诗): 12 题
 * - U4 第四单元 (动物): 13 题
 */

import type { Question } from "../../core/types";
import { pickChoice } from "./questionHelpers";

const U1 = "C4B_U1_NATURE";
const U2 = "C4B_U2_SCIENCE";
const U3 = "C4B_U3_POETRY";
const U4 = "C4B_U4_ANIMALS";

const TYPOS_U1 = "C4B_U1_TYPOS";
const TYPOS_U2 = "C4B_U2_TYPOS";
const TYPOS_U3 = "C4B_U3_TYPOS";
const TYPOS_U4 = "C4B_U4_TYPOS";

export const SEED_QUESTIONS_CHINESE_TYPOS: Question[] = [
  // ============================================================
  // 第一单元 · 错别字辨认 (13 题)
  // 涉及: 古诗 + 乡村田园 (《宿新市》《四时田园杂兴》《清平乐·村居》
  //       《乡下人家》《天窗》《三月桃花水》)
  // ============================================================
  pickChoice({
    id: "cn-u1-typo-001",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下列哪个词没有错别字?",
    options: [
      { id: "a", text: "乡下人家" },
      { id: "b", text: "蓝天百云", errorTag: "form_confusion" },
      { id: "c", text: "桃花流水" },
      { id: "d", text: "鸡鸭成群" },
    ],
    correct: "a",
    solution: ['"蓝天白云" — "百" 应为 "白" (颜色). 同音字易错.'],
  }),
  pickChoice({
    id: "cn-u1-typo-002",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: '下列词语中, "蓝" 字用错的是?',
    options: [
      { id: "a", text: "蓝天大海" },
      { id: "b", text: "蓝色花朵" },
      { id: "c", text: "蓝球比赛", errorTag: "radical_swap" },
      { id: "d", text: "蓝宝石" },
    ],
    correct: "c",
    solution: ['"篮球" 应用 "篮" (竹字头, 装球的筐). "蓝" (草字头) 是颜色.'],
  }),
  pickChoice({
    id: "cn-u1-typo-003",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下面哪句话有错别字?",
    options: [
      { id: "a", text: "春天到了, 桃花开得真美。" },
      { id: "b", text: "我们一起去捉迷蔵。", errorTag: "form_confusion" },
      { id: "c", text: "乡下人家爱养鸡鸭。" },
      { id: "d", text: "天窗外飘着小雨。" },
    ],
    correct: "b",
    solution: ['"捉迷藏" — "蔵" 应为 "藏" (草字头). 形近字易错.'],
  }),
  pickChoice({
    id: "cn-u1-typo-004",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"蜻蜓" 这两个字的偏旁分别是?',
    options: [
      { id: "a", text: "虫字旁 + 虫字旁" },
      { id: "b", text: "日字旁 + 月字旁", errorTag: "radical_confusion" },
      { id: "c", text: "草字头 + 草字头", errorTag: "radical_confusion" },
      { id: "d", text: "虫字旁 + 立刀旁", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['蜻 + 蜓 都是 "虫" 字旁 (形声字, 表示昆虫类).'],
  }),
  pickChoice({
    id: "cn-u1-typo-005",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下列词语没有错别字的一组是?",
    options: [
      { id: "a", text: "天高云阔 / 桃花流水 / 鸭群嬉戏" },
      { id: "b", text: "蓝天百云 / 春暖花开 / 嬉戏玩耍", errorTag: "form_confusion" },
      { id: "c", text: "天高云宽 / 嫩绿粉嫩 / 鸡鸭成群", errorTag: "form_confusion" },
      { id: "d", text: "捉迷蔵 / 春风又绿 / 燕子归来", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['b 错 "百" → "白"; c 错 "宽" → "阔"; d 错 "蔵" → "藏".'],
  }),
  pickChoice({
    id: "cn-u1-typo-006",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph"],
    difficulty: 2,
    stem: '"宿新市徐公店" 中 "宿" 的正确写法?',
    options: [
      { id: "a", text: "宿 (宝盖头 + 百 + 一)" },
      { id: "b", text: "蓿 (草字头 + 宿)", errorTag: "extra_radical" },
      { id: "c", text: "夙 (横折 + 几 + 夕)", errorTag: "form_confusion" },
      { id: "d", text: "缩 (糸字旁 + 宿)", errorTag: "extra_radical" },
    ],
    correct: "a",
    solution: ['"宿" 表示住宿 (宝盖头 + 百 + 一). 其他字虽相似但意思完全不同.'],
  }),
  pickChoice({
    id: "cn-u1-typo-007",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "判断: 下列哪句话没有错别字?",
    options: [
      { id: "a", text: "篱落疏疏一径深, 树头新绿未成隂。", errorTag: "form_confusion" },
      { id: "b", text: "篱落疏疏一径深, 树头新绿未成阴。" },
      { id: "c", text: "蓠落疏疏一径深, 树头新绿未成阴。", errorTag: "radical_swap" },
      { id: "d", text: "篱落疏疏一径深, 树头新绿未成银。", errorTag: "homophone_confusion" },
    ],
    correct: "b",
    solution: ['原文 "树头新绿未成阴". "阴" 不是 "隂" (异体字) 也不是 "银" (同音字).'],
  }),
  pickChoice({
    id: "cn-u1-typo-008",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph"],
    difficulty: 2,
    stem: '"翁媪" 中 "媪" 的正确部首是?',
    options: [
      { id: "a", text: "女字旁" },
      { id: "b", text: "口字旁", errorTag: "radical_confusion" },
      { id: "c", text: "日字旁", errorTag: "radical_confusion" },
      { id: "d", text: "山字旁", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['"媪" 指年老的妇人, 部首 "女" 表示性别.'],
  }),
  pickChoice({
    id: "cn-u1-typo-009",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: '"绣 / 锈 / 秀" 选词填空: 桥上有一只 (   ) 满铜锈的铁狮子.',
    options: [
      { id: "a", text: "锈 (金属生锈)" },
      { id: "b", text: "绣 (绣花)", errorTag: "homophone_confusion" },
      { id: "c", text: "秀 (秀丽)", errorTag: "homophone_confusion" },
      { id: "d", text: "宿", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['"锈" 是金属表面氧化层, 跟铜铁有关.'],
  }),
  pickChoice({
    id: "cn-u1-typo-010",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面哪个词的写法是正确的?",
    options: [
      { id: "a", text: "嬉戏" },
      { id: "b", text: "嘻戏", errorTag: "homophone_confusion" },
      { id: "c", text: "西戏", errorTag: "homophone_confusion" },
      { id: "d", text: "希戏", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"嬉戏" — "嬉" (女字旁) 表示玩耍, 是正字.'],
  }),
  pickChoice({
    id: "cn-u1-typo-011",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"绿荫" 中的 "荫" 字, 下列哪个写法对?',
    options: [
      { id: "a", text: "荫 (草字头 + 阴)" },
      { id: "b", text: "隂 (异体字)", errorTag: "form_confusion" },
      { id: "c", text: "印 (印章)", errorTag: "homophone_confusion" },
      { id: "d", text: "因 (因为)", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"荫" 指树叶遮蔽的地方, 草字头 (跟树木有关).'],
  }),
  pickChoice({
    id: "cn-u1-typo-012",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph"],
    difficulty: 2,
    stem: "下列哪个不是 \"花\" 字的合理搭配?",
    options: [
      { id: "a", text: "桃花朵朵" },
      { id: "b", text: "鲜花盛开" },
      { id: "c", text: "百花齐放" },
      { id: "d", text: "花斗满园", errorTag: "form_confusion" },
    ],
    correct: "d",
    solution: ['"花斗" 不是词语. 应为 "百花斗艳" 或 "花团锦簇".'],
  }),
  pickChoice({
    id: "cn-u1-typo-013",
    unit_id: U1,
    skill_id: TYPOS_U1,
    ability: ["glyph", "vocabulary"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "找出下列短文中的错别字: \"清明时节, 我和小明去乡下人家. 我们走过捉迷蔵的篱笆, 又看到一群嬉戏的鸡鸭, 蓝天上飘着百云, 真是美极了！\"",
    options: [
      { id: "a", text: "蔵 / 百 (两个错别字)" },
      { id: "b", text: "蔵 / 嬉 (两个错别字)", errorTag: "form_confusion" },
      { id: "c", text: "只有 蔵 一个", errorTag: "form_confusion" },
      { id: "d", text: "只有 百 一个", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['"捉迷蔵" → "捉迷藏"; "蓝天上飘着百云" → "白云" (同音错字).'],
  }),

  // ============================================================
  // 第二单元 · 错别字辨认 (12 题)
  // 涉及: 自然科技 (《琥珀》《飞向蓝天的恐龙》《纳米技术》《千年梦圆》)
  // ============================================================
  pickChoice({
    id: "cn-u2-typo-001",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下列哪个词没有错别字?",
    options: [
      { id: "a", text: "纳米技术" },
      { id: "b", text: "纳米枝术", errorTag: "form_confusion" },
      { id: "c", text: "拿米技术", errorTag: "homophone_confusion" },
      { id: "d", text: "纳咪技术", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"纳米技术" — 课本原文. "技" 是手字旁.'],
  }),
  pickChoice({
    id: "cn-u2-typo-002",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph"],
    difficulty: 3,
    stem: '下列词中, "琥珀" 写法正确的是?',
    options: [
      { id: "a", text: "琥珀 (王字旁 + 王字旁)" },
      { id: "b", text: "虎珀 (虎字旁)", errorTag: "homophone_confusion" },
      { id: "c", text: "琥泊 (三点水)", errorTag: "radical_swap" },
      { id: "d", text: "胡珀 (月字旁)", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"琥珀" 是宝石, 两个字都用 "王" 字旁 (玉字旁, 跟玉石珠宝有关).'],
  }),
  pickChoice({
    id: "cn-u2-typo-003",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下面哪句话有错别字?",
    options: [
      { id: "a", text: "恐龙是远古时代的动物。" },
      { id: "b", text: "纳米技术能让我们更建康。", errorTag: "form_confusion" },
      { id: "c", text: "琥珀里有一只小昆虫。" },
      { id: "d", text: "千年梦圆飞天梦。" },
    ],
    correct: "b",
    solution: ['"健康" 不是 "建康". "健" 是单立人旁, 跟人身体有关.'],
  }),
  pickChoice({
    id: "cn-u2-typo-004",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"恐龙" 中 "恐" 的部首是?',
    options: [
      { id: "a", text: "心字底" },
      { id: "b", text: "工字旁", errorTag: "radical_confusion" },
      { id: "c", text: "土字底", errorTag: "radical_confusion" },
      { id: "d", text: "凡字旁", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['"恐" 表示害怕, 部首 "心" (心字底, 跟情感有关).'],
  }),
  pickChoice({
    id: "cn-u2-typo-005",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "下列词语没有错别字的一组是?",
    options: [
      { id: "a", text: "千年梦圆 / 飞向蓝天 / 纳米技术" },
      { id: "b", text: "迁年梦圆 / 飞向蓝天 / 纳咪技术", errorTag: "form_confusion" },
      { id: "c", text: "千年梦园 / 非向蓝天 / 纳米技术", errorTag: "homophone_confusion" },
      { id: "d", text: "千年梦圆 / 飞向兰天 / 纳米枝术", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['课文标题原话, 几处常见错: 迁/千, 园/圆, 兰/蓝, 枝/技, 咪/米.'],
  }),
  pickChoice({
    id: "cn-u2-typo-006",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph"],
    difficulty: 4,
    stem: '形声字: 下列哪个 "技 / 枝 / 肢" 用错了?',
    options: [
      { id: "a", text: "高超技术 (技)" },
      { id: "b", text: "树枝摇摆 (枝)" },
      { id: "c", text: "肢体运动 (肢)" },
      { id: "d", text: "肢能高超 (肢)", errorTag: "homophone_confusion" },
    ],
    correct: "d",
    solution: ['"技能" 应用 "技" (手字旁). "肢" 是身体部分, 不通用.'],
  }),
  pickChoice({
    id: "cn-u2-typo-007",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: '"测量 / 推测 / 测验" 三个 "测" 字都是?',
    options: [
      { id: "a", text: "三点水旁" },
      { id: "b", text: "立刀旁", errorTag: "radical_confusion" },
      { id: "c", text: "贝字旁", errorTag: "radical_confusion" },
      { id: "d", text: "草字头", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['"测" 部首三点水, 跟水或者量度有关.'],
  }),
  pickChoice({
    id: "cn-u2-typo-008",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph"],
    difficulty: 3,
    stem: "找错别字: \"科学家通过推则 (   ) 出恐龙生活在远古时代.\"",
    options: [
      { id: "a", text: "推则 → 推测 (则错)" },
      { id: "b", text: "推则没错", errorTag: "miss_typo" },
      { id: "c", text: "应该是 推断", errorTag: "miss_typo" },
      { id: "d", text: "应该是 推算", errorTag: "miss_typo" },
    ],
    correct: "a",
    solution: ['"推测" 的 "测" 三点水. "则" 是表示规则, 不能用.'],
  }),
  pickChoice({
    id: "cn-u2-typo-009",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下列哪个词正确?",
    options: [
      { id: "a", text: "宇航员" },
      { id: "b", text: "禹航员", errorTag: "homophone_confusion" },
      { id: "c", text: "羽航员", errorTag: "homophone_confusion" },
      { id: "d", text: "雨航员", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"宇" 表示太空 / 宇宙. "禹羽雨" 是同音字, 意思完全不同.'],
  }),
  pickChoice({
    id: "cn-u2-typo-010",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph", "vocabulary"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下面哪句没有错别字?",
    options: [
      { id: "a", text: "科学家在试验室里做研究, 一直工作到深夜。", errorTag: "form_confusion" },
      { id: "b", text: "科学家在实验室里做研究, 一直工作到深夜。" },
      { id: "c", text: "科学家在实验试里做研究, 一直工作到深夜。", errorTag: "form_confusion" },
      { id: "d", text: "科学家在实严室里做研究, 一直工作到深夜。", errorTag: "form_confusion" },
    ],
    correct: "b",
    solution: ['"实验室" — "实" 表示真实, "试" 是测试. 课本用 "实验".'],
  }),
  pickChoice({
    id: "cn-u2-typo-011",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"恐 / 巩 / 工 / 共"  四个字的字形写法, 哪个用错了?',
    options: [
      { id: "a", text: "恐龙 (恐)" },
      { id: "b", text: "巩固 (巩)" },
      { id: "c", text: "工人 (工)" },
      { id: "d", text: "巩龙 (巩)", errorTag: "form_confusion" },
    ],
    correct: "d",
    solution: ['"恐龙" 应用 "恐" (心字底, 害怕). "巩" 是巩固, 跟动物无关.'],
  }),
  pickChoice({
    id: "cn-u2-typo-012",
    unit_id: U2,
    skill_id: TYPOS_U2,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "下列没有错别字的一组词?",
    options: [
      { id: "a", text: "渺小 / 宇宙 / 攀登" },
      { id: "b", text: "缈小 / 宇宙 / 攀登", errorTag: "form_confusion" },
      { id: "c", text: "渺小 / 禹宙 / 攀登", errorTag: "homophone_confusion" },
      { id: "d", text: "渺小 / 宇宙 / 盘登", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['"渺" 三点水 (微小), "宇" (宝盖头), "攀" (上下结构).'],
  }),

  // ============================================================
  // 第三单元 · 错别字辨认 (12 题)
  // 涉及: 现代诗 (《短诗三首》《绿》《白桦》《在天晴了的时候》)
  // ============================================================
  pickChoice({
    id: "cn-u3-typo-001",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"白桦" 中 "桦" 的部首是?',
    options: [
      { id: "a", text: "木字旁" },
      { id: "b", text: "白字旁", errorTag: "radical_confusion" },
      { id: "c", text: "氵字旁", errorTag: "radical_confusion" },
      { id: "d", text: "口字旁", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['"桦" 是树名 (白桦树), 部首 "木".'],
  }),
  pickChoice({
    id: "cn-u3-typo-002",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下列哪个词没有错别字?",
    options: [
      { id: "a", text: "晶莹剔透" },
      { id: "b", text: "晶莹踢透", errorTag: "homophone_confusion" },
      { id: "c", text: "晶滢剔透", errorTag: "form_confusion" },
      { id: "d", text: "井莹剔透", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"晶莹" — "晶" 三个日, "莹" 草字头. "剔" 立刀旁.'],
  }),
  pickChoice({
    id: "cn-u3-typo-003",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下面哪句话有错别字?",
    options: [
      { id: "a", text: "好像绿色的墨水瓶倒翻了。" },
      { id: "b", text: "白桦树在月光下静静地立着。" },
      { id: "c", text: "天晴了的时候, 我和小燕飞过原野。", errorTag: "form_confusion" },
      { id: "d", text: "小屋的窗户上挂满了水珠。" },
    ],
    correct: "c",
    solution: ['"我和小燕" — "燕" 跟人名连用应该有 ""引号"" 或上下文清晰. 实际课文是 "和小燕子"; 4年级常错混 "燕" / "雁".'],
  }),
  pickChoice({
    id: "cn-u3-typo-004",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: '"墨水" 的 "墨" 字怎么写?',
    options: [
      { id: "a", text: "黑 + 土 (上下结构)" },
      { id: "b", text: "黑 + 玉", errorTag: "form_confusion" },
      { id: "c", text: "里 + 土", errorTag: "form_confusion" },
      { id: "d", text: "墨 (左右结构)", errorTag: "structure_confusion" },
    ],
    correct: "a",
    solution: ['"墨" 上面是 "黑", 下面是 "土" (墨是黑色的泥土做的).'],
  }),
  pickChoice({
    id: "cn-u3-typo-005",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下列词语没有错别字的一组?",
    options: [
      { id: "a", text: "墨绿 / 嫩绿 / 翠绿" },
      { id: "b", text: "墨绿 / 嫩录 / 翠绿", errorTag: "form_confusion" },
      { id: "c", text: "黑绿 / 嫩绿 / 萃绿", errorTag: "form_confusion" },
      { id: "d", text: "墨绿 / 嫩绿 / 翠録", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['"绿" 是绞丝旁 (糸). "录 / 録" 都是其他意思.'],
  }),
  pickChoice({
    id: "cn-u3-typo-006",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph"],
    difficulty: 2,
    stem: '"原野" 的 "野" 部首是?',
    options: [
      { id: "a", text: "里字旁 (左)" },
      { id: "b", text: "予字旁", errorTag: "radical_confusion" },
      { id: "c", text: "草字头", errorTag: "radical_confusion" },
      { id: "d", text: "土字底", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['"野" 部首 "里" (在左边). 右边是 "予".'],
  }),
  pickChoice({
    id: "cn-u3-typo-007",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph", "vocabulary"],
    difficulty: 4,
    stem: "找错别字: \"白哗树姑娘披着雪白的衬衫, 站在小道旁.\"",
    options: [
      { id: "a", text: "白哗 → 白桦 (哗错)" },
      { id: "b", text: "披着 → 批着", errorTag: "miss_typo" },
      { id: "c", text: "全对", errorTag: "miss_typo" },
      { id: "d", text: "衬衫 → 衬山", errorTag: "miss_typo" },
    ],
    correct: "a",
    solution: ['"白桦" — "桦" 是木字旁, 树名. "哗" 是口字旁 (喧哗).'],
  }),
  pickChoice({
    id: "cn-u3-typo-008",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"反复 / 反夏" 哪个对?',
    options: [
      { id: "a", text: "反复 (复习)" },
      { id: "b", text: "反夏 (夏天)", errorTag: "form_confusion" },
      { id: "c", text: "反副 (副会长)", errorTag: "homophone_confusion" },
      { id: "d", text: "反付 (付钱)", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"反复" — "复" 是返回, 多次重做的意思. "夏" 是夏天, 不通.'],
  }),
  pickChoice({
    id: "cn-u3-typo-009",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: '"温暖" 的 "暖" 部首是?',
    options: [
      { id: "a", text: "日字旁" },
      { id: "b", text: "三点水", errorTag: "radical_confusion" },
      { id: "c", text: "氵字旁", errorTag: "radical_confusion" },
      { id: "d", text: "火字旁", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['"暖" 跟温度 / 阳光有关, 部首 "日".'],
  }),
  pickChoice({
    id: "cn-u3-typo-010",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph"],
    difficulty: 3,
    stem: "下列哪个词正确?",
    options: [
      { id: "a", text: "晴朗" },
      { id: "b", text: "晴郎", errorTag: "homophone_confusion" },
      { id: "c", text: "情朗", errorTag: "homophone_confusion" },
      { id: "d", text: "睛朗", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['"晴朗" — "晴" 日字旁 (天气), "朗" 月字旁 (明亮).'],
  }),
  pickChoice({
    id: "cn-u3-typo-011",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "找错别字: \"绿色的麦田一望无际, 春风吹拂着嫩録的小草.\"",
    options: [
      { id: "a", text: "录 → 绿 (1 个错)" },
      { id: "b", text: "全对", errorTag: "miss_typo" },
      { id: "c", text: "錄 → 緑", errorTag: "miss_typo" },
      { id: "d", text: "吹拂 → 吹佛", errorTag: "miss_typo" },
    ],
    correct: "a",
    solution: ['"嫩绿" — "绿" 绞丝旁. "录" 是记录, 跟颜色无关.'],
  }),
  pickChoice({
    id: "cn-u3-typo-012",
    unit_id: U3,
    skill_id: TYPOS_U3,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "下列哪句话没有错别字?",
    options: [
      { id: "a", text: "晴朗的天气里, 我们在原野上奔跑。" },
      { id: "b", text: "情朗的天气里, 我们在原野上奔跑。", errorTag: "homophone_confusion" },
      { id: "c", text: "晴朗的天起里, 我们在原野上奔跑。", errorTag: "form_confusion" },
      { id: "d", text: "晴朗的天气里, 我们在源野上奔跑。", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"晴朗 / 天气 / 原野" 都是正字. 易错: 情/晴, 起/气, 源/原.'],
  }),

  // ============================================================
  // 第四单元 · 错别字辨认 (13 题)
  // 涉及: 动物 (《猫》《母鸡》《白鹅》《麻雀》)
  // ============================================================
  pickChoice({
    id: "cn-u4-typo-001",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下列哪个词没有错别字?",
    options: [
      { id: "a", text: "麻雀活跃" },
      { id: "b", text: "麻鹊活跃", errorTag: "homophone_confusion" },
      { id: "c", text: "蚂雀活跃", errorTag: "form_confusion" },
      { id: "d", text: "麻雀火跃", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"麻雀" — "雀" 是鸟. "鹊" 是另一种鸟 (喜鹊). 课文是 "麻雀".'],
  }),
  pickChoice({
    id: "cn-u4-typo-002",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph"],
    difficulty: 2,
    stem: '"猫" 字的部首是?',
    options: [
      { id: "a", text: "犭字旁 (反犬旁)" },
      { id: "b", text: "苗字旁", errorTag: "radical_confusion" },
      { id: "c", text: "口字旁", errorTag: "radical_confusion" },
      { id: "d", text: "草字头", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['"猫" 反犬旁, 跟动物有关. 右边是声旁 "苗".'],
  }),
  pickChoice({
    id: "cn-u4-typo-003",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "下面哪句话有错别字?",
    options: [
      { id: "a", text: "麻雀勇敢地保护它的小宝宝。" },
      { id: "b", text: "白鹅的步态像一位将军。" },
      { id: "c", text: "母鸡警备的看着我们。", errorTag: "form_confusion" },
      { id: "d", text: "猫的胡须一根根竖起来。" },
    ],
    correct: "c",
    solution: ['"警备" 是军事用词. 应是 "警惕" (心字旁 + 易).'],
  }),
  pickChoice({
    id: "cn-u4-typo-004",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"鹅" 字的右边是?',
    options: [
      { id: "a", text: "鸟" },
      { id: "b", text: "我", errorTag: "form_confusion" },
      { id: "c", text: "戈", errorTag: "form_confusion" },
      { id: "d", text: "它", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['"鹅" 左边是声旁 "我", 右边是 "鸟" (表示鸟类). 不是 "戈" 或 "它".'],
  }),
  pickChoice({
    id: "cn-u4-typo-005",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    exam_priority: "MUST_BIG",
    stem: "下列没有错别字的一组词?",
    options: [
      { id: "a", text: "尽职尽责 / 性格古怪 / 蹑手蹑脚" },
      { id: "b", text: "尽职尽则 / 性格古怪 / 蹑手蹑脚", errorTag: "form_confusion" },
      { id: "c", text: "尽职尽责 / 姓格古怪 / 蹑手蹑脚", errorTag: "homophone_confusion" },
      { id: "d", text: "尽职尽责 / 性格古挂 / 蹑手蹑脚", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['课文 《猫》 原话. "责" 是贝字底, "性" 是单立人, "挂" 是手字旁但意思不同.'],
  }),
  pickChoice({
    id: "cn-u4-typo-006",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph"],
    difficulty: 3,
    stem: '形声字: "鸡 / 鹅 / 鸭 / 鸽"  四个字共同部首是?',
    options: [
      { id: "a", text: "鸟字旁 (都是鸟类)" },
      { id: "b", text: "尤字旁", errorTag: "radical_confusion" },
      { id: "c", text: "鸡字旁", errorTag: "radical_confusion" },
      { id: "d", text: "甲字旁", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['这 4 个字都是 "鸟" 字旁, 表示鸟类. 左半是形旁 + 右半是声旁.'],
  }),
  pickChoice({
    id: "cn-u4-typo-007",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"鸣 / 呜 / 鸣" — 哪个写法正确? 老母鸡咕咕地 (   ) 叫.',
    options: [
      { id: "a", text: "鸣 (口 + 鸟)" },
      { id: "b", text: "呜 (口 + 乌)", errorTag: "form_confusion" },
      { id: "c", text: "明 (日 + 月)", errorTag: "homophone_confusion" },
      { id: "d", text: "鳴 (异体字)", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['"鸣" 表示鸟叫. "呜" 是哭声, "明" 是明亮.'],
  }),
  pickChoice({
    id: "cn-u4-typo-008",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph", "vocabulary"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "找错别字: \"那只勇敢的麻鹊飞下来, 用身体保护小麻雀, 不让猎狗欺凌.\"",
    options: [
      { id: "a", text: "鹊 → 雀 (1 个错)" },
      { id: "b", text: "全对", errorTag: "miss_typo" },
      { id: "c", text: "猎 → 列", errorTag: "miss_typo" },
      { id: "d", text: "凌 → 灵", errorTag: "miss_typo" },
    ],
    correct: "a",
    solution: ['"麻雀" 和 "麻鹊" 不同鸟. 课文 《麻雀》 屠格涅夫.'],
  }),
  pickChoice({
    id: "cn-u4-typo-009",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph"],
    difficulty: 2,
    stem: '"傲慢" 的 "傲" 是?',
    options: [
      { id: "a", text: "单立人 + 敖" },
      { id: "b", text: "敖 + 单立人", errorTag: "structure_confusion" },
      { id: "c", text: "草字头 + 敖", errorTag: "radical_confusion" },
      { id: "d", text: "口字旁 + 敖", errorTag: "radical_confusion" },
    ],
    correct: "a",
    solution: ['"傲" 左边单立人, 右边 "敖". 跟人的态度有关.'],
  }),
  pickChoice({
    id: "cn-u4-typo-010",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph", "vocabulary"],
    difficulty: 3,
    stem: "下列哪句话没有错别字?",
    options: [
      { id: "a", text: "白鹅迈着方步, 一副傲慢的样子。" },
      { id: "b", text: "白鹅迈着方步, 一付傲慢的样子。", errorTag: "homophone_confusion" },
      { id: "c", text: "白鹅迈着方步, 一副傲漫的样子。", errorTag: "homophone_confusion" },
      { id: "d", text: "白鹅卖着方步, 一副傲慢的样子。", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"一副" (副是量词); "傲慢" (慢是心字旁竖心); "迈" 是辶字底.'],
  }),
  pickChoice({
    id: "cn-u4-typo-011",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"性格" 写法对的是?',
    options: [
      { id: "a", text: "性 (忄 + 生)" },
      { id: "b", text: "姓 (女 + 生)", errorTag: "homophone_confusion" },
      { id: "c", text: "醒 (酉 + 星)", errorTag: "homophone_confusion" },
      { id: "d", text: "腥 (月 + 星)", errorTag: "homophone_confusion" },
    ],
    correct: "a",
    solution: ['"性格" — "性" 是竖心旁 + "生" (跟心 / 情感有关). "姓" 是女字旁 + "生", 指姓氏.'],
  }),
  pickChoice({
    id: "cn-u4-typo-012",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph"],
    difficulty: 3,
    stem: '"贪睡" 中的 "贪" 是?',
    options: [
      { id: "a", text: "今 + 贝 (上下结构)" },
      { id: "b", text: "贝 + 今", errorTag: "structure_confusion" },
      { id: "c", text: "今 + 见", errorTag: "form_confusion" },
      { id: "d", text: "金 + 贝", errorTag: "form_confusion" },
    ],
    correct: "a",
    solution: ['"贪" 上面 "今" 下面 "贝" (贝字底, 跟钱财有关). 课文猫 "贪睡".'],
  }),
  pickChoice({
    id: "cn-u4-typo-013",
    unit_id: U4,
    skill_id: TYPOS_U4,
    ability: ["glyph", "vocabulary"],
    difficulty: 4,
    exam_priority: "MUST_BIG",
    stem: "下面句子有几处错别字: \"我家的猫真有取 (   ), 它一会儿很温顺, 一会儿又老是抓鱼地不肯回家.\"",
    options: [
      { id: "a", text: "1 处: 取 → 趣" },
      { id: "b", text: "2 处: 取 → 趣 + 抓鱼地 → 抓鱼的", errorTag: "miss_typo" },
      { id: "c", text: "无错字", errorTag: "miss_typo" },
      { id: "d", text: "2 处: 老是 → 老实 + 取 → 趣", errorTag: "miss_typo" },
    ],
    correct: "a",
    solution: ['"有趣" — "趣" 走字旁 (跟乐趣有关). "取" 是耳字旁 (拿取). 只这 1 处错.'],
  }),
];
